### ISSUE TITLE
Component schemas for IDE intellisense

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#1010]
**Is your feature request related to a problem or use case? Please describe.**
When writing HTML that uses the `ids-enterprise-wc` components, there is no help from the IDE (vscode). There is no way to know whether something is miss-spelled, or if using an attribute that doesn't exist. There is also no way to "discover" the API of a component other than reading the documentation.

**Describe the solution you'd like**
There is [a (in progress) standard/schema](https://github.com/webcomponents/custom-elements-manifest) for how a module should describe the custom elements that it provides. There is also a way to [configure VS Code](https://github.com/microsoft/vscode-html-languageservice/blob/main/docs/customData.md) to read a file containing the schema for a component library. The JSON Schema can be found [here](https://github.com/microsoft/vscode-html-languageservice/blob/main/docs/customData.schema.json).

I propose that such a file be generated automatically when building the `ids-enterprise-wc` library and included in the package. It could of course be written by hand, but I imagine that would require a lot of work and be error prone.

**Describe alternatives you've considered**
If there was a way to achieve this through TypeScript typings, I guess that would be preferable. That would allow type-checking and completion for things like `document.createElement("ids-<Ctrl+Space for completion>` and `someCustomIdsElement.addEventListener("customEve<Ctrl+Space>"`-

I tried the following locally in my project, just to see if it worked:

.vscode/settings.json:
```json
"html.customData": [
  "./ids-enterprise-wc.json",
]
```

and ./ids-enterprise-wc.json:
```json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vscode-html-languageservice/main/docs/customData.schema.json",
  "version": 1.1,
  "tags": [
    {
      "name": "ids-button",
      "description": {
        "kind": "plaintext",
        "value": "The IDS Button component is a simple wrapper around a standard HTMLButtonElement that is styled with Infor branding, and contains some additional API that makes it easy to set text, icons, and functionality."
      },
      "attributes": [
        {
          "name": "type",
          "values": [
            {
              "name": "primary"
            },
            {
              "name": "secondary"
            },
            {
              "name": "tertiary"
            }
          ]
        }
      ],
      "references": [
        {
          "name": "GitHub",
          "url": "https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-button"
        }
      ]
    }
  ]
}

```
Which makes the "ids-button" component slightly easier to use:

**Additional context**
<img width="714" alt="image" src="https://user-images.githubusercontent.com/4991954/203362361-9817cced-8d4a-4c77-b0f9-5fa8358eb837.png">
<img width="714" alt="image" src="https://user-images.githubusercontent.com/4991954/203362418-8c0d3e78-9a17-4296-af61-719202deb204.png">

And what application do you work on? Homepages & Portal

**Comment by tmcconechy** [comment]
Interesting i wonder if https://custom-elements-manifest.open-wc.org/analyzer/getting-started/ and could be useful https://www.npmjs.com/package/ts-generate-schema

I noticed this problem as well and agree this could be highly useful

**Comment by anhallbe** [comment]
Having the library in a machine-readable format (the schema described above) might also make it easier to add other integrations, such as Angular Language Service, type checking, eslint etc. Though I'm not sure how all of these tools integrate, so I'm not sure how much it'd help.

**Comment by anhallbe** [comment]
I couldn't figure out a simple way to extract component metadata (name, attributes etc)

...so I did something incredibly hacky that may or may not be useful for somebody who's working on this issue. I created a script that simply goes through all the component `/demos/` files, parses all the `<ids-...` elements, their attributes etc. And builds a `custom-data.json` file that you can point to in `.vscode/settings.json`.

It's not at all complete, and it does not include documentation, but it kind of works 🤣 :
<img width="404" alt="image" src="https://user-images.githubusercontent.com/4991954/203416193-da52ff60-3c5d-404a-8381-2585f3c32bb2.png">
<img width="499" alt="image" src="https://user-images.githubusercontent.com/4991954/203416257-ed3f54d5-9f94-4ad2-931c-28ae25af9921.png">


```typescript
// scripts/generate-component-manifest.ts
// Run with: ts-node -O '{"module":"commonjs"}' scripts/generate-component-manifest.ts

/* eslint-disable jsdoc/require-returns */
/* eslint-disable jsdoc/require-param */
/* eslint-disable jsdoc/require-param-type */
/* eslint-disable no-console */

import fs from 'fs/promises';
import path from 'path';

const componentsDir = path.join(__dirname, '../src/components');
const outputFile = 'custom-data.json';

const IGNORED_ATTRIBUTES = Object.freeze([
  'id',
  'class'
]);

/**
 * Similar to Unix `find`. It just lists all files in a given directory, recursively.
 */
async function find(directory: string): Promise<string[]> {
  const result: string[] = [];
  const dirents = await fs.readdir(directory, { withFileTypes: true });
  for (const dirent of dirents) {
    const child = path.resolve(directory, dirent.name);
    if (dirent.isDirectory()) {
      result.push(...await find(child));
    } else {
      result.push(child);
    }
  }
  return result;
}
interface WebComponent {
  tag: string;
  attributes: Map<string, WebComponentAttribute>;
}

interface WebComponentAttribute {
  key: string;
  values: Set<string>;
}

/**
 * Parses all the demo HTML files and looks for <ids-...> elements.
 * Creates a structure that contains all the custom elements, their attributes, and attribute values
 */
async function parseDemoComponents() {
  const components = new Map<string, WebComponent>();
  const demoFiles = (await find(componentsDir)).filter((file) => file.includes('/demos/') && file.endsWith('.html'));
  for (const demoFile of demoFiles) {
    const htmlElementRegex = new RegExp(/<(?<tag>ids-[^\s>]+)[^>]*>/g);
    const htmlAttributeRegex = new RegExp(/\s*(?<key>[\w-]+)="(?<value>.+?)"\s*/g);
    const content = (await fs.readFile(demoFile)).toString();
    let match: RegExpExecArray | null;
    while (match = htmlElementRegex.exec(content)) {
      if (match.groups) {
        const { tag } = match.groups;
        const component: WebComponent = components.get(tag) ?? { tag, attributes: new Map() };
        const tagMatch = match[0];

        while (match = htmlAttributeRegex.exec(tagMatch)) {
          if (match.groups) {
            const { key, value } = match.groups;
            if (!IGNORED_ATTRIBUTES.includes(key)) {
              const attribute: WebComponentAttribute = component.attributes.get(key) ?? { key, values: new Set() };
              attribute.values.add(value);
              component.attributes.set(key, attribute);
            }
          }
        }

        components.set(tag, component);
      }
    }
  }
  return [...components.values()];
}

interface Schema {
  $schema: 'https://raw.githubusercontent.com/microsoft/vscode-html-languageservice/main/docs/customData.schema.json',
  version: 1.1,
  tags: SchemaTag[]
}

interface SchemaTag {
  name: string;
  attributes: SchemaAttribute[];
}

interface SchemaAttribute {
  name: string;
  values: SchemaAttributeValue[];
}

interface SchemaAttributeValue {
  name: string;
}

/**
 * Creates a VS Code "custom data" schema out of the given component list
 * See https://github.com/microsoft/vscode-html-languageservice/blob/main/docs/customData.schema.json
 */
function toSchema(components: WebComponent[]): Schema {
  const schema: Schema = {
    $schema: 'https://raw.githubusercontent.com/microsoft/vscode-html-languageservice/main/docs/customData.schema.json',
    version: 1.1,
    tags: [],
  };
  for (const component of components) {
    const tag: SchemaTag = {
      name: component.tag,
      attributes: [],
    };
    for (const attr of component.attributes.values()) {
      const attribute: SchemaAttribute = {
        name: attr.key,
        values: [],
      };
      for (const val of attr.values) {
        const value: SchemaAttributeValue = {
          name: val,
        };
        attribute.values.push(value);
      }
      tag.attributes.push(attribute);
    }
    schema.tags.push(tag);
  }
  return schema;
}

(async function generateComponentManifest() {
  const components = await parseDemoComponents();
  const schema = toSchema(components);
  await fs.writeFile(outputFile, JSON.stringify(schema, null, 2));
}());

```

**Comment by tmcconechy** [comment]
https://github.com/open-wc/custom-elements-manifest -> looks like what one tool is using https://shoelace.style/
