### ISSUE TITLE
WC Readme Update

### ISSUE THREAD

**Issue by inforandy** [infor-design/enterprise-wc#1026]
We need to change the readme file that feeds the beta code docs 

"Infor Design System's Enterprise Components"

changes to

"Infor Design Systems's Web Component Beta Library"

"Infor Design System's Enterprise web component library is a framework independent UI library consisting of CSS and JS that provides Infor product development teams, partners, and customers the tools to create user experiences that are approachable, focused, relevant and perceptive."

changes to

"Infor Design System's Enterprise web component library is a framework independent UI library consisting of CSS and JS that provides Infor product development teams, partners, and customers the tools to create user experiences that are approachable, focused, relevant and perceptive.

These tools are currently in beta testing and slated for release in beginning of 2023"

**Comment by tmcconechy** [comment]
Done. But @jmacaluso711 how does this get onto the website?

**Comment by jmacaluso711** [comment]
@corpulent Will have to deploy the updated documentation

**Comment by tmcconechy** [comment]
This was completed https://design.infor.com/code/wc-beta/latest
