### ISSUE TITLE
IdsSearchfield: can clear items in Read-only Search Bar

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1027]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-search-field/example.html
2. Use `Read-only Search Bar`
3. Click x icon
4. See issue

**Expected behavior**
Read-only Search Bar should not be clearable

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/56722184/205050483-caa437b0-ea91-4723-8b76-2f9b9fe40fc1.png">

**Platform**
All
**Additional context**

**Comment by tmcconechy** [comment]
In order to fix this the X should not even be visible in the readonly state

**Comment by andriivarhanov** [comment]
@tmcconechy the `Read-only Search Bar` example uses `clearable-forced` setting what forces it to be clearable even if it's readonly or disabled, `clearable` setting works correctly. I think I can change it to `clearable` for the example and add a new example page with `clearable-forced` setting to avoid confusion

**Comment by tmcconechy** [comment]
Oh OK @andriivarhanov , Yeah lets make readonly not clear be the default in all examples. Im not sure if anyone would use clearable-forced for anything but no need to remove it if its there. Maybe just have a test in for it and not show it in the examples as QA will just report its not working right. Thanks i didnt know it was a setting....

**Comment by deep7102** [comment]
`clearable-forced` use where we need combination of read only and clearable input fields, because `clearable` setting it self not apply on read only inputs it used in `ids-upload`

**Comment by jbrcna** [comment]
Confirming test Passed. thank you
https://main.wc.design.infor.com/ids-search-field/example.html
<img width="577" alt="image" src="https://user-images.githubusercontent.com/56722184/208806325-fd20fb85-f556-41cd-a340-28a74cf679f1.png">
