### ISSUE TITLE
IdsButton: Change `tertiary` type colors to use the primary action color

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#1028]
**Is your feature request related to a problem or use case? Please describe.**
We have a common pattern for modifying IdsButton(s) throughout the WebComponents that we should add as a setting.   Currently, this pattern is instead re-implemented in a few places using custom CSS inside higher-level components.

![Screen Shot 2022-12-01 at 1 28 30 PM](https://user-images.githubusercontent.com/3249601/205132331-073c7814-5fe5-469c-ab9f-d9d986e4f912.png)

This case doesn't exist in any of the current, standard button examples:  https://main.wc.design.infor.com/ids-button/example.html

**Describe the solution you'd like**
Currently in all IdsButton variants, the `type="tertiary"` setting's button colors are identical to `type="default"`.  The only difference between the Tertiary style and the use case that needs cementing is the Azure color.  I propose we change the tertiary style to use Azure, and replace the custom CSS definitions for this case.  We'd have to also review existing examples that may be using "tertiary" and see if the usage is consistent, switching to "default" otherwise.

**Additional context**
Current custom implementations I'm aware of (I think there are others):
- IdsMonthView/IdsWeekView ("Today" button)
- IdsDatePicker ("Today" button)

**Comment by tmcconechy** [comment]
Relates to the designs on https://www.figma.com/file/VcRDGPFqlp3MJ46mEWkGPf/Buttons?node-id=701%3A1222&t=WrIOqnEcLMAatK6P-0

![Screen Shot 2022-12-01 at 1 43 57 PM](https://user-images.githubusercontent.com/814283/205134564-816d5275-f792-4717-ba4f-46e6c5e7e957.png)

They want to make the secondary non - grey. So probably can reconcile this when we do that one...

**Comment by tmcconechy** [comment]
Relates to https://github.com/infor-design/enterprise-wc/issues/985

**Comment by tmcconechy** [comment]
Think we can close this as it is covered on #1046
