### ISSUE TITLE
IdsDataGrid: Add Contextual Toolbar / Selection Actions

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1029]
**Describe The Feature**

Add an example showing a contextual toolbar. The toolbar appears when you select rows and has actions available for selected row items. https://main-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html

- [ ] Add a toolbar variant
- [ ] Add an example (contextual-toolbar.html) to ids-data-grid examples
- [ ] Grid can check for sibling toolbars on selection
- [ ] Should animate in/out on selection/deselection
- [ ] Show a custom button, that removes selected rows
- [ ] Add a counts - counts can find a specific element (by id or class and update the selected counts) -> keep in mind might also need a toolbar example https://main-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar.html

**Comment by hey-yall** [comment]
Also tracked for IDS Design in Jira: https://jira.infor.com/browse/IDS-970

**Comment by hey-yall** [comment]
@tmcconechy -- I have this issue marked as closed in Jira but it's still open here. What else is needed to close this issue?

**Comment by tmcconechy** [comment]
@hey-yall i guess i just have a question on https://www.figma.com/file/yaJ8mJrqRRej8oTsd6iT8P/branch/l5AQOybL3y2Bp5dX29Dq24/IDS-(SoHo)-Component-Library-v4.5?type=design&node-id=19458-11294&t=K9WrAQYszBOKxOAt-0

It doesnt seem like anything changed and i thought we wanted to get rid of the azure toolbar? Maybe just need a quick walk through on the design. Could do it next grooming maybe

**Comment by tmcconechy** [comment]
In grooming we decided we dont want this pattern. instead use a toolbar that enables actions when the items are selected on the toolbar.

![Screenshot 2023-08-16 at 9 35 33 AM](https://github.com/infor-design/enterprise-wc/assets/814283/fa6e1c20-1af5-4b54-abcf-039a59d352d1)

So we wont add for now unless we here other use cases.

**Comment by inforandy** [comment]
reopening this one to review porting this toolbar over as the patterns work gets a deeper revisit next year

**Comment by tmcconechy** [comment]
@clayinfor it means that we somehow connect the toolbar and datagrid. I was at first thinking by being an immediate sibling like the old example does for example..

```
<ids-toolbar contextual="true">
   <ids-text selection-count></ids-text>
   ....
   <ids-button> 
      ....
</ids-toolbar>
<ids-data-grid>
</ids-data-grid>
```

So i just really mean find the contextual toolbar that works with the grid. Because they are siblings. 

But thinking again about it we could like them a newer way maybe this is better?

```
<ids-toolbar contextual="true" id="grid-toolbar">
<ids-datagrid contextual-toolbar="grid-toolbar">
```

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4485
