### ISSUE TITLE
IdsDate Label: A11Y: Screen reader is unnecessarily reading different information in one go.

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise-wc#1032]
**Describe the bug**
Screen reader is unnecessarily reading different information in one go.
WCAG Guideline: 1.3.1 Info and Relationships

**To Reproduce**

1. Launch the URL: https://main.wc.design.infor.com/ids-data-label/example.html
2. Navigate on page using arrow keys and verify

**Expected behavior**
Screen reader should not read different information in one go.

User Impact: Screen reader user will get confuse if all the information will be conveyed in one go.

**Screenshots**
https://www.screencast.com/t/xYWPFXTuc

Dev Recommendation: Place the content in separate para tag.

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome

**Additional context**

**Comment by tmcconechy** [comment]
Might be just the way your navigating the page? Do you use the virtual cursor? What steps and keys are you using?
