### ISSUE TITLE
IdsTextarea : dirty tracker position is not properly aligned 

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1040]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-textarea/example.html
2. Type a text in `Dirty Tracking `field
3. See error

**Expected behavior**
<img width="431" alt="image" src="https://user-images.githubusercontent.com/56722184/207085872-32bff40a-61d3-4155-9c2e-49c6a55ace07.png">

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="500" alt="image" src="https://user-images.githubusercontent.com/56722184/207085573-e5c369fa-ac61-420a-aab3-b4773ecae434.png">
<img width="461" alt="image" src="https://user-images.githubusercontent.com/56722184/207085644-36964aa6-6e50-442f-87e5-086a48532c4b.png">

**Platform**
Safari & Firefox

**Additional context**

**Comment by jbrcna** [comment]
QA Failed. 
**Safari**
<img width="1663" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/f3a2ac0f-1884-48b0-a514-52ff81480592">

**Firefox**
```diff
- failing in Firefox.dirty tracker position is a bit off. slightly not aligned in the corner
```
<img width="1598" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/83b1ce45-18eb-41da-bb96-d1f547955a6d">

**Comment by tmcconechy** [comment]
@jbrcna this looks ok to me on main now... (localhost)

![Screenshot 2023-12-15 at 10 40 21 AM](https://github.com/infor-design/enterprise-wc/assets/814283/3219bf5e-e167-4fb2-a7c8-b5ebec9513d2)

**Comment by jbrcna** [comment]
QA Passed
verified in
https://main.wc.design.infor.com/ids-textarea/example.html
http://localhost:4300/ids-textarea/example.html

Safari
<img width="1605" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/9aa1cba3-559c-4e4c-9a02-fcdd0a48e57c">

Chrome
<img width="1665" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/63ed1f0c-593d-46a7-a649-4c9f330d0b59">

Firefox
<img width="1569" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/81fa1007-15c3-4128-9b7b-05b896476ecf">

Edge
<img width="1646" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/76124490-a7df-454e-8fcb-6d11f3501266">
