### ISSUE TITLE
ListView - expose `activatedIndex` property

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise-wc#1041]
**Is your feature request related to a problem or use case? Please describe.**
To be able to deactivate item programatically, we need to keep the state of `activatedIndex` ourselves

**Describe the solution you'd like**
The property is in the component code, it's just private, so not accessible in implementation. I'd like to have it public.

**Describe alternatives you've considered**
Keeping own state or iterate and try deactivate all items.

**Comment by EdwardCoyle** [comment]
Need to [expose this](https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-list-view/ids-list-view.ts#L75-L76) and smoke test [all things IdsListView](https://main.wc.design.infor.com/ids-list-view/)

**Comment by deep7102** [comment]
@hohnzy 
Activated Index, can get thru `activatedItem` - it spits the activated index and related data.

```
const listView = document.querySelector('ids-list-view');
listView.activatedItem;
```
