### ISSUE TITLE
Dropdown - possibility to show loading indicator

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise-wc#1048]
**Is your feature request related to a problem or use case? Please describe.**
We are using dropdowns which are retrieving data from backend, in that case we want to have the dropdown disabled and showing loading indicator before the data are ready.

Something similar we already use with ng components
![image](https://user-images.githubusercontent.com/11279863/208130306-05f0c264-3586-4bca-abd3-0d8d60fa3d0c.png)

**Describe the solution you'd like**
Either the possibility to slot loading indicator myself or via component boolean attribute

- [x] Maker a smaller loading indicator (option)
- [x] Setting ids-input to show loading indicator (show-loading-indicator="true")
- [x] Show it on trigger fields (covers the trigger field)
- [x] Show it on buttons via an options

**Comment by tmcconechy** [comment]
I just remembered this is on https://github.com/infor-design/enterprise-wc/issues/684 so may close this in favor of that in the future. But will keep for now. It should look like this:

<img width="239" alt="Screen Shot 2022-12-16 at 10 25 28 AM" src="https://user-images.githubusercontent.com/814283/208131248-91131801-c11e-4e3f-9841-6714eb07d4b0.png">

**Comment by glenlieorillo** [comment]
Tested and passed. Moving this ticket to Done.


https://user-images.githubusercontent.com/102151352/224984012-eecb7370-20f4-4cdc-85ac-cd1056ef73fc.mov
