### ISSUE TITLE
IdsDataGrid - Error while running -> npm run build:dist

### ISSUE THREAD

**Issue by LilBiggs** [infor-design/enterprise-wc#1059]
**Describe the bug**
While trying to build the distributable package of enterprise-wc, there is an error in [save-settings-manual.ts](https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/demos/save-settings-manual.ts#L64) and [save-settings.ts](https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/demos/save-settings.ts#L69). 
`Object literal may only specify known properties, and 'filterTerms' does not exist in type 'IdsDataGridColumn'.`

**To Reproduce**

1. Pull down latest enterprise-wc project
2. Run Command: **npm run build:dist**

**Expected behavior**
No error to happen

**Version**
- ids-enterprise-wc: v1.0.0-beta.2

**Screenshots**
![image](https://user-images.githubusercontent.com/6730716/208946362-c2e71a5d-9dd1-4d61-8708-12698ca5b6e6.png)

**Platform**
 - Infor Application/Team Name: Infor WFM

**Additional context**
This does not happen when you run the regular build command: **npm run build**

**Comment by tmcconechy** [comment]
I noticed this also and it is fixed within https://github.com/infor-design/enterprise-wc/pull/1057

**Comment by LilBiggs** [comment]
Thanks @tmcconechy

**Comment by tmcconechy** [comment]
This issue is fixed in https://www.npmjs.com/package/ids-enterprise-wc/v/1.0.0-beta.6 
This was simply a typescript error that needed fixing.
