### ISSUE TITLE
IdsButton: change "type" setting to "appearance", support HTML "type" attribute

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#1062]
**Is your feature request related to a problem or use case? Please describe.**
There's currently a naming convention issue on IdsButton, where its `type` attribute  is used to define the IDS button style (default/primary/secondary/destructive/etc).  

In addition, we don't currently have a way to set the `type` attribute on the inner HTMLButtonElement in shadow root.  For example, `type="submit"` for form buttons won't work properly.

**Describe the solution you'd like**
- [x] Give a new name to our current `type` setting on IdsButton... We can't use "style" because it conflicts with yet another HTML attribute.  Maybe something like `appearance`, but open to suggestions.
- [x] Implement an attribute getter/setter for `type` that simply sets/gets the HTMLButtonElement's `type` attribute
- [x] Probably will need to update quite a few examples/tests to reflect this change

**Additional context**
Discovered while working on #839

**Comment by tmcconechy** [comment]
What about `appearance` been considering using that for something somewhat similar...
https://www.thesaurus.com/browse/type

But i dont hate purpose

**Comment by EdwardCoyle** [comment]
Appearance might make more sense here, good call
