### ISSUE TITLE
IdsDropdown: Dropdown is cutoff by Data Grid containment

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#1065]
**Is your feature request related to a problem or use case? Please describe.**
This issue is related to #667, with a specific focus on IdsDropdown being cut off by the containment of the IdsDataGrid.  To test:

- Open https://main.wc.design.infor.com/ids-data-grid/filter-trigger-fields.html
- Open the "Location" dropdown
- Pick the menu item containing the "broken" image next to "Canada"
- After the grid filters, re-open the Location dropdown and see how it's cut off by the bottom of the grid:

![Screen Shot 2022-12-23 at 11 48 03 AM](https://user-images.githubusercontent.com/3249601/209372525-4c90b927-d109-4a4a-ba00-44a251c41966.png)

**Describe the solution you'd like**
- [ ] Review if the IdsDropdown can have a "separate" list component outside its own containment.  If not, we need to implement this somehow in a way that's similar to how `IdsPopupMenu`, `IdsDatePickerPopup`, etc are able to connect to their triggering elements with an attribute (currently done with an ID reference)
- [ ] Re-implement the "dropdown" filter to account for the separate list component
- [ ] Fix examples/tests/docs to match

**Additional context**
- Discovered while working on #667

**Comment by glenlieorillo** [comment]
Tested and passed.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/223896756-6fe7db87-5fda-4f8f-8071-c2e4236bd6fb.png">

**Comment by glenlieorillo** [comment]
Tested and passed.

https://main.wc.design.infor.com/ids-data-grid/filter-trigger-fields.html
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/225275176-91e63e0e-2cf2-453e-9880-7a603d98659f.png">
