### ISSUE TITLE
IdsDataGrid: Shorter Row Height

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1072]
**Describe the bug**
M3 wants even more room in the data grid. 25px rows and smaller font size. Header height stays as is to avoid too much variation and bugs.

- [x] Reduce font by 2 for XS and XXS
- [x] Fix alignment on header to match rows
- [x] Effective Row Height is 25px instead of 31
- [ ] Test editing and other features
- [ ] Can change this example to XS: http://localhost:4300/ids-data-grid/m3-features.html

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/row-height.html
3. Set row height -> should be 25 now

**Expected behavior**
They want it even smaller down to 25px
**Additional context**
M3 

![Untitled](https://user-images.githubusercontent.com/814283/210627668-92aed4a7-1e1c-4244-a0d0-eb5337df58c6.png)

![image](https://user-images.githubusercontent.com/814283/214327230-fd89e1b2-5a1b-4be8-aa91-0f4b16c51e68.png)

**Comment by tmcconechy** [comment]
Compact Mode Start Point: https://www.figma.com/file/CUC6hyMtzodsfU13Lsbw6G/Input?node-id=1579%3A1394&t=brkkIMUCRq4nxQKT-1

**Comment by tmcconechy** [comment]
Ok So to clarify @inforandy see the original comment. i updated it to how I think we should fix this...

**Comment by tmcconechy** [comment]
@GMInf We are trying to work on this soon. Just a couple clarifications. We will call this XXS (Extra Extra Small Mode)

- Whats the font size? On both the cells and headers?
- Whats the exact header height? Can we vary that a little? With and without filter.
- Whats the exact row height (25px)?
- What about the sort indicator and drag indicator? How can that fit?

**Comment by tmcconechy** [comment]
Thanks @GMInf would this be ok?

- Change the header a little (our icon isnt like that for drag and wont fit it has a double border)
- Vary this to 25px so it matches (30, 35, 40)
- Vary the header a little
- We dont use 13px font size only 14px or 16px

**Comment by inforandy** [comment]
Those changes would work from my side; @GMInf, are these slight variations acceptable from your end?

**Comment by hey-yall** [comment]
Brought to designers in Jira ticket IDS-1058: https://jira.infor.com/browse/IDS-1058

**Comment by GMInf** [comment]
Hi @tmcconechy,
Regarding the drag handle for xxs size, our team would like the one column of dots, similar to the sohodatagrid.
<img width="179" alt="image" src="https://user-images.githubusercontent.com/53523076/235111159-9b403734-cc20-40fa-a5d2-16692c6f3dea.png">

**Comment by tmcconechy** [comment]
@GMInf yeah i think we should use that icon, especially at the lowest size

**Comment by glenlieorillo** [comment]
Tested and Passed.

https://github.com/infor-design/enterprise-wc/assets/102151352/4b676f94-a5ea-43e0-b51f-843702ea4022
