### ISSUE TITLE
IdsDataGrid: Scroll to bottom and add rows

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1074]
**Describe the bug**
M3 (maybe) wants to see an example where when you scroll to the bottom a callback happens and you can append more rows. May only need it if virtual scrolling isnt really fast.

**Expected behavior**
Should work like https://main-enterprise.demo.design.infor.com/components/listview/example-footer-navigation.html

**Additional context**
M3 Call - But needs discussion
May also explore - load data from the backend during virtual scrolling... vs infinite scroll

**Comment by tmcconechy** [comment]
May also explore - load data from the backend during virtual scrolling... vs infinite scroll

**Comment by glenlieorillo** [comment]
Tested and passed.

https://main.wc.design.infor.com/ids-data-grid/infinite-scroll.html
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/224228020-5e6b2d23-d9e4-4587-a421-67aa332414d8.png">

https://user-images.githubusercontent.com/102151352/224228116-47e6971c-363d-40a0-a8b7-b4831c0060f2.mov

https://main.wc.design.infor.com/ids-data-grid/virtual-scroll-infinite-scroll.html
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/224228175-63fa1ce6-23c8-40bd-a4f1-5e8c99f75582.png">


https://user-images.githubusercontent.com/102151352/224228192-0316d77a-7792-489d-86e7-9c2fae267790.mov
