### ISSUE TITLE
IdsActionPanel: dropdown menu looks off

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1078]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-action-panel/example.html
2. Open Action Panel
3. Verify each drop down

**Expected behavior**
dropdown menu should be the same size as its parent

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="515" alt="image" src="https://user-images.githubusercontent.com/56722184/210337579-a161fb3a-54a6-4551-a828-3f0bdf537f0c.png">

**Platform**
all

**Additional context**

**Comment by tmcconechy** [comment]
@andriivarhanov this one you can pick up?

**Comment by andriivarhanov** [comment]
@tmcconechy sure

**Comment by jbrcna** [comment]
this is now working as expected. thank you
<img width="552" alt="image" src="https://user-images.githubusercontent.com/56722184/212355009-908a5ca9-95af-46f6-984f-bb097eeede06.png">
