### ISSUE TITLE
IdsEditor: Text color not working in safari

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1079]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-editor/example.html
2. Highlight a text
3. Click `text color` button
4. See error, nothing happens

**Expected behavior**
should display a color picker and able to choose a color

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![Large GIF (1476x438)](https://user-images.githubusercontent.com/56722184/210338672-680251d8-2216-473d-95e7-f34eac185090.gif)

**Platform**
Safari 

**Additional context**

**Comment by tmcconechy** [comment]
Probably the same as this issue https://github.com/infor-design/enterprise-wc/issues/983

**Comment by glenlieorillo** [comment]
This is now working as expected.


https://github.com/infor-design/enterprise-wc/assets/102151352/8e277491-b0d1-4901-81fc-a3cfca4770af
