### ISSUE TITLE
IdsTriggerField: The trigger button padding should be equal distance on each side

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1091]
**Describe the bug**
Noticed in different sizes the trigger button distance from the right side is the same in all sizes. It should match the distance between the text on the other side.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-dropdown/sizes.html
2. Look at the sizes xs, sm, md, lg
3. See how the text on the left side indents a certain distance but the icon on the right side is all the same
4. Check all trigger fields
5. Check RTL as well
6. Check data grid editors as well

**Expected behavior**
All icons should roughly match the distance to the right side that the text has on the left size.

**Screenshots**
<img width="404" alt="Screenshot 2023-01-06 at 10 35 05 AM" src="https://user-images.githubusercontent.com/814283/211044767-e633d035-357d-4d4f-b80d-d811dd872080.png">

**Additional context**
#1087

**Comment by jbrcna** [comment]
QA Passed
<img width="272" alt="image" src="https://user-images.githubusercontent.com/56722184/222032345-992243ce-179c-477b-a194-a967308ff1d5.png">
<img width="282" alt="image" src="https://user-images.githubusercontent.com/56722184/222033420-1fe34ac2-30a7-49a3-a72a-1a35b3c937a9.png">

<img width="877" alt="image" src="https://user-images.githubusercontent.com/56722184/222032373-6236d884-bf93-4518-b755-763cc7fafaef.png">
