### ISSUE TITLE
Chore: Add time delay to some Percy tests

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#1106]
**Describe the bug**
When our build checks run, a handful of Percy tests seem to consistently fail, either because the page contents haven't loaded in time (screenshot of component turns blank), or because a previously "blank" screenshot suddenly displays a component.

**To Reproduce**
Reproducing this problem depends on how the percy tests execute (speed/available resources/etc), so the only way to reproduce is simply to push a PR and wait.  Often we get [test runs that look like this](https://percy.io/00aaa841/enterprise-wc/builds/24385634/changed/1363973692?browser=chrome&browser_ids=31&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C1280)

For example, the Percy test `ids-bar-chart-horizontal-grouped` produced this test result on this run:

| Baseline (original) | New | Combined |
| ---- |  ---- | ---- |
| ![cc7027a4fd486f646b05019a833cc97dd64b2fcd55c1d209c76cab10c0251c33](https://user-images.githubusercontent.com/3249601/213715121-a7b0dad4-4149-4f58-bfdf-01360c9be3cb.png) | ![009934d5ee54196bae0bc952467ac2a9b8f8fcc41bfeca6de92271a7f278fd0f](https://user-images.githubusercontent.com/3249601/213715162-2a4632c6-a148-490d-8787-2f8794c0ff7a.png) | ![5dfbdf0bd0f000408ac28229f798a9bdea7a74dfbfb849f8566e414d9308b7c5](https://user-images.githubusercontent.com/3249601/213715228-9b9865a2-732d-406b-8825-b3022c7fdb1e.png) |

If we "Accept" the results of this test, it's likely a future Percy test will come up with the opposite result (bar chart exists in baseline images, but would be blank in the new test run)

**Expected behavior**
Screen captures should be more predictable.

One thing we can try in some of these tests is simply waiting longer than the "load" or "DOMContentLoaded" events.  It's likely some of these charts and other components are doing processing that occurs after these events fire.

**Additional context**
This is a known list of Percy tests affected by this problem:
- [ ] ids-bar-chart-horizontal
- [ ] ids-bar-chart-horizontal-grouped
- [ ] ids-bar-chart-horizontal-rotate-name-labels
- [ ] ids-scroll-view-new-light/dark/contrast
- [ ] ids-about-new-light
- [ ] ids-about-new-dark
- [ ] ids-about-new-contrast

**Comment by tmcconechy** [comment]
From what I have observed

- the chart tests can have animated = "false", if not there. This has fixed some
- had a thread about the text "moving" on the about page - may not be solvable. Could be that we try this delay or get rid of this test
- look at new API options

**Comment by tmcconechy** [comment]
No longer needed
