### ISSUE TITLE
Chore - Separate translations/locale

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#1107]
**Is your feature request related to a problem or use case? Please describe.**
From what I can tell, about half of the `enterprise-wc.js` bundle ( ~2.5MB out of ~5MB ) is translation/locale/cultures data:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/4991954/214005965-afa3b360-8e78-42aa-b7ed-831775eb0b03.png">

That means that when loaded in the browser, at least half of the bundle will never be used, assuming the user only needs one language/locale. This is a big deal, since the bundle is already quite large.

**Describe the solution you'd like**
Add a way to separate locale files from the bundle, and a way to lazily load the needed file(s). Something like:

1. `IdsCotainer.setLanguage("en-US")` which would do a dynamic `import()` or `fetch()` the "en-US" locale files
2. `IdsContainer.setLanguage(languageFilePromise)`, like `IdsContainer.setLanguage(import("path/to/en-US.js"))`

**Additional context**
And what application do you work on? [e.g. {Infor XYZ}] InforOS Portal / Homepages

**Comment by tmcconechy** [comment]
Working on this as part of #1063 #814

**Comment by tmcconechy** [comment]
@anhallbe this is completed in https://github.com/infor-design/enterprise-wc/pull/1121 i also released a test package https://www.npmjs.com/package/ids-enterprise-wc/v/1.0.0-beta.6

You will see a substantial size difference (approx 85mb to 19mb). And each file is lazy loaded and code shared via ESM. The locales are fetched as needed and not part of the package.

In angular the assets need to be setup https://github.com/infor-design/enterprise-wc-examples/pull/30/files#diff-d4465bd1a2f96ad9ff9b68e989fafc3854aac06fc0516702455b4becbdd2c699R64

![Screenshot 2023-02-07 at 12 41 33 PM](https://user-images.githubusercontent.com/814283/217322592-756d861f-731f-4186-bc4a-68fc1e019308.png)

Will be closed with that PR.
