### ISSUE TITLE
IdsPopupMenu: Request to add a way for adding shortcut keys on menu items

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1108]
**Is your feature request related to a problem or use case? Please describe.**
Feature to add shortcut key icons in IdsPopupMenu both in html and data object

**Describe the solution you'd like**
- [x] Add a label to display the shortcut keys, similar to the ids enterprise. 
- [x] A new property key should also be available on the context menu data so that shortcut keys can be set in the IdsPopupMenu data object.
- [x] Add TS Types for the [data object that can be passed to ids-menu](https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-menu/ids-menu.ts#L343). The types should match what's available in [this example structure](https://github.com/infor-design/enterprise-wc/blob/main/src/assets/data/menu-contents.json)

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/53523076/214802718-4df9bd21-b2fa-427c-a050-324a4d541469.png)

**Comment by jbrcna** [comment]
QA Passed. moving this ticket to done
https://main.wc.design.infor.com/ids-popup-menu/shortcut-keys.html
<img width="807" alt="image" src="https://user-images.githubusercontent.com/56722184/225192284-bb95864b-bd53-4cd8-ad18-d8a475aed450.png">
