### ISSUE TITLE
IdsDatagrid: Context menu cannot  display all items 

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1119]
**Describe the bug**
When the context menu has a lot of items, not all items are display or inaccessible.

**To Reproduce**

1. Open enterprise-wc
1. Update contextmenu-thru-data.ts
2. Add more to items in id: 'actions-group'
3. npm start
4. Open contextmenu-thru-data.html
5. Right click on the header
6. Error, context menu items is cut

**Expected behavior**
Contextmenu should have a scroll bar when there are a lot of items

**Version**

ids enterprise wc 1.0.0-beta.3

**Screenshots**
![image](https://user-images.githubusercontent.com/53523076/216998822-b0a9cf21-d4ce-49ae-b349-b0ce07cbb050.png)

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: [chrome
Browser Version: 109.0.5414.75 (Official Build) (64-bit)

**Additional context**

**Comment by jbrcna** [comment]
this is now working as expeted.
`edge` , `chrome`
<img width="884" alt="image" src="https://user-images.githubusercontent.com/56722184/222037305-032c81c7-041b-4d6b-b2d5-10144cbd709a.png">

`safari` , `firefox`
<img width="885" alt="image" src="https://user-images.githubusercontent.com/56722184/222037500-4aa2e032-8f32-4855-87f6-44d8d46c678e.png">

**Comment by GMInf** [comment]
I encountered an issue on a slightly different scenario when there is a sub menu included on the context menu. Contextmenu level 1 is ok but when expanding the sub menu, it is inside the container of the main context menu. Here are some screenshots to better show the issue.
![image](https://user-images.githubusercontent.com/53523076/226868094-b0ed1056-64fb-4fef-8859-452bf74a82d2.png)

![image](https://user-images.githubusercontent.com/53523076/226868137-b12efc8e-4416-49be-b050-213d18ffd030.png)

To replicate this, 
1) update src\assets\data\menu-contents.json
2) Add more items in the main context menu so that the scrollbar will show
3) Open http://localhost:4300/ids-data-grid/contextmenu-thru-data.html

**Comment by tmcconechy** [comment]
What exactly in terms of items do you need to add @GMInf ?
CC @deep7102 for possible follow up fix?

**Comment by tmcconechy** [comment]
@GMInf made a new issue https://github.com/infor-design/enterprise-wc/issues/1205
