### ISSUE TITLE
IdsDataGrid: 'Name' column is not readable in Dark Mode.

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#1128]
**Describe the bug**
'Name' column is hard to read in Dark Mode.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/tree-grid-custom-css.html
2. Change to Dark Mode
3. Notice the 'Name' column

**Expected behavior**
'Name' column should be readable like the other column.

**Screenshots**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/218451087-4d7ce899-7969-410d-8c5e-ebc755311f54.png">

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
Was fixed in https://github.com/infor-design/enterprise-wc/pull/1273

**Comment by jbrcna** [comment]
QA Passed
<img width="1648" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/4a7c8a12-50fb-4151-853b-88339938e1aa">
