### ISSUE TITLE
IDSMonthView - Ability to import css classes in example.ts of demos folder

### ISSUE THREAD

**Issue by rvajjhala** [infor-design/enterprise-wc#1129]
**Is your feature request related to a problem or use case? Please describe.**

We have a requirement to change the color of date boxes from grey to yellow/orange when user hovers/selects particular dates.

**Describe the solution you'd like**

As of now, we are unable to achieve the html/styles (scss) for adding/aligning the icons for the custom web components. Also using inline css may not be an ideal solution and for example.ts it seems we dont have feasibility to import styles from external css/scss files.

<img width="175" alt="image2022-5-16_13-13-49" src="https://user-images.githubusercontent.com/121239029/218774847-19844dcd-1f8b-4ff7-8a84-8f9f80fe8663.png">

**Describe alternatives you've considered**

We have modified the code of ts(html) and scss(classes) files of IDS-MONTH-VIEW which seems to be working fine as per our requirement. But if we receive any update from IDS then all of our changes might be overwritten or might need to rework on mentioned above changes.

**And what application do you work on?** Infor WFM

**Comment by tmcconechy** [comment]
Because the web components are encapsulated we cant import working css the normal way. We have to use other methods. I think https://github.com/infor-design/enterprise-wc/issues/1130 covers this issue. We will try and make an example and show you how with that issue.
