### ISSUE TITLE
IdsMonthView - Ability to import css classes in example.ts of demos folder

### ISSUE THREAD

**Issue by rvajjhala** [infor-design/enterprise-wc#1130]
**Is your feature request related to a problem or use case? Please describe.**
We have a requirement to add/align icons to the left side of date number in the box of month view in calendar component with a predefined color for the icons. These icons will be shown for selected dates which would be received in an event/API call (data for dates and icons will be read from here).

**Describe the solution you'd like**
As of now, we are unable to achieve the html/styles (scss) for adding/aligning the icons for the custom web components. Also using inline css may not be an ideal solution and for example.ts it seems we dont have feasibility to import styles from external css/scss files.
<img width="134" alt="image2022-5-23_23-33-50" src="https://user-images.githubusercontent.com/121239029/218776190-47c5e259-a46e-4d10-bd35-33f9a40b88f2.png">
<img width="140" alt="image2022-5-23_23-27-36" src="https://user-images.githubusercontent.com/121239029/218776194-8eb3b4ce-df87-4b0b-ae5d-3e6c5781e0e4.png">

**Describe alternatives you've considered**

We have modified the code of ts(html) and scss(classes) files of IDS-MONTH-VIEW which seems to be working fine as per our requirement. But if we receive any update from IDS then all of our changes might be overwritten or might need to rework on mentioned above changes.

**Additional context**

And what application do you work on? Infor WFM

**Comment by tmcconechy** [comment]
Are these icons functional when clicked or informational only? 
Do you have a designer that can look at this? Do you have some flexibility on the designs as i dont think they currently follow our guidelines for colors, placement and spacing and discoverability.
Can you explain what the colors mean and that they do?

Those questions being said, i think we can make an example of customizing the event look as that could give flexibility but will require an enhancement

**Comment by tmcconechy** [comment]
BTW you might want to read about Css Encapsulation to understand why importing a css file doesnt work in the normal way https://dev.to/jmckenney/web-component-style-encapsulation-in-5-minutes-1ihj

**Comment by tmcconechy** [comment]
Cool so basic summary:

- the event color -> is related to the legend?
- the icons on top or informational -> and are orange due to an alert situation about the day?
- whats the green thing on the bottom corner?
