### ISSUE TITLE
IdsCalendar: Ability to get view picker change event control outside Calendar component

### ISSUE THREAD

**Issue by manoj-kothuri** [infor-design/enterprise-wc#1131]
**Is your feature request related to a problem or use case? Please describe.**
The IdsCalendar component view picker change event listener control is not emitting to outside class where we can override the event pills Y_OFFSET position and set the MAX_EVENT_COUNT dynamically.

**Describe the solution you'd like**
We have our own class to handle the overriding of event pills position (Y_OFFSET) and handle the maximum number of event pills displaying in a day cell dynamically instead of fixed value of 3. As of now we implemented the logic in new class which is working fine for the initial load of Month view but when we change the views and comeback to Month view again the overriding logic is not working.

**Describe alternatives you've considered**
We tried to override the event pill Y_OFFSET position and event overflowing by adding the logic in CustomCalendarEvent class which is meant to be purely override the event pill template (multi line). As it's not ideal to use this class to handle the event pill positions and other logic.

**Additional context**
<img width="428" alt="image" src="https://user-images.githubusercontent.com/113168229/218730017-255f2392-c224-498b-a416-69cdd49f1b57.png">

And what application do you work on? Infor WFM

**Comment by tmcconechy** [comment]
Not sure I understand this issue....

**Comment by tmcconechy** [comment]
Maybe this needs an example setup to see it better?

**Comment by manoj-kothuri** [comment]
> Maybe this needs an example setup to see it better?

Under ids-calendar/demos folder example-custom.html is having the example wherein we can replicate the issue.

**Comment by tmcconechy** [comment]
Ok thanks @manoj-kothuri this is a little unclear to me. Do you think you can reframe the issue in terms of steps to reproduce/expected behavior ect?

**Comment by manoj-kothuri** [comment]
> Ok thanks @manoj-kothuri this is a little unclear to me. Do you think you can reframe the issue in terms of steps to reproduce/expected behavior ect?

As suggested I used the steps recorder to showcase the issue, please find the below attached zip file for the same.
[IdsCalendar Steps Recording.zip](https://github.com/infor-design/enterprise-wc/files/10786074/IdsCalendar.Steps.Recording.zip)

So our main concern is we have implemented a logic to position the event pills accordingly based on the size (if fits in the day cell), it works on the initial load of the calendar. But, when we select the Week view or Day view and navigate back to Month View the event pills are getting overlapped as our logic is not getting called.

So could you suggest any approach to overcome this issue.
