### ISSUE TITLE
IdsThemeSwitcher: Error When menu is not included / Cannot be hidden

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1136]
**Describe the bug**
Noticed in MS Teams and reported. It is not possible to make an ids-theme-switcher hidden and use it to control themes.

**To Reproduce**

1.  Make a page with `<ids-theme-switcher mode="dark" hidden></ids-theme-switcher>`
2. Load the page
4. See errors a) an error configureMenu not found b) it is not hidden

**Expected behavior**
Can hide a theme switcher as mentioned in the docs

**Additional context**
[Add any other context about the problem here.
](https://teams.microsoft.com/l/message/19:b649a7c426e64e3dbedb0cc5202ce2d4@thread.skype/1676217716239?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1676217716239&teamName=IDS%20Enterprise%20Development&channelName=Web%20Components&createdTime=1676217716239&allowXTenantAccess=false)

**Comment by tmcconechy** [comment]
Note on this fix. You probably want hidden on the ids-container to avoid a flash of unstyled content.

```
  <ids-container hidden>
    <ids-text translate-text="Legend">Legend</ids-text>
    <ids-theme-switcher mode="dark" hidden></ids-theme-switcher>
  </ids-container>
  ```

**Comment by glenlieorillo** [comment]
Working as expected.

https://main.wc.design.infor.com/ids-theme-switcher/hidden.html
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/219594162-21e49024-5940-4dd1-bd92-0eeeaa0508f4.png">
