### ISSUE TITLE
IdsAlert: Add ability to support any icon

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1138]
**Describe the bug**
Need to be able to change any icon to an alert icon.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-alert/example.html
2. Change the icon property to calendar `<ids-alert icon="calendar" tooltip="Error" mode="light"></ids-alert>`
4. See it doesnt have a color

**Expected behavior**
3 separate properties, one for icon, one for color and one for size (that uses the icon sizes)

```
<ids-alert icon="calendar" color="error" tooltip="Error" mode="light" size="xs"></ids-alert>
```

**Additional context**
Will break the API since this is a new and beta

**Comment by jbrcna** [comment]
QA Passed.
https://main.wc.design.infor.com/ids-alert/example.html
<img width="472" alt="image" src="https://user-images.githubusercontent.com/56722184/223608007-2c4d9f41-07c9-409c-b1d0-1acd47bd21db.png">
