### ISSUE TITLE
IdsDropdown: Default Keyboard Behavior Stopped Working

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1144]
**Describe the bug**
Can no longer type on default dropdowns in a similar way to a standard select element.

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-dropdown/example.html
2. tab to first dropdown
3. type h
4. see error -> nothing happens should select Hawaii

**Expected behavior**
The default behavior should be similar to https://main-enterprise.demo.design.infor.com/components/dropdown/example-no-search-lsf.html i.e.

- when closed typing a character or series of characters selects the next one found without opening
- when open typing a character will go to the item in the list but not select it

Also like https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

- this method https://main.wc.design.infor.com/ids-dropdown/typeahead.html used on multiselect should still work / multiselect behavior should not change
- should not happen if disabled or readonly

**Additional context**
This worked when this component was introduced but stopped working at some point.

**Comment by andriivarhanov** [comment]
@tmcconechy typeahead is turned off by default, it works here https://main.wc.design.infor.com/ids-dropdown/typeahead.html where it's enabled

**Comment by tmcconechy** [comment]
@andriivarhanov yes but that is slightly different. Maybe this shouldnt be called "typeahead" tho. I mean the default keyboard behavior should be:

- like https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select for dropdown
- like https://main.wc.design.infor.com/ids-dropdown/typeahead.html for mainly multiselect

https://main.wc.design.infor.com/ids-dropdown/typeahead.html might pass but the default behavior used to be different

**Comment by andriivarhanov** [comment]
@tmcconechy 
> Maybe this shouldnt be called "typeahead" tho.

yeah, it's called `autocomplete` initially, got renamed to `typeahead` during PR review, can be anything, the change will not take much time

**Comment by tmcconechy** [comment]
@andriivarhanov i just meant in my issue `typeahead` is ok for the name when its like https://main.wc.design.infor.com/ids-dropdown/typeahead.html (can be anything reasonable to me too and either works). 

But the main thing i was missing is that https://main.wc.design.infor.com/ids-dropdown/example.html when not set to showing the search field/autocomplete/typeahead. Should still work like the "Expected behavior" above. I.E. can type to pick still like a normal select (this could be an additional setting or a "three way" setting)

1. default: typing "goes to the item"
2. typeahead: has a search/typeahead field (used for multiselect or anytime if needed)
3. none

**Comment by andriivarhanov** [comment]
@tmcconechy oh, now I get it, so like `No-Search Dropdown` example from https://main-enterprise.demo.design.infor.com/components/dropdown/example-no-search-lsf.html , thanks for the clarification
