### ISSUE TITLE
IdsText: Csp Error

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1152]
**Describe the bug**
IdsText is giving a csp error - inline styles are not allowed

**To Reproduce**

1. Go to http://localhost:4300/ or http://localhost:4300/ids-text/typography.html
2. Check console error

**Expected behavior**
No error

**Additional context**
Not allowed to do this inline need to use CSSDOM https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-text/ids-text.ts#L105

**Comment by jbrcna** [comment]
QA Passed. moving this ticket to done
https://main.wc.design.infor.com/ids-text/typography.html
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/56722184/225190985-6b1719b4-037e-44d5-8436-28f1f0435e2f.png">
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/56722184/225191351-c40c4449-c082-438a-bb71-1bdff89da7e9.png">
