### ISSUE TITLE
IdsDataGrid: Change Sort to use Excel Like Sort

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1158]
**Describe the bug**

The logic has been changed in EP for sort to match what excel does. On an initial quick attempt i couldn't make it work in this project.

Sort function is noted on https://github.com/infor-design/enterprise/pull/7263/files 

**To Reproduce**

1. Go to new example https://github.com/infor-design/enterprise-wc/pull/1159/files
2. Click on product name
4. Sort should match https://main-enterprise.demo.design.infor.com/components/datagrid/test-combo-sort.html

**Expected behavior**
This is how Excel sorts this kind of data:

- numeric values are grouped together (sorted numerically)
- text values are grouped next (sorted alphabetically)
- blank values are at the bottom of the list (both ascending and descending)
- For example, Excel will sort like this:

Ascending: 1, 2, 07, 11, 1a, 22a, 2ab, a, B, c
Descending: c, B, a, 2ab, 22a, 1a, 11, 07, 2, 1

Add docs for this as well and tests

**Additional context**
Can either use this solution or another https://github.com/infor-design/enterprise/issues/6787#issuecomment-1398479727 depending what works

**Comment by hey-yall** [comment]
Also tracked in Jira for designers: https://jira.infor.com/browse/IDS-962

**Comment by janahintal** [comment]
QA Passed. Now working as expected in https://main-enterprise.demo.design.infor.com/components/datagrid/test-combo-sort.html thanks!
