### ISSUE TITLE
IdsMessage: Add new web component 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#117]
**Phase 1 Features (MVP)**
- Message Types
- Api to Programatically show a message
- Callbacks for when the buttons are pressed
- Accessible Markup
- Xss (allowedTags feature)
- Ability to set the buttons

**Future Features (Not Now)**
- Adjustable width
- Extra Css Class (will use parts instead)
- returnFocus option and noRefocus option
- overlay adjustments

**Suggested API**
```
const message = new IdsMessage();
message.title = 'Delete this Application?';
message.message = 'You are about to delete<br/>this application permanently.<br/>Would you like to proceed?';
message.type = 'alert'
message.show();
```

And
```
<ids-message visible="true">
  <ids-text slot="title">...</ids-text>
  <ids-text slot="message">...</ids-text>
  <div slot="buttons>
    <ids-button>OK</ids-button>
    <ids-button>Cancel</ids-button>
 </div>
</ids-message>

**Suggested Internal Markup**
```js
TBD - Based on how modal looks
```

**Suggested Dependencies**
- ids-modal
- ids-text

**Suggested External Markup**
```js
TBD - Based on how modal looks
```

**Settings**
- title (string / live)
- message (string / live)
- type (string / live)
- buttons (array / not live)

**Events**
- beforehide (vetoable)
- beforeshow (vetoable and async)
- show
- hide

**Other**
Pass the following checklist ordered in priority (some may be left for later)

**Comment by EdwardCoyle** [comment]
This one's a duplicate of #200, which we finished already.
