### ISSUE TITLE
IdsTimePicker: Invalid value when day period goes first in the time format

### ISSUE THREAD

**Issue by andriivarhanov** [infor-design/enterprise-wc#1189]
**Describe the bug**
Similar issue as in EP https://github.com/infor-design/enterprise/issues/7116 just for the web component, the timepicker doesn't format value correctly when day period goes first in the time format

**To Reproduce**
- Go to https://main.wc.design.infor.com/ids-time-picker/example.html
- Change the locale to `ko-KR` in the browser's console `document.querySelector('ids-container').locale = 'ko-KR'`
- Select a time, see the error, 
  - `Time Picker - default` example showing day period after numeric time 
  - `Time Picker - required` triggers error message

**Expected behavior**
The timepicker should format value correctly by the locale's time format

**Additional context**
- errors in the console when selection some locales from theme switcher menu
- issues with selection a time on the page https://main.wc.design.infor.com/ids-time-picker/sandbox.html

**Comment by tmcconechy** [comment]
Feel free to pick this up @andriivarhanov when you have time

**Comment by jbrcna** [comment]
QA Passed.
`ko-KR `
<img width="280" alt="image" src="https://user-images.githubusercontent.com/56722184/234795052-6274210e-8e4b-4854-8af9-0a18053523f6.png">

`zh-Hans`
<img width="358" alt="image" src="https://user-images.githubusercontent.com/56722184/234794769-e3bcfae3-4db9-4a08-8f80-6ba565a1eaf7.png">
