### ISSUE TITLE
IdsIcon: Publish Icon woff2

### ISSUE THREAD

**Issue by pbal** [infor-design/enterprise-wc#1191]
IDS library should also publish icons in woff2 format. This allows 
- compression of icon library before it hits browser
- consuming app to avoid injecting svg in html dom before using any icon. 

With woff2 asset, app can link the asset and refer to the icon name via content attribute. If library can provide ready to use css classes with content already set that would be great.

**Comment by tmcconechy** [comment]
Will probably do this as part of this code base.. At some stage..

**Comment by manbearwiz** [comment]
I took a quick pass at this in case you find it helpful. Here's the important part

https://github.com/manbearwiz/strokes2font/blob/0a98ae60f994c45d65215e27cd9b58237a07050d/index.js#L47-L57

```
  const stream = fs
    .createReadStream(filePath, { encoding: "utf8" })
    .pipe(
      replaceStream(
        'xmlns="http://www.w3.org/2000/svg"',
        'xmlns="http://www.w3.org/2000/svg" fill="none"'
      )
    )
    .pipe(strokeToPath())
    .pipe(new SVGOTransform())
    .pipe(outputStream);
 ```
 
`svgtofont` needs paths with fill. Since ids icons are just strokes without fill, I first add `fill=none` to each svg and then use the Inkscape `object-stroke-to-path` to convert those strokes to paths with fill. SVGO just cleans them up a little so `svgtofont`  doesn't complain. The main issue remaining seems to be on svgs with `fill-rule="evenodd"`. This open issue https://github.com/nfroidure/svgicons2svgfont/issues/62 has some more details and potential workarounds, including a [figma plugin](https://www.figma.com/community/plugin/771155994770327940/Fill-Rule-Editor).

You can see the output font and its issues on this [generated github pages site](https://manbearwiz.github.io/strokes2font/).

**Comment by manbearwiz** [comment]
yeah it is mostly the `-filled` variants that cause issue but here are some others.
![image](https://user-images.githubusercontent.com/3688847/230119730-6211b139-1b18-459e-9ae9-2d610dbfff25.png)![image](https://user-images.githubusercontent.com/3688847/230119867-25991aeb-8356-44e3-b258-98167a138e43.png)![image](https://user-images.githubusercontent.com/3688847/230120008-52cf48d1-ce10-4281-8b6f-2762879a068e.png)

These icons with `fill-rule="evenodd"` aren't just strokes like the other icons, they already have fill between paths. This is the articles icon in `ids-identity`.

```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
    <path clip-rule="evenodd"
        d="M15.213 2C12.15 2 10.05 2.35 9 3.05 7.775 2.263 5.062 2 2.787 2c-.175 0-.437.087-.524.263-.175.087-.263.35-.263.525v10.85c0 .437.35.787.788.787 4.462 0 5.337.787 5.425.962A.84.84 0 009 16c.438 0 .7-.262.787-.7.438-.438 2.975-.875 5.425-.875.438 0 .788-.35.788-.788V2.787A.784.784 0 0015.213 2zm-7 11.55c-1.05-.438-2.626-.613-4.638-.7V3.575c2.187.087 4.287.437 4.637.875v9.1zm1.574.087c1.05-.437 2.538-.612 4.638-.7V3.575c-2.188.087-4.288.437-4.638.875v9.187z"
        fill="currentColor" fill-rule="evenodd" stroke="none"></path>
</svg>
``` 

Inspecting that path in an online path editor, without the fill-rules, you see something similar to the glyph shown in the font
![image](https://user-images.githubusercontent.com/3688847/230123165-8fe4b79e-4a95-4cdd-90f4-12a880b57ddc.png)

**Comment by tmcconechy** [comment]
OK not that familiar with this but maybe we can drop the filled ones and fix the others. Im seeing a few hundred with that rule in it. WIll review with design before we add this officially

**Comment by tmcconechy** [comment]
@danielortiz1982 can you make a Jira for Artem to look at options for exporting from figma to an icon font (both icon sets) (HLO)

**Comment by tmcconechy** [comment]
[IDS-V5-v1.0.zip](https://github.com/infor-design/enterprise-wc/files/13231177/IDS-V5-v1.0.zip)

new font to test and integrate... Manual steps 

1. export from https://www.figma.com/file/NYzUbtJYc4aFh9f4LKjiUN/IDS-System-Icons%3A-5.0?node-id=111%3A11855&mode=dev
2. import into https://icomoon.io then export from there.

**Comment by manbearwiz** [comment]
Nice. Exporting from figma seems to have fixed the fill rule issues. Ideally it would also support ligatures so they can be used like `<i class="ids">alert</i>` without needing css class definitions for each individual icon. I was able to get that working by  dumping the svgs out of your svg font and making a ligature font with the `svgtofont` cli.

[ids-icons.zip](https://github.com/infor-design/enterprise-wc/files/13300122/ids-icons.zip)

**Comment by tmcconechy** [comment]
Yes, @manbearwiz the hold up will be that we want these new icons next year and not sooner but i plan to implement this in the web component so would be something like...

```
<ids-icon icon="alert">
  <shadowRoot>
     <i class="ids-icon">alert</i>
</ids-icon>
````

I.E. whatever i need to implement it for every icon goes in ids-icon. But didnt need to rush that yet do to the timing.

**Comment by tmcconechy** [comment]
@talkaboutdesign can you clarify when you have a chance on exactly how to do these steps:

1. export from https://www.figma.com/file/NYzUbtJYc4aFh9f4LKjiUN/IDS-System-Icons%3A-5.0?node-id=111%3A11855&mode=dev
2. import into https://icomoon.io/ then export from there.

Not seeing exactly how to export them

**Comment by tmcconechy** [comment]
Closing this off its been added to https://github.com/infor-design/ids-foundation
I ended up not using the font for the purposes of this repo however (hard to serve it in a web component). So `<ids-icon>` does not use it.

Will update more docs on it as needed on that new repo
