### ISSUE TITLE
IdsDatagrid: ScrollRowIntoView does not go the the expected row

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1198]
**Describe the bug**
When IdsDataGrid.ScrollRowIntoView() does not go the the expected row

**To Reproduce**

1. Open http://localhost:4300/ids-data-grid/virtual-scroll-infinite-scroll.html
2. Scroll down up to the last record (363) and go back to the top
3. On the console log, run document.querySelector("#data-grid-virtual-scroll").scrollRowIntoView(329)
4. The expected record show should be 330 but I am getting row 298

**Expected behavior**
The datagrid needs to show the row 330 

**Version**

- ids enterprise wc 1.0.0-beta.8

**Screenshots**

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: [chrome
Browser Version: 109.0.5414.75 (Official Build) (64-bit)

**Additional context**

**Comment by clayinfor** [comment]
Hi @GMInf , I'm working on this now, and needed some clarification.  On step 2, you mentioned above "Scroll down up to the last record (363) and go back to the top".  Is 363 correct or did you mean 330?  Just want to ensure I'm not missing something. Thanks!

**Comment by GMInf** [comment]
Hi @clayinfor, 
Yeah, I am not sure how I got 363 records when I was testing this. It is limited to 300. Let me check again.

**Comment by clayinfor** [comment]
Oh ok, many thanks, @GMInf !  In the `virtual-scroll-infinite-scroll.html` example there's a constraint [here](https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/demos/virtual-scroll-infinite-scroll.ts#L102) that should cause the infinite scroll to stop at record 300 (index 299), but it's not being completely respected.  I'll fix that as well.  Thanks again!

**Comment by clayinfor** [comment]
Hey @deep7102, @EdwardCoyle, @andriivarhanov !  I could really use some extra eyes on this issue, if possible for you guys?  Please see the 2 videos I will add in subsequent comments. Thanks in advance!

cc: @tmcconechy @danielortiz1982

**Comment by deep7102** [comment]
Saw some weirdness with safari browser on mac.

1. load page and scroll all the way down till it's not loading any more data (was 330 last)
2. scroll all the way up
3. run in developer tools `document.querySelector("#data-grid-virtual-scroll").scrollRowIntoView(329);`
4. see in view only showing rows (297 to 319) cannot see row 329
5. run same method again with value `29` see it show fine this time ( 29 to 51) so requested row 29 is visibale
6. run same method again with value `429` now this load more then initial load (was 330), but it load (341 to 363)

https://user-images.githubusercontent.com/38439203/228594456-d2c67c1c-c715-49d1-8834-3df8cb71f7ef.mov

**Comment by GMInf** [comment]
Hi @clayinfor,
I've found a way to consistently replicate this. I have changed the the parent of idsDatagrid and set a height for new parent element.
You can override your files with the attached files to replicate the issue.
[scrollrowIntoView.zip](https://github.com/infor-design/enterprise-wc/files/11110141/scrollrowIntoView.zip)

**Comment by clayinfor** [comment]
Ok, thanks @GMInf !

**Comment by clayinfor** [comment]
Hi @GMInf, I just submitted [this PR](https://github.com/infor-design/enterprise-wc/pull/1213) to address the problems you were seeing with infinite-scroll.  If time permits, I'd be happy to hear your feedback on it.  Thanks!

**Comment by GMInf** [comment]
Hi @clayinfor, I can still replicate it using the code changes you have made on the PR.
Here are my replication steps:
1) Download https://github.com/infor-design/enterprise-wc/files/11110141/scrollrowIntoView.zip
2) Overwrite src\components\ids-data-grid\demos\virtual-scroll-infinite-scroll.html, src\components\ids-data-grid\demos\virtual-scroll-infinite-scroll.ts and src\assets\css\ids-data-grid\custom-css.css with the files on the zip file
3) Scroll to the end of data, record 330
4) Scroll up to record 1
5) Run document.querySelector("#data-grid-virtual-scroll").scrollRowIntoView(329) on console
6) Error: IdsDatagrid is showing Record is 230 not 330
![image](https://user-images.githubusercontent.com/53523076/229435701-9537ae08-93a0-4235-9e03-4d5836e05053.png)

* Please take note that I changed the parent container so that it can have a height of 400px. With this layout, the issue is always replicable.
