### ISSUE TITLE
IdsDatagrid: VirtualScroll true - Instantly display data using an index similar to ScrollRowIntoView without scrolling

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1199]
**Is your feature request related to a problem or use case? Please describe.**
Our application needs to display a lot of rows and in some cases we need to show the starting from index 150 for example. Using ScrollRowIntoView(), it is visible that the data is loaded starting from index 0 and then scrolled to index 150. We do not need to show index 0 and the scrolling rows. We just need to display the rows that includes index 150. 

**Describe the solution you'd like**
We would like to request a new function to display/load only rows that includes index X. Or a new parameter on ScrollRowIntoView that skips 0 upto the row close to X (example, ScrollRowIntoView(150, true /*disable scrolling*/),  it will render only rows  staring only in index 110 to 150 (depending on the viewable rows) 

**Describe alternatives you've considered**
A new function or a new parameter in ScrollRowIntoView will do

**Additional context**
And what application do you work on? M3 H5 Angular - Using IdsDatagrid Virtualization

**Comment by clayinfor** [comment]
hey @GMInf , how do you feel about adding another IdsDataGrid attribute as such:
```html
<ids-data-grid start="150"></ids-data-grid>
```

And the datagrid's result-set would first render with record 150 at top... 

cc: @tmcconechy

**Comment by tmcconechy** [comment]
I like that idea for the api @clayinfor 👍🏻

**Comment by GMInf** [comment]
That would be great, thank you!
