### ISSUE TITLE
IdsActionPanel/IdsDropdown: Text in options are centered

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#1200]
**Describe the bug**
Dropdown list option text is centered in the list when an IdsDropdown is used on IdsActionPanel

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-action-panel/example.html
2. Click on "Open Action Panel"
3. Use any of the dropdowns.  The list items are centered

**Expected behavior**
Text alignment should not change compared to when used outside an Action Panel.

**Version**
`1.0.0-beta8`

**Comment by glenlieorillo** [comment]
Tested and passed.


https://user-images.githubusercontent.com/102151352/231133517-165c10d6-0bcf-4d45-9f18-678072cb8368.mov
