### ISSUE TITLE
IdsDatagrid: When resizing columns rows are scrolled 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1209]
**Describe the bug**
When doing a column resize the rows are scrolled. Noticed testing theme updates.

**To Reproduce**

1. Go to  https://main.wc.design.infor.com/ids-data-grid/m3-features.html
2. Scroll down some in the body of the grid
3. Grab any column between the column divider and make it bigger and smaller while dragging
4. See that the rows are scrolling

**Expected behavior**
Should not effect scroll position on the body when you resize a column.
Also check if this is an issue with virtual scroll on and off? Fix it in both situations but my guess is its virtual scroll only

**Comment by glenlieorillo** [comment]
This is now working as expected. However, the edit icon is cut-off.

https://github.com/infor-design/enterprise-wc/assets/102151352/b7cea5dc-556e-4f50-948d-8bf018156ebc

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/e0997ae2-eb23-4b7b-a66b-4402cfbff162)
