### ISSUE TITLE
IdsWizard: Not able to click steps (anymore)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1221]
**Describe the bug**

The wizard is not able to change steps by clicking.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-wizard/example.html
2. Click on a step
3. Should go to that step

**Expected behavior**

- Can click steps on the old version https://main-enterprise.demo.design.infor.com/components/wizard/example-index.html
- Can do it with the keyboard (focus and then enter)
- Should not use hash-url to do it internally

**Additional context**
When doing #1118 I fixed themes and added tokens. But that

**Comment by glenlieorillo** [comment]
Fix already applied. However, upon clicking the steps the title becomes short with ellipses. It should be fully spelled out.

https://github.com/infor-design/enterprise-wc/assets/102151352/8df7bb05-2547-4bd0-862b-e3ea0eef9a00

**Comment by tmcconechy** [comment]
@glenlieorillo fixed that here https://github.com/infor-design/enterprise-wc/pull/1440

**Comment by glenlieorillo** [comment]
Tested and passed.


https://github.com/infor-design/enterprise-wc/assets/102151352/3f85593f-491a-42c5-a304-fa5123913bd5
