### ISSUE TITLE
IdsPopupMenu (Context menu): Close/Open when clicking the target area

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#1222]
**Describe the bug**
While an IdsPopupMenu assigned as a context menu is open, When clicking on an empty spot in the page where it's assigned, IdsPopupMenu does not reposition itself to the click location.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-popup-menu/example.html
2. Right-click the page to activate the context menu
3. Right-click again in an empty place on the page
4. See the IdsPopupMenu doesn't move to the clicked location

**Expected behavior**
The IdsPopupMenu should move to the clicked point in the page

**Version**
`main` @ v1.0.0-beta9

**Additional context**
Discovered on #1212

**Comment by danielortiz1982** [comment]
@andriivarhanov  Will this be finished by the end of this sprint?
