### ISSUE TITLE
IdsModuleNav: Add new component

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1226]
Add the Module Nav component to the Web Components library.  See the ([Figma file](https://www.figma.com/file/bL4EBYtWjgfBsvTVI9seXU/branch/eHul2nKNMdypFLSb55ZwR1/Application-Menu?type=design&node-id=3161-29750&mode=design&t=WpB8WK3PAyXS2p7T-0)) for design guidance.

**Component Parts (barebones components/style settings)**

- [x] container/wrapper component (wraps both drawer and content)
- [x] Module Nav Bar component (based on IdsDrawer)
- [x] Drawer (module nav color variant) 
- [x] content area component (wraps just content)
- [x] Accordion (module nav color variant)
- [x] Accordion Section component
- [x] Searchfield/Input (module nav color variant)
- [x] Dropdown (module nav color variant)
- [x] PopupMenu (module nav color variant)
- [x] Module Nav Switcher component (use IdsButton/IdsDropdown)
- [x] Module Nav Settings component (use IdsMenuButton?)

**Behavior**

- [x] Display Mode setting (needs to work in-tandem with IdsDrawer's `visible` setting)
- [x] Filtering behavior (share/mimic App Menu's accordion filter)
- [x] Pinned behavior
- [x] Content overlap behavior
- [ ] Display tooltips on accordion headers in collapsed mode
- [x] Prevent expand of accordion headers in collapsed mode

**Styles**
- [ ] Dark/Contrast modes for all components ([Figma](https://www.figma.com/file/eHul2nKNMdypFLSb55ZwR1?node-id=5431:85465&mode=design#480352863))

**Additional context**
- Enterprise issue: https://github.com/infor-design/enterprise/issues/7386
- NG component wrapper issue: https://github.com/infor-design/enterprise-ng/issues/1477

**Comment by glenlieorillo** [comment]
Testing failed.

**Issues:**

1. Icons are not visible in Dark Mode.
2. Dirty tracker color is different in Dark and High Contrast Modes.
3. 'Settings' is not working in RTL.

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/ea582456-d135-4afb-bd82-8c311fbee8dc)

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/f9d60207-4708-446b-80c2-0676939f6585)


https://github.com/infor-design/enterprise-wc/assets/102151352/fc07d625-655b-4d85-8f6a-607ae845ca42
