### ISSUE TITLE
IdsDatagrid: Alignment issues on Editable Cell with Tree Expander

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1229]
**Describe the bug**
The expand/collapse button is aligned to the right when the column is right aligned. It should be on the left side, only the cell content should be right aligned.

**To Reproduce**

1. Open enterprise-wc
2. Replace src\components\ids-data-grid\demos\tree-grid.ts with attached file.
[tree-grid.zip](https://github.com/infor-design/enterprise-wc/files/11222591/tree-grid.zip)

3. Run npm start and go to tree-grid.html
4. See alignment issues 
5. Click on the cell to edit
6. Cursor is visible

**Expected behavior**
Expand/collapse button should be left aligned and editable cell should be right aligned. Expand button should be outside the inline editor border?

**Version**

-ids enterprise wc 1.0.0-beta.8

**Screenshots**
![image](https://user-images.githubusercontent.com/53523076/231772296-79ba099d-dee0-427b-9f7c-a491d369e65d.png)

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: [chrome
Browser Version: 109.0.5414.75 (Official Build) (64-bit)

**Additional context**
This happens when 1st column is
1) Formatter is .tree
2) Editable
3) Right aligned
and Grid is Tree

**Comment by hey-yall** [comment]
Bringing in designer expertise with Jira ticket IDS-1047 -- https://jira.infor.com/browse/IDS-1047

**Comment by tmcconechy** [comment]
@GMInf Do you have to right align this if its causing an issue?

**Comment by GMInf** [comment]
Yes, we have to right align because we are displaying editable numeric field on the cell. 
When left aligned, the expander is inside the border. It could be better to display the expander outside the editable field. Here is our implementation on soho-datagrid
![image](https://user-images.githubusercontent.com/53523076/233271921-b77506c1-709c-4e6c-9ae3-27251d8f6a4b.png)

**Comment by tmcconechy** [comment]
Ok thats an idea with the expander but we would have to make it indent and push the input over and would require a bigger / wider column if a lot of levels. But could work.

Working with our design for other ideas.

**Comment by tmcconechy** [comment]
Can we just make an example where the expander is in a different column then the editable text?

**Comment by GMInf** [comment]
Hi @tmcconechy,
We cannot move the expander to another column. That can cause issues on our side and possibly on customer scripts that makes changes to the datagrid.

**Comment by tmcconechy** [comment]
I think its the best design for it. So think about if there is a way. Its what our design team suggested.

**Comment by tmcconechy** [comment]
@GMInf do you presently have this working someplace? We think the ui looks really really really strange on the working version we almost have

![Screenshot 2023-10-04 at 10 15 00 AM](https://github.com/infor-design/enterprise-wc/assets/814283/e8473df3-d2d8-46d1-a3e2-14f6f7504c31)

All the examples show them all collapsed? Would like to see how it looks when expanded?

**Comment by GMInf** [comment]
Hi @tmcconechy,
Here is our application using the expandable editable cell using the soho-datagrid. But our sub row is not editable and we only have one level in this example.
<img width="958" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/53523076/efc6af92-7323-458a-a5e8-9602268e5b5a">

**Comment by tmcconechy** [comment]
ok i figured something like that. @EdwardCoyle maybe we can show a second example like this. But i think the approach you showed me would work either way.

**Comment by jbrcna** [comment]
**QA Failed**
when using XXS height the dirty indicator goes beyond the field
<img width="1506" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/d9df56a7-e6ef-4f48-bafb-1651474d7bf3">

https://main.wc.design.infor.com/ids-data-grid/tree-grid-expand-collapse.html - "+" icon is not centered in XXS height
<img width="1640" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b42a08fb-5893-45b0-bbe0-32671ed8b6e6">

https://main.wc.design.infor.com/ids-data-grid/editable-inline.html - misaligned dirty indicator
<img width="1640" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b42a08fb-5893-45b0-bbe0-32671ed8b6e6">

Also, when you edit the dropdown (to make dirty indicator appear) then move the column to different order, the dirty indicator remains on the same place row/column
https://main.wc.design.infor.com/ids-data-grid/editable-inline.html
https://github.com/infor-design/enterprise-wc/assets/56722184/62340448-58ed-4143-a649-c59bb0124be7

datagrid resized when selecting in datagrid. check each row heights
https://main.wc.design.infor.com/ids-data-grid/editable.html

**Comment by tmcconechy** [comment]
@jbrcna lets add a new issue for that one. So we can get to it later
