### ISSUE TITLE
IdsDropdown: Unable to Close with Keyboard 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1236]
**Describe the bug**
Unable to select and close with Keyboard anymore on dropdown.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-dropdown/example.html
2. Click the label of the first dropdown
3. hit enter to open
4. down arrow a few times and hit enter
5. notice the popup doesnt close (actually it closes and reopens)

**Expected behavior**
This should work.

**Additional context**
Problem seems to be the way its working with `attachKeyboardSelectionEvent` and `attachOpenEvents`. If you watch both the events with `[' ', 'Enter']` they fire in the wrong order

**Comment by jbrcna** [comment]
QA Passed.
<img width="414" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/d4c5329b-292a-4e33-a110-b450ded90e8d">
