### ISSUE TITLE
Card Footer is positioned outside its Card 

### ISSUE THREAD

**Issue by mrtipsytony** [infor-design/enterprise-wc#1240]
**Describe the bug**
When trying to add `<div slot="card-footer">` inside the ids-card, the footer is positioned outside. Currently trying this first in the wc-examples repo.

**To Reproduce**

1. Fork and clone the examples [repository](https://github.com/infor-design/enterprise-wc-examples) 
2. In _react-ts-ids-wc_ directory, run `npm install` 
3. Open _react-ts-ids-wc/src/examples/ids-card/index.tsx_ and add a card footer and also update the content body in one of the cards. See image of the changes here: 
![image](https://user-images.githubusercontent.com/47052061/233045691-f4f81bc1-6f90-463e-8a70-48f6f203d139.png)
4. Save the file and run `npm run start` to launch the IDS Web Components site in localhost:3000
5. Once it launches, in the side bar, click and expand Layouts and click Card option.
6. See the footer inside the card view is out of place
![image](https://user-images.githubusercontent.com/47052061/233045010-c4edb539-0e94-47f5-a98c-3d7948ec96fc.png)

Here's a fork repo of my changes: https://github.com/mrtipsytony/enterprise-wc-examples

**Expected behavior**
The box should be inside the card view. 

Additional Dev Notes:
It looks like we have a position:absolute in the styles for .ids-card-footer. Turning that off seems to fix the issue. 

**Version**

- ids-enterprise: 1.0.0.beta-8

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: Microsoft Edge
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@mrtipsytony im doing some work on cards and widgets and wondering where the footer should be. Is this for a homepage portal like layout or just a single arbitrary card on a page.

I.E. where does the card with a footer appear in your use case
