### ISSUE TITLE
IdsDatagrid: Reorderable drag arrows are not aligned to the proper column

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1241]
**Describe the bug**
The reorderable drag arrows are not aligned to the proper column when the host element of the idsDatagrid is moved to the right. The position of the ids-datagrid parent affects the drag arrows

**To Reproduce**

1. run enterprise-wc
2. open columns-reorderable.html
3. on the dev tool, change the style of the parent of ids-data-grid, the ids-layout-grid's margin-left and position to 1000px and fixed.
<img width="488" alt="image" src="https://user-images.githubusercontent.com/53523076/233058100-88ea9d27-71bf-460b-8a64-942a98b7e9fd.png">
4. drag the 2nd column towards the first
5. Error: arrow position is not on the first column

**Expected behavior**
Drag arrows should be in the first column

**Version**

- ids enterprise wc 1.0.0-beta.8

**Screenshots**

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: [chrome
Browser Version: 112.0.5615.121 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
Issue someplace around here https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/ids-data-grid-header.ts#L188
