### ISSUE TITLE
IdsDatagrid: Request for AfterRedraw Event for Datagrid Customization

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1244]
**Is your feature request related to a problem or use case? Please describe.**

We need additional customizations for our implementation of the ids-datagrid for example:
1) Set the Column filter <input> to uppercase
2) Set the datagrid to disabled. Editable cells will not be editable/clickable and all rows will be grayed out to make it look disabled.
3) Add a new button to the column header for the purpose of expanding all rows for tree view

To do these customizations, I am thinking of updating the html of the datagrid. For example, adding a new part to the column header filter input to make it uppercase. Currently there is no way to add/update the part for the filter input unlike cells. 

**Describe the solution you'd like**
Instead of requesting and implementing the individual requirements above, I think it  would work better if we can update the part(s) of any elements inside the data grid. To do that, we need to know when the idsDatagrid body has been drawn/redrawn so that we can update the elements that we need to.
For example, setting the Column header filter to uppercase. After the idsDatagrid is redrawn and afterRedraw is triggered, our listener
will query all the column filter inputs and add an uppercase part (or class) to change the <input> to uppercase.

**Describe alternatives you've considered**

**Additional context**
Additional button in column header
![image](https://user-images.githubusercontent.com/53523076/233316753-bce7248d-39df-46b7-a6c4-677eef7b06cb.png)

Disabled datagrid
![image](https://user-images.githubusercontent.com/53523076/233317284-8c41d822-270b-495a-861b-11d766210f96.png)

And what application do you work on? M3 H5A

**Comment by tmcconechy** [comment]
1. Add afterRedraw Event that ommits
2. Add `uppercase=true` option to columns (editor / filter in upper case) (editorOptions, filterOptions)
3. Disabled Rows Feature (we may need to discuss API)

**Comment by hey-yall** [comment]
Hey @tmcconechy and @deep7102 -- help me understand what design resources you need for this ask so I can communicate this clearly in the design ticket. Thanks!

**Comment by tmcconechy** [comment]
The only design thing this needs is 

- how do we should the expand all button on the header that expands all rows

I think i saw a Jira for that.

**Comment by hey-yall** [comment]
@tmcconechy -- You're right! The Jira for the expand button is [IDS-1299](https://jira.infor.com/browse/IDS-1299). Just wanted to make sure that we didn't need a separate ticket for items in this. 

I updated IDS-1299 with information that the expand all button design also impacts this Github issue.
