### ISSUE TITLE
Datagrid: Two context menus appear on the filter after adding data

### ISSUE THREAD

**Issue by scott-campbell-infor** [infor-design/enterprise-wc#1258]
Using the ids-data-grid component, after populating the datagrid with data, we get a second context menu appear when we click on the filter options.

![image](https://user-images.githubusercontent.com/78373963/235075458-b3ecbceb-f3a2-4cdb-bf38-511be987c2bf.png)

**To Reproduce**
Steps to reproduce the behavior - in the example provided
1. Click on the Mock Data button (populates data)
2. Click on the first filter option, two menus will appear

**Expected behavior**
When a filter option is clicked, only a single context menu should appear

**Version**
ids-enterprise-wc: 1.0.0-beta.8
Angular 15.2.7

**Platform**
 - Browser Name: Chrome
 - Browser Version: Version 112.0.5615.138 (Official Build) (64-bit)

**Additional context**
Attached is the instances.component to replicate with.  To test, example in to the ids-data-grid\demos directory for the Angular enterprise-wc-examples 
[instances.zip](https://github.com/infor-design/enterprise-wc/files/11350794/instances.zip)

In the ids-data-grid-module.ts file add the following import
import { InstancesComponent } from './demos/instances/instances.component';

In the NgModule -> Declarations add InstancesComponent
![image](https://user-images.githubusercontent.com/78373963/235077353-aa9d98b2-4ecc-4098-94bd-9057904666d5.png)

**Comment by tmcconechy** [comment]
I found one more case that doesnt work presently and its closely related to all these examples. By the time you work on it it will be on http://localhost:4300/ids-widget/example.html 

This example works on toolbar alone but when its in a widget it doesnt not position correctly

![Screenshot 2023-07-25 at 11 30 25 AM](https://github.com/infor-design/enterprise-wc/assets/814283/25dedb72-4826-43cb-9668-f5af86ced950)

**Comment by EdwardCoyle** [comment]
I was able to reproduce this issue in an existing example of ours, as it's related to the IdsDataGrid `redraw()` method:

- open https://main.wc.design.infor.com/ids-data-grid/filter.html
- re-order the headers in any order
- open any filter row menu to set incorrectly-placed duplicates

**Comment by jbrcna** [comment]
QA Passed
<img width="1649" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/9104e0c2-0ce8-42e4-a75a-7452243ffa5d">

**observation:**
notice that there is a tooltip behind when filter is hovered. 
maybe similar to this https://github.com/infor-design/enterprise-wc/pull/1446#pullrequestreview-1598419391
<img width="1395" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/ffbc6fc6-b350-42a0-864e-734cfd5bde68">
