### ISSUE TITLE
IdsCalendar: Dark mode toolbar not rendering properly

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/enterprise-wc#1261]
**Describe the bug**
When switching to dark mode in the `ids-calendar` the toolbar is not updating correctly. Looks like it can be traced to the `.calendar-toolbar-pane` class not being set with any dark mode styles. See video below.

**To Reproduce**

1. Go to http://localhost:4300/ids-calendar/example.html
2. Click on theme switcher and select dark mode.
3. See the toolbar pane is not changing colors.

**Expected behavior**
All components should be updated with the proper theme colors.

**Screenshots**
https://user-images.githubusercontent.com/1084735/235178781-1cc9693c-4278-4a85-a1ef-12e0d5a3ffaa.mov

![Screen Shot 2023-04-27 at 10 29 55 AM](https://user-images.githubusercontent.com/1084735/235180748-7e85c561-8319-4970-968c-30f39db7ea0a.png)

**Additional context**
n/a

**Comment by tmcconechy** [comment]
fyi @jmacaluso711 we fixed this when we did #1118

**Comment by tmcconechy** [comment]
this was fixed with https://github.com/infor-design/enterprise-wc/pull/1273 ~ should have marked it on there

**Comment by jbrcna** [comment]
QA Passed
<img width="1646" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b45cfcbc-2e1f-449f-b6f5-0aca2b95e714">
