### ISSUE TITLE
IdsCalendar: Legend expanded but content not visible on first load

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/enterprise-wc#1263]
**Describe the bug**
When the `ids-calendar` is first loaded the Legend accordion is set to expanded but the content is not visible. After closing then re-opening the accordion the content appears. See attached video of the bug.

**To Reproduce**

1. Go to http://localhost:4300/ids-calendar/example.html
2. Check the legend and see the header is in expanded state but the content is not visible
3. Click on the header and the accordion will close.
4. Click on the header again and the content will be visible.

**Expected behavior**
The content in the legend should be visible on first load.

**Screenshots**
https://user-images.githubusercontent.com/1084735/235226323-1d9aa795-9290-466e-bf88-4b010da01c94.mov

**Additional context**
n/a

**Comment by tmcconechy** [comment]
@jmacaluso711 not sure if i am seeing this on https://main.wc.design.infor.com/ids-calendar/example.html
When i first load it is showing and the arrow is up. When i click it content is hidden and the arrow is down.

Some specific browser?

**Comment by jmacaluso711** [comment]
I'm seeing this issue in Chrome Version 112.0.5615.137, it's working in Firefox, Safari I'm not seeing the legend or events at all.

**Comment by jbrcna** [comment]
QA Passed
https://main.wc.design.infor.com/ids-calendar/example.html
![Large GIF (952x494)](https://github.com/infor-design/enterprise-wc/assets/56722184/65b63daf-b7f5-42ba-9f8f-eab17e37f4fe)
