### ISSUE TITLE
IdsDatagrid: Collapse All/Expand All button on Tree View

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1271]
**Is your feature request related to a problem or use case? Please describe.**
Currently there is no way to collapse/expand all the nodes in the tree view. A button with that purpose would be great.

**Describe the solution you'd like**
An option to display a button for collapse all/expand all on the first column header. It could be in between the reorder icon and the column header.

Another alternative would be functions on idsDatagrid to expand/collapse all tree nodes.

**Describe alternatives you've considered**

**Additional context**

And what application do you work on? M3 H5A

**Comment by tmcconechy** [comment]
Really not much room there for all the things (reorder, text, expand and sort). Especially with https://github.com/infor-design/enterprise-wc/issues/1072

Also the "expand all" icon looks a lot like the sort icon
<img width="143" alt="Screenshot 2023-05-08 at 9 43 31 AM" src="https://user-images.githubusercontent.com/814283/236840070-aa2d1232-7bfb-42ae-bd87-1d07d16c3aff.png">

**Comment by GMInf** [comment]
Hi @tmcconechy, as an alternative for this, can we request just the functions idsDatagrid.expandAllRows() and  idsDatagrid.collapseAllRows()? Or are there existing functions that we could use?

**Comment by tmcconechy** [comment]
Yeah thats probably a good idea. That way you can use a button on the toolbar. We don't have those functions today but you can do it via the data. Would be better to add a function - will do.

**Comment by hey-yall** [comment]
Design work racked under https://jira.infor.com/browse/IDS-1202

**Comment by hey-yall** [comment]
Tracking design resources via Jira ticket [IDS-1299](https://jira.infor.com/browse/IDS-1299)

**Comment by tmcconechy** [comment]
We are discussing this now. Is it possible to use a toolbar above the `datagrid` with a button as a design option. @GMInf 

We did add this example:
https://main.wc.design.infor.com/ids-data-grid/show-header-expander.html

**Comment by GMInf** [comment]
Hi @tmcconechy ,

It is not possible to use a toolbar for the collapse/expand all button on our app.

But I found a work around to manually add the collapse/expand all button on the header while using a custom cell formatter. 
I used the datagrid's `afterrendered `event to manually add the  collapse/expand all button inside the header. I had to tweak some styles and some behaviors to make it work but it is now displaying on our app.

![image](https://github.com/infor-design/enterprise-wc/assets/53523076/fa3bda62-844a-4c08-917b-8a656ae9b1b7)

![image](https://github.com/infor-design/enterprise-wc/assets/53523076/862b3d76-5eb6-4c19-b830-d23462fba8d9)

**Comment by tmcconechy** [comment]
ok and it works on a tree? so can this be closed? 🚀

**Comment by GMInf** [comment]
Yes it works on a tree. I think it uses the click handler for the original collapse/expand all button, so yey!
Yes, this can be closed.

**Comment by GMInf** [comment]
Noted. But due to the design of our tree grid, the users will be expecting the expand/collapse all button on the header.

**Comment by tmcconechy** [comment]
Yep just a note 👍🏻
