### ISSUE TITLE
IdsDatagrid: Tree not selecting or collapsing all children

### ISSUE THREAD

**Issue by scott-campbell-infor** [infor-design/enterprise-wc#1284]
**Describe the bug**
When using the IDS Datagrid with the tree-grid set to true there are a couple of issues
1. collapsing expanded rows will only collapse the first child record, not all
2. selecting a parent record will only select the parent row and the first child
3. clicking the parent selection box to remove the tick, only deselects the parent

**To Reproduce**
Using the Enterprise-WC-Examples-Main as at 2023-05-17 

Add the attached component to the ids-data-grid/demos for Angular
[tree.zip](https://github.com/infor-design/enterprise-wc/files/11495483/tree.zip)

Initial state:
![image](https://github.com/infor-design/enterprise-wc/assets/78373963/8066ea23-ba9e-4d4d-88e9-1a1b93f42050)

Collapsing children
1. click on the minus of the first record to collapse the children, only the first child is collapsed

![image](https://github.com/infor-design/enterprise-wc/assets/78373963/e8259682-ce94-4d6b-acfe-13850209512a)

Selecting parent records
1. click on checkbox for the the parent record, only the parent and the first child are selected

![image](https://github.com/infor-design/enterprise-wc/assets/78373963/b16a2aa2-746b-4051-81d9-9ee5571c2527)

Deselecting the parent record
1. click on the checked checkbox for the parent record, only the parent record is deselected

![image](https://github.com/infor-design/enterprise-wc/assets/78373963/2fa605ea-90ab-46ee-ab8e-8b5267424752)

**Expected behavior**
Collapsing children - all the children should be collapsed
Selecting parent checkbox - all the children should have the checkbox ticked
Deselecting parent checkbox - all children should have the checkbox tick removed

**Version**
- ids-enterprise-wc: 1.0.0-beta.8
- Example testing using the enterprise-wc-examples as at 2023-05-17

**Platform**
- Infor Application/Team Name: Infor Solutions and Innovations
- OS Version: Windows 11
- Browser Name: Chrome
- Browser Version: 113.0.5672.93

**Comment by hey-yall** [comment]
Design work racked under https://jira.infor.com/browse/IDS-1202

**Comment by tmcconechy** [comment]
hey @scott-campbell-infor i noticed we had a setting for this `groupSelectsChildren` or `group-selects-children="true" in the UI.

If you add that does it behave the way you expect? Example has it here https://main.wc.design.infor.com/ids-data-grid/tree-grid.html

**Comment by clayinfor** [comment]
Hey @tmcconechy, I checked `groupsSelectedChildren` and it appears that the attached zip-file does have that option enabled in the angular example, so that's not a problem...

**Comment by tmcconechy** [comment]
ok i wasnt sure. But if you can reproduce it now. Please look for a fix.
