### ISSUE TITLE
IdsDataGrid: Add new Designs

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1285]
**Describe the bug**
Need to finish up alabaster theme design changes for the Datagrid component.

**Expected behavior**
Datagrid Designs: https://www.figma.com/file/4CtBGz8dwvSa6JsBcdtVZQ/Data-Grid?type=design&node-id=2388-30705&mode=design

See: https://jira.infor.com/browse/IDS-1334

**Comment by hey-yall** [comment]
Hey @tmcconechy -- in what context do we need gray columns? Are they for disabled columns, for style, or something else?  I'd like to give the designers as much info as possible to inform their solutions. Thanks!

**Comment by tmcconechy** [comment]
I think the latest designs already are doing this. I think think it should be grey not completely white so it looks better. 

So whenever this figma is complete this will be good i think (grey headers) https://www.figma.com/file/DJPTIKslo7jvWJlHOvrHIz/Design-Language-Audit-(Copy)?type=design&node-id=362-12325&t=BgFCTCkBnZJZKH9K-0

<img width="683" alt="Screenshot 2023-05-30 at 9 51 12 AM" src="https://github.com/infor-design/enterprise-wc/assets/814283/560ca4b3-b3b9-4cb7-999d-b1b4885c3c74">

**Comment by EdwardCoyle** [comment]
Updated Figma link: https://www.figma.com/file/4CtBGz8dwvSa6JsBcdtVZQ/Data-Grid?type=design&node-id=2402-69327&mode=design&t=bkOEkvlOSEGwB1zO-0

**Comment by glenlieorillo** [comment]
QA Passed.

https://main.wc.design.infor.com/ids-data-grid/example.html

https://github.com/infor-design/enterprise-wc/assets/102151352/7e0a529f-b8a3-4c74-9567-1e22afe2d49d

https://main.wc.design.infor.com/ids-data-grid/columns-groups.html


https://github.com/infor-design/enterprise-wc/assets/102151352/86a93577-e3a0-45fb-81c6-4a36b88b6183

https://main.wc.design.infor.com/ids-data-grid/filter.html


https://github.com/infor-design/enterprise-wc/assets/102151352/56b6df7b-0dee-4b34-9ce6-e1915283e552

https://main.wc.design.infor.com/ids-data-grid/tree-grid-expand-collapse.html


https://github.com/infor-design/enterprise-wc/assets/102151352/86b8e342-b5a5-4228-9190-531f8f1ec0f1

https://main.wc.design.infor.com/ids-data-grid/row-height.html


https://github.com/infor-design/enterprise-wc/assets/102151352/a89057f3-8be2-45d8-be0e-ef34d005ca8a
