### ISSUE TITLE
IdsPopupMenu: Loosing keyboard events when re-parenting

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1291]
**Describe the bug**
The IdsPopupMenu is loosing keyboard events when re-parenting. This causes the keyboard on datagrid filter row to be wonky.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/filter.html
2. Click on any filter row item
3. Down arrow -> focuses grid but should work within the menu.
4. https://main.wc.design.infor.com/ids-data-grid/filter-custom.html -> Filter row (color/product-id columns)open pop menu and see list not align
5. https://main.wc.design.infor.com/ids-data-grid/filter-trigger-fields.html
- Filter row open any menu button, up/down arrow keys not work to navigate list (we already saw it focus to body rows)
- Filter row (time/date pickers not open by keyboard)
- Filter row dropdowns open, but after open up/down arrow keys not work to navigate list

**Expected behavior**
up and down should work in the menu

**Additional context**
If you put a debugger in disconnectAllKeyboardEvents in keyboard mixin you can see around here https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/ids-data-grid-filters.ts#L792 its destroying the keyboard events and not bringing them back.

My first attempt was to do this but it did not work. Also not sure what attachKeyboardListeners does

```
        menu.appendToTargetParent();
        menu.popupOpenEventsTarget = document.body;
        menu.refreshTriggerEvents();

        menu.attachEventHandlers(); <--
        menu.attachKeyboardListeners(); <--
```

**Comment by jbrcna** [comment]
QA Failed. 
https://main.wc.design.infor.com/ids-data-grid/filter-custom.html
in first open, the highlight is cut off. when opening it again the highlight is now fine
try in `Safari browser`
<img width="619" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/ac042009-f074-4c00-9fd2-5397063294fa">

https://github.com/infor-design/enterprise-wc/assets/56722184/482c6b60-e3cf-473e-93d3-0d12dc07ca31

https://main.wc.design.infor.com/ids-data-grid/filter-trigger-fields.html - Pressing the down arrow while focused does not activate date and time picker. dropdown is working, pressing down arrow on dropdown shows the list.
<img width="1285" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/a8943162-62f5-4c8e-b717-c5e0279f1874">

**Comment by tmcconechy** [comment]
@jbrcna can you make a new issue for that one? Thanks!

**Comment by jbrcna** [comment]
created a new  issue [here](https://github.com/infor-design/enterprise-wc/issues/1466)
