### ISSUE TITLE
IdsDataGrid: Popups in the wrong position or duplicated

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1297]
**Describe the bug**
Finding some cases where the popup is in the wrong position or duplicated

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/filter-custom.html
2. Click on color popup
3. See error
4. Go to https://main.wc.design.infor.com/ids-data-grid/filter.html
5. Drag one column to another position then open its popup
6. See error

**Expected behavior**
Works when dragged or unslotted

**Additional context**
May want to fix this with https://github.com/infor-design/enterprise-wc/issues/1291

**Comment by jbrcna** [comment]
https://main.wc.design.infor.com/ids-data-grid/filter-custom.html
<img width="1502" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/6a6aa4af-94c8-470d-87d5-dea46d6d9d86">

<img width="1548" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/cdb4d01e-1704-4e7c-91ba-917ac917852f">


https://main.wc.design.infor.com/ids-data-grid/filter.html
<img width="1626" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/f5662ae6-ad9a-4b2b-8cb6-5ebb8322767e">

<img width="1653" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/080155ab-a9f4-4f7f-a15e-0360eb0be5a9">
