### ISSUE TITLE
IdsDatagrid: Running updateDataset() should also render the data changes on the row/cells

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1303]
**Is your feature request related to a problem or use case? Please describe.**
When data changes are done not on the ui but using updateDataset(), the changes are not reflected on the row/cells.

**Describe the solution you'd like**
The idsDatagrid.updateDataset() should also render the changes on the cell.

**Describe alternatives you've considered**
An alternative would be after executing idsDatagrid.updateDataset(), our app could run idsDatagrid.redraw. But there is an issue with redraw() with Virtualization is On. When scrolled down (scroll bar is in the middle) and redraw() is called, the scrollbar resets to the top (it should remain on the middle). If Virtualization is Off, it works, the scrollbar remains at the middle.

**Additional context**
And what application do you work on? M3 UX

**Comment by tmcconechy** [comment]
Might have to think about this one. The intention was to call `data = []` to update the whole grid. We do have a way to update the cell but its on the cell. i.e.

```
$('ids-data-grid').shadowRoot.querySelector('[row-index="1"]').querySelector('[aria-colindex="3"]').renderCell()
```

Maybe a more convenient upper level method? like `datagrid.refreshCell(row, cell)` ? Otherwise the refreshing will "loop"

**Comment by GMInf** [comment]
Yes, datagrid.refreshCell(row, cell) would be great but would it also be possible to do a datagrid.refreshRow(row)?
