### ISSUE TITLE
IdsLayoutGrid: Margin and Padding attributes not working.

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise-wc#1307]
**Describe the bug**
When using ids-layout-grid I want to be able to add spacing on the nested layout grids for consistent behavior. However the listed attributes of margin and padding seems to do nothing when added to the layout grid.

According to documentation here https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-layout-grid#idslayoutgrid I should be able to do the following:
```
  <ids-layout-grid cols="3" margin="10" padding="10" gap="md">
    <ids-layout-grid-cell>
      <ids-text font-size="12" type="h1">Ids Textarea</ids-text>
    </ids-layout-grid-cell>
  </ids-layout-grid>
```
But as you can see there is no margin or padding added to the example:

![image](https://github.com/infor-design/enterprise-wc/assets/9215760/48242341-481e-4cff-9f86-8c8fd5b0f924)

**To Reproduce**
Here I was using the textarea example from the angular example components to showcase the issue. https://github.com/infor-design/enterprise-wc-examples/blob/main/angular-ids-wc/src/app/components/ids-textarea/demos/example/example.component.html
And code to reproduce is the snippet from the issue description. Simply adding the attributes from the documentation.

1. Go to /ids-textarea/example
2. edit to use snippet from description
3. See nothing changes when using the margin and padding attributes

**Expected behavior**

**Version**
- ids-enterprise-wc: 1.0.0.beta-11

**Platform**
- Using angular and the behavior is the same on our angular projects as well as the angular examples in the WC examples repo.

**Additional context**
Just some sidenotes:
- I did not take the time to verify all the different attributes so there may be others that are not working as expected.
- This padding option seems to work on the `<ids-container>` so I assume the behavior for the `<ids-layout-grid>` is expected to be similar.

**Comment by Carlfjord** [comment]
Okay, no I'm actually looking for the spacing between the grid and it's border/wrapping element. This can of course be done with a custom class and css but it would be neat to use the attributes listed for it.

![image](https://github.com/infor-design/enterprise-wc/assets/9215760/43a437e5-7a74-44fa-81d5-c1c62b24f550)

 What I'm looking to do is essentially the following:
```
<!--  A wrapping layout grid to handle unified spacing for all content -->
  <ids-layout-grid cols="1" margin="20">
    <ids-layout-grid-cell col-span="1">
      <router-outlet></router-outlet>
      <!-- router outlet will have components with their own layout grids
             to manage the cell structure of the actual content like so:
        <ids-layout-grid cols="4">
          <ids-layout-grid-cell col-span="1"></ids-layout-grid-cell>
          <ids-layout-grid-cell col-span="3"></ids-layout-grid-cell>
        </ids-layout-grid>
       -->
    </ids-layout-grid-cell>
  </ids-layout-grid>
```

This way I'll only manage the outer spacing in one place.

**Comment by jmacaluso711** [comment]
The `margin` and `padding` attributes can be set with the following values: 

- `xs` = 8px, 
- `sm` = 16px, 
- `md` = 24px, 
- `lg` =  32px, 
- `xl` = 40px

So you could update your code to the following to set the margin to 24px:

```
<!--  A wrapping layout grid to handle unified spacing for all content -->
  <ids-layout-grid cols="1" margin="md">
    <ids-layout-grid-cell col-span="1">
      <router-outlet></router-outlet>
      <!-- router outlet will have components with their own layout grids
             to manage the cell structure of the actual content like so:
        <ids-layout-grid cols="4">
          <ids-layout-grid-cell col-span="1"></ids-layout-grid-cell>
          <ids-layout-grid-cell col-span="3"></ids-layout-grid-cell>
        </ids-layout-grid>
       -->
    </ids-layout-grid-cell>
  </ids-layout-grid>
```

We don't currently allow custom values for those attributes.

**Comment by tmcconechy** [comment]
@Carlfjord @jmacaluso711 i think that means this is a no fix needed? and can be closed

**Comment by Carlfjord** [comment]
Hi @tmcconechy, yes. The solution mentioned by @jmacaluso711 above solves this. Thanks, closing the ticket.
Solution: https://github.com/infor-design/enterprise-wc/issues/1307#issuecomment-1777146902
