### ISSUE TITLE
IdsLayoutGrid: Content max width restrictions

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise-wc#1308]
**Is your feature request related to a problem or use case? Please describe.**
So this is actually a feature that we already have using the enterprise-ng library. In enterprise-ng we would use row and column classes to create the page layouts. As per default the row class will restrict the layout width to make sure content does not get stretched indefinitely. 

Here is an example of how that works in enterprise-ng:

![image](https://github.com/infor-design/enterprise-wc/assets/9215760/4f8cee7a-5b88-4a4c-abef-b0734509d002)

Currently the enterprise-wc library does not provide any limitation to this so content does stretch all available space which might not be a preferred behavior. I could not find any built in way to deal with it currently however I would expect it be fairly straight forward for users to deal with it manually. Even so perhaps some build in handling could be nice. 

**Describe the solution you'd like**
I would like this to be an opt in behavior. So perhaps an attribute for `<ids-layout-grid>` could be a way to do it. Here you already have nice definitions of the [breakpoints](https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-layout-grid#responsive-breakpoints) so perhaps one could just specify which breakpoint or a custom value to set a "MaxWidth" attribute. 

**Describe alternatives you've considered**
I was thinking if the row and column and similar layout classes from enterprise could be useful to port into the wc library. But at the same time I think that might just be messy. Right now the  `<ids-layout-grid>` is the way to do page layouts. And a flexible one at that with that wide range of [attributes](https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-layout-grid#attributes). So instead of adding other tools I'm thinking improving the ones available is likely the better approach.

**Additional context**
Infor M3 Portals

**Comment by tmcconechy** [comment]
cc @jmacaluso711 for comments

**Comment by jmacaluso711** [comment]
Yes, I think this is a good idea. So there will be an optional `maxWidth` attribute that can be given either a `breakpoint` size or a custom size. Additionally, we should add the option to set the `margin` attribute to `auto` in order to center the contained grid if needed. The other option for centering could potentially be to wrap the `ids-layout-grid` in an `ids-layout-flex` and use flex box to center the grid.

**Comment by glenlieorillo** [comment]
QA tested and passed.


https://github.com/infor-design/enterprise-wc/assets/102151352/7819cdaa-2dcd-4271-9df2-01cfecf560d5
