### ISSUE TITLE
IdsDatagrid: Properties to set Uppercase and Maximum Length to Column Filter and Cell Editable Text

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1309]
**Is your feature request related to a problem? Please describe.**
When defining a column, there is a configuration for the column filter and cell editor. But i can't find properties to set to uppercase and maximum length. 

**Describe the solution you'd like**
Additional property to set max length and uppercase the Column Header Text Input Filter
 ```
 columns.push({
    id: 'units',
    name: 'Units',
    field: 'units',
    sortable: true,
    resizable: true,
    reorderable: true,
    formatter: dataGrid.formatters.text,
    filterType: dataGrid.filters.text
  });
```

Additional property to set max length and uppercase the Text Input on Editable cell
```
columns.push({
    id: 'description',
    name: 'Description',
    field: 'description',
    sortable: true,
    resizable: true,
    reorderable: true,
    formatter: dataGrid.formatters.text,
    editor: {
      type: 'input',
      inline: true,
      editorSettings: {
        autoselect: true,
        dirtyTracker: true
      }
    }
  });
```

**Describe alternatives you've considered**

**Additional context**

**Comment by jbrcna** [comment]
QA Failed
FAiling in Safari, you can only type < 2 chars in the filter. editable cell is working as expected.
<img width="887" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/16fe5ca8-f41a-43df-b8ac-f5c55c0b310d">

<img width="448" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/3ef30fd1-43f4-41c5-82b2-da2491c91a33">

**Comment by tmcconechy** [comment]
@jbrcna not sure why this is rejected on safari. Can you make a new issue?

**Comment by jbrcna** [comment]
sure @tmcconechy here's the ticket. https://github.com/infor-design/enterprise-wc/issues/1403
