### ISSUE TITLE
IdsDatagrid: datagrid.rowStart() not loading the right index

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1310]
**Describe the bug**
Running datagrid.rowStart = x; datagrid.data = ... does not go to x index.
I think this is similar to also to https://github.com/infor-design/enterprise-wc/issues/1275.

**To Reproduce**

1. clone enterprise-wc, npm i
2. update virtual-scroll-infinite-scroll-m3.ts
3. set initial record count to 156
4. set rowStart = 120
5. npm start
6. open virtual-scroll-infinite-scroll-m3.html
7. error: showing index 58 instead of 120

code:
```js
const fetchData = async (startIndex = 0) => {
  if (data === null) {
    const res = await fetch(url);
    const results = await res.json();
    data = results.slice(0, MAX_RESULTS_COUNT);
  }

  if (startIndex > MAX_RESULTS_COUNT) return [];

  const numRowsNeeded = Math.max((MAX_RESULTS_COUNT - startIndex), 0);
  return data.splice(0, Math.min(numRowsNeeded, 156));
};

const setData = async () => {
  dataGrid.rowStart = 120;
  dataGrid.data = await fetchData();
  dataGrid.selectRow(120);
};
```

attaching updated virtual-scroll-infinite-scroll-m3.ts
[virtual-scroll-infinite-scroll-m3.zip](https://github.com/infor-design/enterprise-wc/files/11625490/virtual-scroll-infinite-scroll-m3.zip)

**Expected behavior**
datagrid should load with index 120 at the first row instead of index 58

**Version**

- enterprise-wc: 1.0.0-beta.11

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/53523076/4cbc7b26-63a3-4696-88d7-f35c559db0ea)

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: chrome
Browser Version: 113.0.5672.127 (Official Build) (64-bit)

**Comment by GMInf** [comment]
Hi @tmcconechy, may we request this set to high priority?

**Comment by tmcconechy** [comment]
Sure, will need to test this after https://github.com/infor-design/enterprise-wc/issues/1275 is complete (now has a new PR)

**Comment by glenlieorillo** [comment]
Tested and passed.

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/5bdfd7c8-67e4-498e-aef4-39ec51bec05a)
