### ISSUE TITLE
IdsDatagrid: Tooltip callback/asynccallback does not show tooltip for the header title

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1311]
**Describe the bug**
Hovering on the header title does not show the tooltip configured with callback/asynccallback

**To Reproduce**

1. clone enterprise-wc, npm i, npm start
2. go to http://localhost:4300/ids-data-grid/tooltip.html
3. adjust the column width of column "Tooltip async Callback" and make it wider
4. Hover on the header title of column "Tooltip async Callback"
5. error: tooltip is not displayed

**Expected behavior**
Tooltip should be display

**Version**

- enterprise-wc: 1.0.0-beta.11

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/53523076/478d19d2-e7ba-41ff-b936-02bd9f2220c3)

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: [chrome
Browser Version: 113.0.5672.127 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
Seems like its only showing when the tooltip is cut off.

**Comment by tmcconechy** [comment]
Yeah. I think what should happen is...  The tooltip that shows the title text should show the title if that is cut off.
But if the end user sets a specific non/default tooltip then we want that to show all the time.

Didnt check the PR but thats what i think about how it should work. Will review this next lap
