### ISSUE TITLE
IdsSwapList: Working with swaplist and underlaying dataset

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise-wc#1313]
**Describe the bug**
The swaplist seems to not be fully linked with the underlaying dataset. From what we've seen this is making it difficult to use and manage the data. 

There are some separate parts to this:
1. How to input a custom name on the different posts? 
List just use the out of the box name "List #X" 

![image](https://github.com/infor-design/enterprise-wc/assets/9215760/787090ac-e0e7-46d4-b571-a5d6b3fc55cd)

2. How to input data into different posts? Currently the [documentation](https://design.infor.com/code/wc-beta/latest/ids-swaplist) only shows the "count" setting to add number of columns. However any data added gets added in all three. I noticed some ways of dealing with these things in the [non wc library](https://design.infor.com/code/ids-enterprise/latest/swaplist) however that seems to not be compatible with the wc component and would also not be good practice using jquery to target DOM elements in angular.

3. how to retrieve the data from specific post in the swaplist?
It seems the underlaying dataset is not updated when changes are made. So even if we see items switching posts visually the dataset remains unchanged as far as I could tell. 

![image](https://github.com/infor-design/enterprise-wc/assets/9215760/cb14ebfb-34f7-4b49-9e17-b53b422b2593)

**To Reproduce**
I've been looking at the[ swaplist demo component in enterprise-wc](https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-swaplist). Specifically the angular example found [here in the wc-examples](https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc/src/app/components/ids-swaplist/demos/example)

1. Go to the swaplist angular example
2. notice the titles
5. swap around some items
7. check the swaplist data in the click events using the dev console
8. notice no attributes keeping the dataset per post or the list titles.

**Expected behavior**
1. Ideally we can send the data with a title attribute that will then be the visible title.
2.  Ideally we can input the dataset sorted by which data should end up under which title from issue 1. (Like available, selected, deselected ecample below from enterprise-ng)
![image](https://github.com/infor-design/enterprise-wc/assets/9215760/b9176e65-1000-427f-896c-d039e66c59dc)
3. Data to be tracked under each title/post so that when clicking the swap or when saving the document we can easily get data from all lists or one specific list depending on needs.

**Version**
- ids-enterprise-wc beta-11

**Platform**
enterprise-wc with angular

Additional context
Infor M3 Portals

**Comment by Carlfjord** [comment]
Sorry this posted before I was able to completely fill it out. WIP

**Comment by glenlieorillo** [comment]
The fix is already applied. However, the title header should be aligned properly, and the hover has overlapped the border. See screenshots below:

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/7d5b9a7e-3662-4bf5-8dc3-b0630984a96c)

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/6e5f91ec-4f48-4ddd-8f7b-92fc51aa2f4e">

**Comment by glenlieorillo** [comment]
Tested and passed.


https://github.com/infor-design/enterprise-wc/assets/102151352/4c1db0b9-4baa-440b-8ced-7aa8c0756d1e
