### ISSUE TITLE
IdsDatagrid: An option to activate edit mode on an editable cell when right clicked

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1319]
**Is your feature request related to a problem or use case? Please describe.**
When an editable cell is clicked, it goes to edit mode. But when right clicked, it stays a span. We would like to request a configuration to allow the editable cell to be editable when right clicked.

**Describe the solution you'd like**
When a editable cell is right clicked, set the cell to be editable before triggering the beforemenushow.

**Describe alternatives you've considered**

**Additional context**
Currently, right clicking an editable cell does not change it to editable.
![image](https://github.com/infor-design/enterprise-wc/assets/53523076/3ae4b62e-cc69-456d-8d0f-caa80cdc6ab2)

And what application do you work on? M3 H5A

**Comment by GMInf** [comment]
Hi @tmcconechy,
I am trying to put in on the beforemenushow event, when right clicking on an editable cell it gives the type === body-cell, but I was expecting it to be body-editable-cell to be sure it is editable but anyways I retrieved the cell and run startCellEdit() but it did activate to edit mode.
Hoping for an example on this one. Thanks in advance.

**Comment by tmcconechy** [comment]
Ok so the example would

- use beforemenu show (as its a dynamic menu)
- one menu item when clicked would say "edit cell"
- the cell you right clicked should go in edit mode and focus

Can do, but I just want to point out its just as easy to click the cell as it is to right click it. Probably easier because you have to sort through all the menu items.

**Comment by jbrcna** [comment]
QA Passed
https://main.wc.design.infor.com/ids-data-grid/editable-contextmenu-before-show.html
<img width="551" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/54eb66ad-57ef-4fd2-b745-454a9787edae">

`Edit mode`
<img width="674" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b3f9c1e8-dd0d-4a00-86da-e5c430840135">
