### ISSUE TITLE
DataGrid: When we have many lines of data in data grid (over 100 ) data and columns are not shown

### ISSUE THREAD

**Issue by sofien-chaouch-infor** [infor-design/enterprise-wc#1322]
**Describe the bug**
when we have many lines of data in data grid (over 100 ) data and columns are not shown

**To Reproduce**

1. Go to any data grid with over 100 lines of data

**Expected behavior**
show rows and columns
 
**Version**

- ids-enterprise: v14.1.13

**Screenshots**

**Platform**
 - Infor RMS /HPO-RMS

**Comment by tmcconechy** [comment]
@sofien-chaouch-infor we have a lot of examples with more than 100 lines and they work. Can you put together an example to reproduce?

If you take this simple example and plug in the code that shows the issue https://github.com/infor-design/enterprise-wc-examples/tree/main/plain-html then submit it here and we can take a look
