### ISSUE TITLE
IdsDatagrid: Unable to deselect row when it is outside currently loaded rows

### ISSUE THREAD

**Issue by edisonferrer** [infor-design/enterprise-wc#1329]
**Describe the bug**
Unable to deselect a row when it is not on the currently loaded set of rows.

**To Reproduce**
Recreated on samples page: /ids-data-grid/virtual-scroll-row-start.html

1.) Select row 1 
2.) Scroll down the list, making sure that row 1 is not currently on the loaded rows on the DOM,
3.) Issue a deselect command for row 1
Bug: Notice that when you scroll back to row 1, it is still selected.

**Expected behavior**
Rows can be deselected even if it is not currently virtually loaded on the view.

**Version**
1.0.0-beta.11

**Screenshots**
Recording here:

https://github.com/infor-design/enterprise-wc/assets/47999751/a6d9666a-782d-4414-a1a0-7da76ff859f7

**Platform**

**Additional context**

**Comment by glenlieorillo** [comment]
Tested and passed.

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/7b5220ef-60ff-42a9-994e-1f4ed57e9664)
