### ISSUE TITLE
General: Add Mobile Gesture

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#133]
**Is your feature request related to a problem or use case? Please describe.**

We have limited support for touch... This task is to add a new "mixin" to the web components or use the Events mixin to handle more mobile gestures.

Should support:

- [x] Events: Tap event - Fires when user tap on an element.
- [x] Events: Longpress event - Fires when user tap on an element and hold for couple of seconds - this is already in 4.x https://github.com/infor-design/enterprise/blob/main/src/behaviors/longpress/longpress.js and now in WC
- [x] Swipe event -  Fires when user horizontally drag more than 30px over an element.
- [x] Swipeleft event -  Fires when user drag more than 30px over an element in the left direction.
- [x] Swiperight event -  Fires when user drag more than 30px over an element in the right direction.
- [x] Swipe container component (swipe action) - swipe container https://github.com/infor-design/enterprise/issues/5254 in progress
- [x] Scroll container component (carousel) - called ios scrollview
- [ ] Make http://localhost:4000/components/monthview/example-inpage.html scrollable with sticky header
- [ ] open the sharing menu https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
- [ ] clicking a button that does a mailto: or tel: (see that in the design) -> would maybe stick a link off screen and call click

**Describe the solution you'd like**
Add a clean api so we can hook into these features. Integrate them in both the old and new project. And come up with a more complete list and document in the docs

**Describe alternatives you've considered**
See designs for swipe container...
[Archive.zip](https://github.com/infor-design/enterprise/files/6472894/Archive.zip)

**Comment by anton-kurilov** [comment]
Will these be available for use in the angular project as well?

**Comment by tmcconechy** [comment]
Yeah i plan on adding a swipe-container and a swipe-action component to both the old and new code. But will need to remember to add it to angular if needed. So if you find the component is not available in NG and you still need it just let me know when its done.. Gotta get it done first

**Comment by anton-kurilov** [comment]
thanks @tmcconechy !

**Comment by tmcconechy** [comment]
Closing this off as most is implemented that we want to do for now
