### ISSUE TITLE
IdsButton: Components with pixels sizes are not working

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#1334]
**Description**
When set width and height in px to components like button and input it is not changing the size.

**To Reproduce**
At example page: https://main.wc.design.infor.com/ids-button/responsive.html

and:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600&amp;display=swap" rel="stylesheet" />

    <link rel="stylesheet" href="./node_modules/ids-enterprise-wc/themes/ids-theme-default-light.css">

    <script type="module" src="./node_modules/ids-enterprise-wc/components/ids-input/ids-input.js"></script>
    <script type="module" src="./node_modules/ids-enterprise-wc/components/ids-button/ids-button.js"></script>

    <title>Infor IDS</title>
</head>
<body>
    <ids-input label="IDS Text Field" width="500px", height="200px"></ids-input>
    <ids-button appearance="primary" width="500px", height="200px">
        <span>IDS Button</span>
    </ids-button>
</body>
</html>
```

Run the page

**Expected behavior**
Set both input and button width to 500px and height to 200px.

**Version**

- ids-enterprise-wc: v1.0.0 beta 11

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - OS Version: IOS 10.15
 - Browser Name: Chrome
 - Browser Version: 114.0

**Comment by glenlieorillo** [comment]
Tested and passed.

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/2b679106-6b1a-4e6b-8bb5-cdba2d9c8b60">

**Comment by fabiojpoli** [comment]
For my initial example posted on this issue (code bellow) width for button now works, but height for button, width for field and height for field still doesn't work:
```
<ids-input label="IDS Text Field" width="500px", height="200px"></ids-input>
    <ids-button appearance="primary" width="500px", height="200px">
        <span>IDS Button</span>
    </ids-button>
```

![Screen Shot 2023-06-20 at 7 30 10 PM](https://github.com/infor-design/enterprise-wc/assets/663908/19d96b43-585d-4aa9-9d20-3efd779c553e)

**Comment by tmcconechy** [comment]
We dont support changing the height of inputs and buttons. Maybe make a new issue with the use case for that. But we do support a few special sizes https://main.wc.design.infor.com/ids-input/test-sizes.html

May be able to do this with the css theming variables

**Comment by fabiojpoli** [comment]
I understand. Doesn't make much sense change height or even width for field with exact pixels. However, on Infor mongoose designer user is able to create form moving fields and elements and also resize elements dragging and we are bringing IDS components for this designer.

I will create a new issue maybe as suggested feature and post the reference here. Thank you!

**Comment by tmcconechy** [comment]
Sure, we might have a solution with the css variables but post your issue and we can consider it

**Comment by fabiojpoli** [comment]
Feature request: https://github.com/infor-design/enterprise-wc/issues/1344
