### ISSUE TITLE
Tabs: Alabaster Cleanup 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1339]
**Describe the bug**
Need to finish up alabaster theme. on the tab component.

- Module tabs -> https://main-enterprise.demo.design.infor.com/components/tabs-module/example-index.html
- Header -> https://main-enterprise.demo.design.infor.com/components/header/example-index.html
- ~- Multi Tabs -> https://main-enterprise.demo.design.infor.com/components/tabs-multi/example-index.html~
- Header Tabs -> https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html
- Vertical Tabs -> https://main-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html

https://www.figma.com/file/gRpli2TgQ3scLE6GF4e2Hz/Alabaster-Clean-up?type=design&node-id=127-38900&t=bYNV1tThUhGQXib7-0

**Expected behavior**
Add design changes, adapt personalization colors and add deprecated label to multi tabs page

**Comment by jbrcna** [comment]
QA Failed
https://main.wc.design.infor.com/ids-tabs/module.html - misaligned x icon is safari 
<img width="1355" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/4da17f67-47e2-4082-8cf4-e55494e71293">

Also, 
https://main.wc.design.infor.com/ids-tabs/module.html - button sizing is different in safari compared to other browsers.
<img width="1406" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/7d4350b4-8fe1-4981-9ea2-676dcc3202ac">

https://main.wc.design.infor.com/ids-tabs/module.html - x icon is off when hovered.
<img width="1198" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/c862ba7e-d29b-4c2a-987b-682b9af5571e">
