### ISSUE TITLE
IdsDatagrid: Scrolling up fast results to no rows displayed

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1341]
**Describe the bug**
When there are a number of records loaded and the scroll bar is near or at the end, drag the scrollbar at the top/start really fast. The rows are not displayed any more, there is only white background.

**To Reproduce**

1. clone enterprise-wc, npm i
2. update virtual-scroll-infinite-scroll-m3.ts
3. set max count to 1000, `87:  const MAX_RESULTS_COUNT = 1000;`
4. load a lot of data `99:  const dataSet = data.splice(0, Math.min(numRowsNeeded, 900));`
5. remove .rowStart `104:  // dataGrid.rowStart = 120;`
6. remove .selectRow `109: // dataGrid.selectRow(120);`
7. npm start
8. move scrollbar to the bottom, (up to record 1000)
9. move scrollbar to the top/beginning as fast as possible
10. Error: no rows displayed

Updated virtual-scroll-infinite-scroll-m3.ts
[h5-datagridwc.component.ts.zip](https://github.com/infor-design/enterprise-wc/files/11785660/h5-datagridwc.component.ts.zip)

**Expected behavior**
Beginning rows should be displayed

**Version**

- ids-enterprise-wc: 1.0.0-beta.12

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/53523076/4bce011e-af58-4921-ad77-a8a6065a71bb

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: chrome
Browser Version: 113.0.5672.127 (Official Build) (64-bit)

**Additional context**
Upon scroll to the top, transform: translateY was not recomputed;
![image](https://github.com/infor-design/enterprise-wc/assets/53523076/46ac594b-4abe-433b-8a4e-01d66c0b5c24)

**Comment by GMInf** [comment]
Hi,
We also encounter when scrolling down really fast from the middle to the bottom of the scroll puts the scroll bar at the top position. Could it be related to this?

**Comment by tmcconechy** [comment]
Yes it must be @GMInf . @jdilag is looking at this issue next.

**Comment by glenlieorillo** [comment]
Tested and passed.


https://github.com/infor-design/enterprise-wc/assets/102151352/0e6dd11f-97ce-44de-be27-cb8c7c94a777
