### ISSUE TITLE
IdsMultiSelect: Extra space on tags 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1349]
**Describe the bug**
Noticed a regression testing a page.

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-multiselect/example.html
2. Select some values
3. See the extra spaces

**Expected behavior**
Check old versions. Some regression.

**Comment by glenlieorillo** [comment]
Tested and passed.


https://github.com/infor-design/enterprise-wc/assets/102151352/7acece11-30ef-4b00-a99e-6637869ea253
