### ISSUE TITLE
IdsListView: Setting new data does not refresh the list

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1352]
**Describe the bug**

When I changed the data during runtime it somehow wasn't detected. The same issue I observed in 'old' components, the view is changed, but on events like select/activate it returned undefined

**To Reproduce**

1. Make a list view example with a button that changes between two data sets
2. See that it updates when the data changes
3. See all events and actions like selection still work.

**Comment by glenlieorillo** [comment]
QA Passed.


https://github.com/infor-design/enterprise-wc/assets/102151352/face32fd-0a27-4ae7-892e-05a8654e6b43
