### ISSUE TITLE
IdsCalendar: Failed to execute 'observe' on 'ResizeObserver'

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#1359]
**Description of the bug**
When load the page with calendar, console throws an error:

> ids-chunk-ZXDVUHSP.js:315 Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
>     at #u (ids-chunk-ZXDVUHSP.js:315:1916)
>     at p.connectedCallback (ids-chunk-ZXDVUHSP.js:315:1696)
>     at ids-chunk-XE4WFW5M.js:1:64
>     at l (ids-chunk-U7OOVFXE.js:1:254)
>     at ids-chunk-ZXDVUHSP.js:471:1552

**To Reproduce**
Load the page with calendar:
```html
<!DOCTYPE html>
<html manifest="">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta charset="UTF-8" />

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600&amp;display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="./enterprise-wc/build/dist/production-esm-splitting/themes/ids-theme-default-light.css">
    <script type="module" src="./enterprise-wc/build/dist/production-esm-splitting/components/ids-calendar/ids-calendar.js"></script>
  </head>
  <body>
    <ids-calendar></ids-calendar>
  </body>
</html>
```

**Version**
- ids-enterprise: 1.0.0-beta.12

**Platform**
 - Mac OS
 - Browser Name: Chrome

**Comment by tmcconechy** [comment]
The component is looking for an ids-container https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-calendar/ids-calendar.ts#L232

As a workaround you could do..

```html
<!DOCTYPE html>
<html manifest="">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta charset="UTF-8" />

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600&amp;display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="./enterprise-wc/build/dist/production-esm-splitting/themes/ids-theme-default-light.css">
    <script type="module" src="./enterprise-wc/build/dist/production-esm-splitting/components/ids-calendar/ids-calendar.js"></script>
  </head>
  <body>
    <ids-container><ids-calendar></ids-calendar></ids-container>
  </body>
</html>
```

Im not sure if this is really needed so can probably change it. 

NOTE TO SELF. Can be reproduced in plain-html example with

```html
<!DOCTYPE html>
<html lang="en-US">
<head>
  <title>IDS Calendar Component</title>
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600&amp;display=swap" rel="stylesheet" />
  <meta name="viewport" content="width=device-width">
  <meta http-equiv="Cache-control" content="max-age=31536000">
  <script type="module" src="/node_modules/ids-enterprise-wc/components/ids-calendar/ids-calendar.js"></script>
  <link rel="stylesheet" href="/node_modules/ids-enterprise-wc/themes/ids-theme-default-light.css">
</head>
<body>
  <ids-calendar></ids-calendar>
</body>
</html>
```

**Comment by tmcconechy** [comment]
PR didnt work. Will have to try this later. For now try to put ids-container around it. The other part of it is #663 needs to be completed or changing the locale will also not work without an ids-container.

So for now ids-container is required but we can fix that cc @fabiojpoli

**Comment by glenlieorillo** [comment]
Button border is cut-off.

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/8f17334e-b47c-438e-827f-a986796dc0fc)

**Comment by tmcconechy** [comment]
@glenlieorillo can you make a new issue for this?

**Comment by glenlieorillo** [comment]
Sure @tmcconechy, I will create another ticket for this issue.
