### ISSUE TITLE
IdsDatagrid: Property to display the ColumnHeaderExpander Button on first column

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1360]
**Is your feature request related to a problem or use case? Please describe.**
Our application needs to display the ColumnHeaderExpander button. Beta 12 has that feature but the column.formatter needs to be a tree or an expander to display the ColumnHeaderExpander button. Our application has a custom column.formatter to allow us to make the cell's content configurable, for example an expande with a link.
![image](https://github.com/infor-design/enterprise-wc/assets/53523076/616940e7-2f13-4146-b7a5-94fe94596b0b)

**Describe the solution you'd like**
We would like a new property to forcefully add the ColumnHeaderExpander button to the first column like idsDatagrid.showHeaderExpanderOnFirst or idsDatagrid.columns[0].showHeaderExpander.

**Describe alternatives you've considered**

**Additional context**
And what application do you work on? M3 UX H5A

**Comment by glenlieorillo** [comment]
Tested and passed.

https://github.com/infor-design/enterprise-wc/assets/102151352/01c0aeba-c182-406d-a29f-8a8e8251b911
