### ISSUE TITLE
Radio Button Group: Visual issue with the asterisk when displaying horizontally and validation is required

### ISSUE THREAD

**Issue by Spydr331** [infor-design/enterprise-wc#1363]
While working the the radio button group, I used this code:

```
<ids-radio-group label="Horizontal Radio" horizontal="true" validate="required">
<ids-radio value="opt1" label="Option one"></ids-radio>
<ids-radio value="opt2" label="Option two" checked="true"></ids-radio>
</ids-radio-group>
```
I expect the asterisk to appear right after the label for "Horizontal Radio" but instead it appears on the far right of the component after all the horizontal radio options.

**Comment by glenlieorillo** [comment]
Tested and passed.

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/db0335be-8d1b-463e-bd58-a65e7fad1882)
