### ISSUE TITLE
IdsDatagrid: Using RowStart still renders the scrollbar starting from the top not the intended index

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1368]
**Describe the bug**
When using idsDatagrid.rowStart, there is a brief moment that the scrollbar is at the top/beginning. 

**To Reproduce**

1. git clone enterprise-wc, npm i
2. replace virtual-scroll.ts with attached file
3. npm start
4. open virtual-scroll.html
5. See error, the scroll bar starts at the top and moves to the intended rowstart position

**Expected behavior**
The scroll bar should be initially shown in the right position (based on the rowStart value) , not at the top. The behavior should be similar to Infor controls and Soho controls that when a starting position is set, the scrollbar is exactly at the intended position.

**Version**

- ids-enterprise-wc beta 12

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/53523076/c9b1dc5f-326c-44f5-8f2e-dfd6267e5c34)
![image](https://github.com/infor-design/enterprise-wc/assets/53523076/2b8a1232-c8bd-445e-869e-bc2c4a9c2b23)

https://github.com/infor-design/enterprise-wc/assets/53523076/f4c740d5-98e9-4999-8c85-6bfa1d2f08aa

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: chrome
Browser Version: 113.0.5672.127 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
@GMInf ~ Just to clarify is the scrollbar size changes? I.E. At one point its slightly bigger than the other? Also is this a case of appending more data at the bottom?

**Comment by GMInf** [comment]
Hi @tmcconechy, 
Yes, it looks like the scroll bar size changes. It is bigger at the beginning, becomes smaller in the intended scrollbar position. 
For this case, we use this to load all data and start on an index. We are not appending data.

**Comment by tmcconechy** [comment]
Can also be seen pretty easily on https://main.wc.design.infor.com/ids-data-grid/virtual-scroll.html notice as you scroll down.
Just might be an easier way

**Comment by jbrcna** [comment]
QA Failed
**row-start**
https://github.com/infor-design/enterprise-wc/assets/56722184/d10203de-ee74-4ec9-a024-5f03ad70d163

**virtual-scroll-row-start**
https://github.com/infor-design/enterprise-wc/assets/56722184/0d7173aa-228d-48d9-8343-6ad7c05b19ee

**virtual-scroll-infinite-scroll-m3**
https://github.com/infor-design/enterprise-wc/assets/56722184/51d8a26e-403b-4733-bb0f-8de032592858

**Comment by tmcconechy** [comment]
@jdilag90 anything to look at there ☝🏻

**Comment by jdilag90** [comment]
@jbrcna the videos shared look ok. Can you specify why it's marked as failed?

**Comment by jbrcna** [comment]
observe the scroll bar, notice that when I try to load/reload the page the scroll bar resizes/start at the top. try to load over and over again

**Comment by jbrcna** [comment]
this is now working as expected. thank you 
QA Passed.
