### ISSUE TITLE
IdsDatagrid: Make height of Column headers smaller on size XXS

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1369]
**Is your feature request related to a problem or use case? Please describe.**
Some M3 users likes the datagrid to display as much rows as possible. The column header height can still be reduced.

**Describe the solution you'd like**
Make the space in between the header top and label, between label and filter text box or header bottom smaller.
![image](https://github.com/infor-design/enterprise-wc/assets/53523076/54ebf077-381b-4e1e-8a1b-1613fa179ca1)

**Describe alternatives you've considered**

**Additional context**

And what application do you work on? [e.g. M3 UX

**Comment by glenlieorillo** [comment]
Tested and passed.

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/725725c8-fbf7-4bf9-9e8d-94658d508ede)
