### ISSUE TITLE
IdsScrollView: Controls Not Showing When Using *ngFor

### ISSUE THREAD

**Issue by yousef-elkaisi** [infor-design/enterprise-wc#1372]
**Describe the bug**
When we create an ids-scroll-view component in angular, and inside we add another element that is populated using an *ngFor, the control buttons on the scroll-view are not showing.

**To Reproduce**
Create a component in angular and add an ids-scroll-view in the template. In the class, add an array with some items in it. Then inside ids-scroll-view, add another element with an *ngFor that loops over your array and populates that element. When you load the page, you will not see the controls on the bottom of ids-scroll-view.

Example:
`<ids-scroll-view #scrollview>
  <img *ngFor="let cameraSrc of cameraSrcs" [src]='cameraSrc' class="camera-1" slot="scroll-view-item" alt="Slide 1, Sony Camera, Front"/>
</ids-scroll-view>`

In class: 
`  protected cameraSrcs = [
    './assets/images/camera-1.png',
    './assets/images/camera-2.png',
    './assets/images/camera-3.png',
    './assets/images/camera-4.png',
    './assets/images/camera-5.png',
    './assets/images/camera-6.png',
  ];`

**Expected behavior**
The circle button controls should be displayed.

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/132393590/ce0c5ec7-2e81-4f36-a55d-5de6c55ead88)
**Platform**
 - WFM
 - Windows 11
 - Chrome 114.0.5735.133

**Comment by glenlieorillo** [comment]
QA tested and passed.

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/312c8341-aad6-49db-9ea5-d26102f3a1c2)
