### ISSUE TITLE
IdsButton: primary and secondary buttons height

### ISSUE THREAD

**Issue by jomcab** [infor-design/enterprise-wc#1376]
**Describe the bug**
Expecting both buttons to have the same height, but the primary button measures 34px while the secondary button measures 36px.

1. Go to https://main.wc.design.infor.com/ids-button/example.html
2. Right click and inspect elements
3. Hover on buttons to see the height
4. Observe that buttons have different height

**Expected behavior**
Same height out-of-the-box

**Version**
ids-enterprise: 1.0.0.beta-12

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/12105280/0089152b-8746-4b89-9ea6-aeb80a0e5665)

**Comment by tmcconechy** [comment]
@jomcab not seeing the same exact thing. I think it depends how you inspect them

![Screenshot 2023-07-11 at 2 58 45 PM](https://github.com/infor-design/enterprise-wc/assets/814283/38d9454b-a58f-4c6a-a1dc-d8bafd8110ff)
![Screenshot 2023-07-11 at 2 58 54 PM](https://github.com/infor-design/enterprise-wc/assets/814283/e4c4e58b-600e-443d-a9de-f7edf5406fa2)

At the end of the day they are both 36px to me

**Comment by jomcab** [comment]
Tried it on my windows device using chrome, firefox, and edge. All have different heights.
This is the screenshot when I zoom-in:
![image](https://github.com/infor-design/enterprise-wc/assets/12105280/0585c06d-ca5f-4bcf-9f6f-b9c601c61702)

**Comment by jbrcna** [comment]
QA Passed

<img width="450" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/930b1308-41c7-4003-9136-4de33ef9a1af">

<img width="411" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/5c0f44a9-02c6-4b9d-9aad-e66c6fb9509f">
