### ISSUE TITLE
Lottie: Add Examples or Components For Lottie Integration

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1378]
**Is your feature request related to a problem or use case? Please describe.**
https://github.com/airbnb/lottie-web -> design would like to use this to provide some in app fancy animations. Need a way to support this but want to avoid direct dev dependencies.

**Describe the solution you'd like**
 - take example from https://codepen.io/airnan/project/editor/ZeNONO
 - put in either a second repo you can pull from or as examples
 - avoid direct dev dependencies in enterprise-wc
- if needed add a wrapper like `<ids-animation>` the wrapper may add
- colors, sizes and names of supported components
- add the JSON in that repo 
- and README.md on how to use
- use .dotlottie file not JSON

**Describe alternatives you've considered**
Can be in the main enterprise-wc 

**Needs**
- A name if a new component `<ids-animation>` or `<ids-motion>`
- The JSON for it starting with one example

**Additional context**
Ms Teams/PM

**Future**
Some APIS like https://carbondesignsystem.com/guidelines/motion/overview/
Or use figma rather than Adobe After Effects https://www.figma.com/community/plugin/889777319208467032/Motion---UI-and-Games-animation and other figma tools

**Comment by talkaboutdesign** [comment]
Here is a semi related ticket: @tmcconechy 
https://jira.infor.com/browse/IDS-1344

**Comment by tmcconechy** [comment]
OK some of these can be done on the <ids-icon component. But i think possibly we need to keep lottie seperate because of the huge weight of the data and that its third party. Just means keeping it in a seperate place.

Possibly `<ids-icon>` `<ids-image>` and `<ids-animation>`

**Comment by tmcconechy** [comment]
@talkaboutdesign what is a lottie file extension? info please?

**Comment by talkaboutdesign** [comment]
That link should have both options.

**Comment by tmcconechy** [comment]
One idea for doing these in figma instead of after effects. 

https://www.figma.com/community/plugin/889777319208467032/Motion---UI-and-Games-animation

**Comment by tmcconechy** [comment]
Did the initial work on this. All information and examples are in this repo https://github.com/infor-design/ids-animation
Please review. @talkaboutdesign @inforandy for anything you want to include.

I showed all examples in the tests but think the best option is the prebuilt web component that loads lottie files. This repo can serve as docs and a library of the animations
