### ISSUE TITLE
IdsDataGrid: Column title, dropdown filter etc. are hard to read when hovering in Dark Mode

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#1382]
**Describe the bug**
Column title, dropdown filter etc. are hard to read when hovering in Dark Mode.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/disable-client-filter.html
2. Change to Dark Mode
3. Hover column header

**Expected behavior**
Column header should be readable.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/102151352/bfb5ffde-8423-41c5-ad2a-4a2660ed1c62

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
Noticed this as well and is slated to be fixed on the attached PR

**Comment by jbrcna** [comment]
this is now working as expected. moving ticket to Done. thanks
<img width="1587" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/c3b91491-448f-4ad2-ae56-dbea2f1a9485">
