### ISSUE TITLE
IdsDatagrid: Scroll bar in wrong location after scrolling on large records in Virtual Scroll = true

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1390]
**Describe the bug**
When scrolling down, the scroll bar gets on the wrong location and Scroll end is triggered with out reaching the end. This happens when loading a large number of records.

**To Reproduce**

1. clone enterprice-wc, and npm i
2. extract custom-css.css, virtual-scroll-infinite-scroll-m3.ts and m3-item.json from this file: 
[Ids-virtual-scroll.zip](https://github.com/infor-design/enterprise-wc/files/12091437/Ids-virtual-scroll.zip)
3. copy custom-css.css to enterprise-wc\src\assets\css\ids-data-grid\ and overwrite
4. copy  virtual-scroll-infinite-scroll-m3.ts to enterprise-wc\src\components\ids-data-grid\demos\ an overwrite
5. copy m3-item.json to enterprise-wc\src\assets\data
6. npm start
7. open virtual-scroll-infinite-scroll-m3.html
8. scroll down to the bottom and wait for data to load
9. repeat step 8, about 8 to 10 times until scrollbar gets to the middle
10. Error: the scroll bar is no longer in the right position
11. Scroll down, scroll end is triggered without getting near the bottom

**Expected behavior**

**Version**

- ids-enterprise-wc beta 13

**Screenshots**
Videos:
Scroll down Issue
[IDS Data Grid Component - Google Chrome 2023-07-19 13-46-12.zip](https://github.com/infor-design/enterprise-wc/files/12091499/IDS.Data.Grid.Component.-.Google.Chrome.2023-07-19.13-46-12.zip)

Scroll end trigger issue and white display/no rows on scroll
[IDS Data Grid Component - Google Chrome 2023-07-19 21-12-23.zip](https://github.com/infor-design/enterprise-wc/files/12095283/IDS.Data.Grid.Component.-.Google.Chrome.2023-07-19.21-12-23.zip)

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: chrome
Browser Version: 113.0.5672.127 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
https://github.com/infor-design/enterprise-wc/issues/1368 could be related ~ we might want to do this first and see if fixing the scroll size is the actual problem

**Comment by jbrcna** [comment]
QA Passed.
when I grab the scrollbar with my mouse and drag all the way, it only blinks a white screen

**Comment by GMInf** [comment]
Hi @tmcconechy/@EdwardCoyle/@jdilag90,
Tried out Beta 14 on our app. We still encounter an issue after scrolling down several times. After scrolling 5 times, the scroll bar is stuck at the end. But there is still be data at the bottom. I can't replicate on enterprise-wc yet but attaching a video of how to recreate the issue on our environment.
I have deployed unminified Beta 14 to make it readable.
Here are the replication steps:
1) go to https://mingle-cqa-portal.cqa.inforcloudsuite.com/M3CEDEVAPPUP_DEV
2) Click on the App Menu (upper left, 9 dots)
3) Look for XI Ge app, (mostly 5th page)
4) Click on XI Ge
5) Press Ctrl + R
6) Type CMP980BBR, enter
7) Press Ctrl + R
8) Type MMS001, enter
9) At the datagrid, scroll down to the end 5 times
10) Error: Scrollbar is stuck at the end after idsDatagrid.appendData()
Expected: Scroll bar should reposition near the end of the scrollbar not at the end since new data was added with idsDatagrid.appendData()
Video:
https://github.com/infor-design/enterprise-wc/assets/53523076/3ade2d90-fea0-4c62-8579-504309e69bfc

**Comment by jdilag90** [comment]
@GMInf I followed the steps above and found that the example in your portal is using the Soho enterprise version of the datagrid. I don't think the Soho version supports an infinite scroll feature, so it's probably a custom implementation in your app. Can you confirm if your comment is still and issue or not regarding this ticket?

**Comment by GMInf** [comment]
Hi @jdilag90,
Oh right, by default your user will use soho datagrid. I have now set your user to use the new IdsDatagrid. I'll also send instructions if you need to add more users.
Confirming that this is still an issue.

**Comment by jdilag90** [comment]
@GMInf getting a 404 when I navigate to the Xi GE app now
![image](https://github.com/infor-design/enterprise-wc/assets/98347152/eae62475-9e52-413a-97b9-cfc5a9771454)

@tmcconechy @clayinfor are you guys able to access IdsDataGrid under Xi GE

**Comment by tmcconechy** [comment]
No i do not know how to login it doesnt take my infor ID. @GMInf I think we should have a new issue for this. Is there no way to reproduce without Mingle?

**Comment by GMInf** [comment]
Hi @jdilag90, there was an issue yesterday with some nodes returning 404s. The issue is resolved now. But we could try this out on our meeting to be sure.

Hi @tmcconechy, I can't replicate this on enterprise-wc yet. I don't think the issue is with the appendData. The issue happens on our end in  `idsDatagrid.#scrollRowIntoView()` computing a smaller `body.style.setProperty('transform', `translateY(${bodyTranslateY}px)`);` than expected when the rows are reused for the first time. This is from the Beta 14. 

We just added your account, you should be getting an activation email. 

I will try to check this with the latest codes on main.

**Comment by GMInf** [comment]
Hi @tmcconechy,
1. May be you could try different zoom levels? Or it could be that there is a selected record when scrolling down. No records should be selected to replicate the issue ( kindly see 2. ).
2. Please do not select a record when scrolling down to replicate the issue. We have a bug that when there is a record selected and scroll end is reached, after appending the datagrid it scrolls back to the selected record.
3. We do not call it directly, It is called when scrolling, by the idsDatagrid's 'scrollend.data-grid.virtual-scroll' event then  this.#handleVirtualScroll then idsDatagrid.#scrollRowIntoView(). I think that is where the issue happens inside the idsDatagrid.#scrollRowIntoView(), the height of the datagrid body is recomputed but the height is incorrect on our environment. 

I can help you out to replicate the issue if you have some free time and show you where I think the issue happens. Also, I will also try out the main branch.

**Comment by GMInf** [comment]
Hi @tmcconechy,

Tried the main branch, but I can still replicate the issue. 
Also, our code has basically the same logic in https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/demos/virtual-scroll-infinite-scroll-m3.ts#L496.

**Comment by jdilag90** [comment]
@GMInf @tmcconechy @clayinfor I was able to replicate the issue. Looking into it now

**Comment by tmcconechy** [comment]
@jdilag90 if you want to make a new issue with the steps that would be the best idea i think https://github.com/infor-design/enterprise-wc/issues/new/choose
