### ISSUE TITLE
IdsDataGrid: Custom Selection Color Changes after row recycling

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1392]
**Describe the bug**
The custom select color is lost on row recycling or virtual scroll. 

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-data-grid/m3-features.html
2. Click on a row and it has a custom green css color on select
3. Scroll down about 200-300 
4. Scroll back up -> notice the color is the normal selection color not the custom one

**Comment by lucacolumbu** [comment]
Maybe due to cacheing

**Comment by tmcconechy** [comment]
Basically its not applying this logic https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/demos/columns-custom-css.ts#L89 on the recycled row
