### ISSUE TITLE
IdsDatagrid: scrollend is not triggered when treeGrid = true and on a different browser zoom percentage

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1396]
**Describe the bug**
IdsDatagrid does not trigger scrollend when moving scroll to the bottom, treeGrid is set to true and browser zoom level is 110% and above.

**To Reproduce**

1. clone enterprise-wc, npm install
2. copy attached virtual-scroll-infinite-scroll-m3,ts and virtual-scroll-infinite-scroll-m3.html (attached demos.zip) to enterprise-wc\src\components\ids-data-grid\demos\
[demos.zip](https://github.com/infor-design/enterprise-wc/files/12144005/demos.zip)
4. npm start
5. set chrome zoom to 110%
6. scroll down to the end of the scroll bar
7. see error, the datagrid does not trigger scrollend event
8. refresh browser, set back to 100% and scrolldown, it works

**Expected behavior**
IdsDatagrid scrollend should trigger when scrollbar is at the end even if treeGrid = true without sub rows. It works at 100% but it is not working on other zoom level.

**Version**
- ids-enterprise-wc beta 13

**Screenshots**
Video: https://github.com/infor-design/enterprise-wc/assets/53523076/2376a00a-6a7b-4681-80ed-baf683e6dfc9

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: chrome
Browser Version: 113.0.5672.127 (Official Build) (64-bit)

**Additional context**

**Comment by glenlieorillo** [comment]
QA tested and passed.


https://github.com/infor-design/enterprise-wc/assets/102151352/7e6e6ef2-caa1-4be4-9e0d-14298a1971ab


https://github.com/infor-design/enterprise-wc/assets/102151352/51dd495a-a4d1-4444-97e8-86c2e0601afc


https://github.com/infor-design/enterprise-wc/assets/102151352/06e40d8d-a7a1-4a95-a7fe-3d693373eab7
