### ISSUE TITLE
IdsListView: Minor Refactor and Fix Search and Selection

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1400]
**Describe the bug**
After https://github.com/infor-design/enterprise-wc/pull/1377 we left list view in a state that needs some fixes. Namely:

- all the selection examples
- the search example
- additional refactoring https://github.com/infor-design/enterprise-wc/pull/1398

**To Reproduce**
1. on http://localhost:4300/ids-list-view/list-view-items.html i see two selected and selection does not change on click
2. similarly on http://localhost:4300/ids-list-view/list-view-items-selectable-mixed.html cant "activate" the rows by clicking
3. http://localhost:4300/ids-list-view/list-view-items-selectable-multiple.html also a problem changing selection
4. on http://localhost:4300/ids-list-view/list-view-items-search.html 
  a) the search doesn't seem to work
  b) it would look better if it was 100% width

**Expected behavior**

Cleaner code from a minor refactor and working search and selection

**Additional context**
https://github.com/infor-design/enterprise-wc/pull/1377

**Comment by jbrcna** [comment]
the issues mentioned above is now fixed. 
<img width="865" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/f83d00bb-9314-4926-9723-0aae9d99a549">

<img width="857" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b46a297c-ce93-4ef8-bde9-8ae788e32899">

<img width="1692" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/a0ef60c8-b429-4795-bf94-417549066ac0">

<img width="1692" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/a0ef60c8-b429-4795-bf94-417549066ac0">

------------
**just a few observations:**
http://localhost:4300/ids-list-view/list-view-items-sortable.html - unable to sort items in edge, chrome, safari browser. Firefox is working fine. i was able to sort "fifth column item" but it was difficult. it doesnt work on other items.
![Large GIF (850x720)](https://github.com/infor-design/enterprise-wc/assets/56722184/abbd42e4-d78f-45a5-aa8c-61f669a2ee69)


http://localhost:4300/ids-list-builder/example.html - unable to use "space" upon creating/editin an item. Also, when you press space/enter the text looks off
<img width="914" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/106a9ee2-a762-4961-8a35-ac52357206fa">

**Comment by tmcconechy** [comment]
Thanks @jbrcna would you make an issue with those in it and we can hit it later?
