### ISSUE TITLE
IdsDatagrid: filter max length issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1403]
**Describe the bug**
you can type < 2 chars in the filter. editable cell is working as expected.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/editable.html
2. check you can only type 2 chars in the filter
3. check you can type lower case chars and it converts to upper in the filter
4. check you can only type 2 chars in the editable cell
5. check you can type lower case chars and it converts to upper in the editable cell

**Expected behavior**
<img width="833" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/bc56fb41-de38-42d3-98ea-98f712470c32">

**Version**

- ids-enterprise: 

**Screenshots**

**Platform**
Safari

**Additional context**
related to https://github.com/infor-design/enterprise-wc/issues/1309

**Comment by tmcconechy** [comment]
@jdilag @EdwardCoyle @clayinfor I took a quick look and i dont get why Safari is rejecting `maxlength="2"`. Any thoughts?

https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/ids-data-grid-filters.ts#L1092

**Comment by glenlieorillo** [comment]
Tested and passed.

**Chrome**

https://github.com/infor-design/enterprise-wc/assets/102151352/5417d82a-8ef1-46a5-93c9-938a3c322a16

**Safari**


https://github.com/infor-design/enterprise-wc/assets/102151352/9464717b-c83f-40f9-90b4-3ba2676d8a7e

**Comment by jbrcna** [comment]
can confirm on my end. 
Passed.
