### ISSUE TITLE
IdsAppMenu: Close button hover color is off

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#1404]
**Describe the bug**
Close button hover color is off.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-app-menu/example-footer.html
2. Type any in search bar
3. Hover over close button

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="859" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/3a84ba2d-c448-475f-b966-8ec1c1dfce46">

**Platform**
 - All major browsers

**Additional context**

**Comment by tmcconechy** [comment]
I'll steal this one. Fixed it working on color variant refactor for NG

**Comment by glenlieorillo** [comment]
This is now working as expected.

**Light**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/56a7d152-7179-4c0e-bcdf-58b3883c36d9">

**Dark**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/ee3ec795-ec71-4205-95e7-81f825bf0b80">

**Contrast**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/3c8afd67-2c20-4df3-8e52-7e94d8c6161b">
