### ISSUE TITLE
Breakpoint sizes for grid flow attribute.

### ISSUE THREAD

**Issue by yousef-elkaisi** [infor-design/enterprise-wc#1405]
**Is your feature request related to a problem or use case? Please describe.**
We need to be able to adjust the flow attribute for an ids-layout-grid depending on the screen-size. (Ex. flow-xs, flow-md, etc.)

**Describe the solution you'd like**
https://github.com/infor-design/enterprise-wc/pull/1406

**Describe alternatives you've considered**

**Additional context**
Infor WFM Team Supernovas

**Comment by tmcconechy** [comment]
@jmacaluso711 dont we have this already?

**Comment by tmcconechy** [comment]
Fixed on linnked PR
