### ISSUE TITLE
Misc: Pull values from ui.config

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#141]
**Describe the bug**
We have some places where config can be pulled from https://github.com/infor-design/design-system/blob/main/design-tokens/ui.config.js#L199 we can use this for colors. Fonts and more.

**To Reproduce**
1. Pull the ui.config in for https://github.com/infor-design/enterprise-wc/blob/main/src/ids-text/ids-text.js#L16 via  js import from node_modules
1. Remove the xs, sm, md and use numbers
1. Document it

**Questions**
Should this be a part of IdsElement or standalone import.

**Additional context**

**Comment by tmcconechy** [comment]
Rethinking this because a) it adds quite a bit of unused code for little gain b) is easily synced up otherwise

**Comment by lucacolumbu** [comment]
@tmcconechy let's chat about this in our meeting tomorrow.
