### ISSUE TITLE
IdsMulitselect/Dropdown: ngFor not working to provide data

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-wc#1411]
**Describe the bug**
It seems like components such as `ids-multiselect` and `ids-dropdown` has some issues wherein `NgFor` and property binding cannot be used.

**To Reproduce**
```typescript
  listData = [
      { id: "al2", value: "al", tooltip: "The State of Alabama", label: "Alabama" },
      { id: "ak2", value: "ak", tooltip: "The State of Alaska", label: "Alaska" },
  ];
```
```html
<ids-multiselect id="dropdown-5" label="List Data Dropdown (max choices 3)">
  <ids-list-box class="options">

    <!-- <ng-container *ngFor="let option of listData"> -->
      <!-- <ids-list-box-option class="multiselect-option" [id]="option.id" [value]="option.value" [tooltip]="option.tooltip"> -->
      <!--   <ids-checkbox no-margin [label]="option.label" class="justify-center"></ids-checkbox> -->
      <!-- </ids-list-box-option> -->
    <!-- </ng-container> -->
    <ids-list-box-option class="multiselect-option"
      [id]="listData[0].id"
      [value]="listData[0].value"
      [tooltip]="listData[0].tooltip"
    >
      <ids-checkbox no-margin
        [label]="listData[0].label"
        class="justify-center"
      ></ids-checkbox>
    </ids-list-box-option>
  </ids-list-box>
</ids-multiselect>
```

**Expected behavior**
One option to be rendered, or two options rendered uncommenting the `NgFor` in template

**Version**
beta13

**Screenshots**
With one option
![image](https://github.com/infor-design/enterprise-wc/assets/542598/08c1b15a-c983-48d5-93fd-83409c2f0220)

WIth NgFor
![image](https://github.com/infor-design/enterprise-wc/assets/542598/dc69c13f-3ad2-4589-92da-64cf30579ddf)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Related issue https://github.com/infor-design/enterprise-wc/pull/1393/files may need to handle slot change

**Comment by clayinfor** [comment]
hey @tmcconechy , turns out this line is the culprit:
https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-multiselect/ids-multiselect.ts#L359

**Comment by tmcconechy** [comment]
Great, Do you have an angel for a fix? @clayinfor

**Comment by clayinfor** [comment]
yes @tmcconechy , I have PR coming soon :)
