### ISSUE TITLE
IdsLayoutFlex Margin Attribute

### ISSUE THREAD

**Issue by yousef-elkaisi** [infor-design/enterprise-wc#1415]
**Is your feature request related to a problem or use case? Please describe.**
We would like to be able to specify a margin around an ids-layout-flex just like we can with ids-layout-grid.

**Describe the solution you'd like**

**Additional context**
Infor WFM Team Supernovas

**Comment by tmcconechy** [comment]
I think the idea would be to wrap them... They have different uses so use the grid for the margins then put the layout items in it

```
    <ids-layout-grid gap="md" padding-x="md">
      <ids-layout-grid-cell>
            <ids-layout-flex direction="column">
              <ids-layout-flex-item>
                <ids-icon icon="stacked"></ids-icon>
              </ids-layout-flex-item>
              <ids-layout-flex-item>
                <ids-text font-size="16" font-weight="semi-bold">Purchase Order Intake Workbench</ids-text>
              </ids-layout-flex-item>    
            </ids-layout-flex>
      </ids-layout-grid-cell>
    </ids-layout-grid>
    ```

**Comment by yousef-elkaisi** [comment]
Ok, makes sense. Thank you.
