### ISSUE TITLE
Add to WC demo site: new empty state icon

### ISSUE THREAD

**Issue by hey-yall** [infor-design/enterprise-wc#1427]
Need to add the finalized icon (in Jira ticket [IDS-1504](https://jira.infor.com/browse/IDS-1504)) to the [WC demo site](https://main.wc.design.infor.com/ids-icon/example.html) under the "Empty Icons" section. 

Please reach out to Laken Renick (hey-yall) if you have any questions. Thanks!

**Comment by tmcconechy** [comment]
Needs fixes to icon pipeline

**Comment by tmcconechy** [comment]
No this isnt correct @jbrcna can you make an issue for safari?
