### ISSUE TITLE
IdsEditor: Add new Designs

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1434]
**Describe the bug**
Need to finish up alabaster theme design changes for the Editor component

**Expected behavior**

Editor: https://www.figma.com/file/8ekRxSWEbFxDzmvzraB1LH/Rich-Text-Editor?type=design&node-id=518-314&mode=design&t=aaj0rcFpsCQHH7lJ-0

See: https://jira.infor.com/browse/IDS-1335

**Comment by jbrcna** [comment]
this is now working as expected.
https://main.wc.design.infor.com/ids-editor/example.html
<img width="745" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/c1e85b22-d05c-4e9c-8747-6386837cfd39">

However, you some styles don't work in safari browser. when inserting Hyperlink or image , the page froze

![Large GIF (818x316)](https://github.com/infor-design/enterprise-wc/assets/56722184/46e77669-5fad-455d-be8b-58b5b9e583ba)

Also, `hyperlinks` and `dropdown` label were not slate in dark mode
<img width="516" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/45b343bf-eaa7-4c07-b452-33a79acfdc63">
