### ISSUE TITLE
NotificationBanner: Ability to wrap text to multiple lines

### ISSUE THREAD

**Issue by LilBiggs** [infor-design/enterprise-wc#1435]
**Is your feature request related to a problem or use case? Please describe.**
ids-notification-banner does not currently have the ability to wrap text to multiple lines. On small viewport devices (phone, tablets) it can be necessary to see more of the available message. 

**Describe the solution you'd like**
Ability to set a property on the ids-notification-banner to wrap text, instead of ellipsis. 

**Additional context**
Team - Infor WFM
Have checked some other UI Design Libraries out there and it would appear that multiple line notification banners are common.

- https://getbootstrap.com/docs/5.3/components/alerts
- https://tailwindui.com/components/marketing/elements/banners

![image](https://github.com/infor-design/enterprise-wc/assets/6730716/ed0a1e97-78d1-4e62-8eb2-1471c87916e2)

**Comment by glenlieorillo** [comment]
QA Passed.

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/d83a1dcc-d78b-4eec-bf5a-dec99ba7734f)
