### ISSUE TITLE
IdsEditor: Fix color button

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1437]
**Description**

Add fixes to the editor color button

**Describe the bug**
- [ ] Add design change https://github.com/infor-design/enterprise/pull/7780
- [x] Use color picker (it wasn't ready at the time)
- [ ] https://github.com/infor-design/enterprise-wc/issues/1079 will end up being fixed

**Comment by glenlieorillo** [comment]
This is now working as expected.


https://github.com/infor-design/enterprise-wc/assets/102151352/904d926f-e788-455b-b791-b1db3cc7e60c


https://github.com/infor-design/enterprise-wc/assets/102151352/1678ddda-f1be-4147-9bc1-dcd66e0a4c92
