### ISSUE TITLE
Export Individual or Entire Component Modules for Web Components

### ISSUE THREAD

**Issue by eaenriquez** [infor-design/enterprise-wc#1452]
Before, in Soho Components, there is an exported barrel file from the package that is really useful to easily import it into our applications like such:
![image](https://github.com/infor-design/enterprise-wc/assets/68070868/d088ff50-40f0-4524-a2e0-2f2005ef57c0)

In our NgModules:
![image](https://github.com/infor-design/enterprise-wc/assets/68070868/66f77e1d-0210-4080-86c8-0b6273d9c692)

And this might eliminate the need to import the `CUSTOM_ELEMENTS_SCHEMA` as of following the documentation and this would provide us the correct Intellisense and mapping when using it in our html templates.

This same practice will make things easier to migrate from Soho to Web Components

And what application do you work on?
Infor M3 Experience Designer (UX2)

**Comment by tmcconechy** [comment]
Im not sure the import you mentioned makes sense. It has very odd import names. We didnt want to go to special with anything and are just using Es Module imports.

But we do have an import like

```
// ALL
import 'ids-enterprise-wc/enterprise-wc.js';

// OR 
import 'ids-enterprise-wc/components/ids-tag/ids-tag';
import 'ids-enterprise-wc/components/ids-alert/ids-alert';
```

We arent actually giving you angular modules. These are es module components
