### ISSUE TITLE
IdsDatagrid: Arrow keys does not work on contextmenus opened by Shift F10

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1453]
**Describe the bug**
Using arrow keys does not work on a contextmenu opened by Shift F10

**To Reproduce**

1. clone enterprise-wc
2. npm install, npm start
3. open http://localhost:4300/ids-data-grid/editable-contextmenu-before-show.html
4. click on any cell
5. press Shift + F10
6. Press arrow down
7. Error: Active cell goes down instead of the context menu active item

**Expected behavior**
Context menu active item should move down 

**Version**

- ids-enterprise-wc: Sept. 5, 2023 main

**Screenshots**
No active menu item after Shift F10, unable to move arrow up/down on context menu
![image](https://github.com/infor-design/enterprise-wc/assets/53523076/2e20a1fe-c80c-43be-9b23-4ff0d54df91a)

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: chrome
Browser Version: Version 116.0.5845.140 (Official Build) (64-bit)

**Additional context**

**Comment by glenlieorillo** [comment]
This is now working as expected.


https://github.com/infor-design/enterprise-wc/assets/102151352/32a45933-926c-45ba-abc1-b391961e1460
