### ISSUE TITLE
Datagrid: SetActiveCell do not work if rowNavigation is set to false

### ISSUE THREAD

**Issue by jjorge1999** [infor-design/enterprise-wc#1456]
**Describe the bug**
SetActiveCell do not work if rowNavigation is set to false

**To Reproduce**

1. Go to http://localhost:4300/ids-data-grid/example.html
2. Open Dev tool 
3. Make sure rowNavigation is set to false (document.querySelector("#data-grid-1").rowNavigation = false)
4. Then set any cell active through dev tools: document.querySelector("#data-grid-1").setActiveCell(0, 4)
5. Notice nothing happens
*Note : When row navigation is set to true setActiveCell works as expected

**Expected behavior**
A cell should be activated

**Version**

- ids-enterprise-wc: Sept. 5, 2023 main

**Screenshots**
https://github.com/infor-design/enterprise-wc/assets/122866382/15f43e7b-3a1d-484f-9b31-361f9d0c83a0

**Platform**
- Infor Application/Team Name: M3 UX
- OS Version: Windows 11
- Browser Name: chrome
- Browser Version: Version 116.0.5845.140 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
Not 100% sure about this one. Because `document.querySelector("#data-grid-1").rowNavigation = false` is the default.
Do you mean true?

So if i just go to https://main.wc.design.infor.com/ids-data-grid/example.html and type `document.querySelector("#data-grid-1").setActiveCell(0, 4)` it is "working". But the focus changes to the console. So it looks like nothing is happening but if you tab into the grid with the keyboard that is the active cell.

Seems like just a problem debugging the focus (common thing that gets tricky). What exactly do you want to do?

**Comment by jjorge1999** [comment]
Hi @tmcconechy , I was expecting that the cell should be activated just like how rowNavigation=true works. 
Kindky use this vid as reference.
https://github.com/infor-design/enterprise-wc/assets/122866382/e99d273f-d61d-46ee-8778-ae61ff244d5c

**Comment by tmcconechy** [comment]
Hmm not sure why the row works i think thats because it uses a class but its not really focused. I dont really want to use a class for focus when i dont have to for the cell as it gets a tabindex. But maybe i can do something. The problem is testing in the console wont work because the focus stays there. 

Did you try with a button or timeout?

**Comment by jjorge1999** [comment]
Yeah we also tried timeout, however sometimes cell does not activated which make it hard to navigate using arrow keys.

**Comment by tmcconechy** [comment]
Ok, i can play around with this and see if its possible to improve or not. If the console changes focus its not but. maybe i can try with a timeout or button.

Whats the use case for focusing it programatically? Im sure there is one but just checking. I think its a general rule you shouldnt change focus if possible from the user

**Comment by jjorge1999** [comment]
We set this programmatically on our end. 
Like for example 
1. User double clicks a row
2. This will open new page (storing prevclicks and allows us to determine last active row)
3. When the user goes back to the previous page
4. The cell should still be active and selected.

**Comment by tmcconechy** [comment]
ok i'll make a working test page

**Comment by jjorge1999** [comment]
Okey . Thank you @tmcconechy !

**Comment by tmcconechy** [comment]
@jjorge1999 please checkout this example and note that it works if you do it programmatically because its setting focus. The row activation works differently because it uses a css class so we can make them identical but you will find it works if you set the focus when the grid is visible.


Example Html based on example.html (add a button)

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= htmlWebpackPlugin.options.title %></title>
  <%= htmlWebpackPlugin.options.font %>
</head>
<body>
  <ids-container role="main" padding="8" hidden>
    <ids-theme-switcher mode="light"></ids-theme-switcher>
    <ids-layout-grid auto-fit="true" padding="md">
      <ids-text font-size="12" type="h1">Data Grid</ids-text>
    </ids-layout-grid>
    <ids-layout-grid auto-fit="true" padding-x="md">
      <ids-layout-grid-cell>
        <ids-button id="test1" appearance="secondary">
          <span>Focus</span>
        </ids-button>
        <ids-data-grid id="data-grid-1" row-selection="multiple" label="Books" row-height="md"></ids-data-grid>
      </ids-layout-grid-cell>
    </ids-layout-grid>
  </ids-container>
</body>
</html>

```

Example js based on example.ts (added an event handler to show the command)
```js
import type IdsDataGrid from '../ids-data-grid';
import '../ids-data-grid';
import type { IdsDataGridColumn } from '../ids-data-grid-column';
import booksJSON from '../../../assets/data/books.json';

// Example for populating the DataGrid
const dataGrid = document.querySelector<IdsDataGrid>('#data-grid-1')!;

if (dataGrid) {
  (async function init() {
    // Do an ajax request
    const url: any = booksJSON;
    const columns: IdsDataGridColumn[] = [];

    // Set up columns
    columns.push({
      id: 'selectionCheckbox',
      name: 'selection',
      sortable: false,
      resizable: false,
      formatter: dataGrid.formatters.selectionCheckbox,
      align: 'center'
    });
    columns.push({
      id: 'rowNumber',
      name: '#',
      formatter: dataGrid.formatters.rowNumber,
      sortable: false,
      resizable: true,
      reorderable: true,
      readonly: true,
      width: 65
    });
    columns.push({
      id: 'description',
      name: 'Description',
      field: 'description',
      sortable: true,
      resizable: true,
      reorderable: true,
      formatter: dataGrid.formatters.text
    });
    columns.push({
      id: 'ledger',
      name: 'Ledger',
      field: 'ledger',
      resizable: true,
      reorderable: true,
      formatter: dataGrid.formatters.text
    });
    columns.push({
      id: 'publishDate',
      name: 'Pub. Date',
      field: 'publishDate',
      resizable: true,
      reorderable: true,
      formatter: dataGrid.formatters.date
    });
    columns.push({
      id: 'publishTime',
      name: 'Pub. Time',
      field: 'publishDate',
      resizable: true,
      reorderable: true,
      formatter: dataGrid.formatters.time
    });
    columns.push({
      id: 'price',
      name: 'Price',
      field: 'price',
      resizable: true,
      reorderable: true,
      formatter: dataGrid.formatters.decimal,
      formatOptions: { locale: 'en-US' } // Data Values are in en-US
    });
    columns.push({
      id: 'bookCurrency',
      name: 'Currency',
      field: 'bookCurrency',
      resizable: true,
      reorderable: true,
      formatter: dataGrid.formatters.text
    });
    columns.push({
      id: 'transactionCurrency',
      name: 'Transaction Currency',
      field: 'transactionCurrency',
      formatter: dataGrid.formatters.text,
    });
    columns.push({
      id: 'integer',
      name: 'Price (Int)',
      field: 'price',
      formatter: dataGrid.formatters.integer,
      formatOptions: { locale: 'en-US' } // Data Values are in en-US
    });
    columns.push({
      id: 'location',
      name: 'Location',
      field: 'location',
      formatter: dataGrid.formatters.hyperlink,
      href: '#',
      click: () => { console.info('Link was clicked'); }
    });
    columns.push({
      id: 'postHistory',
      name: 'Post History',
      field: 'postHistory',
      formatter: dataGrid.formatters.text
    });
    columns.push({
      id: 'active',
      name: 'Active',
      field: 'active',
      formatter: dataGrid.formatters.text
    });
    columns.push({
      id: 'convention',
      name: 'Convention',
      field: 'convention',
      formatter: dataGrid.formatters.text
    });
    columns.push({
      id: 'methodSwitch',
      name: 'Method Switch',
      field: 'methodSwitch',
      formatter: dataGrid.formatters.text
    });
    columns.push({
      id: 'trackDeprecationHistory',
      name: 'Track Deprecation History',
      field: 'trackDeprecationHistory',
      formatter: dataGrid.formatters.text
    });
    columns.push({
      id: 'useForEmployee',
      name: 'Use For Employee',
      field: 'useForEmployee',
      formatter: dataGrid.formatters.password
    });
    columns.push({
      id: 'deprecationHistory',
      name: 'Deprecation History',
      field: 'deprecationHistory',
      formatter: dataGrid.formatters.text
    });

    dataGrid.columns = columns;
    const setData = async () => {
      const res = await fetch(url);
      const data = await res.json();
      dataGrid.data = data;
    };

    setData();

    document.querySelector('#test1')?.addEventListener('click', () => {
      dataGrid.setActiveCell(1, 4); // ADDED THIS
    });
  }());
}
```

**Comment by jbrcna** [comment]
QA Passed
<img width="1673" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b6a65233-c69a-4d93-81fd-a4df32bd05fa">
