### ISSUE TITLE
IdsDataGridColumn: Add options property support

### ISSUE THREAD

**Issue by eaenriquez** [infor-design/enterprise-wc#1457]
Compared to Soho Components, the `SohoDatagrid: SohoDataGridColumn` can accept a property `options?: SohoGridCellOption[]` which allows us to yield these values when using it in formatters (especially dropdowns).

We would like to request the same feature for the `IdsDatagridColumn`

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/infor-design/enterprise-wc/assets/68070868/162437db-3a15-4b7c-a1eb-763e888c22a9)

**Comment by tmcconechy** [comment]
The equivalent option in this case is now https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/ids-data-grid-column.ts#L229

Which lets you pass any settings to any of the editors (like dropdown). But it doesn't apply to anything formatter related as we dont invoke the components Plus our types are more typed now. So would rather add specific options. 

What is it you want to be able to do / control as we will have to add the exact types (not just options) and also make sure whatever it is works? I think thats what we need here.

**Comment by eaenriquez** [comment]
Yes, that's the equivalent option from the editor, and we need it too for formatters.

The use case is like this:

![image](https://github.com/infor-design/enterprise-wc/assets/68070868/3a299f8e-06d7-4df0-9044-ec21f460f418)

The top datagrid is the soho-datagrid, and uses a custom `dropdownFormatterFn` that references the `SohoGridCellOption` from the column definition, so that it knows how to display key value pairs with more meaning.

The datagrid on the bottom is the IDSDataGrid, and we need the same way to store column options/settings so that we can access it whenever we're using custom formatters like so:
![image](https://github.com/infor-design/enterprise-wc/assets/68070868/7b4e7ca6-d377-41f0-bb2a-a9b11d7dfe55)


In this use case, a `options: Record<string, unknown>` or a similar structure from `options: SohoGridCellOption[]` will do the job.

**Comment by tmcconechy** [comment]
Ok, But it does not invoke a dropdown. What we did was add the options to the editor options. That should let you render from a code in the database to the dropdown value like before.

https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/ids-data-grid-formatters.ts#L218-L220

So i think what you want is there.

```js
columns.push({
  id: 'description',
  name: 'Description',
  field: 'description',
  resizable: true,
  reorderable: true,
  formatter: dataGrid.formatters.dropdown, // <-- this
  editor: {
    type: 'dropdown',
    editorSettings: {
      options: [  // <-- this
        {
          label: 'Option 1',
          value: 'opt1' // database has ths
        },
        {
          label: 'Option 2',
          value: 'opt2'' // database has ths
        }
      ]
    }
  }
});
```

So it is as before but under editorOptions

**Comment by whernebrink** [comment]
@tmcconechy, ìn emmans example, we're formatting the options based on the value, in the formatterFn that soho has. How would you reccomend us doing in the case of the web components, where the options are already defined?

**Comment by tmcconechy** [comment]
Not familiar with `dropdownFormatterFn` i dont see it in the old API? Is this just a custom formatter like before? If so you can still do custom column formatters as per https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/README.md#custom-formatters

Might be missing something here....

**Comment by whernebrink** [comment]
I think this should work for us! We used the `SohoDataGridColumnFormatterFunction` (so just a custom formatter we named dropdownFormatterFn).  Thanks a lot! I bet this is enough for @eaenriquez to continue our adoption. :)

**Comment by whernebrink** [comment]
@tmcconechy possible to combine customFormatter with editorSettings.options? 

You had `<-- this` on the line for the dropdown formatter, which made me believe that might be required for options to work? 


<img width="423" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/73601152/419966e1-acd3-4dae-8e8d-b1972b0b48de">

**Comment by tmcconechy** [comment]
@whernebrink yes i think you could combine them. Its just that your logic in the custom formatter would have to use them. i.e.

```js
  formatter: (rowData: Record<string, unknown>, columnData: Record<string, any>) => {
    console.log(columnData.editorSettings.options); // i think?
    return `<span class="text-ellipsis">${value}</span>`;
  }
```

The `<--- this` was just to point it out. It should be working / exists now

**Comment by eaenriquez** [comment]
@tmcconechy , we got it to work your way, by just passing a custom formatter function that returns a `string`

A slight problem though is that our values need to be wrapped in a `span.text-ellipsis` to look nice, otherwise it looks like this:
![image](https://github.com/infor-design/enterprise-wc/assets/68070868/02908055-55d0-4a94-98cb-8fc016b77e4b)

This might be a given since this is a custom formatter, but would there be a setting for it automatically wrap it and not handle it in our custom formatterFn?

**Comment by tmcconechy** [comment]
Yeah for custom formatter i left this off. You can manually add it if you need it just a span https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/ids-data-grid-formatters.ts#L83

I guess we can close this then. If you think you need the setting i guess we could add it but i think it seems reasonable enough if your doing the custom formatter you add it

**Comment by whernebrink** [comment]
Totally reasonable! 👍
