### ISSUE TITLE
IdsAxisChart: Make responsive chart

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1458]
**Describe the bug**
At the moment in a chart you can only set height and width to a pixel. Should make this setable to 100% so it can be responsive and/or make it change on resize to 100%

1. Go to https://main.wc.design.infor.com/ids-axis-chart/example.html
2. resize browser on iphone size

**Expected behavior**
- will go from a pixel size and 100% on smaller devices
- can set to 100%

**Additional context**
MS Teams

**Comment by jbrcna** [comment]
QA Failed
<img width="464" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/344d6081-408e-40b9-b419-b01f7db30183">
**RTL**
<img width="403" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/cd8ddb54-9290-46b1-a23d-f1616278f0b9">

**Comment by tmcconechy** [comment]
@jbrcna its never going to work great at that size. Maybe make a new issue and we could hide the labels or something.
