### ISSUE TITLE
IdsTabs: Ensure can use in a CAP

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise-wc#146]
**Is your feature request related to a problem or use case? Please describe.**
Support to have vertical tabs work within an Action Panel Modal.

Below is an example of what we are trying to do.
![image](https://user-images.githubusercontent.com/50192038/114964715-d414fa80-9ea1-11eb-9888-5c2219475225.png)

**Describe alternatives you've considered**
Currently we are creating a design that we'll implement on our application.

**Additional context**
 - Infor Application/Team Name: M3 H5 UI Team

**Comment by jbrcna** [comment]
Hello, the tabs in CAP on safari browser looks different.
https://main.wc.design.infor.com/ids-tabs/action-panel.html
<img width="968" alt="image" src="https://user-images.githubusercontent.com/56722184/201829655-1cfc5830-2f1c-4747-ba95-e1b679d0744e.png">
