### ISSUE TITLE
IdsCalendar: beforerendermonth event triggered multiple times for calendar loading

### ISSUE THREAD

**Issue by JunyiZhao720** [infor-design/enterprise-wc#1464]
**Describe the bug**
Currently, when loading ids-calendar, it will render this event at least 5 times.
The expectation of beforerendermonth event is only being rendered once right before calendar month view starts loading.

**To Reproduce**

1. catch the event using a method 
    <ids-calendar #calendar (beforerendermonth)="onBeforeRenderMonthTest($event)">
2. within the method
onBeforeRenderMonthTest($event){     console.log("before render month event is emitted!") }

**Expected behavior**
I should only see "before render month event is emitted!" be displayed once.

**Version**

- ids-enterprise-wc@1.0.0-beta.13
- ids-enterprise@4.85.0

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/22669426/8aa3428e-060a-43bc-9ab3-f10da17516ba)

**Platform**
All major browsers

**Comment by tmcconechy** [comment]
This issue can be more simply reproduced by just going to https://main.wc.design.infor.com/ids-calendar/example.html and checking the console.
