### ISSUE TITLE
IdsCalendar: Support for Content Projection in Popup

### ISSUE THREAD

**Issue by JunyiZhao720** [infor-design/enterprise-wc#1474]
**Is your feature request related to a problem or use case? Please describe.**
We might not have implemented it correctly, but from our observations, the IdsCalendar doesn't seem to support content projection for its popup effectively. Currently, the content of the popup appears to be hard-coded, and we couldn't locate a slot tag for customization.

**Describe the solution you'd like**
I would like enhanced support for content projection in the popup of IdsCalendar, allowing developers to customize the content as needed.

**Describe alternatives you've considered**
At a minimum, please provide an option to disable the double-click event that triggers the default popup. While we can use our own popup solution, preventing the double-click from activating the default popup is essential for our use case.

**Comment by glenlieorillo** [comment]
This has been tested and passed.

https://github.com/infor-design/enterprise-wc/assets/102151352/625f2856-f514-4696-9b37-3d29cfc7a18c
