### ISSUE TITLE
General: Error _defineProperty on prod build

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1476]
**Describe the bug**

Tailing this issue to see if any workarounds.
https://github.com/angular/angular-cli/issues/25369

**To Reproduce**
1. See example and steps on https://github.com/angular/angular-cli/issues/25218

**Expected behavior**
- Can we solve this error somehow with NG config. Or changes to a file?
- Is the code valid / can it be changed to fix without waiting for an NG build

**Additional context**
Reported also in teams (Ion Process and Home Page Teams)

![Screenshot 2023-09-12 at 12 26 47 PM](https://github.com/infor-design/enterprise-wc/assets/814283/72e8c236-0a15-4496-89c3-bf80ac05a137)

**Comment by yousef-elkaisi** [comment]
I am also currently facing this issue.  "Uncaught ReferenceError: _defineProperty is not defined" when running the application in Android Webview.

**Comment by tmcconechy** [comment]
I think its related to the angular build not the browser. Would that be the case in your situation too @yousef-elkaisi ?

**Comment by yousef-elkaisi** [comment]
Yes it's a build issue. Running `ng serve --configuration production`  I was able to reproduce the same issue in Chrome. Must be a problem with production build.

**Comment by ashachodavarapu** [comment]
Hi @tmcconechy,
In which version of IDS web components, this defect will be fixed?
Thanks.
