### ISSUE TITLE
IdsAxisCharts: Do not reload and sometimes dont load on Windows 11

### ISSUE THREAD

**Issue by Spydr331** [infor-design/enterprise-wc#1477]
**Describe the bug**
Reloading the page (on windows) and on mac with latency seems to load an empty svg file. The demo chart example on first load runs okay, but on refresh (using the F5 key) the content disappears and the only content that appears is text that says "AXIS CHART - AXIS LABEL".  It looks like the SVG markup is empty. 

Hitting the refresh button on the browser, or hitting CTRL+F5 doesn't seem to cause the issue as often.  Pressing F5 seems to make it appears 1 every 3 times (windows). Or follow the steps to reproduce as per @tmcconechy 

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-axis-chart/axis-label.html
2. Click on network tab and slow down to 'Fast 3g'
3. Shift Reload

On my windows machine a simple reload will do it more consistency. Might depend on network speed.
But on browser stack i could not reproduce

**Screenshots**

<img width="1225" alt="Screenshot 2023-09-12 at 3 30 31 PM" src="https://github.com/infor-design/enterprise-wc/assets/814283/3249bd74-b58c-42b7-b24a-f56af66972f7">

**Platform**
 - Browser Name: Chrome
 
**Additional context**
Ms Teams chat

**Comment by jdilag90** [comment]
Closed via fix from this PR https://github.com/infor-design/enterprise-wc/pull/1522
PR included fix for axis chart to wait for theme to be loaded before doing any chart calculations

**Comment by glenlieorillo** [comment]
Passed.

Windows 11 - Chrome (BrowserStack)
![image](https://github.com/infor-design/enterprise-wc/assets/102151352/afd60888-c71f-44f3-b695-3cf57bbd690d)

Mac - Chrome
![image](https://github.com/infor-design/enterprise-wc/assets/102151352/1e25191b-ae71-4e75-b0c4-ad28f32be6e5)
