### ISSUE TITLE
IdsDataGrid: Add IdsLookup Input for IdsDataGridEditor

### ISSUE THREAD

**Issue by eaenriquez** [infor-design/enterprise-wc#1478]
**Is your feature request related to a problem or use case? Please describe.**
To add IdsLookup type on `IdsDatagridEditor.input` so that it's possible to add lookup on editable IdsDatagrids

**Describe the solution you'd like**
It would be good to have the same functionalities that the `Soho.Editors.Lookup` offers. This should probably also work like a modal where we can provide a callback function to call whenever we resolve a value inside a lookup modal/form

**Describe alternatives you've considered**
N/A

**Additional context**
For additional context:
The `Soho.Editors.Lookup` that's used by the `SohoDataGridColumn.editors` API:
![image](https://github.com/infor-design/enterprise-wc/assets/68070868/2ce89ced-1f39-4a00-8b16-d3c97e56df83)

![image](https://github.com/infor-design/enterprise-wc/assets/68070868/63771885-341c-4821-84eb-af48d61bef0a)

**Comment by whernebrink** [comment]
@tmcconechy, nothing critical as of now, from our (experience designer) point of view,  but might be needed/good to have in the future.

**Comment by tmcconechy** [comment]
Ok, we are missing a lookup editor example. We will probably vary hows this works given the differences in API's but I agree this is a gap we should fill
