### ISSUE TITLE
IdsPager: Add new web component 

### ISSUE THREAD

**Issue by katieinfor** [infor-design/enterprise-wc#148]
Add the standalone pager component ONLY. See https://main-enterprise.demo.design.infor.com/components/pager/example-standalone.html

The idea is to have a flexible slot so they can put in what pager items they want between:
- next/prev/left/right button
- page selector menu button
- small page selector menu button
- page input https://main-enterprise.demo.design.infor.com/components/pager/example-datagrid.html
- page numbers https://main-enterprise.demo.design.infor.com/components/pager/example-listview.html

then control the states / disabled ect

**Phase 1 Features (MVP)**
- Standalone pager
- All supported pager items can be put in as explained above
- Fires events will internally storing a page state object

**Future Features (Not Now)**
- integration with other components
- all old pager logic will be deprecated it will just be a "dumb" pager that holds the items and fires events

**Suggested Internal Markup**
```js
<ids-message>
  <div slot="title"></div>
  <div slot="message"></div>
  <div slot="buttons"></div>
</ids-message>
```

**Suggested Dependencies**
- ids-tooltip (on buttons)
- ids-text
- ids-button
- ids-input (page input)
- ids-menu-button (page selector)
- ids-hyperlink (numbers)

**Settings**
NA

**Design**
- https://www.figma.com/file/ri2Knf3KchdfdzRAeds0Ab/IDS-Mobility-v4.6?node-id=1%3A5740

**Events**
- pagechanged

**Other**
Pass the following checklist ordered in priority (some may be left for later) https://github.com/infor-design/enterprise-wc/blob/main/doc/CHECKLIST.md

**Comment by rob2d** [comment]
So on the interface for this I was thinking as theres optional left and right-aligned content, to make the interface look like:

```
<ids-pager>
  <slot name="left">
    Any Left-floating-Content
  </slot>
  <slot>
    Main Pager/Nav
  </slot
  <slot name="right">
    Any right-floating content e.g. page row-count option
  </slot>
</ids-pager>
```

This way the user can also use this as the interface with no slots:

```
<ids-pager>
  Simple center-aligned pager content
</ids-pager>
```

Also debated having it like:

```
<ids-pager>
  <div>Left Content</div>
  <div>Main Content</div>
  <div>Right Content</div>
</ids-pager>
```
^ classes get auto appended

The last option to me is most idiomatic and simple vs slot name interface, but may not be more traditional/"WebComponent" oriented. Hence going with first one for the sake of consistency and no (more) unpleasant surprises w WCs.

(Any input welcome -- thinking this out early on in case there's anything I missed or I am using an antipattern here)

**Comment by tmcconechy** [comment]
@EdwardCoyle did this sort of thing in toolbar https://github.com/infor-design/enterprise-wc/blob/main/app/ids-toolbar/example.html#L18 but he used an align property so could do..

```
<ids-pager>
  <ids-pager-section>
    Any Left-floating-Content
  </slot>
  <ids-pager-section align="center">
    Main Pager/Nav
  </ids-pager-section>
  <ids-pager-section align="right">
    Any right-floating content e.g. page row-count option
  </ids-pager-section>
</ids-pager>

<!--  (i like this one a lot as its most common) -->

<ids-pager>
  Simple center-aligned pager content
</ids-pager>
```

**Comment by rob2d** [comment]
@tmcconechy vs having `align='left'`, `align="right"`, could we also use boolean flags? e.g. `left` `right` and have a center as default (since with 1 panel v 3 it's centered)? I  wasn't sure if we still always say `="true"` after discovering it was more of an ARIA thing than needed in spec and I'm fine with both, mostly curious what are accepted patterns.

**Comment by rob2d** [comment]
actually: if we did go this route either align or not another thing I just realized is then we could just check the index of the panels/sections of `this.children` so the user doesn't need to do that themselves (theoretically).

**Comment by deep7102** [comment]
I would use `start` and `end` instead of left/right -so it can help in RTL later

**Comment by tmcconechy** [comment]
I suppose we could but we used the `align = 'left'` already (non boolean) in a few places. I'm not sure what @EdwardCoyle did for center in his example.

I like the idea of the sections so maybe you could configure where some of the elements sit in some cases. But you could just as well use the indexes (except if they just have 2).

To Deepaks idea in a pending PR i added this to the ids-layout-grid..

```
<ids-layout-grid-cell justify="end">
```

So this maps to `justify-self` in flex. Maybe we could use the grid inside to lay this out that way? Or you could do `justify: end/start`? I picked justify since thats what the css setting is called. So another idea

**Comment by rob2d** [comment]
This is super subjective but I think maybe adding extra layout stuff for the grid might not be ideal in this case-- I mean just if it is already going to need extra rules e.g. ensure the height or specifically in this case I was going to set the padding for sub panel items so it's consistent from center icons or if user does that in the left/right. 

e.g. 
```

.ids-pager-panel.left > :not(:first-child) {
  @include ml-4(); /* children may have their spacing controlled; then need inner divs as well */
}
```

Also considered the `::part` thing but then remembered doing that doesn't support relational things e.g. `>` so it's mostly a shadowDOM thing that's causing any issues with re-using that and keeping it lean here.

**Comment by tmcconechy** [comment]
OK this is my vote then but i would vote "do it like toolbar" so its relatively consistent. Not sure about the grid layout as well as this is more "fixed"

**Comment by EdwardCoyle** [comment]
@rob2d @tmcconechy @deep7102 The toolbar sections use an `align` property with a default of "start" (which will equate to "left" on LTR settings, "right" on RTL settings). Other settings can be "center" and "end" ("right on LTR, "left" on RTL)

**Comment by tmcconechy** [comment]
Ok works for me then @EdwardCoyle - so i would suggest you mimic toolbar for the settings in pager then @rob2d
