### ISSUE TITLE
IdsDataGridCell: checkbox formatter 'align' property issue

### ISSUE THREAD

**Issue by snelanti** [infor-design/enterprise-wc#1481]
**Description of bug**
Checkbox is not aligned left in Grid column even after providing align:'left' while column object creation instead it is always centered 

**To Reproduce**
**Root code used:** angular-ids-wc (project present in git and is provided by web components team). just added align:'left' and replaced this.dataGrid.nativeElement.formatters.selectionCheckbox to this.dataGrid.nativeElement.formatters.checkbox as below 
C:Downloads\enterprise-wc-examples-main\angular-ids-wc\src\app\components\ids-data-grid\demos\example\example.component.ts
<img width="491" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/141207120/0df18e1d-6e59-46d6-b03a-0c8de6ad468a">

1. Create a Grid with column specifying as in above screenshot 
2. Try to expand the checkbox column, and is observed that checkbox is center aligned even after providing align:'left' in column creation object

**Expected behavior**
Checkbox should be left aligned

**Version**
ids-enterprise-wc: "^1.0.0-beta.14"

**Screenshots**
<img width="759" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/141207120/6fdc5065-59f3-4c14-b1b9-29789dba10b7">

**Platform**
 - Infor ION

**Comment by glenlieorillo** [comment]
This is now working as expected.

<img width="1791" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/e2f1a168-e0a3-4c86-a89d-a61b63d9c8ea">
