### ISSUE TITLE
TextArea: Add min/max height/width setting

### ISSUE THREAD

**Issue by snelanti** [infor-design/enterprise-wc#1482]
**use case description.**
Unable to add neither **min-height/max-height** nor **min-width/max-width** to ids-textarea field. It would be good if attributes are provided for these options for <ids-textarea> component

**Describe the solution you'd like**
<ids-textarea [minHeight] = "20" [maxHeight]=100  [minWidth]=10 [maxWidth]=100></ids-textarea>

**Additional context**
<img width="231" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/141207120/9007eb3b-a036-43a2-9d73-8b82b0496ad8">
Infor-ION

**Comment by tmcconechy** [comment]
Also consider textarea rows and columns may need to add both or just use.

**Comment by jbrcna** [comment]
QA Passed
https://main.wc.design.infor.com/ids-textarea/sizes.html
<img width="1655" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/bb03b032-8321-4e1b-b59c-8ac3cd694fd2">
<img width="1219" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/62967764-f7ae-4d15-883a-e5d3daccfd63">

**Comment by jbrcna** [comment]
However, in https://main.wc.design.infor.com/ids-textarea/standalone-css.html, resizable textarea is not resizable.
<img width="879" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b0433a3f-059a-423f-990c-b7dbfc121b49">
