### ISSUE TITLE
IdsDatagrid: Runtime error on Treegrid idsDatagrid.expandAll()

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1485]
**Describe the bug**
Runtime error on IdsDatagrid Treegrid when idsDatagrid.expandAll() is executed.

**To Reproduce**

1. clone enterprise-wc, npm i
1. npm start and go to http://localhost:4300/ids-data-grid/tree-grid-virtual-scroll-infinite-scroll.html
1. Scroll down to row number 270
1. Click on Expand All Button
1. Error: Runtime error should not happen in the console

**Expected behavior**
All rows should be expanded and no errors.

**Version**

- ids-enterprise-wc (src/main Sept 15, 2023)

**Screenshots**

Video:
https://github.com/infor-design/enterprise-wc/assets/53523076/f78203a2-9124-40d3-b1bd-0b333216a202

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: chrome
Browser Version: Version 116.0.5845.140 (Official Build) (64-bit)

**Additional context**

**Comment by edisonferrer** [comment]
linking related ticket here: https://github.com/infor-design/enterprise-wc/issues/1486

**Comment by tmcconechy** [comment]
@clayinfor http://localhost:4300/ids-data-grid/tree-grid-virtual-scroll-infinite-scroll.html seems to be included. Do i really need to unzip a different example? If so could we just include it or do the steps just need correcting?

**Comment by clayinfor** [comment]
hey @tmcconechy , I've already updated http://localhost:4300/ids-data-grid/tree-grid-virtual-scroll-infinite-scroll.html in the PR to match what they did in the zip, so you can ignore their zip file.

**Comment by jbrcna** [comment]
QA Passed.
verified in 
https://main.wc.design.infor.com/ids-data-grid/tree-grid-virtual-scroll-infinite-scroll.html
https://main.wc.design.infor.com/ids-data-grid/tree-grid-expand-collapse.html
https://main.wc.design.infor.com/ids-data-grid/show-header-expander.html
