### ISSUE TITLE
IdsDatagrid Treegrid: Blank rows after idsDatagrid.collapsedAll()

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1486]
**Describe the bug**
After running idsDatagrid.collapseAll() and loading new collapsed rows, the displayed rows have blank rows

**To Reproduce**

1) clone enterprise-wc, npm i
2) Update tree-grid-virtual-scroll-infinite-scroll.html, add buttons for expandAll() and collapseAll() by overwriting tree-grid-virtual-scroll-infinite-scroll.html and tree-grid-virtual-scroll-infinite-scroll.ts with these files
[demos.zip](https://github.com/infor-design/enterprise-wc/files/12618380/demos.zip)
3) npm start and open tree-grid-virtual-scroll-infinite-scroll.html
4) click collapse all button
5) scroll down to row 180
6) Error: Rows are not displayed on the lower half of the grid

**Expected behavior**
Rows should be displayed at the lower half of the grid

**Version**

- ids-enterprise-wc (src/main Sept 15, 2023)

**Screenshots**
Video:

https://github.com/infor-design/enterprise-wc/assets/53523076/0a9b3536-9ce3-42ac-b400-c14a10dc38f2

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: chrome
Browser Version: Version 116.0.5845.140 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
Looks like its not recovering the space. (So needs a redraw). I think who gets this should look at 3 close related issues:

- this, https://github.com/infor-design/enterprise-wc/issues/1485 and https://github.com/infor-design/enterprise-wc/issues/1472

**Comment by jbrcna** [comment]
QA Passed
![Large GIF (1676x686)](https://github.com/infor-design/enterprise-wc/assets/56722184/91196dbc-15cb-4598-9371-148fe10bcb0b)
