### ISSUE TITLE
IdsLayoutGrid: need responsive gaps in grid layout 

### ISSUE THREAD

**Issue by kellyFeng1** [infor-design/enterprise-wc#1487]
**Is your feature request related to a problem or use case? Please describe.**
presently the gap is not a responsive attribute in ids layout grid, and the row gap and column gap always share the same value.  It would be good if row-gap and column-gap could be separately configured based on screen size.

**Describe the solution you'd like**

<ids-layout-grid col-gap-md="md" col-gap-xs="xs"></ids-layout-grid>

**Platform**
Infor-WFM

**Comment by tmcconechy** [comment]
Could you put a different ids-layout grid with different gaps or nest them? What is the use case exactly?

But suggestion seems valid
- row-gap
- column-gap
- row-gap-mobile
- column-gap-mobile

**Comment by EdwardCoyle** [comment]
Noting that we also discussed these settings need to be configured by breakpoint -- @jmacaluso711

**Comment by EdwardCoyle** [comment]
@talkaboutdesign do you have any input on this one?

**Comment by tmcconechy** [comment]
Idea for this:

- tokenize the breakpoints
- tokenize the gap / margin sizes (i.e. 4/8/16/20 or whatever)
- update the component to be able to go between breakpoints and gaps

**Comment by jmacaluso711** [comment]
The following pattern where xs/sm/md/lg/xl/xxl represent the breakpoints, would be consistent with the way [cols](https://github.com/infor-design/enterprise-wc/blob/8d7110eda6cc849528d5c543334e3c4a0bee03d0/src/components/ids-layout-grid/ids-layout-grid.scss#L602) and rows currently handle breakpoints in the component:

`gap` (already exists)
`gap-xs`
`gap-sm`
`gap-md`
`gap-lg`
`gap-xl`
`gap-xxl`

`row-gap`
`row-gap-xs`
`row-gap-sm`
`row-gap-md`
`row-gap-lg`
`row-gap-xl`
`row-gap-xxl`

Here's an example of what that might look like:

```
  <ids-grid 
    col="3" 
    gap="sm" 
    gap-md="lg" 
    row-gap="sm" 
    row-gap-md="lg"
  >
```

**Comment by hey-yall** [comment]
@talkaboutdesign suggests that we see a use case for this so we can develop the proper solution. Can we get video or screenshots to inform the use case for this enhancement request?
