### ISSUE TITLE
IdsMultiselect: tag overlaps dirty tracker

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1488]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-multiselect/example.html
2. Select items on each drop down
3. See error
4. notice that the tag overlaps dirty tracker 

**Expected behavior**
should have enough room for dirty tracker to show up

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="354" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/99ea18f1-8e27-4316-895e-f5d9e71f77f0">

**Platform**
All major browser

**Additional context**
In safari the X icon looks way more bigger compare to other browsers
<img width="455" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/6b71a8f5-1db5-4eb3-ad78-507752a5d8b3">

**Comment by tmcconechy** [comment]
Maybe we get rid of the dirty indicator on web components. Deprecate it.

**Comment by jbrcna** [comment]
QA Passed

<img width="451" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/eb0148da-0602-4c6b-97d7-5437d9f402e9">

**Safari**
<img width="462" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b9670fb4-c822-490c-ae4c-abae4400582b">

**Firefox**
<img width="380" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/9dc4bce6-7b55-4220-9825-bad5d1140a40">

**Edge**
<img width="407" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/f25fdb5f-103d-490c-8f8d-756090d300f2">
