### ISSUE TITLE
Charts: Add axis label alignment settings to fix bottom X-axis label alignment bug

### ISSUE THREAD

**Issue by hey-yall** [infor-design/enterprise-wc#1490]
Design work must be coded and added to the demo site. 

https://jira.infor.com/browse/IDS-1592 The Figma file is in the comments under Lauren Steigerwald. The issue fixes a bug with overlapping x and y axes on the Data Vis line charts. 

Please reach out with any questions. Thanks!

**Comment by tmcconechy** [comment]
https://main.wc.design.infor.com/ids-bar-chart/horizontal.html is another options for this type of thing.
