### ISSUE TITLE
ids-theme-default-light.css is loaded for every component

### ISSUE THREAD

**Issue by AndrewDeiak** [infor-design/enterprise-wc#1491]
**Describe the bug**

ids-theme-default-light.css loaded for every component. I clone the repo https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc and if you start navigating between components, the ids-theme-default-light.css will be loaded for each page/component.

1. Clone and run https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc
2. When opened the application  ids-theme-default-light.css loaded twice:

![image](https://github.com/infor-design/enterprise-wc/assets/26046663/e3c4c738-032a-4371-96ea-5045d30bb427)

3. And also when clicking on any component (IDS Alert) 
4.  ids-theme-default-light.css will be loaded again, but only once
![image](https://github.com/infor-design/enterprise-wc/assets/26046663/b6e263ef-f60a-4af6-bf58-a81765f1e396)

**Expected behavior**
ids-theme-default-light.css should be loaded only once and does not matter how many component on the page.

**Version**
 "ids-enterprise-wc": "^1.0.0-beta.14",

**Comment by tmcconechy** [comment]
Might be due to this option reload https://github.com/infor-design/enterprise-wc/blob/main/src/core/ids-element.ts#L258
https://developer.mozilla.org/en-US/docs/Web/API/Request/cache

**Comment by jbrcna** [comment]
QA Passed
<img width="1316" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/3160cdae-3262-4c4b-88f8-0cdec12467c7">
<img width="1524" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/5f45b3b9-fb7c-4479-bd3a-f125c5dc2623">
