### ISSUE TITLE
Datagrid: Height and scroll issues

### ISSUE THREAD

**Issue by eaenriquez** [infor-design/enterprise-wc#1493]
**Describe the Issue**
The Datagrid Web Component doesn't really inherit the height of its parent container.

The desired solution are:
1. to not modify the css out of the box at all
2. have a property for the datagrid header to be sticky or not.
3. to not have the columns visually shifted when there is a scrollbar (might be just from my solution)
 
I put some style modifications inside some of the elements inside the rendered DatagridWC, mostly `overflow: scroll` and `height: inherit` to achieve the desired outcome below
![image](https://github.com/infor-design/enterprise-wc/assets/68070868/143db02c-35e6-4f75-9456-7928aa5b3a4e)

- sohoxi-version: 4.64.4
- enterprise-ng-version: 13.5.4
- enterprise-wc-version: 1.0.0-beta.14

Would there be a way to style the scrollbar on the datagrid?

**Comment by tmcconechy** [comment]
By default the datagrid does not scroll it just shows all the lines without a scrollbar. But we have two options you can use:

https://main.wc.design.infor.com/ids-data-grid/auto-fit-bottom.html -> will fit to the bottom of the page
https://main.wc.design.infor.com/ids-data-grid/auto-fit.html -> will size to any parent height

This is how we approached it to have 3 sizing options. 

It may be possible to use CSS to style the scrollbar https://www.digitalocean.com/community/tutorials/css-scrollbars but this has limited support. We like to keep the scrollbars the way the browser. intended to avoid confusion.

**Comment by EdwardCoyle** [comment]
@tmcconechy we assigned this to @jdilag90 just to address adding some examples of changing the height

**Comment by tmcconechy** [comment]
Ok, i'll watch for it. Dont want to fundamentally change the way height works though.

**Comment by tmcconechy** [comment]
Going to close this as we are using `position: sticky` which works in the way where the scrollbar goes up to the top. See css position: sticky. https://developer.mozilla.org/en-US/docs/Web/CSS/position 
To do it that way also requires checking scrollbar width on every OS and scrollbar size setting on every browser and device so thats why we use this method of straight css.

To change this would require a lot of rework of the logic of the datagrid and probably mess up virtual scrolling and would be too much work for a preference. We could consider this in the future if a lot of folks complain but for now its too much effort for a small detail.

Similar Examples: https://css-tricks.com/position-sticky-and-table-headers/
