### ISSUE TITLE
IdsDataGrid rowStart scrollbar load position

### ISSUE THREAD

**Issue by jdilag90** [infor-design/enterprise-wc#1497]
**Describe the bug**
IdsDataGrid rowStart scrollbar is positioned at the top on page load and not at intended index

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-data-grid/virtual-scroll-row-start.html
2. Notice that the scrollbar is positioned at top on page load
3. Try reloading page to observe issue

**Expected behavior**
Scrollbar should first render/appear in the correct position (rowStart index)

**Version**
- ids-enterprise-wc: 1.0.0-beta.15

**Screenshots**
row-start
https://github.com/infor-design/enterprise-wc/assets/56722184/d10203de-ee74-4ec9-a024-5f03ad70d163

virtual-scroll-row-start
https://github.com/infor-design/enterprise-wc/assets/56722184/0d7173aa-228d-48d9-8343-6ad7c05b19ee

virtual-scroll-infinite-scroll-m3
https://github.com/infor-design/enterprise-wc/assets/56722184/51d8a26e-403b-4733-bb0f-8de032592858

**Platform**
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 113.0.5672.127 (Official Build) (64-bit)

**Additional context**
Related to issue #1368

**Comment by jbrcna** [comment]
QA Passed. 
**scrollbar position** 

https://main.wc.design.infor.com/ids-data-grid/row-start.html
https://github.com/infor-design/enterprise-wc/assets/56722184/2a086166-408f-4a0e-8ba7-09fdcf1a2bc5


https://main.wc.design.infor.com/ids-data-grid/virtual-scroll-row-start.html
https://github.com/infor-design/enterprise-wc/assets/56722184/ffe6ea9f-708b-445c-a800-abbcc1b56c4f


https://main.wc.design.infor.com/ids-data-grid/virtual-scroll-infinite-scroll-m3.html
https://github.com/infor-design/enterprise-wc/assets/56722184/97aef3e3-55e7-4033-a8cf-2c9cd2a73430


**Additional**
https://main.wc.design.infor.com/ids-data-grid/editable.html
<img width="1059" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b7b3cd13-1007-40e0-ad46-19e80b67a189">
<img width="908" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/2c3266a9-5fc2-4909-9c5b-8b1e8af9acca">
<img width="958" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/351641fe-0d59-4944-9468-2d1842de30ce">

https://main.wc.design.infor.com/ids-data-grid/filter.html
<img width="721" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/6ff47a7e-b492-4b47-9418-28e7274ce86f">

**Comment by jbrcna** [comment]
However, in RTL i noticed this
https://main.wc.design.infor.com/ids-data-grid/editable.html
<img width="615" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/47b11f6f-81e4-4af3-ab45-c00373b0ed93">
<img width="655" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/bdebc2aa-1779-480b-afef-16904fc345f5">
<img width="427" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/16fa0212-9947-44a9-861a-b9111b36195e">


https://main.wc.design.infor.com/ids-data-grid/filter.html
<img width="640" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/aef4484e-ebd4-4f8d-8e0f-7f5bad5da408">

**Comment by tmcconechy** [comment]
@jbrcna can you make a new issue I think its a bug with popupmenu
