### ISSUE TITLE
Themes: Loading of ids-theme-default-light.css is failed because of lack of base href in the url 

### ISSUE THREAD

**Issue by AndrewDeiak** [infor-design/enterprise-wc#1498]
**Describe the bug**
Loading of the theme failed because of missing base href in the request URL:

![image](https://github.com/infor-design/enterprise-wc/assets/26046663/2afdbdde-f233-4d6d-a7ba-9ac3fe4fa640)

**To Reproduce**
1. Add a base href to your Angular project https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base 
2.  After adding it the theme file will be failed with 404 status.

**Expected behavior**
When calling the theme endpoint, the URL should include the baseHref if it's presented in the application:
`${baseHref}/themes/ids-theme-default-light.css`

Example:

http://localhost:4200/process-intelligence/themes/ids-theme-default-light.css

![image](https://github.com/infor-design/enterprise-wc/assets/26046663/25baa0a8-5a05-4dc4-a1b6-ccf1727631e8)

**Version**

- ids-enterprise-wc: [1.0.0-beta.14]

**Additional context**
The problem occurs in the Angular 15 version.

I think the same issue occurs in the React, Vue.js frameworks. It would be nice if you could also check if we can fix it in all frameworks. Thanks!

**Comment by tmcconechy** [comment]
@AndrewDeiak to test in Angular does this sound right.

1. Add   <base href="/ids-enterprise-ng-demo/"> to index.html 
2. Add this to angular.json

```json
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "ids-enterprise-ng-app:build",
            "servePath": "/ids-enterprise-ng-demo" <-----------
          },
```

**Comment by hohnzy** [comment]
Hi @tmcconechy, we use basehref only for production build like this
ng build --configuration production --base-href=/datafabricui/

**Comment by jbrcna** [comment]
QA Passed
https://main.wc.design.infor.com/ids-theme-switcher/example.html
<img width="1165" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/8cf6df5e-a230-4339-9673-f832f16f34af">

https://main.wc.design.infor.com/ids-theme-switcher/base-href.html
<img width="1588" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/19173703-b1ea-46a8-92c8-603548c654ae">
