### ISSUE TITLE
IdsPager: Unable to 'enable' pager-button when not using 'total' and 'page-number' attributes

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#1506]
**Describe the bug**
In landmark we don't know the number of record or what page we are on. When not using 'total' and 'page-number' attributes the ids-pager-button's never get enabled.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-pager/example.html
2. Open developer tools
3. In console type "$('[first]').disabled = false"
4. Notice the button does not get enabled

If you break in ids-pager-button #updateDisabledState you'll see that this.hasAttribute('nav-disabled') return true causing the button to be disabled.

**Expected behavior**
When not using total, page-number settings don't consider 'nav-disabled' functionality.

**Version**
latest web component

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/4737815/7c6aa8ce-6027-4a44-aa82-e3c0d7fa9794)

![image](https://github.com/infor-design/enterprise-wc/assets/4737815/6a620018-07e8-4781-b78d-d7b30b46d02c)

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: windows 11
 - Browser Name: chrome
 - Browser Version: latest

**Comment by tmcconechy** [comment]
https://main-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html
