### ISSUE TITLE
IdsPager: Need short page size chooser button option

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#1507]
**Describe the bug**
In landmark we solely use the "short" page size chooser button. 

1. Go to https://main.wc.design.infor.com/ids-pager/pager-size-dropdown.html
2. Notice page size chooser says "10 Records Per Page"

**Expected behavior**
Would like an option so we can remove the label.

**Version**
latest web components 

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/4737815/b1964909-844d-4aa8-b8d6-af8615885158)

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: window 11
 - Browser Name: chrome
 - Browser Version: latest

**Additional context**

**Comment by glenlieorillo** [comment]
QA Failed.  The pager dropdown appeared double in RTL. Also, the arrow from the menu looks off.

<img width="1791" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/0b85e0c9-b69e-417d-9258-5f9ab0b4e3fe">



https://github.com/infor-design/enterprise-wc/assets/102151352/8169f473-d9c2-4f32-a545-31cd76239378

**Comment by tmcconechy** [comment]
@glenlieorillo lets add a new issue for that please
