### ISSUE TITLE
ids-pager: need a setting to set page sizes in page size chooser

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#1508]
**Describe the bug**
Currently unable to set the page sizes in the page size chooser in ids-pager

**Expected behavior**
Add a setting to set the page sizes in the page size chooser
page-sizes="[5,10,20,50,100,200]"

**Version**

latest web components

![image](https://github.com/infor-design/enterprise-wc/assets/4737815/95e20017-f76e-4b5e-ab0d-70359744c22f)

**Comment by tmcconechy** [comment]
To fix this need to make https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-pager/ids-pager-dropdown.ts#L85 into a get/setter (setting)

**Comment by jbrcna** [comment]
QA Passed
https://main.wc.design.infor.com/ids-pager/custom-pager-sizes.html
<img width="1190" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/4a70fb33-acb9-4452-991e-5d911d30d54b">
