### ISSUE TITLE
IdsTimePicker: Add new web component 

### ISSUE THREAD

**Issue by ghost** [infor-design/enterprise-wc#151]
Add the timepicker component https://main-enterprise.demo.design.infor.com/components/timepicker/list

**Phase 1 Features (MVP)**
- Configure to show hours, minutes, seconds (and period depending on locale info) -> default is everything except seconds
- Ability to set locale (using local mixin) -> this will format the field according
- Since dropdown isnt done can use an input for the fields
- Keyboard: Down arrow to open then tab in the popup and esc to close
- Input states (validation, required, enabled, disabled, dirty ect)
- Theme

**Future Features (Not Now)**
NA - Smaller component so can probably do it all

**Possible Internal Markup**
```js
 <ids-time-picker id="time-picker-1" disabled="false" label="Regular Time Picker" seconds="true">
```

**Suggested Dependencies**
- ids-trigger-field
- ids-locale-mixin
- ids-popup
- ids-input / ids-dropdown

**Settings**
- seconds
- locale
- language
- id/ automation id
- states settings

**Design**
- https://www.figma.com/file/ri2Knf3KchdfdzRAeds0Ab/IDS-Mobility-v4.6?node-id=1%3A5740

**Events**
- change/input

**Other**
Pass the following checklist ordered in priority (some may be left for later) https://github.com/infor-design/enterprise-wc/blob/main/doc/CHECKLIST.md

**Comment by tmcconechy** [comment]
dropdown is merged so all the trigger changes are in. so this is ready to fix now 👍🏻
