### ISSUE TITLE
IdsButton: Slot styles get overridden by 4.x CSS

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise-wc#1513]
**Describe the bug**
When running the web components and the 4.x controls side-by-side, we noted that the slotted `<span>` in an `ids-button` gets incorrect styling from the 4.x stylesheets.
 
**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-button/side-by-side.html
2. See style issues for web component buttons

The missing padding and wrong font weight are what stand out to me, but might be more.

**Expected behavior**
Buttons looking like below, even with 4.x stylesheets loaded.
https://main.wc.design.infor.com/ids-button/example.html

**Version**
- ids-enterprise-wc: 1.0.0-beta.15

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/1101770/45fe6b0f-aa9b-42fb-832a-e2590bc3537b)

**Comment by tmcconechy** [comment]
@volante007 this issue is fixed for the button case. I tried to look at the impact of removing the reset in enterprise but its too much, it broke popups, layouts and a lot of things quite badly. So too disruptive.

I think we will just need to fix case by case on such issues as the fix to add direct css padding was simple. Feel free to raise any other cases you find

**Comment by volante007** [comment]
Yes I guess case by case sounds good. But this only fixes the padding, not the font weight (and other generic typography overrides for span?)

**Comment by tmcconechy** [comment]
I think the fonts should be ok. As i had tested this all when we introduced the side by side examples and because it needs a font explicitly in the shadow root.

But if you see any specific cases just raise and its an easy fix.

**Comment by tmcconechy** [comment]
https://github.com/infor-design/enterprise/pull/8090 -> added a fix for the font size

Also adjusted the rule in EP https://github.com/infor-design/enterprise/pull/8090 this rule can be more targetted the main reset caused a lot of layout issues so not touching it for now. But if these persist could try it again

**Comment by jbrcna** [comment]
#### $\textcolor{green}{\textsf{This is working as expected.}}$
https://main.wc.design.infor.com/ids-button/side-by-side.html
<img width="1486" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/9d691298-3209-4db6-b139-465e8d8289a8">

However, in https://main.wc.design.infor.com/ids-button/variant-alternate.html, the **button is not visible** when hovered (Light & High Contrast)

<img width="1651" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/1cc95544-1668-411d-8ff1-496316635c9d">

in dark mode, **the button is only  visible** when hovered.
<img width="1675" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/022aea70-166a-49a4-a693-0e188a4293b6">
