### ISSUE TITLE
IdsModal: Make modal dialogs moveable

### ISSUE THREAD

**Issue by kkabamalan** [infor-design/enterprise-wc#152]
**Is your feature request related to a problem or use case? Please describe.**
There are users which have more personalization on the modal dialogs window for the Cash Management Account and they are asking if it's possible to make the modal dialogs screen to be moveable so they will be able to move the screen and view the account behind it.

Cash Management > Cash Management Processing > Statement Processing > Bank Statements. Leave the screen open as they use the screen as a reference when they Journalize the Distributions. Cash Management >Cash Management Processing > Journalize Distributions > Bank Statement Line Distributions. On the parameter window, search for Cash Account. It now completely blocks the previous screen they are using as a reference.

The client is asking if it's possible to make the modal dialogs screen movable so they can still view the details behind the modal dialogs screen. Please see attached screenshot 

**Describe the solution you'd like**
Make modal dialogs moveable

**Describe alternatives you've considered**
If the modal dialog box has an exact dimension even if there is a lot of personalization on it, there should be a horizontal scrollbar so the user can still see the data behind the modal dialogs.

**Additional context**
And what application do you work on? CSF FSM 
![image](https://user-images.githubusercontent.com/79097033/107959934-f8a64080-6fde-11eb-9ee2-24acb5279f2f.png)

**Comment by lipetzan** [comment]
@tmcconechy would you and @kevinwhitedesign like to be connected with the latest customer asking for this again?  Many of Kevin's assumptions (adding even more information (which maybe be impossible to predict) in a single columned constrained space isn't that feasible, neither is not have a model).

Perhaps we could me to explore this once we understand the customer need.

**Comment by tmcconechy** [comment]
cc @inforandy

**Comment by tmcconechy** [comment]
Closing this out as discussed we dont plan to make modals draggable as its a ux no-no as mentioned
