### ISSUE TITLE
IdsLoadingIndicator: Add example of blocking the UI full page  

### ISSUE THREAD

**Issue by ashachodavarapu** [infor-design/enterprise-wc#1520]
- For IDS loading indicator doesn't have the property for blocking the backend UI.
- **For Ex:** I have added Soho busy indicator block UI for the reference (below snippet)
![image](https://github.com/infor-design/enterprise-wc/assets/105051938/f9d93f8e-f506-4c3b-b861-74f4aceaca8e)
- Take the above snippet as a reference same functionality is  expected to work for **circular & linear ids-loading-indicator**
-  If possible provide an example of  **circular & linear** ids-loading-indicators and how to make use of this functionality in angular.

**use case:**
-  when the ids-loading-indicator appears on the complete page it needs to block the backend UI.
- when a user does some action there is some ongoing communication between the UI and the backend, the user should be blocked from doing other activities until the response is received from the backend.  This is a common use case in any application.
- Please consider this as a priority enhancement

**Comment by tmcconechy** [comment]
The original design was around showing a linear loader at the top of the page. Will discuss if we want both options.

**Comment by tmcconechy** [comment]
@talkaboutdesign i know for components like datagrid you suggested the circle loader vs the linear loader but what about full page? circle or linear?

**Comment by talkaboutdesign** [comment]
It has to be more inline in the UI. Or you think this is necessary still? This blocking of UI from being interactive?

**Comment by tmcconechy** [comment]
Yeah I made the blocking an option, i think the usually need it. What do you mean by "more inline in the UI".

See https://github.com/infor-design/enterprise-wc/pull/1694 if you can?
