### ISSUE TITLE
IdsDatagrid: Click event on cell and hyperlink is broken when rowNavigation is true

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1523]
**Describe the bug**
When the idsDatagrid.rowNavigation is set to true, hyperlink does not work and some cells do not proceed with selection

**To Reproduce**

1. git clone enterprise-wc, npm i, npm start
2. open http://localhost:4300/ids-data-grid/columns-formatters.html
3. click on a hyperlink under the column Hyperlink
4. see console log, "Link clicked" is displayed
5. go to the developer tools - console log
6. set rowNavigation to true by running this, `document.querySelector("#data-grid-formatters").rowNavigation = true` or do it in columns-formatters.html or columns-formatters.ts.
7. click on a hyperlink
8. error: see console log, hyperlink handler is not called anymore and the cell/row is not selected

**Expected behavior**
Hyperlink should still work and the row should be selected when hyperlink is clicked when rowNavigation is set to true

**Version**

- ids-enterprise: Beta 15

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/53523076/ffd6c7b7-2432-409f-8092-bf3b3c4a6598

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: chrome
Browser Version: Version Version 117.0.5938.132 (Official Build) (64-bit)

**Additional context**
It looks like when rowNavigation is set to true, the target is ids-datagrid-row which is not expected, the expected target should be ids-hyperlink, a cell or any element inside the cell.

<img width="751" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/53523076/27bc5611-3e0e-4cee-9ce1-db52f93cd1a3">

**Comment by jbrcna** [comment]
QA Passed
<img width="1714" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b907eb0e-f0a3-416e-9a4a-7f8e1c2bfe70">
