### ISSUE TITLE
IdsModal: Calling <ids-model> with fullsize="always" fails to make the modal fullsize

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#1525]
**Describe the bug**
When solely passing in the fullsize on the ids-modal html element the modal does not display full size

```
  <ids-modal id="my-modal" fullsize="always" aria-labelledby="my-modal-title">
```

**To Reproduce**
1. Put attached sample in place
2. run the example
3. click the Trigger a Modal button
4. See modal is not full size

**Expected behavior**
modal should be full size.

**Version**
- ids-enterprise-wc: latest

**Platform**
 - Infor Application/Team Name: Landmark
 - Browser Name: Chrome
 - Browser Version: latest

**Additional context**
Example
[fullsize2.zip](https://github.com/infor-design/enterprise-wc/files/12822022/fullsize2.zip)

**Comment by jbrcna** [comment]
QA Passed
<img width="1607" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/c0b3778a-c9c7-4e6e-a989-6584f75bd478">
