### ISSUE TITLE
IdsModal: Add setting to put a close button on the top

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#1527]
**Describe the solution you'd like**
Want to have an at the top of the modal instead of having a close button in the button section.

**Additional context**
Enterprise had showCloseButton

**Comment by tmcconechy** [comment]
When we add

- new setting that appens it and positions it (working on RTL as well)
- refactor the ids-about.ts to use the new setting as it now appends it manually. and maybe that logic can be moved.

**Comment by jbrcna** [comment]
this is working as expected 
<img width="645" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/66556fb1-c98d-4c5b-81ee-5a01056b7375">
<img width="921" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/0b734ae5-0969-4d01-9a8b-c0beb04d320c">
<img width="418" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/c4b18931-a928-4476-8c05-cafff0cfb072">

**However**, when x button is placed left on modal. **the x icon overlaps with the text**
<img width="489" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/d18e869d-4c69-4202-be85-cff3eddbc65a">

**Comment by tmcconechy** [comment]
@jbrcna can you add a new issue for that one?
