### ISSUE TITLE
IdsTree: feature to only expand and collapse a node by clicking on the icon.

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#1528]
**Is your feature request related to a problem or use case? Please describe.**
Cannot select a tree node w/o it expanding/collapsing.

**Describe the solution you'd like**
Want to be able to expand and collapse a tree node solely by clicking on the node icon. 

4.x already has this feature, it can be turned on by using `tree.options.expandTarget = 'icon'`

```
/**
 * The available options for expand target.
 * `node` can toggle by clicking on icon or node text.
 * `icon` allows to toggle when clicking only the icon portion of the tree node.
 */
type SohoExpandTarget = 'node' | 'icon';
```

**Comment by tmcconechy** [comment]
Additionally:

1. Make sure the select event fires only on click of the item not the icon (that should fire the expand)
2. Make sure you can swap icon out on the folder with seperate settings

**Comment by jbrcna** [comment]
QA Passed
https://main.wc.design.infor.com/ids-tree/sandbox.html
![Large GIF (548x656)](https://github.com/infor-design/enterprise-wc/assets/56722184/640fd6ea-e629-4b06-b4e9-b19bb89cde9a)
