### ISSUE TITLE
IdsModal: splitter is positioned incorrect on initial display.

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#1529]
**Describe the bug**
In a full size modal I have a splitter with a tree on left and a list view on the right. The real feature we are doing is a landmark drill around modal.

**To Reproduce**
1. Put attached example into place in the ids-modal directory.
2. Open the example in a browser
4. Click on the Trigger Modal button
5. drag the splitter left to see the left content spill past it
6. See the left content spills past the splitter and the right content is shifted to the right.

If you resize the browser then it all seems to be working.

Example
[tree-detail-modal.zip](https://github.com/infor-design/enterprise-wc/files/12834903/tree-detail-modal.zip)

**Expected behavior**
This modal content displays correctly when opening the modal.

**Version**
- ids-enterprise-wc: latest

**Screenshots**
When first opened, if the browser is wide drag the splitter to the left to see the tree spill past the splitter

![image](https://github.com/infor-design/enterprise-wc/assets/4737815/37540189-8188-4639-90af-9b6143e259ee)

After resizing the browser it seem to be ok
![image](https://github.com/infor-design/enterprise-wc/assets/4737815/4e41ff6c-99bf-440e-8678-5b65e12155b4)

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: latest

**Additional context**

**Comment by glenlieorillo** [comment]
Passed.

https://main.wc.design.infor.com/ids-modal/contains-tree-detail.html

<img width="1184" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/9e746fef-a16a-4680-9edd-e2d5585b8938">

https://main.wc.design.infor.com/ids-action-panel/example.html
<img width="1343" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/439b79df-f988-4667-8e17-3d6020494842">

https://main.wc.design.infor.com/ids-modal/contains-components.html

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/bc34024b-df88-40ff-9179-c69f55bb9d77)


https://main.wc.design.infor.com/ids-splitter/list-detail.html


![image](https://github.com/infor-design/enterprise-wc/assets/102151352/88dc0961-6dbb-4242-a715-e3d2be8d894c)
