### ISSUE TITLE
General: Add xlsx and csv compatible export

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise-wc#153]
**Is your feature request related to a problem or use case? Please describe.**
Having a true xlsx export would solve a lot of issues users have with exported data. For example, in M3/GLT container number is a text field. It is not uncommon for that value to be a very long string of numbers. Currently a container number value of '3050000010100000' is exported correctly from the datagrid but when excel opens that file, be it CSV or XLS, it interprets it as a big integer and renders it as '3.05E+15'. When the the user subsequently saves that csv or xls, it saves the value as '3.05E+15'. This can also be the case for lot numbers in M3, as another example. I could give lots more. I'm sure this issue is prevalent in other Infor MRP products - long text values with only numeric characters. Xlsx would let you explicitly designate those long fields as text values and avoid Excel's 'wizardry'. We realize this is an Excel issue but that's not how customers see it. When they do an export and open it in Excel and the data is scrambled, it's not a good look for us. We also realize that there is import functionality in Excel that can circumvent this. In reality, users don't want to go through 10 steps (or whatever) every time they open an export. Our application is essentially a querying one so exports are commonly used to send data to FDA, etc.

**Describe the solution you'd like**
Add 'xlsx' as a export option to the datagrid/excel.js component. 

**Describe alternatives you've considered**
1. As a workaround, you can prepend a tab or single quote character to each value for xls or csv exports. That forces Excel to interpret the value as text but in reality you are changing the data from what it truly is. Not good. It looks odd when displayed. If something needs to programmatically read the xls file, it will likely not like a leading tab or quote char. This is our current workaround solution but it is lacking.

2. Write/obtain our own xlsx code. Not great. It would be inconsistent with other applications that use IDS. Also, we would need to modify the standard grid behavior/code.

**Additional context**
1. I'm only mentioning csv here because that's what we've advised users to do. It gets rid of the 'The file format and extension of 'xxxxx.xls' don't match' warning. They would gladly go to xlsx if it was available. In our opinion, csv should be left alone as it's more likely to be read programmatically and should have raw data in it.
2. Ref this issue: https://github.com/infor-design/enterprise/issues/2995 
And what application do you work on? [e.g. {Infor XYZ}] 
GLT and by extension M3
4. Excel export works "properly" in DataTables https://datatables.net/extensions/buttons/examples/initialisation/export.html
and it does - although they export in xlsx format.
5. Check out https://github.com/exceljs/exceljs/blob/master/spec/browser/exceljs.spec.js for a possible start

**Additional context**
Nested datagrid data?

**Comment by jbrcna** [comment]
working as expected. no error is given when the Excel file is being opened.
https://main.wc.design.infor.com/ids-data-grid/export-excel.html

`Test special characters/locales` is also working
https://main.wc.design.infor.com/ids-data-grid/example.html
**excel**
<img width="1633" alt="image" src="https://user-images.githubusercontent.com/56722184/225200038-2888ff00-5145-435b-b36c-fadb60b988c8.png">
**csv**
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/56722184/225200218-4a2caffe-a976-4957-8107-bd7709b03251.png">

**Comment by jbrcna** [comment]
However, the exported css does not match the datagrid data (Product id column) in
 https://main.wc.design.infor.com/ids-data-grid/export-excel.html
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/56722184/225199213-775aa736-afec-499e-9261-8b1460584a77.png">

**Comment by jdilag90** [comment]
@jbrcna that's due to the column width. If you expand the column for Product Id it should show the full number. I don't think there's a way to control column width in csv exports.

https://stackoverflow.com/questions/15224052/how-to-set-size-of-column-of-csv-file#:~:text=You%20can't...,or%20OASIS%20Open%20Document%20Format%20(.

**Comment by jbrcna** [comment]
thanks for clarifying @jdilag90 . I can see the full value of product id after expanding the column. moving this ticket to done.
<img width="686" alt="image" src="https://user-images.githubusercontent.com/56722184/225496240-3fc2ecf3-1b4c-4124-ba64-c1a918ef6232.png">
