### ISSUE TITLE
IdsModal: when making the browser shorter or taller a full size modal shifts up or down

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#1530]
**Describe the bug**
when making the browser short a full size modal shift up

**To Reproduce**
1. Put attached example into place in the ids-modal directory.
2. Open the example in a browser
4. Click on the Trigger Modal button
5. Make the browser short until you see the modal shift up.
6. Make the browser taller until you see the modal shift down.

**Expected behavior**
Modal should not shift up or down

**Version**
- ids-enterprise-wc: latest

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/4737815/b2ca0ab7-db98-472d-9f62-068fcfd50a8b)

![image](https://github.com/infor-design/enterprise-wc/assets/4737815/827d0d0e-177b-4745-9334-d942d3d2b24d)

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: latest

**Additional context**

**Comment by jbrcna** [comment]
QA Passed
https://main.wc.design.infor.com/ids-action-panel/example.html
<img width="1155" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/d25d8f1d-d0e0-4c08-8622-ad0f94d8f41f">
<img width="1187" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/3698cb4a-e37f-481a-bf86-42bdacb89b0b">

https://main.wc.design.infor.com/ids-modal/contains-components.html
<img width="1258" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/8b3d1915-55db-4b6d-9057-8cad5e71452d">
<img width="1720" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/901a8e43-be2a-4aa0-b931-80928c663b38">
