### ISSUE TITLE
IdsStackedChart: Create a stacked column % chart with a vertical legend to the right

### ISSUE THREAD

**Issue by tfavorite** [infor-design/enterprise-wc#154]
**Is your feature request related to a problem or use case? Please describe.**
There are several chart donuts that might do better as a single stacked column of 100%, with the legend to the right. Legends frequently sort in the same order as the chart items. Users don't often get to see that because legends are placed beneath, and wrap around, making following the order less intuitive for users (and eating up vertical space).

Here, we envision a legend that is a simple, vertical column of colors and labels that is more easily parsed by the user (and saves vertical space). See attached wire (below) for layout.

**Describe the solution you'd like**
An option to put legend on the side.

**Describe alternatives you've considered**
The only option right now seems to be putting the legend on the bottom.

**Additional context**
<img width="517" alt="TO-status-stacked-column-right-legend" src="https://user-images.githubusercontent.com/347235/98560109-6969ee00-2275-11eb-9829-28a2b1f7aff7.png">
And what application do you work on? Infor Nexus

**Comment by alex-infor** [comment]
Not urgent - but is there a Jira ticket associated with this? Just want to link to it from a project page. Many thanks!

**Comment by tmcconechy** [comment]
No this is the only issue for this one. We use github not jira (except for some design issues)

**Comment by alex-infor** [comment]
Got it. Thanks for the quick response :-)

**Comment by EdwardCoyle** [comment]
Depends on #400
