### ISSUE TITLE
IdsErrorpage: modal container not displayed 

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1540]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-error-page/example.html
2. See error

**Expected behavior**
<img width="1313" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/845299e8-1f29-4aad-9a8c-db6b63a18de7">

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1675" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/0b7d0bbd-86b8-4193-9c99-231ef665865e">

**Platform**
Safari

**Additional context**

**Comment by EdwardCoyle** [comment]
Noting that the error dialog doesn't show up when initialized in Safari

**Comment by jbrcna** [comment]
this is now working in local
**Safari**
<img width="1166" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/0c9aef52-6bed-4acb-9858-7253d14001bc">

main
<img width="1512" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/1be26188-f6bc-4370-9ad5-ca5cff9bc58d">

**Comment by jbrcna** [comment]
moving to done. thank you
<img width="1183" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/8bd7face-d9f4-4a20-a81c-aa4dfa1c1b37">
