### ISSUE TITLE
ListView: Row Click Event is Selecting the row item and Checkbox Too in Angular

### ISSUE THREAD

**Issue by ashachodavarapu** [infor-design/enterprise-wc#1543]
**Issue Description:**
**Multiselect list view:**
-  On clicking the list row(multi-select), observed that two click events are triggered, one for the checkbox and another row selection event. ( in HTML used **(click)** event both check box & row selected).
- observe below snippet=> for **(click)**:
<img width="966" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/105051938/0f08af82-e21e-402d-96e6-11b3e89d570b">
-  The same thing was tried by using **(**selected**)** only one event triggered but both the checkbox and row were selected in this scenario. Observe the below snippet. 
<img width="951" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/105051938/c29378c3-3647-4430-bdfe-c0cc171dae14">

**Mixed Select List View:**
-   On clicking the list row(mixed-select), observed that two click events are triggered, and the checkbox is not selected. ( in HTML **(click)** event used, row only selected). observe below snippet
<img width="1021" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/105051938/19f8209d-bcfe-43fe-826d-526d2f486981">
- The same thing was tried by using **(selected)** no events were triggered for the row selection. Observe the below snippet. 
<img width="958" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/105051938/7b40e247-f55e-4bbe-991e-d04fc4720d53">
-  On clicking the checkbox(mixed-select), observed that two click events are triggered, and the row is not selected. ( in HTML **(click)** event used). observe the below snippet.
<img width="962" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/105051938/780d43c2-276a-4d75-95d9-91798d5e5075">
-  The same thing was tried by using **(selected)**, one event was triggered for the checkbox selection. Observe the below snippet. 
<img width="964" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/105051938/6399fbd7-8a04-4bd5-b474-5451bea79fd3">
**Query:** For mixed row selection is there a separate click event property available?

**Please refer to the below video:**
https://github.com/infor-design/enterprise-wc/assets/105051938/dd32d8a5-c474-42fb-80ef-8dee8b5d6ce3

**Reproduction steps:**
- Open multi & mixed select list view example in ids-wc examples angular application.
-  Add a click event for the list and inside the method put one console log. (you can use (click) and (selected)
- observed the above-described issue.
**Expectations:**
* separate click events will need to be triggered for the checkbox and row selection.
* Only one event will trigger either the checkbox or row selection

**Comment by tmcconechy** [comment]
@ashachodavarapu having a hard time following this issue. Do you think you can simplify it?

- include the code example code
- just add steps to reproduce and expected results

see template: https://github.com/infor-design/enterprise-wc/issues/new/choose

**Comment by ashachodavarapu** [comment]
Hi @tmcconechy ,
below is the code and output of the code snippet for the multiselection listview **(using (click))**
`HTML:
  <ids-list-view
          #listView
          id="demo-lv-selectable-multiple"
          selectable="multiple"
          item-height="76"
          (click)="onMultiListClick()"
        >
ts:
 onMultiListClick(){
    console.log('onListClick both checkbox and item selected in multiple list view')
  }`
![image](https://github.com/infor-design/enterprise-wc/assets/105051938/675d310f-176d-4548-ab3d-858d2b79e007)
**Using (selected) event in HTML:**
- only one event was triggered but both the checkbox and row were selected.

`  <ids-list-view
          #listView
          id="demo-lv-selectable-multiple"
          selectable="multiple"
          item-height="76"
          (selected)="onMultiListClick()"
        >`
**output:**
![image](https://github.com/infor-design/enterprise-wc/assets/105051938/cb88669b-3a83-435d-98c9-5fab009f85cf)

**Comment by tmcconechy** [comment]
Thanks @ashachodavarapu that will help

**Comment by jbrcna** [comment]
QA Passed
https://main.wc.design.infor.com/ids-list-view/selectable-single.html
<img width="1724" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/0c433b16-699f-49ba-b7d5-68914c58f438">

https://main.wc.design.infor.com/ids-list-view/selectable-mixed.html
<img width="1698" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/39e1f5a1-cd0b-45b8-8c66-4a45439abeec">


https://main.wc.design.infor.com/ids-list-view/selectable-multiple.html
<img width="1669" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/872a4b8f-2915-427c-a408-56448cee48fa">
