### ISSUE TITLE
IdsInput:  need 'required field' asterisk with customized validation message

### ISSUE THREAD

**Issue by kellyFeng1** [infor-design/enterprise-wc#1553]
**Is your feature request related to a problem or use case? Please describe.**
Need to localize the 'required' validation message. We are using addValidationMessage() but then there is no sudo ui '*'. Tried to add 'validate="required" ' but got two validation messages.

**Describe the solution you'd like**
It would be great if we could customize the 'required' message while keeping the asterisk. 

**Version**
ids-enterprise-wc: 1.0.0-beta.15

**Platform**
WFM

**Comment by tmcconechy** [comment]
Yeah the problem is its tied to the required...

```
<ids-input type="text" label="Last Name" validate="required"></ids-input>
```

Should make this a property. And you can make your own custom rule with a custom message

```
<ids-input type="text" label="Last Name" validate="custom" required></ids-input>
```

**Comment by jbrcna** [comment]
QA Passed
verified in https://main.wc.design.infor.com/ids-input/validation-required.html
<img width="1084" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/e9d005c4-4733-4998-acaa-f4b02d3874f0">

https://main.wc.design.infor.com/ids-input/example.html
<img width="436" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/a5f7192d-c58e-41d5-9c53-cc8295815307">

https://main.wc.design.infor.com/ids-trigger-field/example.html
<img width="1117" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/e17c7e4e-a3f7-455b-aeb3-efe0f333809f">


https://main.wc.design.infor.com/ids-dropdown/example.html
<img width="405" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/e333cf6b-10ae-428e-9cd3-2843de629aa5">
