### ISSUE TITLE
IdsInput: 'Label - Ellipsis' label not working

### ISSUE THREAD

**Issue by max-hizon** [infor-design/enterprise-wc#1554]
**Describe the bug**
'Label - Ellipsis' label not becoming ellipsis

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-input/label-wrap.html
2. See Error

**Expected behavior**
'Label - Ellipsis' label should use ellipsis

Note that this web component page demonstrates different types of text wrapping of each text input label. For the example that should demonstrate ellipsis, it does not do so.

**Version**
- ids-enterprise-wc: latest

**Screenshots**
<img width="919" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/79514236/6febb3d4-8da9-4956-871e-3fb5d578bae8">

**Platform**
 - Browser Name: Any

**Additional context**

**Comment by jbrcna** [comment]
QA Passed
<img width="1063" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/214ba06a-6252-42a1-84b5-8026761b2bc9">

<img width="1141" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/ad35f0e5-f118-4911-95fa-0b7b4b4fcfb3">

<img width="386" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/6149d391-9b33-49da-8cba-5ea3f6c8e391">
