### ISSUE TITLE
IdsAxisChart - overlapping text in mobile view

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1555]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-axis-chart/responsive.html
2. Switch to mobile view
3. See error
4. Check also in RTL

**Expected behavior**
text should be clear / not overlapping

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="471" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/3f707dad-1f44-44a3-b7f9-3d6de9a1631a">
<img width="436" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/739616c0-a07f-43db-8c9e-d90b149469e0">

**Platform**
mobile

**Additional context**
related to https://github.com/infor-design/enterprise-wc/issues/1458#issuecomment-1764569354

**Comment by tmcconechy** [comment]
1. make this use home pages
2. improve the example to use small/medium/large labels (exists)
3. add option to hide labels on mobile entire

**Comment by jbrcna** [comment]
QA Failed. issue still exists
https://main.wc.design.infor.com/ids-axis-chart/responsive.html
<img width="841" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/de6943b7-0b24-49a3-86d8-eff88f8c2638">

RTL
<img width="799" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/fee3994c-3fc7-4ca7-bd10-821a1dbf6415">

**Comment by jbrcna** [comment]
it is working as expected in local.
verified in http://localhost:4300/ids-axis-chart/responsive.html
<img width="475" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/f8dd2d83-a031-4d3e-b12a-17ea75b0da1e">
<img width="558" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/51ffc59a-c422-4f68-8b10-8bf0f92adb19">
