### ISSUE TITLE
IdsAccordion/IdsModuleNav: Reclaim space for accordion top

### ISSUE THREAD

**Issue by shalini-patro12** [infor-design/enterprise-wc#1563]
**Issue**
1. on clicking the menu button left side nav-menu items are displayed,  there is some space allocated for the profile, and if the profile is not needed after removing the profile. Then also it is occupying some space,
2. Space should be removed in case we don't want to give a profile or name in angular.  Refer below snippet
has a context menu.
3. Some extra icon is added (dropdown icon arrow) when I am using <ids-accordion-header> inside <ids-accordion> in angular. the requirement is like by using <ids-accordion-header> inside <ids-accordion> icon shouldn't be there if there is no child menu items for header item
4. file path=>enterprise-wc\src\components\ids-app-menu\demos\example.html
URL: https://main.wc.design.infor.com/ids-app-menu/example.html
snippet:

<img width="226" alt="Screenshot 2023-10-18 121602" src="https://github.com/infor-design/enterprise-wc/assets/148531844/3a25c
<img width="229" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/148531844/85336654-0fad-4802-9695-96f3ed7d8732">
737-0064-4c1b-b15a-b5e1af7cb2db">
<img width="977" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/148531844/d9c11447-aadb-48c2-ac2d-3df26d395169">

 Reproduction steps:-
1. Open the ids app menu component and remove profile and observe the extra space is being added.

**Comment by tmcconechy** [comment]
@shalini-patro12 this issue is a little unclear. I know about the extra space it takes up. But can you try to add a description of what you actually want? I.E. the data and roughly how you would like it displayed. Then we can make it work.

Also is it ok if we do this on the new component instead https://main.wc.design.infor.com/ids-module-nav/

**Comment by shalini-patro12** [comment]
Hi @tmcconechy ,
Yeah by using this  https://main.wc.design.infor.com/ids-module-nav/ i am able to add menu item without accordion also.
But yes, i want to remove the extra space from top if i don't want to display image and name.

**Comment by tmcconechy** [comment]
To fIx: Add example like https://main-enterprise.demo.design.infor.com/components/module-nav/example-hide-show-sections.html?colors=fff with no sections shown that you can toggle and a reclaim space
