### ISSUE TITLE
IdsCalendar: Support for proper legend content projection

### ISSUE THREAD

**Issue by JunyiZhao720** [infor-design/enterprise-wc#1564]
Currently, the ids-calendar component supports content projection for the desktop legend but not for the mobile one. I've noticed that the desktop and mobile legends are quite different and come from different components.

For the desktop legend:

![image](https://github.com/infor-design/enterprise-wc/assets/22669426/51ac53a2-0c03-4fee-a992-6ad354a5f618)
The legend resides inside the ids-calendar component but not within any specific view.

For the mobile legend:
![image](https://github.com/infor-design/enterprise-wc/assets/22669426/03f9a65d-bb67-41c7-91a3-d6d68638e37b)
The legend comes from the month-view component.

We're planning to create a customized legend. However, due to the differences between the desktop and mobile legends and the lack of content projection support for the mobile legend, implementation becomes complex.

**Describe the solution you'd like**
Ideally, both desktop and mobile views should use the same legend. One solution would be to allow clients to use the current mobile legend for both views and also support content projection for the mobile legend. This way, we would only need to implement one customized legend for both views.

**Comment by tmcconechy** [comment]
Whats the use case for picking different legends? I think we want to avoid too many options that can make bugs and extra work and inconsistency. Why not just use it as it works?

**Comment by JunyiZhao720** [comment]
> Whats the use case for picking different legends? I think we want to avoid too many options that can make bugs and extra work and inconsistency. Why not just use it as it works?

We can agree to use the provided legend, but the existing legend styles differ too much between desktop and mobile views. We can accept using the mobile legend on both screens, but using the desktop version is definitely not an option. The main reason is that our design only supports a legend positioned at the bottom. If, for desktop, it appears as a sidebar on the left, that would break the existing design as far as I know.

**Comment by JunyiZhao720** [comment]
Also, in the future, when we replace the Soho component with the web component, a new legend design is in progress. I've tried customizing the legend, but as mentioned, content projection is currently unavailable. Using the default style is only a placeholder for the future.

**Comment by tmcconechy** [comment]
The EP issue i think we wont want to spend time in both places. I could see being able to provide your own legend via content projection / overrides. But i think it would not be connected in any way. I.E. just an example with a "custom legend".

Would that work? And it fits more here in this project and is pretty hard to change in the other project

**Comment by JunyiZhao720** [comment]
I understand the difficulty. So you're suggesting the action item will be to provide content projection capabilities for a standalone legend? Personally, I don't see that as a problem, as long as we can easily attach it to the calendar and extend or override it.

**Comment by tmcconechy** [comment]
Yeah have to figure it out. Not super simple. But essentially if you place a legend / anything in the legend slots it will replace whats there in the page.

**Comment by JunyiZhao720** [comment]
I can't find a web component called 'ids-legend' or similar. The only things I've found are in 'ids-month-view-common.ts': 'IdsLegend' and 'IdsLegendSettings', which are just TypeScript types. If I understand your approach correctly, we should expect to find an 'ids-legend' web component that we can use, extend, or override. This is unrelated to the calendar, correct?

**Comment by tmcconechy** [comment]
It actually does have a slot https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-calendar/ids-calendar.ts#L289 so it would be something like this..

https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-calendar/demos/example-custom.html#L41-L43

```
<ids-calendar>
  <div id="mylegend" slot="legend"></div>
</ids-calendar>
```

Then you can put whatever you want in there and it will render in place of the current legend. (This is actually content projection with slots). You will have to add event handlers and styling ect.. Its just swaps out that html with what you provide.

Since the slot is there you can play around but i think this will need changes / or errors will happen ect... Its untested.

**Comment by JunyiZhao720** [comment]
The legend slot is only for desktop. The mobile legend is within month-view and doesn't support content projection. Desktop and mobile legends are rendered from different locations. I just tested it; the desktop legend is replaced, but the mobile one remains unaffected.

**Comment by tmcconechy** [comment]
Ok, might have to add a slot for the mobile one. Plus we dont support picking whatever one you wish. Ultimately do you only want the mobile one? And it custom? 

If so will have to work through this when we have time.

**Comment by JunyiZhao720** [comment]
Ideally, we should allow the mobile legend to display on both screens and support content projection. This would mean we only need to override one legend. If we only add support for the mobile legend, we'd still have to override two legends, and the desktop one's left-side position could cause issues.

**Comment by tmcconechy** [comment]
ok got it

1. prefer the mobile legend in desktop and mobile
2. support customization on it

**Comment by JunyiZhao720** [comment]
this is one of the prototypes of our future legend. 
1. it should always display at bottom
2. it should be used both for desktop view and mobile view
![image](https://github.com/infor-design/enterprise-wc/assets/22669426/70772305-02d9-48b1-89f9-38a125a42e55)

**Comment by jbrcna** [comment]
QA Passed
https://main.wc.design.infor.com/ids-calendar/custom-legend.html
<img width="598" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/72dfc523-47a6-4187-a679-8af44f103296">

desktop
<img width="1188" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/6fb04d4e-bf25-410a-aa83-4a54add8df91">

mobile
<img width="522" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/192149e1-0d05-48ea-ab72-b6e1bbc35906">


desktop
<img width="1183" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/8ceba1ab-c1c5-4df4-a27e-dd512093cd19">


mobile
<img width="523" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/22dcc39c-222c-468e-95ed-a41b6a217c9c">
