### ISSUE TITLE
IdsRadio: selected states are different

### ISSUE THREAD

**Issue by max-hizon** [infor-design/enterprise-wc#1568]
**Describe the bug**
Selected state of the radio options with color is different from the selected state of the rest of the radio options

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-radio/example.html
2. Select a radio option under any label except for colored and switch option using up and down arrow keys to show selected state
3. Do the same for the colored radio options

**Expected behavior**
Selected state should be the same. Unsure which selected state is correct
**Version**
- ids-enterprise-wc: latest

**Screenshots**
thin outer circle
<img width="158" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/79514236/824ca58c-aff3-4e00-b165-7b7b59c4c308">

shadow outer circle
<img width="281" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/79514236/015e9876-beb0-48c1-b881-59d46af5b670">

**Platform**
 - Browser Name: Any
 
**Additional context**

**Comment by glenlieorillo** [comment]
QA Passed.

https://github.com/infor-design/enterprise-wc/assets/102151352/94feab1d-bab6-431b-87da-3f33047acf55
