### ISSUE TITLE
IdsSearchfield: Clear button not working

### ISSUE THREAD

**Issue by max-hizon** [infor-design/enterprise-wc#1569]
**Describe the bug**
Clear button does not clear the searchfield. It only clears the initial text

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-search-field/example.html
2. Type anything on any of the searchfields with a clear button
3. Click the clear button

**Expected behavior**
Clear button should clear the text on the searchfield

**Version**
- ids-enterprise-wc: latest

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/79514236/7cb75d20-aa67-43a8-b502-dcd7652d8f8e

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by lucacolumbu** [comment]
@max-hizon please test again this should be fixed already.

**Comment by glenlieorillo** [comment]
Passed.


https://github.com/infor-design/enterprise-wc/assets/102151352/8c820269-2a96-40de-abe0-aef7fdc4e4a2
