### ISSUE TITLE
IdsInput: Impossible to remove readOnly state

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#1570]
When set a field initially as readonly, it is impossible to remove readonly from it. This was not happening on previous versions.

```html
<ids-input id="ids-field" label="IDS Text Field" readonly></ids-input>
```

Now remove the readonly property:
```javascript
document.getElementById('ids-field').removeAttribute('readonly');
```

Btw the doc (https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-input) says "readonly {boolean} sets the input's readonly state." (for disabled and readonly accepts boolean value), but when set `document.getElementById('ids-field').readonly = false`, still doesn't work.

Visually looks like is not readonly anymore, but it is impossible to type in the field.

**Version**
1.0.0-beta.16

**Screenshots**
![MicrosoftTeams-image](https://github.com/infor-design/enterprise-wc/assets/663908/a95aac59-6ee4-4680-8a8e-b008e0fa4ed6)

**Platform**
 - OS Version: Mac OS
 - Browser Name: Chrome
 - Browser Version: 118.0.5993.88 (Official Build) (x86_64)

**Comment by jbrcna** [comment]
QA Passed. moving this ticket to done
verified in https://main.wc.design.infor.com/ids-input/example.html
<img width="1533" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/88212323-4969-48d9-8562-944b46cc9f28">
