### ISSUE TITLE
IdsDatagrid.scrollRowIntoView() does not work on tree grid

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1573]
**Describe the bug**
When a large number of rows are loaded on idsDatagrid tree grid, idsDatagrid.scrollRowIntoView() does not work as it should. It has to be executed a number of times to go to the intended row/row index.

**To Reproduce**

1. clone enterprise-wc, npm i, npm start
2. open http://localhost:4300/ids-data-grid/tree-grid-virtual-scroll-infinite-scroll.html
3. scroll down to row # 514
4. open dev tools - console
5. run `document.querySelector("#tree-grid-virtual-scroll").scrollRowIntoView(349)  ` to go to row `#350`
6. Error: datagrid did not go to the intended row `(#350)`

**Expected behavior**
Row `#350` should be visible

**Version**

- ids-enterprise-wc beta 16

**Screenshots**

Video:

https://github.com/infor-design/enterprise-wc/assets/53523076/802c1ab0-0c01-48a4-8d4b-42014f0b1404

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: chrome
Browser Version: Version Version Version 118.0.5993.89 (Official Build) (64-bit)

**Additional context**
ScrollRowIntoView() needs to executed a number of times before the row shows up on the datagrid.

**Comment by jbrcna** [comment]
QA Passed
![Large GIF (1612x642)](https://github.com/infor-design/enterprise-wc/assets/56722184/29ba3ffe-9487-48c8-b375-f6ed7204da8e)
