### ISSUE TITLE
IdsDataGrid: Column header filter button is also aligning to the right

### ISSUE THREAD

**Issue by eaenriquez** [infor-design/enterprise-wc#1575]
**Describe the Issue**
Having a Datagrid column that is right aligned is also aligning the filter button to the right.

**To Reproduce**
Steps to see the question or problem:
1. Render a datagrid column and data with one column set to right align

**What are you trying to do**
To not also align the button to the right inside the datagrid column's header

**What did you try so far**
N/A

**Version**
- ids-enterprise-wc: 1.0.0-beta.15

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/68070868/01c6dc94-58c9-4254-8b6c-351b56095144)

**Platform**
- Browser Name: Chrome
- Browser Version: 118.0.5993.70 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
@eaenriquez why would it make sense to change to not right align the button?

**Comment by tmcconechy** [comment]
Since we have `align: 'right'` and `headerAlign: 'right'` already. I propose we add `filterAlign` so you can do this..

![Screenshot 2023-10-31 at 12 38 16 PM](https://github.com/infor-design/enterprise-wc/assets/814283/273b8d1d-34ed-445b-9d5b-6c6f06579d2c)

```
   align: 'right',
    headerAlign: 'right', // optional because its the same
    filterAlign: 'left' <-- new
  });
```

**Comment by eaenriquez** [comment]
> @eaenriquez why would it make sense to change to not right align the button?

It is just we never had this from the soho-components and this is preferred by the stakeholders of our project.

**Comment by tmcconechy** [comment]
Ok no worries @eaenriquez we decided it looks ok and we can add a new option here.

**Comment by glenlieorillo** [comment]
Fix has been applied. However, if you change to RTL (other locale) it doesn't change its position like the other filters.

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/e8990438-90e2-4960-b308-e2d0a2d3dd03)

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/97207e8e-7bbf-48f2-a6a0-98245449e4fb)

**Comment by tmcconechy** [comment]
@EdwardCoyle good point ☝🏻 I forget to test RTL here. Do you want a new issue or just do a supplemental fix here?
