### ISSUE TITLE
IdsDatePicker: Date with Time pickers are not working properly

### ISSUE THREAD

**Issue by snelanti** [infor-design/enterprise-wc#1576]
**Describe the bug**
Date with Time picker is always picking some constant time even after selecting some different time other than default value in field

**To Reproduce**
https://main.wc.design.infor.com/ids-date-picker/sandbox.html
Please watch below vedio for clear reproduction steps of the issue
https://www.screencast.com/t/8xwqTN3PJNJW

1. Go to https://main.wc.design.infor.com/ids-date-picker/sandbox.html
2. Click on Date Time Picker Current Time (or) Date Time Picker 24-Hour (or) Date Time Picker AM/PM
3. Please select time from Date time picker and click outside the picker
4. Observe that the selected time is not reflected in date time picker trigger field

**Expected behavior**
Selected Time should be reflected dynamically in date time picker trigger field when time is changed in the date time picker

**Version**
  "name": "ids-enterprise-wc",
  "version": "1.0.0-beta.15",

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/141207120/cc88466e-4b7b-4e46-a1fe-1c30e64890af)
![image](https://github.com/infor-design/enterprise-wc/assets/141207120/7c0c256d-26c3-44cb-a55f-14e21a3a8432)
![image](https://github.com/infor-design/enterprise-wc/assets/141207120/8b922799-d7bd-463b-902a-0ad0f71f7c6d)

**Comment by tmcconechy** [comment]
Also Note: WHen reopening the picker it should reflect the correct time. This is not happening.

**Comment by jbrcna** [comment]
the issue is now fixed. However, i noticed that I was able to input  more than 3 digits in time.
May i clarify if this is expected?
<img width="356" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/ead262cd-6cb0-4e4f-8ddd-3a1f6a71847d">

**Comment by tmcconechy** [comment]
@jbrcna That doesnt seem right. Can you look again @andrivarhanov adding a fix if needed?

Thanks!

**Comment by andrivarhanov** [comment]
@tmcconechy sure

**Comment by jbrcna** [comment]
QA Passed
all issues are now fixed. moving to done. thanks

![Large GIF (572x280)](https://github.com/infor-design/enterprise-wc/assets/56722184/0e1290ce-5ea5-45d8-9386-61613fc21adc)
