### ISSUE TITLE
IdsScrollView: incorrect controls after assigning a new array to ngFor

### ISSUE THREAD

**Issue by kellyFeng1** [infor-design/enterprise-wc#1577]
**Describe the bug**
we are using the ids-layout-grid inside an ids-scroll-view. When the screen size changes from mobile to desktop, we will assign a new array to the item2DArray as the number of items in one slide changes.

However, I just found when I assign a new array to the item2DArray when I am not in the first slide,  the first circle button in the carousel will become blue like it automatically scrolls to the first slide, but the slide doesn't change.

before assigning
![image](https://github.com/infor-design/enterprise-wc/assets/128092878/6c448425-118b-4f8a-9ee4-414200befa80)
after assigning a new array
![image](https://github.com/infor-design/enterprise-wc/assets/128092878/1db7548c-7be0-4a0f-8b82-0f97bb725dbc)

HTML
```
<ids-scroll-view #scrollView>
  <div *ngFor="let items of item2DArray" slot="scroll-view-item">
   <ids-layout-grid
       cols="4"
       rows="3"
       cols-sm="12"
       rows-sm="2"
       gap="md"
       flow-sm="column"
       flow="row">
       <ids-layout-grid-cell col-span="2" *ngFor="let item of items">
            <ids-icon [icon]="item.name"></ids-icon>
          <ids-text font-size="20" text-align="center">{{ item.name }}</ids-text>
       </ids-layout-grid-cell>
     </ids-layout-grid>
  </div>
 </ids-scroll-view>
```

Besides, also wondering if it is possible to remove the controls when there is only one slide.

**Platform**
 - Infor Application: WFM

**Comment by EdwardCoyle** [comment]
@kellyFeng1 the pager button controls won't disappear automatically, but they are can be hidden/shown under whatever conditions you'd like to implement using the `suppress-controls` attribute:

![Screenshot 2023-12-04 at 9 49 17 AM](https://github.com/infor-design/enterprise-wc/assets/3249601/3df69897-ace5-48d1-85ca-b20dfc555bdb)

Can you pass along some information about the dataset (or the dataset itself) you're using?  I'm also not clear on what you're trying to display per slide?  Are you sometimes displaying multiple items per slide as opposed to one, similar to the [SoHo circle pager](https://main-enterprise.demo.design.infor.com/components/circlepager/example-index.html)?

**Comment by tmcconechy** [comment]
Lets see what @kellyFeng1 says but my assumption was that if an ngFor is updated it doesnt reflect in the component. Maybe need a slotchange ultimately similar to https://github.com/infor-design/enterprise-wc/pull/1661/files

I think an option to hideIfOne would be ok (have to check if there is any with a similar name already for consistency).

**Comment by kellyFeng1** [comment]
Hi @EdwardCoyle and @tmcconechy, yes we have similar case to this [SoHo circle pager](https://main-enterprise.demo.design.infor.com/components/circlepager/example-index.html). I think the issue here is the control doesn't reflect the real slide number after ngFor is updated.
For example, we have 16 items to display. This is what we have for mobile view. Normally, these items should be displayed at first slide.
![image](https://github.com/infor-design/enterprise-wc/assets/128092878/6450c6cd-25aa-4b88-bf0c-c0910a33b8df)
and this is the second slide
![image](https://github.com/infor-design/enterprise-wc/assets/128092878/1d50e4b0-8547-4b23-916d-bc50c6274962)
And we have a different layout in desktop view like this.
![image](https://github.com/infor-design/enterprise-wc/assets/128092878/6a83e435-1a9d-4d3f-adb9-24314e60d1ce)
The issues happen when I am at the second slide in desktop view, and then I resize to mobile view. It will display the items at second slide, but the control show i'm at the first slide.
![image](https://github.com/infor-design/enterprise-wc/assets/128092878/6ed52811-8c47-4bd4-bd29-480db9b7a44d)

If I tried to go to the third slide, the items displayed correctly, but the control will look like this. And if I click on the second dot, nothing happens.
![image](https://github.com/infor-design/enterprise-wc/assets/128092878/5c6d14cd-383b-4646-ba9a-7670aa4dbfe1)
