### ISSUE TITLE
IdsSpinbox: Enabled non-number/non-integer value

### ISSUE THREAD

**Issue by max-hizon** [infor-design/enterprise-wc#1578]
**Describe the bug**
Spinbox allows for non-number/non-integer input

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-spinbox/example.html
2. Clear the number on the spinbox
3. Add any character onto the spinbox

**Expected behavior**
Non-number/non-integer character inputs should be disabled

**Version**
- ids-enterprise-wc: latest

**Screenshots**
<img width="340" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/79514236/a49140ef-83a0-4156-a6ab-a6d923eafb25">

**Platform**
 - Browser Name: Any
 
**Additional context**

**Comment by glenlieorillo** [comment]
This has been tested and passed.

https://github.com/infor-design/enterprise-wc/assets/102151352/51576fb8-aa46-487a-8445-d026a3e0bc96
