### ISSUE TITLE
IdsDataGrid: Empty data text still showing when adding grid row

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#1580]
**Describe the bug**
The grid initially has no data and shows the message "No data available", but when add new rows to the grid, the message still is there.

**To Reproduce**
```html
<ids-data-grid id="data-grid-1"></ids-data-grid>
```

```javascript
window.addEventListener('load', function() {
  var dataGrid = document.querySelector('#data-grid-1');

  dataGrid.data = [];
  dataGrid.columns = [{
    id: 'id',
    name: 'id',
    field: 'id'
  },{
    id: 'name',
    name: 'name',
    field: 'name'
  }];
});
```

From the console run: 
```javascript
document.getElementById('data-grid-1').addRow({id: 1, name: 'name 1'})
```

![Screen Shot 2023-10-26 at 4 31 42 PM](https://github.com/infor-design/enterprise-wc/assets/663908/5ff6ab6a-da85-4321-a7bb-2268d8bca5e7)

**Expected behavior**
Message about empty data hidden.

**Version**
1.0.0-beta.16

**Comment by jbrcna** [comment]
QA Passed
https://main.wc.design.infor.com/ids-data-grid/empty-message.html
<img width="1188" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/ed95998c-f88d-464b-8841-b6535ff21e26">
