### ISSUE TITLE
IdsTimePicker: Hour Range 12h AM only has no 12:00 option

### ISSUE THREAD

**Issue by max-hizon** [infor-design/enterprise-wc#1581]
**Describe the bug**
The option for 12 in the Hour drop down does not exist

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-time-picker/sandbox.html
2. Click on 'Hour range 12h AM only' time picker
3. Clicl the 'Hours' dropdown
4. Scroll to the bottom
5. See error

**Expected behavior**
'12' should be an available option in the 'Hours' dropdown

**Version**
- ids-enterprise-wc: latest

**Screenshots**
<img width="222" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/79514236/16e91e10-69c9-4ed5-be93-a03e8fd7b5f1">

Below is the same time picker but for the PM only options. 12 is an available option here
<img width="208" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/79514236/78eb589a-cc49-4b3c-a64a-1ae35b0e2cf0">

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@max-hizon not seeing this issue now on https://main.wc.design.infor.com/ids-time-picker/sandbox.html

<img width="402" alt="Screenshot 2023-10-30 at 10 02 41 AM" src="https://github.com/infor-design/enterprise-wc/assets/814283/b2e884da-35a3-4388-9df8-b14f9b247082">

**Comment by max-hizon** [comment]
Recreated using Windows 10 and 11

It seems to only occur when 'Period' isn't selected first but shows once you select it once
Note period here is empty but when you select it, the 12 option shows
![image](https://github.com/infor-design/enterprise-wc/assets/79514236/4bd8a0df-78e1-411d-8860-62ce93225cf3)


![image](https://github.com/infor-design/enterprise-wc/assets/79514236/1f50f6d4-f8d6-4d37-b157-2c6634d6c374)

For the PM only time picker, Period is set to PM by default.

![image](https://github.com/infor-design/enterprise-wc/assets/79514236/d9ee1676-c8c3-4cae-801a-6085133a3dc2)

I think it should be the same for AM as well to avoid this issue occuring

**Comment by tmcconechy** [comment]
@max-hizon seems ok now can you verify? or the steps we are having issue with

**Comment by jbrcna** [comment]
this is what I  see on my end. 
<img width="1111" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/69ac3f7d-cd8b-49c4-8397-ec80045076c1">
