### ISSUE TITLE
IdsText: line-clamp setting doesn not work

### ISSUE THREAD

**Issue by kellyFeng1** [infor-design/enterprise-wc#1585]
**Describe the bug**
I have code like
`<ids-text line-clamp="2"  tooltip="true" font-size="20" text-align="center">{{ name }}</ids-text>` but the text still takes more than 2 lines.

![image](https://github.com/infor-design/enterprise-wc/assets/128092878/bfd367da-30d8-428d-8820-9341d82bc261)

If I manually add the 'has-line-clamp' class to the span above, it works fine.
![image](https://github.com/infor-design/enterprise-wc/assets/128092878/80a0cb5e-be8d-42b5-b57c-caa01be438dc)

**Version**
1.0.0-beta.16

**Platform**
 - Infor Application: WFM

**Comment by tmcconechy** [comment]
In the example i made this for i use it with a max-width

```
<ids-text font-size="16" font-weight="semi-bold" overflow="ellipsis" tooltip="true" line-clamp="2" max-width="120">
                          Veni, veni. Ne me mori facias. Veni, veni, venias
</ids-text>
```

But. could be true we are not adding the class in some case when its added dynamically.

**Comment by jbrcna** [comment]
QA Passed
verified in https://main.wc.design.infor.com/ids-text/line-clamp.html
<img width="1521" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/da5d41e4-c370-4716-8d36-33173394a44a">
<img width="1366" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/7bba11d4-18a4-4b94-96f1-6ccffc51c44c">
