### ISSUE TITLE
IdsTriggerField: Web Component example looks off

### ISSUE THREAD

**Issue by max-hizon** [infor-design/enterprise-wc#1586]
**Describe the bug**
Example looks off

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-trigger-field/side-by-side.html
2. See error

**Expected behavior**
There should only be a single trigger field example with button inside field

**Version**
- ids-enterprise-wc: latest

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/79514236/456723e1-67d3-4110-a617-257bca55a232)

**Platform**
 - Browser Name: Any

**Additional context**

**Comment by jbrcna** [comment]
QA Passed
verified in https://main.wc.design.infor.com/ids-trigger-field/side-by-side.html
<img width="600" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/773a0bea-fa9f-4247-892a-24021a9135ce">



verified in https://main.wc.design.infor.com/ids-trigger-field/example.html
<img width="1526" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/d35a7dc0-e84f-49ba-a7e7-7bf4220cc550">
