### ISSUE TITLE
IdsDatagrid: Tree grid moves/scrolls rows after appendDataset() 

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1587]
**Describe the bug**
The datagrid moves/scrolls row after appendDataset() is executed. This happens on a large number of rows or when all rows are collapsed. In the tree-grid-virtual-scroll-infinite-scroll.html example, the rows are moved after scrolling at the end to get new records.

**To Reproduce**

1. clone entreprise-wc, npm i, npm start
2. open tree-grid-virtual-scroll-infinite-scroll.html
3. click collapse all
4. scroll down to the end to load new data, take note of the last row before and after new data is loaded
5. repeat a couple of times until the expected last row changes
6. error: last row is moved after appending new data

**Expected behavior**
When appendDataset() is called, the last row should not move, only the scrollbar should move/resize indicating that new records where added.

**Version**

- ids-enterprise-wc beta 16

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/53523076/25402f95-2846-4e23-be47-eee268d04b48

**Platform**
Infor Application/Team Name: M3 UX
OS Version: Windows 11
Browser Name: chrome
Browser Version: Version Version Version 118.0.5993.89 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
cc @clayinfor

**Comment by EdwardCoyle** [comment]
This is related to #1587

**Comment by jbrcna** [comment]
QA Passed
<img width="1718" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/0ed83fa0-693f-4b06-9209-ace027385827">
<img width="1670" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/35137220-ca13-4253-852d-425010cb258b">

scrollbar size on page load
<img width="1728" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/ffc0c879-d202-4609-acb8-f5ad6a380881">

scrollbar size on expanded
<img width="1726" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/7dd2f355-5d03-4ac8-b6aa-3e617f7690e1">

scrollbar size on collapse
<img width="1728" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/486b0a79-6b79-479d-88fa-0d2fe356caf1">

scrollbar size on mouse hover 
<img width="113" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/836bfe88-3952-4ab3-93eb-b95fd39427ff">
<img width="191" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/17289df7-10aa-4360-a522-e0a199ec81f7">

**scrollintoview**
![Large GIF (1642x634)](https://github.com/infor-design/enterprise-wc/assets/56722184/009c5b3d-0280-4a52-9795-debace3e38c1)
