### ISSUE TITLE
IdsDatagrid: Left/right arrow keys does not work inside a text editable cell

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise-wc#1588]
**Describe the bug**
On a text editable cell, the user cannot navigate on the text value by using the left/right arrow keys. The focus goes to the next cell.

**To Reproduce**

1. clone enterprise-wc, npm i, npm start
2. open http://localhost:4300/ids-data-grid/editable-inline.html
3. click on the first editable cell
4. once the value is highlighted, press left to go to the first letter
5. Error: the focus goes to the next cell

**Expected behavior**
The expected result should be to navigate using left/right arrow keys inside the text editable cell (similar to excel or windows explorer when updating cell value or renaming a file). Once finished with the edit (by pressing enter or escape), then the arrow keys will navigate within the cells. 

**Version**
- ids-enterprise-wc beta 16

**Platform**
 - Browser Name: Any
 
**Additional context**

**Comment by tmcconechy** [comment]
Thanks. Will have to look at this. I agree but the keyboard for cells is arrows. So maybe need to take the "actionable mode" in mind. https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/readme.md#keyboard-shortcuts (which also doesnt work)
