### ISSUE TITLE
IdsUploadAdvance: cannot fully upload files

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1589]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-upload-advanced/example.html
2. Check each fileupload by uploading a file
3. See error
4. Notice that it does not indicate a 100% success upload

**Expected behavior**
should be able to successfully upload a file. should indicate 100% label with green color

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1243" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/a8851164-c5bb-4a02-b5a0-fe299d5ce346">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
@jbrcna unfortunately the update functionality will only work when running on localhost because that main server cant handle uploads safely/securly. So we have this known limitation in the example page.

Try it on localhost and it will work. So known issue

**Comment by jbrcna** [comment]
thanks for clarifying @tmcconechy .
verified in localhost
<img width="1701" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b8638b76-3e73-4a6a-9c94-2738d3dfe350">
