### ISSUE TITLE
IdsDatagrid: Performance in M3 Experience Designer

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1592]
**Describe the bug**
M3 is reporting issues with dragging and general loading in their designer.

**To Reproduce**

1. Go to https://oxford.awsdev.infor.com/William.Hernebrink/exd-light
2. Clone, Then `npm i` and `npm run start`
3. Focus on the Ids Datagrid Page

- loading is slower than old version
- resizing widgets can be improved
- the splitter is even slower

Additional Issues:
- loose clicking (after resise the click events dont work)
- header is not sticky -> parent has overflow
- slower on page load -> how many times is resize called
- ResizeObserver is firing on resize and could be the culprit - tooltip or context menu
- redraw body is firing
- make an example with old home page resize and data grid
- why does connected callback call -> can this be sped up 

**To Reproduce in Main**
- https://main.wc.design.infor.com/ids-data-grid/columns-percent.html
- debug redrawBody
- drag ids-datagrid to body

**Expected behavior**
Faster

**Additional context**
Was observed that Angular is removing and readding the datagrid (debugging the disconnected and connectedCallback shows this). This causes to be reloaded and may be a key area for improvement.

**Initial Suggestions to M3**
- add an overlay during resize
- cache the widths/height so it doesnt fire redraw on resize unless needed (should not be needed css should be ok
- turn on virtual scroll for faster page render
- prevent reinserting (ng IF / for may be doing this) seems to remove then re add the component

**Comment by whernebrink** [comment]
Please request access to the example repository if needed, it's is not a public one.

**Comment by tmcconechy** [comment]
One thing i want to look at is https://medium.com/8451/600-faster-stencil-components-in-angular-d442fb87babd for this. As i did suspect zone was an issue.

**Comment by tmcconechy** [comment]
@whernebrink i tried this on https://oxford.awsdev.infor.com/William.Hernebrink/exd-light it does seem a bit faster. Maybe give a try as one part of this.

To add it 

- make a file at with apps/m3/src/zone-flags.js `window.__Zone_disable_customElements = true;` in it
- change project.json line ` "polyfills": ["zone.js", "apps/m3/src/zone-flags.js"],`

Still need to test side effects of this but seems pretty good so far. Also working on some other changes so it doesnt rerender when you move it around in the DOM

**Comment by whernebrink** [comment]
Hey @tmcconechy ! 

Thanks for the suggestion. We've updated the main branch now with our performance enhancements as well as the flag. Toggling that zone flag do not seem to do that much for us right now. Care to have another go at it, pulling our updated main? Thanks!

**Comment by tmcconechy** [comment]
@whernebrink 

Yeah i thought i saw a small difference with the zone flag (small tho). You see absolutely no change? Did you do anything else to make sure you dont constantly reload all the grids on resize?

My next step is to finsh some fixes in datagrid so it doesnt render when you move it, when thats done i'll retry.

Do you know how to setup the SSH keys in gitlab is there docs? My clone is old and a download zip.

**Comment by tmcconechy** [comment]
@whernebrink which branch is the latest and greatest https://oxford.awsdev.infor.com/William.Hernebrink/exd-light/-/branches (with trackBy)

Also did you see if the new NG signals stuff improves performance.

**Comment by hernebrink** [comment]
> @whernebrink which branch is the latest and greatest https://oxford.awsdev.infor.com/William.Hernebrink/exd-light/-/branches (with trackBy)
> 

That should be the `main` branch. 

> Also did you see if the new NG signals stuff improves performance.

Have yet to try anything signal related.

**Comment by tmcconechy** [comment]
Im going to close this issue. I got the https://oxford.awsdev.infor.com/William.Hernebrink/exd-light repo working with ssh and cloned and tested the latest combined without latest Web Component code on `main` and its looking pretty good to me.

1. Its faster now / no much noticeable lag but about the best we can do for now
2. The scroll bar issue is fixed
3. Moving it in the DOM no longer rerenders
4. The clicking in the datagrid works after dragging

So lets make a new issue if any other small issues. I did notice that the tabs need a bit more space and something strange with two drag bars in the first widget but assume your just working on something.

<img width="468" alt="Screenshot 2023-12-18 at 11 35 52 AM" src="https://github.com/infor-design/enterprise-wc/assets/814283/17d507d4-3090-4099-aa8f-d411f46ea28e">
<img width="465" alt="Screenshot 2023-12-18 at 11 35 46 AM" src="https://github.com/infor-design/enterprise-wc/assets/814283/8feda380-9bb1-4cae-a791-3d99a4986ccc">

**Comment by whernebrink** [comment]
Thanks @tmcconechy. Did you push anything or is the scrollbar "issue" fixed in wc-library? I assume it has something to do with our structure? Given the scrollbar issue is now solved, I would assume that we also will get the scrollbar events that was not previously emitted. Additionally, might add a new issue if this issue is sill present, but we had issue with when the datagrid is on a tab that is not in view, when it got into view, the columns of the datagrid were all stacked on top of each other. Not sure if the main branch of my repo showcased that?

**Comment by tmcconechy** [comment]
@whernebrink 

- if i use whats on main vs the package you have set in your project it fixes: a) the column stacking on each other issue (i think but not sure about the tab part) and b) the scroll bar issue
- I did not test the event being omitted

Will need beta.18 which will make in a bit. If any remaining issues with the tab problem or events not being omitted lets make individual focused issues?

**Comment by jdilag90** [comment]
@tmcconechy @whernebrink 
This is the column stacking issue. I think there's a temp fix for it by doing a `setTimeout(() => dataGrid.redraw());` in a `ngAfterViewInit`. Could have been fixed with the lifecycle changes, I'll check using our latest main branch and see if we can remove that temp fix.
![image](https://github.com/infor-design/enterprise-wc/assets/98347152/a234c6e5-6b27-4212-a995-949661282017)

The scrollbar issue is the one where the scroll is coming from a `.grid-container` element and not the datagrid. 
I think I found a fix for it (screenshot below), just have to recall what I changed since I haven't setup ssh with that git repo yet (don't have change tracking) 
![image](https://github.com/infor-design/enterprise-wc/assets/98347152/3b07c376-57ad-466e-96ea-f24f346fc3f8)

**Comment by tmcconechy** [comment]
@jdilag90 but if i pull on a build from `main` i no longer see the column issue and the scrollbars look ok now and they scroll under the header again. So I think i fixed it...

- try `npm i` on the code then try
- then build main and copy it over and you can see the diff

I was able to get tracking by following the links https://oxford.awsdev.infor.com/-/profile/keys
https://oxford.awsdev.infor.com/help/user/ssh.md

**Comment by jdilag90** [comment]
@tmcconechy awesome!

I'll just have to address this then in another PR. 

```
Also I have to push a fix for the scrollMaxRows datagrid setting. I added it when the tree-grid virtual scroll was fixed and forgot to test that setting with the non-tree virtual scroll.
```
