### ISSUE TITLE
IdsDatePicker: Minutes/Seconds Interval setting is not working as expected

### ISSUE THREAD

**Issue by snelanti** [infor-design/enterprise-wc#1594]
**Describe the bug**
ids-date-picker : I see minute-interval="1" in the code but minute dropdown is showing minute-interval as 5 on the UI.

1. Go to https://main.wc.design.infor.com/ids-date-picker/sandbox.html
2. Click on date-picker under 'Date Time Picker Current Time' label and inspect the code using developer tools
3. Click on Minute dropdown in date-picker, it is observed that dropdown list has numbers with interval 5 but code in developer tools show minute-interval=1 for respective <ids-date-picker>

**Expected behavior**
Minute dropdown in ids-date-picker should have list of numbers with interval 1.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![dd2b41ac-30d4-426d-8870-51227ea18826](https://github.com/infor-design/enterprise-wc/assets/141207120/2100f46a-50bf-4d9a-9f0e-14b8954524fd)

**Platform**
https://main.wc.design.infor.com/ids-date-picker/sandbox.html

**Comment by snelanti** [comment]
one more observation, may be because of this issue.
![15885b14-94d2-49f4-a51f-0e55053f4351](https://github.com/infor-design/enterprise-wc/assets/141207120/6764c8a1-2daa-4cc1-817b-00af6ac7f79b)
since minute-interval="1" is not binding and minute-interval="5" is taken as default, the minute and hour fields are empty by default even though value is shown as "23:59". this is because 23 and 59 are not multiples of 5.

**Comment by tmcconechy** [comment]
@snelanti i dont know whats wrong but its probably around how the drop downs get popuplated / should be unrelated to the value. We'll figure it out when we can find time.

**Comment by jbrcna** [comment]
QA Passed
![Large GIF (574x740)](https://github.com/infor-design/enterprise-wc/assets/56722184/c956732d-9058-44d3-bc5e-725ea45fea8f)
