### ISSUE TITLE
IdsTextarea: Two issues related to characterCounter 

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise-wc#1598]
**Describe the bug**
1. It doesn't seem like it's possible to hide the character counter below the textarea. There is a setting in the documentation, `characterCounter` (I assume it's corresponding attribute would be `character-counter`?), but it doesn't work.
2. The "characters left" text isn't translated 

**To Reproduce #1**
1. Edit one of the textarea demos to use the character-counter attribute, like
```
<ids-textarea maxlength="500" character-counter="false"><ids-textarea>
```
**Result**: Character counter isn't hidden

**To Reproduce #2**
1. Go to https://main.wc.design.infor.com/ids-textarea/example.html
2. Change locale to something else than English
3. See example that uses the standard characters left text for the counter (max length example left column)
**Result**: Text shown in English

**Version**
- ids-enterprise-wc: v1.0.0-beta.16

**Screenshots**
![MicrosoftTeams-image (6)](https://github.com/infor-design/enterprise-wc/assets/1101770/849d130f-73ea-49ba-b065-eb18cd1943f0)

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by tmcconechy** [comment]
1. You mean you cant turn it off once its first turned on correct? I can see why its just removing the attribute here https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-textarea/ids-textarea.ts#L690 needs to remove the label.

2. The string should be added to the translations. Seems hard coded https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-textarea/ids-textarea.ts#L59

**Comment by volante007** [comment]
1. I want it off completely, so it's not turned on explicitly by me before that. Just setting `character-counter="false"` 

2. Oh, right. Yes that was a clear one :)

**Comment by tmcconechy** [comment]
1. if you want it off completely seems like most of them on this page do not have it https://main.wc.design.infor.com/ids-textarea/example.html ? or i guess you want maxlength but no character count and that doesnt work?

**Comment by volante007** [comment]
Yes that's right, maxlength without character counter

**Comment by jbrcna** [comment]
QA PAssed.
<img width="478" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/95a9d024-1334-4360-b976-123be259ab65">
