### ISSUE TITLE
IdsStats: Component broken in Safari (17.1)

### ISSUE THREAD

**Issue by talkaboutdesign** [infor-design/enterprise-wc#1599]
**Describe the bug**
In safari 17.1 Stats component appears broken. 

See below screenshots:

![CleanShot 2023-11-02 at 10 37 55@2x](https://github.com/infor-design/enterprise-wc/assets/2926534/3343dd88-647a-44e1-b741-d38e6ef04d48)

![CleanShot 2023-11-02 at 10 37 58@2x](https://github.com/infor-design/enterprise-wc/assets/2926534/2b34f3a5-1eb9-4998-82d0-41d31e183bfe)

**To Reproduce**

- open https://main.wc.design.infor.com/ids-stats/example.html in safari

**Comment by jbrcna** [comment]
QA Passed
verified in https://main.wc.design.infor.com/ids-stats/example.html
<img width="1660" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/e5655b6f-3b48-467d-9d84-da63c019c202">
