### ISSUE TITLE
IdsDatagrid: Datagrid resizes when selecting in dropdown

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1600]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/editable.html
2. Select a value in dropdown
3. Change row height to XXS
4. Select a value in dropdown
5. See error
6. Notice that when you select a value in dropdown the data grid resizes
7. Check each row height

**Expected behavior**

**Screenshots**
https://github-production-user-asset-6210df.s3.amazonaws.com/56722184/278382893-112e7765-4215-4a77-9f72-f04b6ea9ab9f.mp4

**Platform**
 - Browser Name: Any
 
**Additional context**
related to https://github.com/infor-design/enterprise-wc/issues/1229

**Comment by tmcconechy** [comment]
@jbrcna maybe lets add an issue for the toolbar issue. Thats wierd what its doing in Firefox
