### ISSUE TITLE
IdsDatagrid: dirty indicator remains on the same place row/column after reorder

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1601]
**Describe the bug**
when you try to change the order of the column that has a dirty indicator, the dirty indicator can't be moved.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/editable-inline.html
2. Update a cell to make dirty indicator appear
3. Change column order

**Expected behavior**

**Screenshots**
https://github.com/infor-design/enterprise-wc/assets/56722184/62340448-58ed-4143-a649-c59bb0124be7

**Platform**
 - Browser Name: Any
 
**Additional context**
related to https://github.com/infor-design/enterprise-wc/issues/1229

**Comment by jbrcna** [comment]
QA Failed
verified in https://main.wc.design.infor.com/ids-data-grid/editable-inline.html
dirty indicator of dropdown element is not in proper place after reorder
<img width="699" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b04d45b5-42bc-4b5c-acb4-d1b088f2a1b3">
also, the dirty indicator of the dropdown element is duplicated when changing values
<img width="487" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/4617d50c-64e6-4d9c-a1f0-4d61209a7865">

<img width="710" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/80ba8a7c-02c4-4f8d-be02-c8903a70b776">

when you select a value from the dropdown and click outside, the dropdown value becomes blank
<img width="330" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/9b2bfa9a-c569-41b8-ba47-8400208c7fa8">

**Comment by tmcconechy** [comment]
@jbrcna can you test on localhost (again we have issues deploying latest).

**Comment by jdilag90** [comment]
@jbrcna @tmcconechy 
It's a separate issue since you can replicate it with the dropdown before any column reordering.
That datagrid dropdown bug was there before my changes, but noticed it's being addressed in this PR (https://github.com/infor-design/enterprise-wc/pull/1684)

**Comment by jbrcna** [comment]
> @jbrcna can you test on localhost (again we have issues deploying latest).

the issue also persists in local
<img width="864" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/5c710ce6-9091-48bf-a1df-fce3492b9705">
