### ISSUE TITLE
IdsDatagrid: header  "+" icon is not centered in XXS height

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1603]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/tree-grid-expand-collapse.html
2. Change height to XXS
3. See error
4. Check each row height

**Expected behavior**
should be centered

**Version**
- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1309" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/70752e43-c74c-4dc7-bce9-5329406fb891">

**Additional context**
related to https://github.com/infor-design/enterprise-wc/issues/1229

**Comment by tmcconechy** [comment]
Also could we add a hover state?
