### ISSUE TITLE
IdsInput: mask=number not working as expected

### ISSUE THREAD

**Issue by snelanti** [infor-design/enterprise-wc#1608]
**Describe the bug**
ids-input is accepting letters and special characters even though using mask=number 

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-input/example.html
2. Click on any input field it accepts letters and special characters even though using mask=number

**Expected behavior**
Input field should not accept letters and special characters when mask=number is used.

**Version**
**"ids-enterprise-wc": "^1.0.0-beta.15"**

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/141207120/5fc15357-b0ad-4f9e-a6c8-19b5a9038e3d)

**Platform**
 - Infor Application/Team : ION

**Comment by glenlieorillo** [comment]
This is now working as expected.

https://github.com/infor-design/enterprise-wc/assets/102151352/7193cde7-4ba5-4698-9d44-dec85246da35
