### ISSUE TITLE
IdsPager: Pager dropdown appeared double on the page

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#1610]
**Describe the bug**
Pager dropdown appeared double on the page.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-pager/pager-size-dropdown.html
2. Notice the pager dropdown is duplicated

**Expected behavior**
Page should only have one pager dropdown.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/102151352/91be1cbc-7ef0-4f57-84be-3f9b1a9c1264)

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
This is just to show that it can be added on either side in the example... So its showing the option to put it on either side
