### ISSUE TITLE
IdsDataGrid: The selection check box cannot select/deselect all the records

### ISSUE THREAD

**Issue by Varalaxmi26** [infor-design/enterprise-wc#1612]
1- Load the data grid with some records
2- Go to the last page. The last page contains the records less than the page-size drop-down. (ex: the last page contains 4 records)
3- Go to the first page.
4- Click on the Select all check box. Now observe. Only a few records were selected which were presented on the last page(here 4). Internally The data grid data is not updating with the latest page selection. Other records were not able to be selected.

**Expected behavior**
The selection check box should be able to select and deselect all the records on the current page.

**Screenshots**
![MicrosoftTeams-image (2)](https://github.com/infor-design/enterprise-wc/assets/59650265/24bed7a5-2151-472e-9034-870dbb358bae)

**Comment by tmcconechy** [comment]
We probably need the feature to select across all pages for this to work https://github.com/infor-design/enterprise-wc/issues/1565

Would you be able to add a working example / reduced test case. I'm a bit unclear on these especially number 2.

**Comment by Varalaxmi26** [comment]
> We probably need the feature to select across all pages for this to work #1565
> 
> Would you be able to add a working example / reduced test case. I'm a bit unclear on these especially number 2.

The last page means, here that was the 100th page in the screenshot. The page should contain only four records(the page size is 10). As it is a server-side search every page may not contain the records equal to the page size.

I can reproduce this in the demo example by making some changes. How to give that working example here?

**Comment by tmcconechy** [comment]
Great! You can just put it in the a zip file and upload it here and say; "replace the example xxx with the files in the zip"

Or you could provide a fork or put it in ``` (backticks) if not too big in size

**Comment by tmcconechy** [comment]
Fixed see https://inforwiki.atlassian.net/browse/IDS-4480
