### ISSUE TITLE
IdsDataGrid: Able to enter characters in the page number input when used a data grid along with pagination.

### ISSUE THREAD

**Issue by Varalaxmi26** [infor-design/enterprise-wc#1613]
Able to enter characters in the page number input when used a data grid along with pagination.

**To Reproduce**
1. Go to IdsDatagrid with pagination.
2. Try to enter characters in the page number input box. Able to enter the characters in page number input.
https://main.wc.design.infor.com/ids-data-grid/pagination-server-side.html
**Expected behavior**
<ids-pager-input> should not allow the character.

**Screenshots**
![MicrosoftTeams-image (4)](https://github.com/infor-design/enterprise-wc/assets/59650265/3013c850-d87a-44c5-9dff-834b875c0881)

**Comment by tmcconechy** [comment]
Maybe we add a pager mask option for this so the mask can be used.

**Comment by glenlieorillo** [comment]
QA Passed.


https://github.com/infor-design/enterprise-wc/assets/102151352/501fe01d-56c7-440c-be35-954e6c01576e
