### ISSUE TITLE
IdsDatePicker : Today button is not working properly

### ISSUE THREAD

**Issue by snelanti** [infor-design/enterprise-wc#1614]
**Description**
On  clicking "Today" button in date picker popup,  ids-datepicker is selecting today's date but value in trigger field is not reflecting today's date. Where as in ids-enterprise-ng it is working as expected. 

**To Reproduce**
Please view the below vedio for issue reproduction steps.
https://app.screencast.com/HLbaa1MFiVL8j

1. Go to https://main.wc.design.infor.com/ids-date-picker/example.html
2. Click on calender icon to open date-picker popup
3.Click on Today button in date-picker popup
4. Observe that today's date is being selected but value in trigger field i.e., calendar input field is not reflected.

**Expected behavior**
On  clicking "Today" button in date picker popup,  ids-datepicker should selecting today's date and trigger field value should be updated with today's date

**Version**
ids-enterprise-wc: ^1.0.0-beta.15

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/141207120/7608fb1e-4f37-450d-b330-920a26367990)

**Platform**
 - Infor Application : ION

**Comment by tmcconechy** [comment]
@glenlieorillo its ok that one has a setting on `show-today="true"` is set here on that so thats why

**Comment by glenlieorillo** [comment]
> @glenlieorillo its ok that one has a setting on `show-today="true"` is set here on that so thats why

Thanks for the quick response, @tmcconechy! Will move this to Done.

**Comment by glenlieorillo** [comment]
> @glenlieorillo its ok that one has a setting on `show-today="true"` is set here on that so thats why

Thanks for the quick response, @tmcconechy! Moving this issue to Done.
