### ISSUE TITLE
IdsText - status warning makes the font color green

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise-wc#1619]
`<ids-text status="warning">Lorem Ipsum</ids-text>` makes the font color green instead of yellow/orange because
![image](https://github.com/infor-design/enterprise-wc/assets/11279863/93cadd0f-f88b-47ca-90df-4a1a781531ec)

**Comment by glenlieorillo** [comment]
Passed.

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/f002a37c-0422-4bd3-a3fd-e7a171eea27d)
