### ISSUE TITLE
IdsTooltip: Target binding for hardcoded string? (Support/Angular)

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise-wc#1625]
**Support/Question**
Hi, for `<ids-tooltip>`, I'm wondering why `target="#target"` doesn't work, and has to be a binding like `[target]="'#target'"` or `[attr.target]="'#target'"` (as wc angular sample shows). Do you know why? Binding hardcoded strings always feels wrong :)

**To reproduce**
1. Modify https://github.com/infor-design/enterprise-wc-examples/blob/main/angular-ids-wc/src/app/components/ids-tooltip/demos/example/example.component.html
2. Use `target="#button-1"` instead of `[attr.target]="'#button-1'"` 
3. Tooltip doesn't show up

**Version**
- ids-enterprise-wc: v1.0.0-beta.16

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by jbrcna** [comment]
the tooltip for text field is not in proper place. the arrow should be above and pointing on the field
http://localhost:4300/ids-tooltip/sandbox.html
<img width="782" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/083fc8c3-dd85-49a8-bc68-291c6d013d1b">
