### ISSUE TITLE
IdsTooltip: Better support for IdsListView

### ISSUE THREAD

**Issue by ashachodavarapu** [infor-design/enterprise-wc#1637]
**Description:**
- After adding the tooltip attribute and max-width attribute in HTML for the IDS List view, unable to see the tooltip even if it's reached the max-width.
- Overflow = "ellipsis" is also not applied to the List View after reaching its max-width.

**To Reproduce**
- Add the below code to the IDS List View.
-  Observe tooltip (on hovering) and ellipsis are not applied to the list items.
- Add the below code in this specified path file=> enterprise-wc-examples\angular-ids-wc\src\app\components\ids-list-view\demos\selectable-multiple\selectable-multiple.component.html

```
    <div class="parent-container">
        <ids-list-view
          #listView
          id="demo-lv-selectable-multiple"
          selectable="multiple"
          item-height="76"
          **tooltip="list-View"
          max-width="50"
          overflow="ellipsis"**
          searchable
          (selected)="onMultiListClick()"
        >
        </ids-list-view>
      </div>`
```

**Steps to reproduce the behavior:**
1. Go to the IDS list view and hover over the list items.

**Expected behavior**
- If the tooltip, overflow ("ellipsis"), and max-width attributes are present in the list view, they should be applied to the list items.
- If possible, provide an example in the wc angular code base.

**Version**
- ids-enterprise-wc: "1.0.0-beta.16"

**Comment by tmcconechy** [comment]
@ashachodavarapu for this one did you try to use `ids-text` in the list view to get the overflow. That way we dont have to add all the same settings to listview as well?

We can make an example if needed?

**Comment by ashachodavarapu** [comment]
@tmcconechy I tried with ids-text in the list view item able to see the overflow, But  unable to see the tooltip
If possible please make an example with list view items with overflow and a tooltip in angular 
Thank you

**Comment by jbrcna** [comment]
QA PAssed
verified in https://main.wc.design.infor.com/ids-list-view/tooltip-overflow-ellipses.html
<img width="1027" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/e9aed86a-e2b6-4de7-8651-d510168e6c62">
<img width="902" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/24f82db9-c78b-4ba7-9f22-1dcc6f8cb83c">
