### ISSUE TITLE
IdsText: Using dynamic tooltips

### ISSUE THREAD

**Issue by ashachodavarapu** [infor-design/enterprise-wc#1638]
**Describe the bug**
- Max-width and overflow(ellipsis) attributes are not applied to the IDS text, able to see the full text.
- If the tooltip text is passed dynamically unable to see the tooltip in UI.
**NOTE**:  If the tooltip text is passed statically by using the tooltip attribute it's working fine.

**To Reproduce**
- Add the below code to the IDS text.
- Observe tooltip (on hovering) and ellipsis are not applied to the text when the tooltip text passes dynamically.
- Add the below code in this specified path file=>enterprise-wc-examples\angular-ids-wc\src\app\components\ids-text\demos\example\example.component.html.

```
<ids-text max-width="10" overflow="ellipsis" tooltip="{{selectedItem.message}}" placement="top">{{ selectedItem.message }}</ids-text>
```

**Expected behavior**
- Dynamic text for the tooltip, max width, max height for the IDS text also `line-clamp`
- Pass settings through ids-text to ids-tooltip

**Version**
- ids-enterprise-wc: "1.0.0-beta.16"

**Screenshot**
Observe the below snippet, where max width and overflow are not applied for the IDS text.
![image](https://github.com/infor-design/enterprise-wc/assets/105051938/f932f199-f46a-4c6a-a43b-0124d9428b82)

**Comment by vamsiprathipati** [comment]
Hi @tmcconechy,
Is there any update on this?, I'm also facing the same issue 
Thanks

**Comment by tmcconechy** [comment]
This issue is just getting started to work on @clayinfor can you add anything about the status?

**Comment by jbrcna** [comment]
QA Passed
<img width="1642" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/9fec494c-2bd1-424b-91a1-e5fe4aaa0f66">
