### ISSUE TITLE
IdsTooltip: Placement top does not seem to work

### ISSUE THREAD

**Issue by ashachodavarapu** [infor-design/enterprise-wc#1639]
**Describe the bug**
-  After giving placement="top" attribute for any Ids component by using **ids-tooltip** tag, the tooltip is placed in the wrong position.

**To Reproduce**
- Add the below code to any IDS component (for example text).
- Observe tooltip (on hovering) and ellipsis are not applied to the text.
- Add the below code in this specified path file=> enterprise-wc-examples\angular-ids-wc\src\app\components\ids-text\demos\example\example.component.html

```
<ids-text max-width="10" id="text-1" overflow="ellipsis" placement="top">{{ selectedItem.message }}</ids-text>
<ids-tooltip [attr.target]="'#text-1'" >{{selectedItem.message}}</ids-tooltip>
```

**Expected behavior**
- When placement="top" is given tooltip should displayed on the top.
- If possible, provide an example in the wc/wc angular code base.

**Version**
- ids-enterprise-wc: "1.0.0-beta.16"

**Screenshot**
- Observe the below snippet, the tooltip placement is below the text even though placement="top".
![MicrosoftTeams-image](https://github.com/infor-design/enterprise-wc/assets/105051938/dd329045-8e60-42c2-81e8-fdb2e4ae4b25)

**Comment by tmcconechy** [comment]
One thing to note for this @ashachodavarapu is i dont think you can setup the text ellipsis setting this way. Maybe we need to add a tooltip-placement setting to ids-text. So you dont need the extra ids-tooltip element because it uses its own internally.

Does that make sense? Is the issue more about tooltip in general or getting it to work with ids-text?

**Comment by ashachodavarapu** [comment]
yeah @tmcconechy, It's about tooltip only.
I tried using this manner But it is not working out, that's why I raised it.

**Comment by tmcconechy** [comment]
Ok was wondering because it works ok on https://main.wc.design.infor.com/ids-tooltip/sandbox.html
Just thinking the problem is when combined with ids-text ellipsis option?

**Comment by clayinfor** [comment]
hi @ashachodavarapu ,  looks like you have `placement="top"` on `<ids-text>`. Can you please try moving `placement="top"` to the `<ids-tooltip>` like this:

```html
<ids-text max-width="10" id="text-1" overflow="ellipsis">{{ selectedItem.message }}</ids-text>
<ids-tooltip [attr.target]="'#text-1'" placement="top">{{selectedItem.message}}</ids-tooltip>
```

Or try this which should automatically place the tooltip on top:

```html
<ids-text max-width="10" id="text-1" overflow="ellipsis" tooltip="true">{{ selectedItem.message }}</ids-text>
````

**Comment by clayinfor** [comment]
hi @ashachodavarapu , I've also just submitted a PR that adds support for using `placement` attribute on IdsText element as you request:

```html
<ids-text max-width="10" id="text-1" overflow="ellipsis" tooltip="true" placement="top">{{ selectedItem.message }}</ids-text>
````

**Comment by jbrcna** [comment]
QA Failed
verified in https://main.wc.design.infor.com/ids-tooltip/sandbox.html
<img width="531" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/4f1b3c0b-dac3-4740-9736-9340baf5a078">
<img width="345" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/7af11d28-1f45-4b81-953e-fec770b71e34">
<img width="634" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/4cc4e992-b4a8-4f14-be6f-7b64b8a3a940">

----- 

**Safari**
tooltip right is not aligned in safari
<img width="761" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b2feaf4f-535c-413c-8914-283fb65808ce">

**Comment by tmcconechy** [comment]
@jbrcna lets make a new issue for safari looks like just the right align one.
