### ISSUE TITLE
IdsModal: x icon overlaps text when placed in left

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1647]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-modal/example.html
2. Click on button
3. Check that close button is shown by default for ids-about
4. Run `$('ids-modal').showCloseButton = 'right'`
5. See error

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="495" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/c24ef398-9991-4f6d-ae7e-f0648f5ccaf4">
<img width="328" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/34b13b2b-0fc2-4a21-acfc-e2e1d319f1d8">

**Platform**
all

**Additional context**
related to https://github.com/infor-design/enterprise-wc/issues/1527

**Comment by tmcconechy** [comment]
cc @jdilag in case you want to pick this up for a quick follow up fix

**Comment by jdilag90** [comment]
@tmcconechy the original ticket mentions a setting for "appending it and positioning it"
I can make it so that it appends on the top right corner by default, and top left corner for RTL only?

**Comment by tmcconechy** [comment]
oh sorry i'm not sure what i meant there. I think its usually on the top right.. So thats probably fine. I think i meant a setting to add it and THEN position it :)

**Comment by glenlieorillo** [comment]
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/77254aec-15b0-4b72-8b4e-c56dcd139bf1">

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/66a34ec5-2471-47b1-8f26-6484a936a2ec">
