### ISSUE TITLE
IdsDataGrid: Cant select blank

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1648]
**Describe the bug**

Selecting a blank dropdown option no longer clears it.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/filter-trigger-fields.html
2. Click on '.NotFilteredItem' in the filter row
3. Select a value
4. Open again and select blank -> doesnt work

**Expected behavior**
Blank should "clear" the filter - i think this did work

**Comment by lucacolumbu** [comment]
no able to reproduce
