### ISSUE TITLE
IdsTree: Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1649]
**Describe the bug**
when adding multiple nodes, uncaught range error can be seen in console

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-tree/add-node.html
2. Click on Blog (item/node)
3. Click add node (after selected node)
4. Click the first newly created node
5. Click add node (as children of selected folder)
6. Repeat steps 2 - 5 until you see an error in console
7. Also, try to check each option in adding nodes by adding multiples of it

**Expected behavior**
should have no errors in console

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

![Large GIF (1672x706)](https://github.com/infor-design/enterprise-wc/assets/56722184/5d2b00d6-5e27-4c18-948c-4e3bb9a939f7)

**Platform**
All major browser

**Additional context**
related to https://github.com/infor-design/enterprise-wc/issues/1517#issuecomment-1815571395

**Comment by tmcconechy** [comment]
@jbrcna seem to be having a hard time reproducing this. Can you clarify/simplify the steps? I think its confusing because it alternates between adding a single node and a group of nodes.

But i did steps 2-5 and never got any error

**Comment by jbrcna** [comment]
at first I tried all the available options  inside the dropdown from top to bottom.
<img width="277" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/5cac43f1-c7e1-441a-9cfb-633bc620a9a9">
and then I tried it using only `after selected node` followed by `as children of selected folder`
Steps.
1. click blog item/node
2. use `after selected node`
3. from the newly created nodes. click the first one
4. use `as children of selected folder`
5. click blog item/node again
6. use `after selected node`
7. from the newly created nodes. click the first one
8. use `as children of selected folder`
9. repeat until to see an error in console

`after selected node` is used for blog item/node.
then from the nodes created below 
`as children of selected folder` on first node

**Comment by jbrcna** [comment]
QA Passed
verified in https://main.wc.design.infor.com/ids-tree/add-node.html
<img width="1694" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/ac438d1d-8980-450f-945e-c244a236bf29">
