### ISSUE TITLE
Datagrid: Virtual-scroll height and sticky-header issues when data set to empty-array

### ISSUE THREAD

**Issue by clayinfor** [infor-design/enterprise-wc#1664]
@see [original MS Teams post by Mikolaj](https://teams.microsoft.com/l/message/19:b649a7c426e64e3dbedb0cc5202ce2d4@thread.skype/1701260072055?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1701260072055&teamName=IDS%20Enterprise%20Development&channelName=Web%20Components&createdTime=1701260072055)

To summarize the problem: While virtual-scrolling, the data-grid's header loses stickiness and its height becomes full-screen after setting data to an empty-array, and then repopulating data.

**Describe the bug**
Hi Web Components, I am facing issues with data grid when using virtual scroll feature. I have enterprise-wc-examples repository locally. 

I have simple code that is loading data into grid component. It should render cells with "First data fetch" text, after 5 seconds it should render cells with "Second data fetch" text, after next 5 second it should render empty data grid and finally after next 5 seconds it should render cells with "Third data fetch" text. When using virtual scroll feature something goes wrong after setting grid data to empty array. If we set data again then column header that was always sticky to the top and visible disappears as we scroll. Additionally the grid fills the entire height of the page even though I set the height to 500px. Without setting virtual-scroll to "true" in HTML code everything works fine. I plan to use this component for a large dataset, so this virtual scroll feature is important to me. I pasted code below. I will try to provide a video in the comment.
Html code: 
```html
<div style="height: 500px; width: 100%; ">
    <ids-data-grid #dataGrid id="idsDataGridTest"
                   auto-fit="true"
                   list-style="true"
                   virtual-scroll="true"
                   row-height="xs">
    </ids-data-grid>
</div>
```
 

Component code: 
```typescript
export class ExampleComponent implements AfterViewInit {
    @ViewChild('dataGrid', {read: ElementRef}) dataGrid;
    public columns = [];
    ngAfterViewInit(): void {
        this.dataGrid.nativeElement.columns = [{
            id: 'value',
            name: 'value',
            field: 'value',
            formatter: this.dataGrid.nativeElement.formatters.text,
            filterType: this.dataGrid.nativeElement.filters.text
        }];
        this.dataGrid.nativeElement.data = [...Array.from(Array(100).keys()).map((x) => ({value: `First data fetch value: ${x}`}))];
        setTimeout(() => {
            this.dataGrid.nativeElement.data = [...Array.from(Array(100).keys()).map((x) => ({value: `Second data fetch value: ${x}`}))];
        }, 5000)
        setTimeout(() => {
            this.dataGrid.nativeElement.data = [];
        }, 10000)
        setTimeout(() => {
            this.dataGrid.nativeElement.data = [...Array.from(Array(100).keys()).map((x) => ({value: `Third data fetch value: ${x}`}))];
        }, 15000)
    }
}
```

**To Reproduce**

Steps to reproduce the behavior (see screen recording):

https://github.com/infor-design/enterprise-wc/assets/93789065/bc9413f0-e370-4f1d-a159-8635f3605bfc

**Expected behavior**

https://github.com/infor-design/enterprise-wc/assets/93789065/f9a9e141-a344-4751-867a-4ea16d0f7d37

**Comment by clayinfor** [comment]
This is problem is likely related to the `IdsDataGrid.redraw()` nuking and then regenerating HTML for the data-grid header and the body.

**Comment by clayinfor** [comment]
Btw if you try to add more columns to have scroll at the bottom of the page without virtual-scroll attribute set to true everything is fine 
![MicrosoftTeams-image](https://github.com/infor-design/enterprise-wc/assets/93789065/9240fb4b-2fbe-497a-a0ca-94b18b8839bf)


this horizontal scrollbar is at the end of the grid, so it is impossible to scroll to the right without going to the end of the page

![MicrosoftTeams-image (1)](https://github.com/infor-design/enterprise-wc/assets/93789065/e9099bd1-9674-474e-898d-04e54ecc9ba2)

**Comment by jdilag90** [comment]
I think the problem happens here. You can try removing that line in your example to test.
https://github.com/infor-design/enterprise-wc/blob/349398009a9e081244c44d3c82044ad13442cb52/src/components/ids-data-grid/ids-data-grid-empty-message.ts#L115

When the data is set to an empty array, the 100% height applied by auto-fit is removed and is never set back to 100% after the datagrid is populated again. It probably looks like the datagrid lost its sticky header because it's the datagrid's parent container that handles the overflow scroll and not the datagrid

**Comment by jbrcna** [comment]
QA Passed
![Large GIF (1292x758)](https://github.com/infor-design/enterprise-wc/assets/56722184/7d96d2c3-2260-4aaf-83ba-c2cc41670cca)
