### ISSUE TITLE
IdsSlider: Cant set value with JS

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#1667]
**Describe the bug**
Trying to change slider value on demo page changes the value attribute but does not change the element visually (stays on 0 value).

**To Reproduce**
Open: https://main.wc.design.infor.com/ids-slider/example.html
Focus the first slider element on dev tools and run: `$0.setAttribute('value', 50);`

**Expected behavior**
Set the value on the field moving slider from 0 to 50.

**Version**
Latest

**Screenshots**
![Screen Shot 2023-11-29 at 12 10 04 PM](https://github.com/infor-design/enterprise-wc/assets/663908/e32c4a0b-aa40-43e6-9d2d-fe1ecc942126)

![Screen Shot 2023-11-29 at 12 10 21 PM](https://github.com/infor-design/enterprise-wc/assets/663908/dff7f8d1-940a-4c8b-b6c4-89e14e322598)

**Platform**
- Chrome on Mac OS

**Comment by tmcconechy** [comment]
Note that `$0` was not returning the right element for me but this bug is valid. Because none of these work

1. Setting value in the dom in dev tools
2. `$('ids-slider').value = 50`
3.  `$('ids-slider').setAttribute('value', 50)`

**Comment by jbrcna** [comment]
QA Passed
verified in https://main.wc.design.infor.com/ids-slider/example.html
`$('ids-slider').setAttribute('value', 50)`
<img width="1592" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/4aeb649e-e505-43ae-a958-f00cdaf38833">

`$('ids-slider').value = 20`
<img width="1521" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/4250486f-994b-4b59-82e0-a79c0e01539e">

`$('ids-slider').value = 30`
<img width="1478" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/a40bed84-4b6d-42da-af7f-fe8c74bb8743">
