### ISSUE TITLE
IdsDataGrid: Column header filter button aligns to the wrong place in RTL

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#1669]
**Describe the issue:**
This is a follow-up issue to #1575.  The original fix described in that issue and corresponding PR has been applied. However, if you change to RTL (use he-IL or ar-EG locales) it doesn't change its position like the other filters:

**Expected solution**
Need to fix the alignment rule for `dir='rtl'`, or better yet fix with logical properties unaffected by RTL if possible

**Screenshots:**
![image](https://github.com/infor-design/enterprise-wc/assets/102151352/e8990438-90e2-4960-b308-e2d0a2d3dd03)

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/97207e8e-7bbf-48f2-a6a0-98245449e4fb)

**Additional Context:**
_Originally posted by @glenlieorillo in https://github.com/infor-design/enterprise-wc/issues/1575#issuecomment-1814310784_

**Comment by glenlieorillo** [comment]
The bug has been fixed. However, the drag icon under `Units` column is still on the left side in RTL.


https://github.com/infor-design/enterprise-wc/assets/102151352/c85c61c1-f231-429c-ad77-d556cfb53150

**Comment by ericangeles** [comment]
@tmcconechy can we move this to WC project board?

**Comment by tmcconechy** [comment]
@ericangeles yes feel free anytime to move any issues if they are wrong
@glenlieorillo sounds like a new issue and Ed is gone now. Can you make a new issue for that last point? Thanks!

**Comment by glenlieorillo** [comment]
Hello @tmcconechy, I have created a new issue for the bug found. [1811](https://github.com/infor-design/enterprise-wc/issues/1811)
