### ISSUE TITLE
IdsPie: Unable to hide legend + unable use legend-placement attribute

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise-wc#1672]
**Describe the bug**
Two issues related to IdsPie (in my case, used as donut)

1. There doesn't seem to be a way to hide the legend, which was possible in 4.x using the `showLegend` option. In a 1x1 widget, it might make sense to hide it.
2. Can't set legend placement using the attribute, unless binding it (Angular, similar to https://github.com/infor-design/enterprise-wc/issues/1625)
```
<!-- Doesn't work -->
<ids-pie-chart legend-placement="bottom"></ids-pie-chart>

<!-- Works -->
<ids-pie-chart [attr.legend-placement]="'bottom'"></ids-pie-chart>
<ids-pie-chart [legendPlacement]="'bottom'"></ids-pie-chart>
```

The second might be a generic problem in many components when used with Angular, but not sure how to best verify/catch them all?

**Comment by jbrcna** [comment]
QA Passed
<img width="1269" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/f8d74429-7f82-4888-a08c-66fcdcb6045d">
<img width="609" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b8629800-1d43-4fe1-9ec9-cca1a08ac66f">
<img width="532" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/a8d7bae6-7b1b-4863-8559-6af596a62c99">
<img width="616" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/1510ec74-f238-4c8d-9ce7-2cbd1ecd5ba7">
<img width="721" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/bcec7eb1-c717-4e7f-8958-4a5fc34c6692">
