### ISSUE TITLE
IdsActionPanel: Add autoFocus setting to actionPanel/modal

### ISSUE THREAD

**Issue by ajayponnapati** [infor-design/enterprise-wc#1675]
**Describe the bug**
Add a setting to select the focus element on a modal by a selector or select none. Currently seems like the last element is focused. In my use case I want to remove focus.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-action-panel/example.html
2. Open panel
3. Notice the checkbox is mysteriously focused -> would like none or first selected

**Expected behavior**
Want no focus in this situation when loading action panel.

**Platform**
 - Browser Name: All

**Additional context**
- Started in Ms Teams chat
- I have tried getting the reference of the component and applying elementRef.focus = false.But it didnt help.

**Comment by EdwardCoyle** [comment]
Whoever picks this one up should check the [Focus Capture Mixin](https://github.com/infor-design/enterprise-wc/blob/main/src/mixins/ids-focus-capture-mixin/ids-focus-capture-mixin.ts#L157-L174) to see if the code that targets elements on the page is working correctly -- seems like it should already be focused on the first element but currently is not doing so.

Additionally, this would be the place to add an option to *not* focus.

**Comment by jbrcna** [comment]
QA Passed
https://main.wc.design.infor.com/ids-modal/focus.html
<img width="1255" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/d124fd31-e8e5-462a-ab20-fd724c06303f">

<img width="1297" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/088162ec-4513-4aeb-943a-2482c0da7d14">

https://main.wc.design.infor.com/ids-action-panel/example.html
<img width="820" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/6c77c947-4821-4816-9847-72b21a8a2d6b">
