### ISSUE TITLE
IdsAxisChart/IdsBarChart: Console error when using "inherit" as width/height value

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise-wc#1676]
**Describe the bug**
In a widget, the chart should take as much space as possible, i.e. full size of its parent. We can't set numeric widths and heights, as a widget might be resized in runtime. The bar chart / axis chart does not seem to default to using the size of its parent. The default size, if omitting height/width, is very large. 

I saw that a sample used `width="inherit" height="inherit"` which seemed promising. It works fine, but I see the following error in console
```
Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
    at Xj.lD (main.js:33038:8857)
    at set width [as width] (main.js:33038:2722)
    at Xj.attributeChangedCallback (main.js:51:118345) <---
    at l.invoke (polyfills.js:29:8641)
    at Dt.runGuarded (polyfills.js:29:4099)
    at Xj.attributeChangedCallback (polyfills.js:29:3872)
    at l.invoke (polyfills.js:29:8641)
    at Dt.runGuarded (polyfills.js:29:4099)
    at Xj.attributeChangedCallback (polyfills.js:29:3872)
    at fe.setAttribute (chunk-L2PDWX23.js:1:8945)
```
```
     this.#r?.disconnect(),
        this.#r ??= new ResizeObserver(Vi(e=>{
            let t = e[0].contentRect
              , i = this.resizeToParentWidth ? t.width : this.width
              , r = this.resizeToParentHeight ? this.svg.getBoundingClientRect().height : this.height;
            this.resize(i, r)
        }
        , Cz)),
        this.#r.observe(this.chartContainer) <--- this.chartContainer is null initially
```

**To Reproduce**
The sample I saw is no longer using `inherit` as value, because it was reverted to fix some tests? Maybe same errors were seen?
https://github.com/infor-design/enterprise-wc/commit/221491e9ae92d97fda7c0d227dcef615bfeb37bc

Should be able to see it with just 
```
<ids-bar-chart width="inherit" height="inherit"></ids-bar-chart>
```
Inside some parent

**Expected behavior**
Able to use `inherit` as width and height, without initial console errors. Or, if the chart fits inside its parent as default behavior (as pie/donut?)

**Version**
- ids-enterprise-wc: 1.0.0-beta.17

**Platform**
 - Infor Application/Team Name: OS Portal

**Additional context**
Setting the width and height to "inherit" on the element in JavaScript does not result in same errors.

**Comment by tmcconechy** [comment]
Yes it should be `inherit` i change the example to fixed sizes because of bugs / and with a fixed widget that made more sense. But should have added an inherit example back., will add it and see about the error.

This was a recent fix. I thought inherit would still work

**Comment by tmcconechy** [comment]
@volante007 i readded the example with responsive back and put the widgets on their own example. But i could not see the error on the ResizeObserver. Any idea how you saw it?

See: https://github.com/infor-design/enterprise-wc/pull/1688

**Comment by jbrcna** [comment]
this is working as expected. However, in RTL the text is cut off
verified in https://main.wc.design.infor.com/ids-axis-chart/responsive.html
https://main.wc.design.infor.com/ids-axis-chart/in-widget.html
<img width="1716" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/98edcbbe-674e-4292-8127-aa64d9fd57a2">
<img width="1524" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/1119795a-3bf3-4dc6-8ad8-52ecb27b5521">

<img width="1239" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/f2e5a672-d30b-4117-8034-22e76e2f7ff5">

**Comment by tmcconechy** [comment]
ok thanks @jbrcna lets make a new issue for that one
