### ISSUE TITLE
IdsModuleNav: Add settings for external users

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#1677]
**Is your feature request related to a problem or use case? Please describe.**
We need to add a couple settings to IdsModuleNav for external user Landmark cases.  This issue mimics infor-design/enterprise#8232

**Describe the solution you'd like**
1. A setting to disable and hide the module switcher, for scenarios that do not have any modules to switch among
2. A setting to relocate the user profile information in the top part of the nav to the bottom of the nav (see design reference below)

Design reference is here: https://www.figma.com/file/kibzUkQhlNArg0P4PvvpME/Module-Nav%3A-Standalone?type=design&node-id=0-1&mode=design&t=47WmlX6ZqvPenn3v-0

**Comment by tmcconechy** [comment]
Looks good.I only see two wierd things tho

1. Maybe disable dirty indicator from "Display Mode" at tripped me up when you expand it to becomes dirty but its disabled
2. At this size:

<img width="253" alt="Screenshot 2024-01-10 at 9 56 50 AM" src="https://github.com/infor-design/enterprise-wc/assets/814283/c78e733f-2d9f-4108-b173-e804a9f2efac">

Everything is sitting on top of each other:
<img width="830" alt="Screenshot 2024-01-10 at 9 56 36 AM" src="https://github.com/infor-design/enterprise-wc/assets/814283/a58ecd71-b047-479b-ac01-c4bc9f294f25">

**Comment by jbrcna** [comment]
QA Failed
when Enable Responsive (Mobile) Behavior is checked, and resize to responsive, the text were overlapping
<img width="639" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/637cf77b-619e-4d04-b115-c83983388129">

**Comment by tmcconechy** [comment]
@jbrcna i think this was fixed on a later PR lets watch main and raise it a little later after all PR's are merged

**Comment by jbrcna** [comment]
working as expected. thanks
<img width="913" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/8cee5469-9b2b-4a41-8d42-74dab967432d">
<img width="897" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b81c8def-9113-40fc-a00b-5639b2f484c6">
<img width="561" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/93635376-6b52-422b-8e46-413d8e93cd08">
