### ISSUE TITLE
IdsSpinbox: Values lower/higher than the min/max values can be entered with the keyboard

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise-wc#1678]
**Describe the bug**
The min/max values are correctly enforced when decreasing/increasing the value using the - and + buttons, but values lower/higher than those can still be entered with the keyboard.

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-spinbox/example.html
2. Select one of the spinboxes that have min/max values and enter a number lower/higher than them with the keyboard
3. Click anywhere outside of the spinbox
4. The value isn't changed to the min/max value which is the behavior in the jQuery and Angular components.

**Expected behavior**
I guess it should preferably not be possible to enter a value lower/higher than the min/max values in the first place, but the value should at least be changed to the min/max value when focus is lost in the spinbox.

**Version**
`ids-enterprise-wc: 1.0.0-beta.17`

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by tmcconechy** [comment]
Agreed should revert the value to the closest value (min / max) when tabbing out.

**Comment by glenlieorillo** [comment]
This has been tested and passed.

https://github.com/infor-design/enterprise-wc/assets/102151352/0cab83ec-4702-4098-8895-e9ad8612a5ee
