### ISSUE TITLE
IdsDropdown: Page scrolls when opening

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1681]
**Describe the bug**
In ids-dropdown the page moves when you open and select. Maybe only an issue when the page is bigger with a lot of contents but still valid

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-personalize/example.html
2. Go down to the dropdown
3. Open it -> see page scrolls
4. Select values -> see page scrolls

**Comment by tmcconechy** [comment]
Maybe check https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior if it can fix it?

**Comment by glenlieorillo** [comment]
This has been tested and passed.

https://github.com/infor-design/enterprise-wc/assets/102151352/0cdaf761-c759-4ccc-9e49-ab1e0dd974ad
