### ISSUE TITLE
IdsTree: Not able to set label attribute

### ISSUE THREAD

**Issue by ajayponnapati** [infor-design/enterprise-wc#1683]
**Is your feature request related to a problem or use case? Please describe.**
For ids-tree, label attribute is not being set for ultimate child nodes.For parent nodes we can set the label using label='somename'.but for child when we do the same its not working as expected.

In the below example .Child1 is not visible but Child2 is visible

code :

![image](https://github.com/infor-design/enterprise-wc/assets/144166021/dda71130-b6c0-4a4d-afe7-081529a0452f)

on UI:

![image](https://github.com/infor-design/enterprise-wc/assets/144166021/7efc3df3-1017-4183-88f8-17be0c354a46)

**Describe the solution you'd like**
Label works correctly?

**Comment by tmcconechy** [comment]
@ajayponnapati can you clarify the issue? 

a) Can you attach the source code? (not a screen shot of code)
b) Where do we put it it / how do we run it? I think this was an angular problem?
c) Basically clarify the steps

**Comment by ajayponnapati** [comment]
Code --

<ids-tree  label="Tree with Markup only">
  <ids-tree-node id="tm-leadership" label="Parent">
    <ids-tree-node id="tm-leadership-2" label="Child1"></ids-tree-node>
    <ids-tree-node id="tm-history" disabled="true">Child2</ids-tree-node>
  </ids-tree-node>
</ids-tree>

you can place the above code in https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-tree/demos/sandbox.html and check it

**Comment by tmcconechy** [comment]
Got it. Strange as thats very similar to the example we have
