### ISSUE TITLE
IdsDatagrid: Make datagrid composable with its individual elements

### ISSUE THREAD

**Issue by bartlomiej-k** [infor-design/enterprise-wc#1691]
**Describe the bug**
When a component used as a formatter or editor component of a column contains a soho-checkbox, this checkbox cannot be checked/unchecked from the UI. From user perspective, it looks like the cell intercepts the click and doesn't propagate it to the checkbox, even though the cursor changes its style to pointer only when hovering over the checkbox.

Our use case is to display up to 10 columns containing checkboxes that act as true/false flags of edited objects, so trying to configure checkbox columns like they were 'select row' checkboxes is not a solution for us.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1701-7vtkax
2. Click on any cell in _Editor checkbox_ column to open editor component.
3. Click checkbox.
4. Observe checkbox doesn't change its value.
5. Click any other cell or press enter to get out of the edit cell mode.
6. Click on any checkbox in _Formatter checkbox_ column.
7. Observe checkbox doesn't change its value.

**Expected behavior**
Checkbox changes its value, just like it does in the same component placed below the datagrid.

**Version**
- ids-enterprise-ng: v17.0.1

**Platform**
 - Infor Application/Team Name: Infor WFM

**Comment by bartlomiej-k** [comment]
As long as it's just importing the component and not recreating it using stylesheets extracted in a tricky way, it's fine. All in all, using a web component always requires importing it. 

Thanks for converting the issue, it's more about the web components now.

**Comment by inforandy** [comment]
Hi @bartlomiej-k,

Looking to understand the original use case better on our side and what the team is ultimately trying to build. Would you or someone on the WFM team be able to reach out to me andrew.kopas@infor.com to set up a quick chat to dive in here? 

Thanks!

**Comment by tmcconechy** [comment]
Comments From Grooming:

Thinking of this another way. What if we just made angular components work in a cell. And added an example of 10 checkboxes in a custom editor (both JS and Angular)?

The problem here is that you would have to add all the code to make this all work (keyboard/selection/editing).
 
We will setup a call and discuss further. Cc @inforandy

**Comment by tmcconechy** [comment]
@bartlomiej-k we looked at this in the grooming again. As a "workaround" couldn't you setup a simple data set and use the grid the normal way. That way you get all the functionality you need.

Suggestion for now...

**Comment by bartlomiej-k** [comment]
I'm not sure I understand this workaround. How would it make our components work if we cannot put them inside the datagrid? We don't need any grid functionalities - we don't need selection, editing, sorting or anything like that. We need functionalities of our components. The only thing we need the datagrid for is the styling - that the data is presented in a table, the table has headers with a given font style and background color, all cells have some paddings and borders defined, rows are scrollable if they do not fit into the container. That's all.

Our current workaround is a custom "datagrid" that provides exactly these things - a way to display some components in a tabular way with a predefined styling and no additional functionalities. We plan to replace this thing with a "styling-only" version of the datagrid once it's created.

**Comment by tmcconechy** [comment]
We did the css only version https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/demos/standalone-css.html#L11 but it doesnt use web components. I guess we could do that but i was afraid of the effort worth value.

Also the part in here about the checkbox in stackblitz was confusing as it looks like that is functionality there on the checkbox we would have to make work.

Will continue to see if this is viable.. What about if we had an angular component formatter so you could use an angular formatter in the normal grid?

**Comment by tmcconechy** [comment]
Descoping this one. I dont see a way we can do this without introducing additional problems and increased performance.
