### ISSUE TITLE
IdsTabs: Text alignment looks off

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#1696]
**Describe the bug**
Text alignment looks off.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-tabs/app-example.html
2. Click on Plus sign to add tabs
3. Click on 'More' dropdown button
4. Notice the text alignment

**Expected behavior**
Text should be aligned accordingly.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/102151352/a277dd56-d5b8-43e3-be88-7ebfe5b2565d)

**Platform**
 - All major browsers

**Additional context**

**Comment by tmcconechy** [comment]
Fix a fix

1. Should the x be on the right?
2. Use normal menu padding
3. Make sure menu isnt off the page on the right
4. Try RTL

**Comment by EdwardCoyle** [comment]
FYI this requires a slight enhancement to IdsMenuItem's structure, which doesn't currently allow IdsIcons or interaction-driven on the "right" or "end".

**Comment by jbrcna** [comment]
this is now working as expected. However, in Firefox browser, theme switcher button is visible in popup
verified in https://main.wc.design.infor.com/ids-tabs/module.html
<img width="755" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/af87e842-f0a7-4f11-a0f3-5cb60735c890">

firefox
<img width="414" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/861f3cda-f5a9-4a8b-853e-d9760ec43435">

**Comment by tmcconechy** [comment]
Lets make a new minor issue. Will have to switch back to that later. Its just the overflow ellipsis text

**Comment by jbrcna** [comment]
moving to done. new issue has been created https://github.com/infor-design/enterprise-wc/issues/1754
