### ISSUE TITLE
IdsPopupMenu: Cannot make IdsTriggerField use an IdsPopupMenu

### ISSUE THREAD

**Issue by sowmyaNelanti** [infor-design/enterprise-wc#1697]
**Is your feature request related to a problem or use case? Please describe.**
ids-popup-menu in combination with ids-trigger-field
I am triggering ids-popup menu for click event of an icon in input trigger field. But ids-popup menu is opening even if I click anywhere in a page.

**Describe the solution you'd like**
1. Please use the below code to reproduce the issue
```
<ids-trigger-field
  size="mm"
  label="Date Field"
  field-height="md"
  aria-haspopup="menu"
>
  <ids-trigger-button slot="trigger-end">
    <ids-text audible="true">Activation Date</ids-text>
    <ids-icon id="trigger-field" icon="schedule"></ids-icon>
  </ids-trigger-button>
</ids-trigger-field>
<ids-popup-menu
  class="popupmenu-position"
  id="my-menu"
  align="bottom, left"
  target="trigger-field"
  trigger-type="click"
  role="none"
>
  <ids-menu-group role="group">
    <ids-menu-item id="item-one"
    >Last hours
    </ids-menu-item>
    <ids-menu-item id="item-one"
    >Last days
    </ids-menu-item>
  </ids-menu-group>
</ids-popup-menu>
```

2. After running the project go to the component page where this code is placed and try to click anywhere in the screen the pop up menu is opening which is not expected. popup should be opened only when clicked on the icon in trigger-field

**Additional context**
"ids-enterprise-wc": "^1.0.0-beta.17"

**Comment by jbrcna** [comment]
QA Passed
<img width="1590" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/5268d05b-8316-46fe-b082-5fade9db6011">
