### ISSUE TITLE
Ids-Tabs: Selected attribute not working

### ISSUE THREAD

**Issue by ajayponnapati** [infor-design/enterprise-wc#1705]
**Describe the bug**
Selected attribute to ids-tab is not working.When we add selected=true to a tab, it is not being selected.Code is shared below.

**To Reproduce**
Use the below code to reproduce the bug.In the below code selected="true" for Opportunities tab, But when you run it we see other tab as selected.
```html
<ids-tabs-context>
  <ids-tabs >
    <ids-tab value="contracts">Contracts</ids-tab>
    <ids-tab value="opportunities" selected="true">Opportunities</ids-tab>
    <ids-tab value="attachments">Attachments</ids-tab>
    <ids-tab value="notes">Notes</ids-tab>
  </ids-tabs>
</ids-tabs-context>
``` 

1. Go to https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-tabs/demos/side-by-side.html
2.Place the shared code in the above file and run
3. You will see **Notes** tab selected.But **Opportunities** should be selected

**Expected behavior**
The tab which has the attribute selected to true should be selected(should be highlighted).

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/144166021/8f4aa1ef-0197-4818-9447-5bf75be6a5c7)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by jbrcna** [comment]
QA Passed
verified in https://main.wc.design.infor.com/ids-tabs/selected.html
<img width="1697" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/0e5fea2c-68ab-419a-9aad-fa6930e3f107">

**Comment by tmcconechy** [comment]
Reopening because moving the selected to a different tab doesnt seem to work.
