### ISSUE TITLE
IdsMultiselect: List items position not retained after deselection

### ISSUE THREAD

**Issue by sowmyaNelanti** [infor-design/enterprise-wc#1709]
**Description**
I am using ids-multiselect with "ngFor"
Please observe the items position in multiselect dropdown before selecting any option (default items position)
After selecting the items and closing and re-opening the dropdown list, the selected options are moved at the top (which is expected behavior).
Deselect the options now , close and re-open the dropdown and observe the list items position it is not retained >> It is an issue.

**To Reproduce**
1. Run the application in local using code base from  https://github.com/infor-design/enterprise-wc-examples
2. Go to ids-multiselect >> example 
click on dropdown list under "Test Multiselect (using ngFor) " label
3. Observe the order of items (Alaska, Maine, Montana) in the list and then Select Alaska, Montana and click anywhere on the screen so that dropdown list is closed.
4. Now re-open the dropdown list and it is observed that Alaska and Montana are moved into selected area of dropdown
5. Now deselect Alaska and Montana. Close the dropdown list
6. Re-open the dropdown and observe that the positions of list items are not retained(Alaska, Montana, Maine) (ideally items order should be same as first time clicking multiselect like Alaska, Maine, Montana)
NOTE: This issue is observed only on using ngFor and works expected when used static list items.

Please observe below vedio which is created using code base from "angular-ids-wc" in  
https://github.com/infor-design/enterprise-wc-examples

**Expected behavior**
The order of items in the list should be retained after deselecting and we probably have to more differentiate on the top section than the old version.

**Version**
 ids-enterprise: beta.17

**Screenshots**
Below is the image of default dropdown list
![image](https://github.com/infor-design/enterprise-wc/assets/41888743/e3874816-b913-4342-bb95-3d2772cd84f4)
Below is the image of dropdown list after selecting and deselecting the options
![image](https://github.com/infor-design/enterprise-wc/assets/41888743/71886957-9d6b-4757-970f-085c381aa853)

**Comment by jbrcna** [comment]
QA Passed

<img width="365" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/f589d6aa-26d2-4615-a480-70c0f500e49a">

<img width="479" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/29bb55e7-6c39-4172-bd2b-743c14867547">
<img width="345" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/af83d745-31f6-4fe6-aeb0-3fd3bc9ec048">
