### ISSUE TITLE
IdsTree: after adding child node, with IdsTree#addNodes, clicking on a child node failes and causes a javascript error

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#1713]
**Describe the bug**
after adding child node, with IdsTree#addNodes, clicking on a child node failes and causes a javascript error

**To Reproduce**

1. Go to http://localhost:4300/ids-tree/add-node.html
2. select first tree node ("Home")
3. click Add Node > As children of selected folder
4. click on "New Node" under "Home"
5. See error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'elem')
    at handleClick (ids-tree.ts:1118:17)
    at HTMLUListElement.eval (ids-tree.ts:1196:7)
handleClick @ ids-tree.ts:1118
eval @ ids-tree.ts:1196
```

**Expected behavior**
Should not throw error and should get selected events. 

**Version**

- ids-enterprise-wc: main branch

**Screenshots**

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: latest

**Comment by tmcconechy** [comment]
@pwpatton i retried after all of the tree fixes got merge and its fixed along with recent changes on main now.

- `git checkout main && git pull`
- `npm i && npm run start`
- Repeat above steps
