### ISSUE TITLE
Set Column Editor Dropdown Options From Server

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#1714]
**Describe the bug**
Trying to set options from the server to a column editor type drop down, but after set options, when try to change the value, it set the cell to empty and the dropdown option is not selected:
![Screen Shot 2023-12-20 at 4 32 42 PM](https://github.com/infor-design/enterprise-wc/assets/663908/b93d7536-8ba3-40e9-8596-9c58420cda41)

**To Reproduce**
Create an example with the code bellow:
```html
<ids-data-grid id="data-grid-1" editable=true row-selection="single"></ids-data-grid>
```

```javascript
window.addEventListener('load', function() {
  var dataGrid = document.querySelector('#data-grid-1'),
    columns = [{
      id: 'id',
      name: 'ID',
      field: 'id',
      editor: {
        type: 'input',
        editorSettings: {
          autoselect: true,
          dirtyTracker: true
        }
      }
    },{
      id: 'name',
      name: 'Name',
      field: 'name',
      editor: {
        type: 'input',
        editorSettings: {
          autoselect: true,
          dirtyTracker: true
        }
      }
    },{
      id: 'isAdmin',
      name: 'Is Admin',
      field: 'isAdmin',
      formatter: dataGrid.formatters.checkbox,
      editor: {
        type: 'checkbox',
        editorSettings: {
          autoselect: true,
          dirtyTracker: true
        }
      }
    },{
      id: 'role',
      name: 'Role',
      field: 'role',
      // formatter: dataGrid.formatters.dropdown,
      editor: {
        type: 'dropdown',
        editorSettings: {
          autoselect: true,
          dirtyTracker: true,
          // options: [{
          //   value: 'Administration',
          //   label: 'Administration'
          // },{
          //   value: 'Manager',
          //   label: 'Manager'
          // },{
          //   value: 'Developer',
          //   label: 'Developer'
          // }]
        }
      }
    },{
      id: 'date',
      name: 'Date',
      field: 'date',
      editor: {
        type: 'datepicker',
        editorSettings: {
          autoselect: true,
          dirtyTracker: true
        }
      }
    }],
    gridData = [{
      id: 1,
      name: 'User 1',
      isAdmin: true,
      date: '05-11-2022',
      role: 'Administration'
    },{
      id: 2,
      name: 'User 2',
      isAdmin: false,
      date: '06-11-2022',
      role: 'Manager'
    },{
      id: 3,
      name: 'User 3',
      isAdmin: true,
      date: '07-11-2022',
      role: 'Developer'
    }];

  dataGrid.data = gridData;
  dataGrid.columns = columns;

  // set options later simulating options comming from server
  dataGrid.columns[3].editor.editorSettings.options = [{
    value: 'Administration',
    label: 'Administration'
  },{
    value: 'Manager',
    label: 'Manager'
  },{
    value: 'Developer',
    label: 'Developer'
  }];

  // set formatter later to be able to render the value in the cell correctly
  dataGrid.columns[3].formatter = dataGrid.formatters.dropdown;
});
```

1. Click on any cell of the Role column to edit;
2. The cell content disappears and the dropdown value(option) is not set

**Expected behavior**
Keep the cell with the content and set the correspondent value in the dropdown.

**Version**
- 1.0.0 Beta 16

**Screenshots**
![Screen Shot 2023-12-20 at 4 32 42 PM](https://github.com/infor-design/enterprise-wc/assets/663908/c2b3dcfd-8de7-411f-8176-f7984d8cf3b1)

**Platform**
 - Macbook
 - OS Version: Mac OS Catalina
 - Browser Name: Chrome

**Comment by tmcconechy** [comment]
Strange. It looks like the values in the initial data are'nt matching but they seem to be. you can select after you pick them once. Something must not be right in this way of doing it. Will plan this for next sprint and take a deeper look

**Comment by fabiojpoli** [comment]
Reghie found this (if helps):
"Regarding this issue "When clicking on cell with combo the value disappears" upon further investigating. I Was brought to this area where the value disappears. I was not able to solve it yet since i was not that familiar with it. Hoping this image can provide clue with the issue."

![image](https://github.com/infor-design/enterprise-wc/assets/663908/9225055b-33d9-4998-9b59-c0a87e277e51)
