### ISSUE TITLE
Tabs: ids-tabs-context is not part of the bundle

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#1718]
**Describe the bug**
When the library bundle is imported (rather than individual components), the Tabs component does not work.

Eg:
```ts
import "ids-enterprise-ng";
```

or

```html
<script type="module" src="url/to/ids-enterprise-wc/enterprise-wc.js"></script>
```

**To Reproduce**

1. Go to https://stackblitz.com/edit/web-platform-p62rez?file=index.html
2. See the tabs in the Preview frame
3. The contents from all tabs are rendered, and clicking the tab headers does nothing.

**Expected behavior**
Tabs should work.

**Version**

- ids-enterprise: 1.0.0-beta.17

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/4991954/4ca82c9c-5f98-4ab4-ac0b-f91885d7eb9c

**Additional context**
Explicitly importing `ids-enterprise-wc/components/ids-tabs/ids-tabs-context.js` works around the problem.

**However, this causes another issue**. The first tab cannot be selected:
https://stackblitz.com/edit/web-platform-p62rez?file=workaround-but-buggy.html

https://github.com/infor-design/enterprise-wc/assets/4991954/6bf67f64-9206-4b26-86aa-6a2e6dcbc2b2

**Comment by tmcconechy** [comment]
As part of this lets fix the NG example http://localhost:4200/ids-tabs its also not working
