### ISSUE TITLE
Charts: An error is logged with inherited with/height

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#1719]
**Describe the bug**
The charts components (all of them? at least `<ids-bar-chart>`) with `width="inherit"` and/or `height="inherit"` throw an error

**To Reproduce**

1. Go to https://stackblitz.com/edit/web-platform-l6qeaj?file=index.html
2. Open the dev tools console
3. See error:

```
Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
```

**Expected behavior**
No errors are thrown

**Version**

- ids-enterprise: 1.0.0-beta.17

**Platform**
 - Infor Application/Team Name: Portal
 - Browser Name: chrome, safari

**Comment by tmcconechy** [comment]
@anhallbe i didnt get the same error in the stackblitz?

<img width="464" alt="Screenshot 2023-12-22 at 9 39 55 AM" src="https://github.com/infor-design/enterprise-wc/assets/814283/bec24cf1-ed4a-432b-8db8-30121c13d280">

**Comment by anhallbe** [comment]
Interesting. I was sure I could see that error in Chrome earlier. But now this is what I'm seeing in Chrome:

<img width="840" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/462cf9ff-8e45-4004-9ccc-3f8842c89448">

Still seeing the error in Safari though:
<img width="816" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/c060170d-02f6-4473-9c3e-418d07025a94">

**Comment by tmcconechy** [comment]
Added a fix on https://github.com/infor-design/enterprise-wc/pull/1727 it seems like when it initially renders it renders with incorrect style but renders again correct after. 

Should fix it. The other problem i think was fixed by a recent fix. Lets try this again when beta 18 is release by EOW with this fix
