### ISSUE TITLE
Charts: Undefined "name" is rendered as "undefined"

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#1720]
**Describe the bug**
The `IdsChartData` declares the `name` property as optional, implying that it can be omitted. But if it is omitted, the legend will render with the string `undefined`.

**To Reproduce**

1. Go to https://stackblitz.com/edit/web-platform-l6qeaj?file=index.html
2. See the preview window

**Expected behavior**
One of the following:
1. Allow the `name` to be nullish, and if so don't render the legend at all. Or is there another way to not show the legend?
2. Declare the `name` as mandatory, and perhaps log/throw if it is not set?

**Version**

- ids-enterprise: 1.0.0-beta.17

**Screenshots**
<img width="312" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/42b1b6df-3375-418d-a2a3-874afa88e9c6">

**Platform**
 - Infor Application/Team Name: Portal

**Comment by tmcconechy** [comment]
I think we should allow it to be empty in case it needs to be omitted. Then hide it/not show undefined

**Comment by jbrcna** [comment]
QA Passed
https://main.wc.design.infor.com/ids-axis-chart/hide-legend.html
<img width="1209" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/6868df7f-1e5f-4fc4-a339-b302d3f0afef">

https://main.wc.design.infor.com/ids-bar-chart/one-exactly.html
<img width="1587" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/e8bd9c76-7593-4c24-8442-f71c4cacafd1">
