### ISSUE TITLE
IdsTree: e.details.node.data not sent in selected event for nodes added via IdsTree.addNodes()

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#1721]
**Describe the bug**
In most cases this seems to work but for this example where I only have one "root" node the issue happens. 

**To Reproduce**
1. Put attached example into place (add-node-issue.zip) 
2. Go to 'http://localhost:4300/ids-tree/add-node-issue.html'
3. Set a breakpoint in 'selected' event listener in add-node-issue.ts.
4. Click on 'New Node 1' child node
5. Inspect event and notice e.details.node has no data object

**Expected behavior**
Expect e.details.node to have data object of the node I added via addNodes()

**Version**
- ids-enterprise-wc: latest pull from 'main' branch

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/4737815/f42ad770-5f58-4e7a-90f0-ad8162185527)

**Example**
[add-node-issue.zip](https://github.com/infor-design/enterprise-wc/files/13753710/add-node-issue.zip)

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Window 11
 - Browser Name: Chrome
 - Browser Version: latest

**Comment by jbrcna** [comment]
QA Passed
verified in https://main.wc.design.infor.com/ids-tree/add-node-issue.html
<img width="1716" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/af415042-fcb3-4ae3-960a-61d9df9bb6ef">
