### ISSUE TITLE
IdsProcessIndicator: Labels and icons are overlapping

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#1730]
**Describe the bug**
Labels and icons are overlapping.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-process-indicator/example.html
2. See error
3. If you dont see it hit reload on the page

**Expected behavior**
Label and icon should rendered properly.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/893a38aa-5a0a-4f41-86cd-0d5a83f03a82">

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@glenlieorillo im not seeing it look like your screen shot hover it could look a bit better in firefox. Is there anything else we need to add to see the issue? This is what i see:

![Screenshot 2023-12-29 at 9 14 05 AM](https://github.com/infor-design/enterprise-wc/assets/814283/999a8294-55f1-4adf-b1e4-986df3fff70e)

Also some icons arent aligned the best but i dont see what your seeing?

**Comment by glenlieorillo** [comment]
Hello @tmcconechy. Happy New Year!

Once you open the link, try to refresh the page. You could see the overlapping of the text and icon. Kindly see the clip below for reference:

https://github.com/infor-design/enterprise-wc/assets/102151352/a84a9056-dfc0-409a-8c51-168dbbea16e7
