### ISSUE TITLE
IdsTreemap: Label and value are misaligned in RTL

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#1731]
**Describe the bug**
Label and value are misaligned in RTL.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-treemap/example.html
2. Change to RTL locale (_Hebrew_)
3. See error

**Expected behavior**
Label and value should be in the proper place.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/80b6b18e-a61a-4c9e-8182-2d6728daffa8">

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by jbrcna** [comment]
QA Passed
verified in https://main.wc.design.infor.com/ids-treemap/example.html
**chrome**
<img width="1712" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/f1485e89-5e61-41b7-9dce-7574f357ed28">

**firefox**
<img width="1666" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/28d02b70-9b38-45a7-9bbe-43b0bdce0db3">

**safari**
<img width="1721" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/02bb0909-2d96-4fde-8354-09065df82b08">

**dege**
<img width="1669" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/cddc7fc7-5a93-4956-984a-7360f079e255">
