### ISSUE TITLE
IdsListView: unable to use "space" upon creating/editin an item

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1732]
**Describe the bug**

**To Reproduce**

1. Go to http://localhost:4300/ids-list-builder/example.html 
2. Click on '+' icon
3. Type a text and hit space 
5. Also, when you press space/enter the text looks off

**Expected behavior**
should be able to use space key,

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="762" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/c1744fee-e311-4ed0-b596-0172127c66fe">

**Platform**
All

**Additional context**
related to https://github.com/infor-design/enterprise-wc/issues/1400

**Comment by jbrcna** [comment]
this is now working as expected. you can now use space and enter keys. However, when you click plus icon then hover over to a selected item. the color is off.

Steps.
1. select last item
2. click + icon
3. hover over to the item above the last item
4. notice that upon clicking the plus icon, all items with highlight (being selected) when hovered, the text is off
<img width="947" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/d460b8f0-d9a5-42aa-a56f-843d5cf7a32c">

**Comment by tmcconechy** [comment]
@jbrcna ok lets make a new issue for that one please
