### ISSUE TITLE
IdsDropdown: Typeahead option no longer working

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1737]
**Describe the bug**

**To Reproduce**
1. Go to  https://main.wc.design.infor.com/ids-dropdown/typeahead.html
2. Click tab to the dropdown and type a -> see that search works
3. Reload and click to open the dropdown
4. Type a -> see that this doesnt work when opening it first 

**Expected behavior**

Should work same if you click to open or type to open. Also should work on https://main.wc.design.infor.com/ids-multiselect/ which it is not right now.

**Legacy version**

- https://main-enterprise.demo.design.infor.com/components/dropdown/test-reload-typeahead.html
- https://main-enterprise.demo.design.infor.com/components/dropdown/test-typeahead-automation-id.html

**Comment by jbrcna** [comment]
QA Passed
verified in https://main.wc.design.infor.com/ids-dropdown/typeahead.html
<img width="666" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/5df96714-c1d7-4a6a-b656-b5c3d6dd7224">
https://main-enterprise.demo.design.infor.com/components/multiselect/example-index.html
<img width="1232" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/61cc2fed-8078-4550-8f72-8e6fa68011c9">
