### ISSUE TITLE
IdsModal: The modal content is rendered even though it is not shown

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#1744]
**Describe the bug**
The modal content is displayed on the page even though the modal is never .show():n.

**To Reproduce**

1. Go to https://stackblitz.com/edit/web-platform-qwrfco?file=index.html (NOTE: it might take some time for the enterprise-wc bundles to download)
3. See modal content is displayed
4. Click "Show Modal"
5. The modal overlay is displayed, but without content

**Expected behavior**
The modal content should only be visible when the modal is shown.

**Version**

- ids-enterprise: beta.17 & beta.18

**Screenshots**
<img width="947" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/08d3fca5-c601-4ef6-b4af-20967dceafcc">

<img width="2111" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/84c274d1-9490-4d61-a5b2-0fc09844a13f">

**Platform**
 - Infor Application/Team Name: Portal
 - OS Version: macOS
 - Browser Name: Chrome, Safari

**Additional context**
I only noticed this when upgrading to beta.18 (up from 17). But the issue can be reproduced in the Stackblitz with both versions.

**Comment by glenlieorillo** [comment]
This is now working as expected.


https://github.com/infor-design/enterprise-wc/assets/102151352/a0ec9a55-747c-42cf-80b2-efb788e09c17
