### ISSUE TITLE
IdsSlider: Element value is not decimal as tooltip shows

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#1746]
**Describe the bug**
Slider element value is not decimal as tooltip shows

**To Reproduce**
Go to https://main.wc.design.infor.com/ids-slider/example.html using single slider example.

1. Go to https://main.wc.design.infor.com/ids-slider/example.html
2. Inspect the single slider example
3. Change the slider value clicking or dragging on the component
4. On the inspection the value is not a decimal as tooltip shows (it is like 47.69 instead of 48)

**Expected behavior**
The value on element needs to be decimal

**Version**
Latest

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/663908/2f920493-9c2a-40f9-9e6a-74bc6825e8c4)

**Comment by jbrcna** [comment]
QA Passed
verified in https://main.wc.design.infor.com/ids-slider/example.html
<img width="1697" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/346fde10-0f61-41f7-99af-2d33fe881194">
<img width="1565" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/4064633d-6db8-4ef4-91bd-720572eabb13">
