### ISSUE TITLE
IdsTabs: Theme switcher button is visible in popup

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1754]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-tabs/app-example.html
2. Click on Plus sign to add tabs
3. Click on 'More' dropdown button
4. Hover over the first menu item
5. See error

**Expected behavior**
<img width="221" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/486058d8-e6c1-4b24-80c6-514ed36ad5a9">

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
\
<img width="1728" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/24fc1e50-6260-452d-b5cb-d5b2a7aa60e2">

**Platform**
Firefox

**Additional context**

**Comment by tmcconechy** [comment]
Closed as per https://inforwiki.atlassian.net/browse/IDS-4360
