### ISSUE TITLE
IdsInput: Add tooltip and text-overflow: ellipsis option to ids-input

### ISSUE THREAD

**Issue by sowmyaNelanti** [infor-design/enterprise-wc#1755]
**Missing use case.**
Use case missing: tooltip should be shown only when "text-verflow: ellipsis" style is added for value in input field

**Describe the solution you'd like**
Tooltip should be visible ONLY when "text-verflow: ellipsis" style is added for value in input field (as tooltip meaning which gives extra information other than content visible on the screen)

**Describe alternatives you've considered**
Applied tooltip for ids-input but it is always visible even when ... (text-verflow:ellipsis) is not applied

**Additional context**
This is important as in below scenario for us , where when left pane is minimizing it becomes hard for user to read input fields, if tooltip is automatically enabled when ... is visible in input field value, it would be good
![image](https://github.com/infor-design/enterprise-wc/assets/41888743/7f2bc880-3c35-4a7c-80ee-a3c6651a560b)

![image](https://github.com/infor-design/enterprise-wc/assets/41888743/c098e259-1854-42a6-8a80-e1dd2478afe1)

**Comment by jbrcna** [comment]
this is woking as expected. however, the tooltip is not aligned in the field.


<img width="1437" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/9de6456f-ec3d-4ccc-87c8-b7a284510794">

**Comment by tmcconechy** [comment]
Can you add a new issue for this? @jbrcna

**Comment by jbrcna** [comment]
okay @tmcconechy
