### ISSUE TITLE
Fieldset: Legend has no margin or padding when running with old component stylesheet

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#1756]
**Describe the bug**
When an app is using the `<ids-fieldset>`, the old ids-enterprise stylesheet sets the `margin` and `padding` of `<legend>` to 0, which makes it look a bit off.

**To Reproduce**

1. Go to https://stackblitz.com/edit/web-platform-tqyxgh?file=index.html
2. Notice that the fieldset legend has no margin or padding

**Expected behavior**
Styles from the old ids-enterprise lib should not override styles in ids-enterprise-wc.

**Version**

- ids-enterprise: 1.0.0-beta.18

**Screenshots**
ids-enterprise-wc + ids-enterprise:
<img width="348" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/7efbc2e1-9ed8-4567-8721-a930377999cd">

ids-enterprise-wc:
<img width="348" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/419ebffc-6f61-4022-9f7e-6f1a57c4bbf9">

**Additional context**
<img width="404" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/0a912c7f-77fd-4765-b5e4-cda3d35e9294">

**Comment by tmcconechy** [comment]
Will require 4.92 to fix
