### ISSUE TITLE
IdsDatagrid: delete/clear button only remove items on a selected page

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1757]
**Describe the bug**
when using delete/clear button, it only clears/deletes the selected item on a selected page. Also, the text on the top/left of the Datagrid toolbar does not reflect the correct number of records upon deleting/clearing an item.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/pagination-client-side.html
2. Select one row
3. Go to other page
4. Try any combination of page number, page size, and selection. 
5. Click delete button
6. See error
7. Also try clear button

**Expected behavior**
should be able to delete/clear items

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![Large GIF (1708x398)](https://github.com/infor-design/enterprise-wc/assets/56722184/a477047e-3114-4452-9774-bc5d6c972bbd)

**Platform**
All

**Additional context**

**Comment by ericangeles** [comment]
Moving this to WC sprint board.

**Comment by jbrcna** [comment]
QA Passed
