### ISSUE TITLE
IdsDatagrid: child was not selected after selecting its parent

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1758]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/tree-grid-virtual-scroll.html
2. Select row one
3. Expand row one (Crawler)
4. See error.
5. Child is not selected

**Expected behavior**
when a parent is being selected, child items should be selected as well

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="804" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/891abb43-da9a-4cf0-8213-3be51690d8e2">

**Platform**
 All
**Additional context**

**Comment by tmcconechy** [comment]
This is ok @jbrcna because the option `group-selects-children` is not enabled in this example. So not an issue and is a possible configuration
