### ISSUE TITLE
IdsText: Align ids-icon with IdsText

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1759]
**Describe the bug**

**To Reproduce**
1. Place an ids-icon in ids-text and check alignment

![Screenshot 2024-01-12 at 9 48 27 AM](https://github.com/infor-design/enterprise-wc/assets/814283/97612619-8581-45a5-9cc6-142913524de8)

**Expected behavior**
Make it possible to align text in a span

**Additional context**
[Add any other context about the problem here.](https://teams.microsoft.com/l/message/19:b649a7c426e64e3dbedb0cc5202ce2d4@thread.skype/1705007223882?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1705007223882&teamName=IDS%20Enterprise%20Development&channelName=Web%20Components&createdTime=1705007223882)

**Comment by jbrcna** [comment]
QA Passed
verified in. https://main.wc.design.infor.com/ids-icon/align-icon.html
<img width="1443" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/fdc8636e-789e-4010-b5c3-f27394971b23">

**Comment by radovaniljic** [comment]
@tmcconechy would it also be possible to fix the alignment when using an `ids-alert` inside the `ids-text`?

**Comment by tmcconechy** [comment]
Sure can you add a new issue with markup you used? @radovaniljic 
FYI also i did alert tooltips here https://main.wc.design.infor.com/ids-alert/example.html but may not be the same.
