### ISSUE TITLE
IDSDataGrid: Customizable Table Header

### ISSUE THREAD

**Issue by ShwetaKhera** [infor-design/enterprise-wc#1761]
**Is your feature request related to a problem or use case? Please describe.**
We have created an angular component that consumes ids-data-grid to build a table. Our table header needs to have a subtext as well as a checkbox that allows column selection. These options are not provided in ids-data-grid, and neither is the column header customizable.

**Describe the solution you'd like**
There are two possible solutions to this problem:
- Add support for subtext and checkbox for column selection, and/or
- Allow the table column header to be customized

**Describe alternatives you've considered**
No other components have filtering abilities which are provided in ids-data-grid

**Comment by tmcconechy** [comment]
The most viable solution would be a subtext example / support. Making it fully customizable is going to be much harder to support and take much longer.

Can you give me a visual of how it might work for your use case? Im thinking maybe

``` 
name: 'Description<br>Test',
// or
name: 'Description',
subtitle: 'Test'
```

**Comment by ShwetaKhera** [comment]
If we can get Name and subtext, that would be great. Also, would it be possible to add a checkbox 'selected' which allows the selection of all the column values? I have added the screenshot for a visual reference.

```
name: 'Description',
subtext: 'Test',
selected: true
```

<img width="304" alt="Screenshot 2024-01-16 at 3 20 44 PM" src="https://github.com/infor-design/enterprise-wc/assets/30701871/f657dd2e-62b2-4294-b329-f9932c30b05d">

**Comment by tmcconechy** [comment]
For the @ShwetaKhera -> what does the selected do? Normally we just have one selection checkbox for selecting all the rows like this example https://main-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html

For the subtext feature good to go. For the selected need some clarification

**Comment by ShwetaKhera** [comment]
Having a full-row selection is a really nice part, similar to that, we need a way to be able to select full column. So when we click on OrderID checkbox, all column values(i.e, '200', '300') are selected. And I want to be able to select multiple columns. When I select both checkboxes (OrderID and ProductID), all values under these columns should be selected. 
 
<img width="302" alt="Screenshot 2024-01-18 at 12 26 41 PM" src="https://github.com/infor-design/enterprise-wc/assets/30701871/68c691df-d2a7-4839-a5f4-c6de30190860">

**Comment by tmcconechy** [comment]
The column selection adds additional scope.

**Comment by tmcconechy** [comment]
@ShwetaKhera do you want to split this in two issues.

1. The two line column header is ready to implement
2. But we are not sure about the checkbox in the header, whats the use case? You can only select all the column rows. The way i would do it is use a mouse or keyboard to select range so you can select multiple columns.

So suggest splitting this in two and adding more info so we can work on the cell select use case

**Comment by tmcconechy** [comment]
@ShwetaKhera i made two issues since one requires design and one is good to go

https://github.com/infor-design/enterprise-wc/issues/1793
https://github.com/infor-design/enterprise-wc/issues/1794

Can you add a quick note on the use case on https://github.com/infor-design/enterprise-wc/issues/1793 to help. I wonder if you need row and cell selection and why just selecting an entire column? But not part of the column/rows?

So will close and use those two issues
