### ISSUE TITLE
Dropdowns: Break in angular after upgrade to beta.18

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise-wc#1762]
**Describe the bug**
Dropdowns break after upgrade to beta.18 in angular. This also applies to other components using dropdowns.

**To Reproduce**
- In the angular-ids-wc examples project, update to ids-enterprise-wc beta.18.
- Notice how dropdowns no longer open in the correct place and selection does not work.

**Expected behavior**
ModuleNav and dropdowns in general should work like before upgrade to beta.18

**Version**
https://github.com/infor-design/enterprise-wc-examples
- ids-enterprise-wc@1.0.0-beta.18

**Screenshots**

![ModuleNavAndDropdownIssues](https://github.com/infor-design/enterprise-wc/assets/9215760/7ef4e6d0-4fcc-4d2b-a260-dc96619eef31)

**Comment by tmcconechy** [comment]
@clayinfor is this being fixed on https://github.com/infor-design/enterprise-wc/issues/1737

**Comment by jbrcna** [comment]
this is working as expected. However I noticed the menu is not aligned in the field
https://main.wc.design.infor.com/ids-multiselect/example.html
<img width="621" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/54ec6ad1-e70f-4a35-be74-8b3101f45efd">

**Comment by tmcconechy** [comment]
@jbrcna lets make a minor issue for that. (Could be perfect if we fix that as well).

Thanks!
