### ISSUE TITLE
IdsInput/IdsTextarea: issues with how event is fired in web components

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-wc#1765]
**Describe the bug**
`input event` in for example `ids-input` is fired twice whenever a change happens. For plain HTML text input the event is only fired one time, and that's the expected behaviour.

In the case of Angular, you can use `ngModel` and bind it with `ngModelChange` with e.g. a function,  which will fire each time the model is changed. When using it with web components, it will fire one time after the component has been loaded. When you use `ngModel` with plain HTML text input it does not fire on load, which is the expected behaviour. 

You can see the ngModel issue in your example project

**To Reproduce**

You can see the ngModel issue here
https://github.com/infor-design/enterprise-wc-examples/blob/main/angular-ids-wc/src/app/components/ids-forms/demos/example/example.component.html

1. build and run the angular examples
2. go to the IDS forms example

**Expected behavior**

For the `ngModel` case:
- During load it should to run the function binded with `ngModelChange`

For `input` event case:
- It should not fire twice whenever a input happened.
- It should not fire input change when you have set the value attribute

**Comment by guoliang** [comment]
I've filled out a bit, and I think the importance here is to fix the `input` event.

**Comment by tmcconechy** [comment]
Noting, also should fix for textarea and test
