### ISSUE TITLE
IdsDataGrid: Filters jump to wrong position when the grid is displayed inside of an ids-modal

### ISSUE THREAD

**Issue by mecharmor** [infor-design/enterprise-wc#1766]
**Describe the bug**
The ids-data-grid component is loaded from within an ids-modal and when that is observed we will see that the toggle able filters are not at the correct positioning.
![image](https://github.com/infor-design/enterprise-wc/assets/12702175/6635e903-00dd-48c5-bdeb-90ae05726013)

**To Reproduce**

1. Embed the ids-data-grid component inside ids-modal
2. open the modal
3. observe your table is shown and click on any filter option

Steps to reproduce the behavior. Use the following code and render any data grid content like this:
```
<ids-modal id="my-modal-id>
      <ids-data-grid
         id="my-table"
         label="my-table"
         row-height="xs"
         filterable="true"
     ></ids-data-grid>
</ids-modal>
```

**Expected behavior**
The filter option should work in the same manner it already does but without the positioning in an incorrect placement

**Version**
From the package.json
`"ids-enterprise-wc": "^1.0.0-beta.17",`

**Screenshots**
Expected:
![image](https://github.com/infor-design/enterprise-wc/assets/12702175/6b13a798-3158-4bc0-b8fb-8c96f2b41de4)

Actual:
![image](https://github.com/infor-design/enterprise-wc/assets/12702175/44614a48-86d4-41fb-bebf-c49fecfa9ca9)

**Platform**
 - Infor Application/Team Name: N/A
 - OS Version: Mac OS Ventura
 - Browser Name: Chrome
 - Browser Version: Version 120.0.6099.129 (Official Build) (x86_64)

**Additional context**

**Comment by ShwetaKhera** [comment]
@tmcconechy This issue is also noticed when ids-menu-button, ids-popup-menu are used inside ids-splitter component.
<img width="355" alt="Screenshot 2024-02-05 at 1 30 07 PM" src="https://github.com/infor-design/enterprise-wc/assets/30701871/20815e75-3e79-4378-8b8c-7416c9dd1b49">
