### ISSUE TITLE
IdsLoader: Inner bars are the wrong size

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1768]
**Describe the bug**
On http://localhost:4300/ids-loading-indicator/example.html you can see the inner and outer bars on both types of loaders are not the same size

**To Reproduce**

1. Go to http://localhost:4300/ids-loading-indicator/example.html 
2.See error

**Expected behavior**
Should be 6px

**Comment by jbrcna** [comment]
QA Passed
https://main.wc.design.infor.com/ids-loading-indicator/example.html
<img width="786" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/574841e1-e468-4068-a44f-9a1670a15a8f">
<img width="571" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/b230caee-067a-47e6-b61b-ec5a88761eb3">
<img width="704" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/ef038e23-858a-4bae-a33a-621a93f0cfbd">
<img width="1035" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/07779f08-8be3-4aff-862e-4944e5c3ca19">

observation
the other stroke width is 3px
<img width="1045" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/d364ee6a-c9b2-4a81-9ff7-aba2085555f2">
