### ISSUE TITLE
Dropdowns: On a cell of a datagrid appear far from the original cell

### ISSUE THREAD

**Issue by edisonferrer** [infor-design/enterprise-wc#1770]
**Describe the bug**
Dropdowns on a cell of a datagrid appear far from the original cell. For the first few rows, dropdowns are alright, however as you go further down the list, the dropdowns appear transposed to another place. 

Encountered on enterprise-wc 1.0.0-beta.18

**To Reproduce**
1.) Load the following demo page: https://main.wc.design.infor.com/ids-data-grid/editable-lookup.html
2.) Click the dropdowns on the last three rows.
3.) Dropdowns are shown on a different place 

Note: Issue not encountered on low zoom levels. But can consistently be recreated when zooming in your browser.

**Expected behavior**
Dropdowns should appear below the cell similar to the previous rows.

**Version**
enterprise-wc 1.0.0-beta.18

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/47999751/335a588a-4f96-4d18-9f14-e5e92692fb34)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: google chrome
 - Browser Version: 120.0.6099.217 

**Additional context**

**Comment by tmcconechy** [comment]
Similar to https://github.com/infor-design/enterprise-wc/issues/1766
