### ISSUE TITLE
IdsStats: part attribute missing for  ids-widget-body

### ISSUE THREAD

**Issue by ajayponnapati** [infor-design/enterprise-wc#1771]
**Describe the bug**
I am using `<ids-widget>` which also contains `<ids-stats>`.In the shadow-root of <ids-widget> there are some tags and one of them (ids-widget-body) doesn't have part attribute.

below is the code of shadow-root for ids-widget copied from browser.
```
<div class="ids-widget" part="widget">
        <div class="ids-widget-body">
          <div class="ids-widget-header" part="header">
            <slot name="widget-header"></slot>
          </div>
          <div class="ids-widget-search" part="search">
            <slot name="widget-search"></slot>
          </div>
          <div class="ids-widget-content " part="content" style="padding-block: 8px;">
            <slot name="widget-content"></slot>
          </div>
          <div class="ids-widget-footer" part="footer">
            <slot name="widget-footer"></slot>
          </div>
        </div>
      </div>
```

It would be helpful to style ids-widget-body if it has a part attribute.

**To Reproduce**

1. run 'ids-stats' example page (https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-stats/demos/example.html)
2. Inspect any one of the widget and expand #shadow-root
3. Scroll down to div of ids-widget-body 
4. part attribute is missing while all other div have part attribute except for ids-widget-body div

**Expected behavior**
if part attribute is added to ids-widget-body , It would be helpful to style that div as mentioned in the this link. [[enterprise-wc/doc/CUSTOMIZING.md at main · infor-design/enterprise-wc · GitHub](https://github.com/infor-design/enterprise-wc/blob/main/doc/CUSTOMIZING.md)](url)

**Version**

-ids-enterprise-wc: "^1.0.0-beta.18",

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/144166021/26317ef5-7adb-4ebc-a1fc-79863945c176)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
What would you like to customize? (It may be possible with a css variable (or easier))

**Comment by ajayponnapati** [comment]
I need to add some height to ids-widget-body which is in shadow-root
