### ISSUE TITLE
IdsColorPicker: Not binding to [formControl] in Angular, tooltip position off, and the popover causing scrollbar to appear

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise-wc#1774]
**Describe the bug**
In Angular, adding [formControl]="control" to the `ids-color-picker` components, nothing happens in valueChanges for the control, and the selected color value is not visible in the input field. In contrast to e.g. `ids-spinbox` where it works. I have added the `IdsFormAccessorsModule` in my code as per the angular-wc example.

Also, when triggering the colors popup, the tooltip with info, and the caret down, is way off, and it "takes space" causing us to get a scrollbar.

**To Reproduce**
Use this code in e.g. the angular-wc example:
```ts
import {
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy,
  Component,
  OnInit,
} from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';

import IdsColorPickerComponent from 'ids-enterprise-wc/components/ids-color-picker/ids-color-picker';
import IdsSpinboxComponent from 'ids-enterprise-wc/components/ids-spinbox/ids-spinbox';

import { IdsFormAccessorsModule } from '../directives/ids-form-accessors.module';

@Component({
  selector: 'idsa-colorpicker',
  standalone: true,
  imports: [ReactiveFormsModule, IdsFormAccessorsModule],
  template: `
    <ids-spinbox [formControl]="control2"></ids-spinbox>

    <ids-color-picker
      id="picker"
      label="Default Color Picker"
      [formControl]="control"
    ></ids-color-picker>
  `,
  styles: `
    :host { display: block; }
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IdsaColorPickerComponent implements OnInit {
  readonly control = new FormControl('', { nonNullable: true });
  readonly control2 = new FormControl(0, { nonNullable: true });

  ngOnInit() {
    this.control.valueChanges.subscribe((value) => {
      console.log('colorpicker:', value);
    });
    this.control2.valueChanges.subscribe((value) => {
      console.log('spinbox:', value);
    });
  }
}

```

1. Please see code, screenshot, .gif.

**Expected behavior**
- Selected value should be reflected, both in the formControl, but also in the input
- When selecting color, tooltip should be positioned correct
- Should not cause a scrollbar to appear when it does not "fit"

**Version**
- ids-enterprise-wc: 1.0.0-beta.18

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/73601152/7974bca2-d432-4ffd-bf35-be022a6f7ee0)

Unfortunately you don't see the cursor, hopefully it is clear anyway that: when hovering, the tooltip and caret down are off, when selecting a color, nothing appens (no log no value set in the input), and at the end, the popover causes scrollbar:

https://github.com/infor-design/enterprise-wc/assets/73601152/62af202a-6b33-457b-9f70-b869c6108488

**Platform**
 - Infor Application/Team Name: M3
 - Browser Name: Chrome
 - Browser Version: 
![image](https://github.com/infor-design/enterprise-wc/assets/73601152/3f0c06e8-8ad6-4f59-b814-9918154b3283)

**Comment by jbrcna** [comment]
QA Passed
verified in https://main.wc.design.infor.com/ids-color-picker/example.html
<img width="1159" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/7667cdc4-9e8a-45f7-a3fe-f8457a64b433">
<img width="1259" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/8b36d02d-6294-469e-b5df-d85f5fd602af">
