### ISSUE TITLE
IdsText: The order of attributes matter

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#1775]
**Describe the bug**
Changing the order of attributes in `<ids-text>` also changes how it is rendered.

For example:
```html
<ids-text type="p" font-weight="semi-bold">
   This text is bold
</ids-text>
<ids-text font-weight="semi-bold" type="p">
   This text is NOT bold
</ids-text>
```

**To Reproduce**

1. Go to https://stackblitz.com/edit/web-platform-eej6qm?file=index.html
2. See how the text blocks look different, even though they have the same attributes (just different order).

**Expected behavior**
Order of attributes should not matter.

**Version**

- ids-enterprise: 1.0.0-beta.18

**Screenshots**
<img width="518" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/a3c64e73-6d1a-471e-b088-5589e2b9cff0">

**Platform**
 - Infor Application/Team Name: Portal

**Additional context**
Note that this particular issue with `type` and `font-weight` is trivial to work around. However this might affect other components, which may be more critical.

**Comment by tmcconechy** [comment]
Im guessing its specific in this case, the type will change the underlying DOM more than a property will so its order might be causing it.

Can certainly fix this and anything else that arises
