### ISSUE TITLE
IdsStats: Unable to set kpi with no formatting

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1776]
**Describe the bug**
See https://teams.microsoft.com/l/message/19:b649a7c426e64e3dbedb0cc5202ce2d4@thread.skype/1705585909472?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1705585909472&teamName=IDS%20Enterprise%20Development&channelName=Web%20Components&createdTime=1705585909472

You can set kpiFormat to undefined but it doesnt work. It tries to format and shows NaN

**To Reproduce**

1. IN the stats component add one that has no kpiFormat i.e.
2. `document.querySelector<IdsStats>('#stat-ac-one')!.kpiFormat = undefined;`
3. See error on page

**Expected behavior**
If kpiFormat is undefined should show whats in it and not try to format

**Comment by jbrcna** [comment]
working as expected. moving ticket to done
https://main.wc.design.infor.com/ids-stats/example.html
<img width="1262" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/f68f25f8-893b-407c-a6a3-f233373e63ba">
<img width="1120" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/9441c2bd-fd36-4639-b76b-12e0ff38edff">
<img width="1172" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/d56b37f6-4f0b-486a-a8a5-40c65c3f9208">
