### ISSUE TITLE
IdsNotificationBanner: Text not rendering - Default message displaying

### ISSUE THREAD

**Issue by NikosLardas** [infor-design/enterprise-wc#1782]
**Description:**

After the latest update for the Web Components to version `1.0.0-beta.18`, the notification banners used in our Angular project stopped displaying the hardcoded text that is provided in the `message-text` attribute, and instead display only the default message of `Enter Message Text`

**Reproducing the issue:**

Using the latest version of the project on: https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc 
running the project without modifying any code, this is what is visible for the notification banner example:

![image](https://github.com/infor-design/enterprise-wc/assets/69582244/bb89d566-844c-40f7-8bf4-a30fe2f9b740)

**Video example:**

https://inforonline.sharepoint.com/sites/SoHoXiDevelopment/_layouts/15/stream.aspx?id=%2Fsites%2FSoHoXiDevelopment%2FShared%20Documents%2FWeb%20Components%2Fscreen%2Dcapture%2Ewebm&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview

**Example from our project**:

![image](https://github.com/infor-design/enterprise-wc/assets/69582244/31b0535f-505e-4311-8fe6-2556f85918bc)

**Expected behavior:**

The message-text value displays correctly in the notification banner

**Version:**
    "ids-enterprise-wc": "^1.0.0-beta.18",
    Angular: 16.2.10

**Comment by jbrcna** [comment]
working as expected. Test Passed
verified in https://main.wc.design.infor.com/ids-notification-banner/example.html
<img width="1094" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/a43af8a9-db6c-40ad-963d-1dce1ffdbcf7">
