### ISSUE TITLE
IdsModal/IdsActionPanel: Popup not disappearing after close action

### ISSUE THREAD

**Issue by NikosLardas** [infor-design/enterprise-wc#1787]
**Description:**

After the latest update for the Web Components to version `1.0.0-beta.18`, all the action panels/modals we have in our angular application stopped working correctly. Specifically, the action panel will appear as a popup and the rest of the screen is grayed out, and when the user tries to close the modal, the modal will remain visible in the screen, although the rest of the screen returned into focus. I run the wc-examples project locally (https://github.com/infor-design/enterprise-wc-examples) with "ids-enterprise-wc": "^1.0.0-beta.18"  and I see the same error being reproduced for the modal examples, as you can see in the attached screen recording.

**Reproducing the issue/Video example:**

Using the latest version of the project on: https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc 
running the project without modifying any code, this is the functionality of the modals:

https://inforonline.sharepoint.com/sites/SoHoXiDevelopment/_layouts/15/stream.aspx?id=%2Fsites%2FSoHoXiDevelopment%2FShared%20Documents%2FGeneral%2Fscreen%2Dcapture%20%283%29%2Ewebm&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview

**Example from our project**:

[screen-capture (4).webm](https://github.com/infor-design/enterprise-wc/assets/69582244/0c98315c-d6ff-4267-b709-f960fb203413)

**Expected behavior:**

The modal/action panel disappears from the screen once it is closed.

**Version:**
    "ids-enterprise-wc": "^1.0.0-beta.18",
    Angular: 16.2.10

**Comment by tmcconechy** [comment]
@andrivarhanov this i think is the same issue as https://github.com/infor-design/enterprise-wc/issues/1820
