### ISSUE TITLE
IdsDataGrid: Custom validation rule for editable column

### ISSUE THREAD

**Issue by shalini-patro12** [infor-design/enterprise-wc#1791]
**Is your feature request related to a problem or use case? Please describe.**
Below use case is missing.
To add custom validation rule and custom error message for ids-data-grid editable columns. As of now only 'required' validation is working.

**Describe the solution you'd like**
User should be able to add custom validation rules and custom error message for ids-data-grid editable columns, the same functionality available as in ids-input (addValidationRule mixin)

**Describe alternatives you've considered**
Tried by adding "editor" settings in datagrid columns but it is not working. Below is the code snippet used to try custom validation and custom error message
`ngAfterViewInit(): void {
		console.log('datagrid', this.dataGrid);

		this.dataGrid.nativeElement.data = [];
		this.columns.push({
			id: 'selectionCheckbox',
			name: 'selection',
			sortable: false,
			resizable: false,
			formatter: this.dataGrid.nativeElement.formatters.selectionCheckbox,
			align: 'center'

		});

		this.columns.push({
			id: 'name',
			name: 'Name',
			field: 'name',
			// sortable: true,
			formatter: this.dataGrid.nativeElement.formatters.text,

			editor: {
				type: 'input',
				editorSettings: {
					autoselect: true,
					dirtyTracker: true,
					validate: 'required',
					check: (input: any) => {
						const val = input.value;
						return /^[A-Z]*$/.test(this.dataGrid.name.value);
					},
					message: 'No numbers allowed',
					type: 'error',
					id: 'my-custom-uppercase'
				}
			},

		});

		this.columns.push({
			id: 'dataType',
			name: 'Data Type',
			field: 'dataType',
			formatter: this.dataGrid.nativeElement.formatters.text,

			editor: {
				type: 'input',
				editorSettings: {
					validate: 'required',
				}
			},

		});

		this.columns.push({
			id: 'defaultValue',
			name: 'Default Value',
			field: 'defaultValue',
			// sortable: true,
			formatter: this.dataGrid.nativeElement.formatters.text,
			editor: {
				type: 'input',
				editorSettings: {
					//   autoselect: true,
					//   dirtyTracker: true,
					validate: 'required',

				}
			},

		});

		this.dataGrid.nativeElement.columns = this.columns;

	}`
**Additional context**
Datagrid will have Name column which should satisfy below requirements

1. The variable name is mandatory. The empty field is highlighted in red.
2. The variable name can contain only allowed characters. [a-zA-Z_][a-zA-Z0-9_]{0,255}. Tooltip message: “The variable name contains invalid characters. Please use only characters in accordance with the pattern [a-zA-Z_][a-zA-Z0-9_]{0,255}.“  
3. The variable name cannot exceed 255 characters. No tooltip, it should not be possible to enter more than 255 characters.
4. The variable name should be unique.  Tooltip message: The variable name is already in use. Please choose a different name.

**Comment by tmcconechy** [comment]
The main ask here is that you can set custom validation on a datagrid column
