### ISSUE TITLE
IdsDataGrid: Add multi line text in the header

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1793]
**Describe the Feature**
Would like something like:

```js
name: 'Description',
subtext: 'Test',
```

Which will show multiline text in the header
![Screenshot 2024-01-23 at 9 43 50 AM](https://github.com/infor-design/enterprise-wc/assets/814283/03abc862-f9cf-4d9f-94af-a338f3273a03)

Or as `name: ['Description', 'Line Two']` maybe

**Expected behavior**
Provide a way to show a grid column header with two lines

**Additional context**
https://github.com/infor-design/enterprise-wc/issues/1761

**Comment by ShwetaKhera** [comment]
@tmcconechy For our use case, we need subtext to display the datatype of the column values. Example: 
```
{ name: 'Name', subtext: 'Text' },
{ name: 'Orderdate', subtext: 'Date' },
{ name: 'Quantity', subtext: 'Numeric' }
```
