### ISSUE TITLE
IdsPopupMenu: Add a beforeShow callback so data can be added programmatically

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise-wc#1804]
**Is your feature request related to a problem or use case? Please describe.**
We have a use case where we want to programmatically construct the data for an IdsPopupMenu when it's opened. This is because we have to call back to the server to know what to display, and don't want to bog down initialization for these calls when they may not be needed.

**Describe the solution you'd like**
Something like the beforeShow method on IdsDropdown would work well. This would have to be accessible thru an IdsMenuButton as well, 

Also, this callback would have to work for a submenu in the IdsPopupMenu and in a submenu on the IdsToolbarMoreMenu.

These cases work in the 4.0 controls, so I think they were just missed on the initial implementation

**Describe alternatives you've considered**
Attempted to use the beforeShow event, but the popup menu opens before the getting data call is complete. This means that the popup menu would need to get opened twice to see the returned data, and then it flickers. You can see this in the attached example.

[async-callback.zip](https://github.com/infor-design/enterprise-wc/files/14088224/async-callback.zip)
You can unzip this in the demo directory under src/app/components/ids-popup-menu/demos and then add the component to the .module.ts files.

![IDSPopupMenuIssue](https://github.com/infor-design/enterprise-wc/assets/22107636/b6de79c6-f4c8-4e44-b81f-56f105f5b5c2)

**Additional context**
And what application do you work on? Landmark

**Comment by tmcconechy** [comment]
Very Good, I think we need to

a) make sure https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-tooltip/demos/sandbox.ts#L12-L26 works (both the event and the call back)
b) provide an example in ids-popup-menu that shows loading the menu when clicking a menu button and on submenus (submenus may need a new callback/event)
c) IdsMenuButton doesnt need the call back (due to renaming will be more like a button option)

**Comment by tmcconechy** [comment]
My math ends at nine here .. I think its fine :)

**Comment by jbrcna** [comment]
moving to done. test Passed
