### ISSUE TITLE
GenAI: Add Gen AI Components

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1805]
**Describe the bug**

Add the AI generation components

a) button and event to editor
b) new button type
c) button animation and standalone generation animation (loading indicator)

**Expected behavior**

https://main-enterprise.demo.design.infor.com/components/button/example-index.html
https://main-enterprise.demo.design.infor.com/components/busyindicator/example-ai-loading-indicator.html
https://main-enterprise.demo.design.infor.com/components/editor/example-with-gen-ai-button.html

**Comment by jbrcna** [comment]
QA Passed
<img width="1384" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/c54337e0-bef0-4514-b977-c08ccea7fc8f">
<img width="1525" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/20015fee-0215-47d7-bf60-7d7db38d91df">

<img width="1292" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/04c36db2-615f-4fca-b89c-a7d27534a8cc">
<img width="1084" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/5f33fd30-d7e6-40ee-97f7-19afc7ea639c">

<img width="1008" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/f2f6a715-bc90-433d-b1f0-be4cec2ed010">
<img width="584" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/70e8019c-9263-4d11-8f2d-e95edceaf652">
