### ISSUE TITLE
IdsListbuilder: selected item hover color is off

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1809]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-list-builder/example.html
2. Click an item
3. Click + icon
4. Hover over the selected items (item with blue highlight)
5. See error
6. Notice that the text is not readable

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="897" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/a3299167-2274-4db1-b147-b0eda6412e06">

**Platform**
all

**Additional context**
related to https://github.com/infor-design/enterprise-wc/issues/1732

**Comment by jbrcna** [comment]
QA Failed
<img width="868" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/5d1e4c80-5d50-4a9d-a369-a134189abf86">

**Comment by tmcconechy** [comment]
Seems ok now https://main.wc.design.infor.com/ids-list-builder/example.html maybe the page was not loading. Can you recheck.

**Comment by jbrcna** [comment]
Thanks @tmcconechy , this is now working as expected.
<img width="1001" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/5741d5b0-5225-427a-b4ee-30969744acaa">
