### ISSUE TITLE
Tooltip displayed on click when selected trigger is hover

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-wc#181]
**Describe the bug**
I have a button which has a tooltip on it, and when I click on it it will switch to another template. But due to the on button click trigger the tooltip will be displayed on a corner in the new template 

**To Reproduce**
1. Go to http://htmlpreview.github.io/?https://github.com/guoliang/soho-sandbox/blob/master/index.html
2. Click on button to see the bug

**Expected behavior**
If the selected trigger is "hover" it should not add extra that tooltip will be displayed on click.

**Version**
- ids-enterprise v4.18

**Platform**
 - Chome

**Additional context**
Refer to this [line](https://github.com/infor-design/enterprise/blob/bb27ba44d631d664f01673d19f78cd9a0e1a8d54/src/components/tooltip/tooltip.js#L260)

**Comment by tmcconechy** [comment]
This should work ok in the new web component
