### ISSUE TITLE
IdsDropdown: dropdown menu is not aligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#1812]
**Describe the bug**
the menu is not aligned in the field

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-multiselect/example.html
2. Click on `Multiselect (with max 3 choices and dirty tracker)`
3. See error

**Expected behavior**
dropdown menu should be aligned in input field

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="517" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/2fc35986-acfd-40ef-8888-499803920e5c">

**Platform**
all

**Additional context**
related to https://github.com/infor-design/enterprise-wc/issues/1762

**Comment by tmcconechy** [comment]
Fixed this while doing other work, can you recheck? @jbrcna

**Comment by jbrcna** [comment]
confirmed. Test passed. Thanks @tmcconechy 
verified in https://main.wc.design.infor.com/ids-multiselect/example.html
<img width="394" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/87134c49-59f7-4b10-9ec2-acb738e63ce7">
<img width="458" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/f5cc7249-6ded-4d3c-a8dd-43d8fe093f02">
<img width="524" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/fcbe94a9-0eca-4473-99aa-474514e67f34">
