### ISSUE TITLE
IdsPopupMenu: Selected event gets fired multiple times on data grid

### ISSUE THREAD

**Issue by edisonferrer** [infor-design/enterprise-wc#1813]
**Describe the bug**
Context menu item selected event gets fired multiple times after doing successive context menu selects.

**To Reproduce**
1. Load the sample http://localhost:4300/ids-data-grid/contextmenu-before-show.html
2. Open the developer tools to see the console log when an item has been selected.
3. Do a context menu on either the header or the cell and select any item on the context menu. Do this multiple times.
4. Notice that on the developer tools, console logs of context menu item selected appears exponentially after each succeeding selects.

**Expected behavior**
item selected event only gets fired once per click.

**Version**
- ids-enterprise-wc: beta-18

**Screenshots**
https://github.com/infor-design/enterprise-wc/assets/47999751/8f8e9243-5110-42b4-b7a7-e93623ced3f3

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by jbrcna** [comment]
QA Passed
<img width="1696" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/0a73aa3d-4423-412b-8f93-9d58b7df5cca">
