### ISSUE TITLE
IdsPopup: Close popup on external click events

### ISSUE THREAD

**Issue by NikosLardas** [infor-design/enterprise-wc#1816]
**Description:**
 
The Ids Popup web component does not currently provide the option of closing the popup when the user clicks anywhere outside of the popup container limits. This functionality exists on the popup menu but currently not on the Ids Popup. This would be a helpful addition, that will be necessary for our project.
 
**Version:**
    "ids-enterprise-wc": "^1.0.0-beta.18",
    Angular: 16.2.10

**Comment by jbrcna** [comment]
go to http://localhost:4300/ids-popup/example.html
trigger the popup
the above scenario is working as expected.
![Large GIF (720x390)](https://github.com/infor-design/enterprise-wc/assets/56722184/953214f7-dabb-44d8-9a21-00f0b76d5ed8)

May i clarify if the other componenets should also close when you click outside?
some components does not close when you click outside
http://localhost:4300/ids-modal/example.html
http://localhost:4300/ids-action-panel/example.html 
![Large GIF (1106x544)](https://github.com/infor-design/enterprise-wc/assets/56722184/16f5a9fe-c8f7-4c43-af58-485a984f56a4)

**Comment by andrivarhanov** [comment]
@jbrcna the modal and actiion panel (contextual action panel) should not close on click outside, similar to enterprise components
https://main-enterprise.demo.design.infor.com/components/modal/example-index.html
https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-index.html

**Comment by jbrcna** [comment]
thanks for clarifying @andrivarhanov . moving this ticket to Done.
