### ISSUE TITLE
Missing icons in <ids-pager>

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-wc#1826]
**Describe the bug**
`<ids-pager>` is missing its direction icons.
Issue can be seen e.g. in the `enterprise-wc-examples` repo.

**To Reproduce**

1. Go to the pager example in `enterprise-wc-example` for Angular

**Expected behavior**
Direction icons should be visible

**Version**

- beta.19

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/542598/e529fa97-3b66-481d-8784-652790fa5ed0)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by jbrcna** [comment]
working as expected.
<img width="1086" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/f6ba141b-e9d5-47f4-878d-e006f8c8948f">
