### ISSUE TITLE
IdsTextArea: Can not longer type in it

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1827]
**Describe the bug**
Can not longer type in IdsTextArea

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-textarea/example.html
2. Try to type

**Comment by jbrcna** [comment]
QA Passed
<img width="1594" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/495f8a3e-901a-451a-8778-8e31cfcae36e">
