### ISSUE TITLE
Tests: Convert Dropdown Tests

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1846]
**Describe the bug**
Convert tests from tests-to-convert to tests and check coverage.

**Additional context**
N/A

**Comment by jbrcna** [comment]
may I help you on this one @clayinfor ?

**Comment by tmcconechy** [comment]
@jbrcna you can take this one as @clayinfor couldnt find time to finish it up. But there is a starting point:

https://github.com/infor-design/enterprise-wc/compare/1846-ids-dropdown-multiselect-tests?expand=1
branch name: 1846-ids-dropdown-multiselect-tests

So maybe you can resume the conversion on that branch. Thanks!!!

**Comment by jbrcna** [comment]
Sorry, @tmcconechy, I can't. We are not authorized to obtain tickets that have been given to someone else. Also, I have three tickets open right now, and am currently wip on slider. Thank you. I appreciate it.

**Comment by n-ace-ancog** [comment]
Is it correct @tmcconechy that the scope for this issue is for the dropdown component only? Since we already have another issue for the multiselect at #1957.

**Comment by tmcconechy** [comment]
@n-ace-ancog sure lets treat them as two issues, important thing is they get done one way or another.
