### ISSUE TITLE
IdsHyperlink: Still possible to click when disabled 

### ISSUE THREAD

**Issue by ajayponnapati** [infor-design/enterprise-wc#1849]
**Describe the bug**
I am using breadcrumbs as in the below code(same code as we have in  wc examples). Disabled Item should not be clickable.But click events are being triggered even on disabled item.Just disabled css class is added to the Disabled Item.

```
<ids-breadcrumb>
  <ids-hyperlink href="#">First Item</ids-hyperlink>
  <ids-hyperlink href="#">Second Item</ids-hyperlink>
  <ids-hyperlink disabled>Disabled Item</ids-hyperlink>
  <ids-hyperlink>Current Item</ids-hyperlink>
</ids-breadcrumb>
```

**To Reproduce**

1. run [https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-breadcrumb/demos/example.html](url)
1. Add a handler `$('[disabled').addEventListener('click', ()=> console.log())`
1. Click the disabled item
1. it is clickable

**Expected behavior**
Disabled hyperlink should not fire any click events

**Additional context**
Ms Teams

**Comment by glenlieorillo** [comment]
This is now working as expected.

https://github.com/infor-design/enterprise-wc/assets/102151352/37c2a495-5c8d-43cf-a2e6-7082287f37d6
