### ISSUE TITLE
Dropdown: Issue with form control value

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1850]
**Describe the bug**
Possibly after recent changes the dropdown form control value isnt changing.

**To Reproduce**

1. Go to https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc
2. `npm i && npm run start` to get the latest
3. Go to http://localhost:4200/ids-reactive-forms/example
4. Change the dropdown from option 4 to option 5
5. check the console and notice the form control value did not update
6. Can filter like this:

![Screenshot 2024-02-13 at 12 10 55 PM](https://github.com/infor-design/enterprise-wc/assets/814283/eaf78689-f865-445b-8d79-d4513655b263)

**Expected behavior**
Form control should update.

**Additional context**
Not 100% sure what caused this.

**Comment by jbrcna** [comment]
when searching in the lookup, no result was found. even tho the search term is available in the list
<img width="1458" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/d4427e66-a4f8-49f7-9229-710090d2479c">
<img width="997" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/2246171e-c932-4653-92a9-ca6b701403d0">

**Comment by tmcconechy** [comment]
@jbrcna can you make a new issue for that?
