### ISSUE TITLE
IdsTree: selected event returning incorrect node data after adding children through IdsTree.addNodes

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#1851]
**Describe the bug**
Adding children seems to cause issues with the node data sent through the selected event. The node data seems to be from the index of what element was there before the children were added.

**To Reproduce**

1. Go to 'http://localhost:4300/ids-tree/add-node.html'
2. Click on 'Add Node > As children of selected folder'
3. click on 'About Us' node 
4. See in console that the data returned is from new node

![image](https://github.com/infor-design/enterprise-wc/assets/4737815/d93b2ee8-f691-47fb-8c1a-1f5837fc5991)

**Expected behavior**
Correct node data should be sent through selected event.

**Version**

- latest ids-enterprise-wc (pulled from main)

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Window 11
 - Browser Name: latest chrome

**Comment by lucacolumbu** [comment]
re opening this as @pwpatton noticed that the issue persist, @andrivarhanov please take a look at this again
