### ISSUE TITLE
IdsMultiselect: Add typeahead example and feature

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#1867]
**Describe the Enhancement**
The IdsMultiselect should also support typeahead like dropdown does.

**Expected behavior**
- Add a typeahead example like ids-dropdown but in ids-multiselect
- See if it works as before https://main-enterprise.demo.design.infor.com/components/multiselect/example-index.html
- If it doesnt work make it work in multiselect or improve as needed

**Additional context**
https://github.com/infor-design/enterprise-wc/pull/1844

**Comment by tmcconechy** [comment]
@andrivarhanov can you check these maybe a recent PR has a fix?

**Comment by andrivarhanov** [comment]
@tmcconechy same as here https://github.com/infor-design/enterprise-wc/issues/2432
