### ISSUE TITLE
BusyIndicator/Loader: New Styles 

### ISSUE THREAD

**Issue by laurensteiger** [infor-design/enterprise-wc#187]
**Is your feature request related to a problem? Please describe.**
The current progress indicator looks out of place with uplift. It's also not as flexible as we would like it to be. 

**Describe the solution you'd like**
We have options for spinners, lines, buttons, determinate and indeterminate progress indicators. Designs can be viewed in the figma file below.

https://www.figma.com/file/PwwLkUtTxpxLzRJzm5kACM/Progress-Indicators?node-id=0%3A1

** Animation Demonstration **
![updated animation](https://user-images.githubusercontent.com/814283/87463380-4a1cc600-c5df-11ea-8d4e-eacfd8f62924.gif)

**Describe alternatives you've considered**
None

**Comment by tmcconechy** [comment]
I broke those out into the parts we should need to do and the breakout https://github.com/infor-design/enterprise-wc/issues/201 will replace this Dev task
