### ISSUE TITLE
IdsDatagrid: Filter Type Integer not allowing numbers after a leading zero

### ISSUE THREAD

**Issue by crisjoshua-inf** [infor-design/enterprise-wc#1877]
**Describe the bug**
Filter Types that use formatter integer does not allow leading zero numbers and even does not allow typing after the leading zero

**To Reproduce**
Go to http://localhost:4300/ids-data-grid/filter-trigger-fields.html and type leading zero in Price filter

1. Go to http://localhost:4300/ids-data-grid/filter-trigger-fields.html
2. Type leading zero in Price Filter
3. Attempt to type more numbers after leading zero
4. See unable to type more numbers

**Expected behavior**
Allow more numbers to be typed after leading zero and do not filter value even after filtering

**Version**
1.0.0-beta.21

**Platform**
Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
OS Version: [e.g. Windows 10 or iOS 8]
Browser Name: Google chrome
Browser Version: 121.0.6167.185 (Official Build) (64-bit)

**Additional context**
Discussed in teams: To add allowLeadingZeros setting
https://teams.microsoft.com/l/message/19:b649a7c426e64e3dbedb0cc5202ce2d4@thread.skype/1708340216737?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1708340216737&teamName=IDS%20Enterprise%20Development&channelName=Web%20Components&createdTime=1708340216737

**Comment by glenlieorillo** [comment]
This is now working as expected.

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/b9941c15-e0cd-463b-9e18-d0c8f32c2561">
