### ISSUE TITLE
IdsDropdown: Prevent the "enter" key here from opening the dropdown

### ISSUE THREAD

**Issue by crisjoshua-inf** [infor-design/enterprise-wc#1878]
**Describe the bug**
We need a way to prevent the "enter" key here from firing the open event of the dropdown. This is because the enter key functions as a form submission to server side filter/position. 

Also, discovered weird behavior when setting the idsDatagrid.data with a same value(acts as data refresh), the ids-dropdown-list DOM element doubles.

**To Reproduce**
For 1st Issue: Press enter on Dropdown filter (Will open the datagrid filter and has no means of not allowing this to happen)

For 2nd Issue: 
See zip attached is a code modification of the multiple-virtual-scroll files in wc code which added a "reset data button" which recalls the setData method.
[multiple-virtual-scroll.zip](https://github.com/infor-design/enterprise-wc/files/14353398/multiple-virtual-scroll.zip)

For 1st Issue:
1. Go to http://localhost:4300/ids-data-grid/filter-trigger-fields.html
2. Focus on NotFilteredItem Dropdown filter
3. Press Enter
4. Not possible in code to stop the enter event from preventing the opening of the dropdown

**Expected behavior**
Allow in code to stop the enter key event from firing to open the dropdown filter

For 2nd Issue:
1. Open zip file attached named multiple-virtual-scroll.zip and overwrite html and ts file in WC code with the same name "multiple-virtual-scroll"
2. Open http://localhost:4300/ids-data-grid/multiple-virtual-scroll.html
3. Click the Reset Data
4. Open Developer tools and look for ids-dropdown-list DOM element with ID = "ids-data-grid-filter-inStock-2-dropdown-list"
5. See error as ids-dropdown-list has duplicate element with same ID

**Expected behavior**
When resetting the datagrid data, DOM has to be unique. Only one ids-dropdown-list should be present.

**Version**
1.0.0-beta.21

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/115533426/57717d4c-a1cc-4f2f-9b9f-69e0aab666d7)

**Platform**
Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
OS Version: [e.g. Windows 10 or iOS 8]
Browser Name: Google chrome
Browser Version: 121.0.6167.185 (Official Build) (64-bit)

**Additional context**
Discussed in teams:
https://teams.microsoft.com/l/message/19:b649a7c426e64e3dbedb0cc5202ce2d4@thread.skype/1708073343085?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1708073343085&teamName=IDS%20Enterprise%20Development&channelName=Web%20Components&createdTime=1708073343085

**Comment by tmcconechy** [comment]
Makes sense lets follow https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select -> enter can be used to select an item but not open and close it. Space and down arrow down or up will open it
