### ISSUE TITLE
IdsModuleNav: The accordion Icons are missing in Angular

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise-wc#1881]
**Describe the bug**
Icons are no longer showing up when using the module nav component in Angular. This seems to be related to the use of dynamically created accordion as the icons work in the static example but not in the sandbox example using ng templates. 

A note for potentially finding the cause is that this was working in beta 17 and the issue was observed after upgrade to beta 19. Still an issue in beta 21. 

**To Reproduce**
This behavior can be observed in the module nav demo examples in [Angular examples](https://github.com/infor-design/enterprise-wc-examples/blob/main/angular-ids-wc/src/app/components/ids-module-nav/demos/sandbox/sandbox.component.html)

1. Open the angular-wc-examples and look at module nav sandbox demo
2. Notice the accordion icons are missing

**Expected behavior**
Icons should appear when the icon attribute on the ids-module-nav-item has a valid value. Correct behavior can be observed here: [main.wc](https://main.wc.design.infor.com/ids-module-nav/sandbox.html)

**Version**
- ids-enterprise: beta 21

**Screenshots**

![angularwc-moduleNav2](https://github.com/infor-design/enterprise-wc/assets/9215760/625355fe-187c-4e59-8844-477bb0e0ece1)

**Platform**
Angular 17
- Infor Application/Team Name: Infor M3 Portals

**Comment by clayinfor** [comment]
## Fixed:

<img width="1728" alt="Screenshot 2024-03-26 at 12 04 15 PM" src="https://github.com/infor-design/enterprise-wc/assets/93789065/30b28b49-4338-4164-8391-c10657d08820">
