### ISSUE TITLE
IdsModuleNav: Settings popup misaligned in Angular

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise-wc#1882]
**Describe the bug**
The popup menu triggered by ids-module-nav-settings does not align with the menu but rather pops up in the center of the page. 
sidenote: Seems to be an issue while using angular but works as intended in main wc.

**To Reproduce**
This behavior can be observed in the module nav demo examples in [Angular examples](https://github.com/infor-design/enterprise-wc-examples/blob/main/angular-ids-wc/src/app/components/ids-module-nav/demos/sandbox/sandbox.component.html)

1. Open the angular-wc-examples and look at module nav sandbox demo
2. Click the settings icon 
3. Notice how the popup is not aligning to the nav bar as intended

**Expected behavior**
The popup should align with the module nav nav bar. Correct behavior can be observed here: [main.wc](https://main.wc.design.infor.com/ids-module-nav/sandbox.html)

**Version**
- ids-enterprise: beta 21

**Screenshots**

![angularwc-moduleNav1](https://github.com/infor-design/enterprise-wc/assets/9215760/357b88d8-db4f-4bb5-b7ed-2a73635e32ff)

**Platform**
Angular 17

- Infor Application/Team Name: Infor M3 Portals

**Comment by andrivarhanov** [comment]
@tmcconechy just checked in Angular examples, it should be fixed, can confirm
