### ISSUE TITLE
IdsWizard: None of the examples work with Angular

### ISSUE THREAD

**Issue by SAIPRANAY-GANGULA** [infor-design/enterprise-wc#1885]
**Describe the bug**
None of IDS web-component wizard examples work with Angular.

https://stackblitz.com/~/github.com/SAIPRANAY-GANGULA/enterprise-ng-wc
1. Go to 'Wizard: A clickable 4-step wizard' example
2. Try accessing `example` & `sandbox`
3. We can't see any examples being displayed.
4. We have 2 errors in the console.

**Expected behavior**

**Version**
"ids-enterprise-wc": "^1.0.0-beta.20"

**Screenshots**

![image](https://github.com/infor-design/enterprise-wc/assets/56952302/8a275786-e2e4-417c-bb52-3ef46d533e76)
[screen-capture (4).webm](https://github.com/infor-design/enterprise-wc/assets/56952302/c552fdf4-b29f-419e-b400-9e0acd9a5133)

**Platform**
 - Infor Application/Team Name: Infor Process Intelligence
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: Version 121.0.6167.185 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
I think maybe that warning is going off because of the way angular loads the DOM. Will take a look
