### ISSUE TITLE
Notification banner dynamic variables in message-text for angular 

### ISSUE THREAD

**Issue by ilb-infor** [infor-design/enterprise-wc#1888]
**Describe the bug**
When I'm trying to use notification-banner to show a dynamic variable I have to use [attr.message-text]="errorMessages" to make it work. 
```
<ids-notification-banner
        id="error-message-for-configuration"
        type="error"
        [attr.message-text]="errorMessages">
      </ids-notification-banner>
```

**To Reproduce**
To reproduce it write where errorMessages is a variable like: 

let errorMessages = 'This is my perfect error message I would like to show'
```
<ids-notification-banner
        id="error-message-for-configuration"
        type="error"
        message-text="errorMessages">
        hidden="{{errorMessages.length === 0}}"
      </ids-notification-banner>
```

Add a notification banner to any page where you can use it and change between 'message-text' and '[attr.message-text]'

**Expected behavior**
I would like to see my message 'This is my perfect error message I would like to show' when I use a dynamic variable in message-text. 

**Version**
    "ids-enterprise-wc": "^1.0.0-beta.21" and angular version ^17.2.1

**Screenshots**

**With message-text:**
![Screenshot 2024-02-23 at 08 59 59](https://github.com/infor-design/enterprise-wc/assets/92725588/b6e2ef75-1fd3-4530-bd49-fc5e5412a919)

**With [attr.message-text]:**
![Screenshot 2024-02-23 at 08 59 36](https://github.com/infor-design/enterprise-wc/assets/92725588/96fb45f2-3888-4eb7-bd5e-de04b9169247)

**Platform**
 - Infor Application/Team Name: M3Portals
 - Device: Macbook Pro
 - OS Version: Somana 14.2.1
 - Browser Name: Chrome
 - Browser Version: Version 121.0.6167.184 (Official Build) (x86_64)

**Comment by tmcconechy** [comment]
See example on https://github.com/infor-design/enterprise-wc-examples/pull/60

**Comment by tmcconechy** [comment]
Seems like a dup of https://github.com/infor-design/enterprise-wc/pull/2104 maybe is fixed there
