### ISSUE TITLE
Modal: Clicking outside the modal issue

### ISSUE THREAD

**Issue by jomcab** [infor-design/enterprise-wc#1892]
**Describe the bug**
1. ids-modal keep-open feature is not working as expected.
2. Clicking outside the modal does not close the modal anymore.
3. Issue encountered both in react sample and Main Example site: https://main.wc.design.infor.com/ids-modal/keep-open.html

**To Reproduce**

1. Go to [https://github.com/infor-design/enterprise-wc-examples/tree/main/react-ts-ids-wc](https://github.com/infor-design/enterprise-wc-examples/tree/main/react-ts-ids-wc)
4. Update ids version in package.json: "ids-enterprise-wc": "^1.0.0-beta.21",
5. npm i && npm run start to get the latest
6. Go to http://localhost:3000/ids-modal
7. Click the Trigger Modal button, click outside the modal popup and see that it does not close the modal.

**Expected behavior**
Clicking outside the modal should close it.

**Version**
- "ids-enterprise-wc": "^1.0.0-beta.21"

**Platform**
 - Infor Application/Team Name: Rhythm Billing
 - Browser Name: Edge, Firefox, Chrome

**Comment by jbrcna** [comment]
QA Passed
![Large GIF (1712x590)](https://github.com/infor-design/enterprise-wc/assets/56722184/4a168192-9bc2-4c08-8968-007a59bfd213)
