### ISSUE TITLE
Checkbox: asterisk positioning issue when checkbox is required

### ISSUE THREAD

**Issue by jomcab** [infor-design/enterprise-wc#1893]
**Describe the bug**
Asterisk is displayed far right from checkbox label/texts

**To Reproduce**

1. Go to [https://github.com/infor-design/enterprise-wc-examples/tree/main/react-ts-ids-wc](https://github.com/infor-design/enterprise-wc-examples/tree/main/react-ts-ids-wc)
2. Update ids version in package.json: "ids-enterprise-wc": "^1.0.0-beta.21",
3. Update the label of required checkbox in examples/ids-checkbox/index.tsx:
`<ids-checkbox label="By checking this box, you agree to the Terms and Conditions and Privacy Policy." validate="required"></ids-checkbox>`
5. npm i && npm run start to get the latest
6. Go to http://localhost:3000/ids-checkbox
7. Adjust the browser's width and observe instances where the asterisk is far from the labell:
![image](https://github.com/infor-design/enterprise-wc/assets/12105280/06a075d1-1018-43d0-a3c2-a72fbb673547)

**Expected behavior**
Asterisk to be displayed near the label

**Version**
- "ids-enterprise-wc": "^1.0.0-beta.21"

**Platform**
 - Infor Application/Team Name: Rhythm Billing
 - Browser Name: Edge, Firefox, Chrome

**Comment by jbrcna** [comment]
QA Passed
<img width="390" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/23bb6186-cf95-4d92-b549-fc38f0d70c93">
