### ISSUE TITLE
Tests: Convert Checkbox Group Tests

### ISSUE THREAD

**Issue by AAlviar** [infor-design/enterprise-wc#1921]
Describe the task
Convert Checkbox Group tests from https://github.com/infor-design/enterprise-wc/tree/main/tests-to-convert/ids-checkbox-group to https://github.com/infor-design/enterprise-wc/blob/main/tests/ids-checkbox-group/ids-checkbox-group.spec.ts

Additional context
N/A

**Comment by n-ace-ancog** [comment]
Related issues:

- #2020 
- #2021
