### ISSUE TITLE
Tests: Convert Empty Message Tests

### ISSUE THREAD

**Issue by AAlviar** [infor-design/enterprise-wc#1932]
Describe the task
Convert Empty Message tests from https://github.com/infor-design/enterprise-wc/tree/main/tests-to-convert/ids-empty-message to https://github.com/infor-design/enterprise-wc/blob/main/tests/ids-empty-message/ids-empty-message.spec.ts

Additional context
N/A

**Comment by jbrcna** [comment]
may I help you on this one @yohannahbautista ?
