### ISSUE TITLE
Tests: Convert Hyperlink Tests

### ISSUE THREAD

**Issue by AAlviar** [infor-design/enterprise-wc#1941]
**Describe the task**
Convert Hyperlink tests from https://github.com/infor-design/enterprise-wc/tree/main/tests-to-convert/ids-hyperlink to https://github.com/infor-design/enterprise-wc/blob/main/tests/ids-hyperlink/ids-hyperlink.spec.ts

**Additional context**
N/A

**Comment by jbrcna** [comment]
and this one as well @glenlieorillo 😃

**Comment by jbrcna** [comment]
removing this on me .  apologies @glenlieorillo 😅 . you may continue your work in progress
