### ISSUE TITLE
Tests: Convert Locale Tests

### ISSUE THREAD

**Issue by AAlviar** [infor-design/enterprise-wc#1948]
Describe the task
Convert Locale tests from https://github.com/infor-design/enterprise-wc/tree/main/tests-to-convert/ids-locale

Additional context
N/A

**Comment by tmcconechy** [comment]
@n-ace-ancog one thing to note on this one is to check the coverage. The instinct would be to just code the tests the same way but i think they need to run in the page.

I need to write one test for this module so will try and set this up so you can see what i mean in the new file.
