### ISSUE TITLE
Tests: Convert Notification Banner Tests 

### ISSUE THREAD

**Issue by AAlviar** [infor-design/enterprise-wc#1958]
**Describe the task**
Convert Notification Banner tests from https://github.com/infor-design/enterprise-wc/tree/main/tests-to-convert/ids-notification-banner to https://github.com/infor-design/enterprise-wc/blob/main/tests/ids-notification-banner/ids-notification-banner.spec.ts

**Additional context**
N/A

**Comment by jbrcna** [comment]
@glenlieorillo may I help you on this one?
