### ISSUE TITLE
Tests: Convert Radio Tests

### ISSUE THREAD

**Issue by AAlviar** [infor-design/enterprise-wc#1966]
**Describe the task**
Convert Radio tests from https://github.com/infor-design/enterprise-wc/tree/main/tests-to-convert/ids-radio to https://github.com/infor-design/enterprise-wc/blob/main/tests/ids-radio/ids-radio.spec.ts

**Additional context**
N/A

**Comment by ericangeles** [comment]
There is an existing ticket in radio component conversion https://github.com/infor-design/enterprise-wc/issues/1872
