### ISSUE TITLE
Tooltip: Animation jiggle when showing and hiding

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#198]
**Describe the bug**
Seeing a newly noticed animation problem on tooltip. Noticed it did not happen on my branch so was one of the PR's in the this sprint.

**To Reproduce**
1. Go to http://localhost:4300/ids-tooltip
2. hover button -> see it jiggle a little
3. hover out of button -> see it jank off the page

**Expected behavior**
As it was before

**Additional context**
Noticed it did not happen on my branch so was one of the PR's in the last 10 days. Also reverted ids-popup and thats not it. But seems something in the context of the setting of properties.

Can be fixed by changing:

```
    this.popup.alignTarget = null;
    this.removeAttribute('visible');
    this.#hide();
 ```

to

```
    this.#hide();
    this.popup.alignTarget = null;
    this.removeAttribute('visible');
```

But want to make sure there isnt something worse happening.

**Comment by tmcconechy** [comment]
cc @EdwardCoyle @deep7102 for ideas?

**Comment by EdwardCoyle** [comment]
@tmcconechy It's possible this changed after the Modal PR, as there were some adjustments made to the Popup there.  However, I tested this against my Popup revisions branch for #135 and I'm not seeing the issue anymore.  Will test further and try to cover any more oddities found on my upcoming PR for that issue.

**Comment by tmcconechy** [comment]
ok perfect - i could use my fix but wasn't sure if this uncovered a bigger issue - its tricky to debug this one
