### ISSUE TITLE
General: Components stop working after removed/added from the DOM

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#2015]
**Describe the bug**
Some components / mixin stop working after the elements are removed & re-added from the DOM. Not sure which ones specifically except those listed here, but I assume that more are affected.

- IdsDropdown: The dropdown can no longer be closed after re-attaching.
- IdsInput: Validation stops working after re-attaching.
- IdsSwaplist: The `defaultTemplate` disappears

This issue was first discovered when using an Angular RouteReuseStrategy that attempts to restore the DOM state when routing. There are probably other ways that DOM elements can be removed/added which should cause the same issue.

**To Reproduce**

1. Go to https://stackblitz.com/edit/web-platform-cteeex?file=index.html
2. Click Detach
3. Click Attach
4. Try to interact with the components

**Expected behavior**
The components should behave as if they were never removed from the DOM.

**Version**

- ids-enterprise-wc: 1.0.0-beta.20

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/4991954/551

https://github.com/infor-design/enterprise-wc/assets/4991954/ff170039-6428-488a-bea5-3a87dc78fc68

1a609-b461-4f32-a6e3-0f94537d0acd

**Platform**
 - Infor Application/Team Name: Portal / Homepages

**Additional context**
Angular routing repro: https://oxford.awsdev.infor.com/Andreas.Hallberg/repro-route-reuse

This can be reproduced on some of the sample pages by running this in the dev tools console:

```js
(function() { const container = document.querySelector("ids-container"); const parent = container.parentNode; parent.removeChild(container); parent.appendChild(container); })()
```

This assumes that there is a single `<ids-container>` element which contains all the relevant sample template

**Comment by anhallbe** [comment]
Update: The dropdown issue is also in `<ids-date-picker>`, so I'm guessing the problem is in the popup? Or some shared mixin.

**Comment by anhallbe** [comment]
Update: The swaplist issue is probably this:
<img width="552" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/f9ff3a82-b46f-49f0-98a7-facbe300ffa3">

If the template is defined by setting the `defaultTemplate` rather than through a `<template>` element, this code will set the value to an empty string every time it is added to the DOM.

**Comment by tmcconechy** [comment]
@anhallbe on the swap list part I was doing it like this... To get around the `${}` being the same thing as string substitution  (which was what i was going for)

```
  // eslint-disable-next-line no-template-curly-in-string
  swaplist.defaultTemplate = '<ids-text>${text}</ids-text>';
```

**Comment by tmcconechy** [comment]
WIP: https://github.com/infor-design/enterprise-wc/tree/2015-reattach-comps
Fixed: Swaplist and Validation

@jdilag90 is working on dropdown/popup

**Comment by anhallbe** [comment]
@tmcconechy in Angular, if the template looks like this:

```html
<ids-swaplist>
	<template>
		<ids-text>${text}</ids-text>
	</template>
</ids-swaplist>
```

an error is thrown and crashes (at least with JIT compilation, I suspect something similar happens with AoT):

> Error: Errors during JIT compilation of template for _a39: Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("

Escaping it would look something like this:

```html
<template>
	<ids-text>{{'${text}'}}</ids-text>
</template>
```

...however, this doesn't work either. I *think* this is because the Angular binding is resolved *after* the swaplist is added to the DOM, so it's too late to set up a template. The value of the `defaultTemplate` property is `<ids-text></ids-text>`. See:

<img width="844" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/68add594-5a68-4a8e-939f-7b525496b703">

...so this is why we set the `defaultTemplate` property directly instead of the `<template>` approach (same as the ids-enterprise-examples sample). And that one fails because of the whole `defaultTemplate = .....` thing mentioned earlier.

**Comment by tmcconechy** [comment]
@anhallbe ok lets make a new issue for the template. Do you think we can make it work for angular somehow? But if you check my fix on that branch I made defaulTemplate a setter. So it resolves this issue for now that way.
