### ISSUE TITLE
IdsCheckBoxGroup: IdsCheckboxGroup.checkboxesSelected returns all instead of only selected checkboxes

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise-wc#2021]
**Describe the bug**
Calling the `IdsCheckboxGroup.checkboxesSelected` returns all, selected and not, checkboxes under the group.

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-checkbox-group/example.html
2. Open the developer's console
3. Type `document.querySelector('ids-checkbox-group').checkboxesSelected` and press enter
4. Return is 3 instead of 2

**Expected behavior**
Only selected checkboxes are return

**Version**
ids-enterprise-wc

**Screenshots**
![Animation](https://github.com/infor-design/enterprise-wc/assets/156752175/d60cefa8-5dc8-466e-adb9-70975c7b12ba)

**Comment by jbrcna** [comment]
QA Passed
<img width="1716" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/ff25362e-f178-40a9-9c73-59f709cbb56e">
<img width="1705" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/6202ce11-6dba-4e8a-be74-5d5d6cc2039a">
