### ISSUE TITLE
Value Attribute Do Not Change On IdsCheckbox/IdsSwitch

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#2027]
**Describe the bug**
When checking/unchecking a checkbox, the value attribute is not updated.

**To Reproduce**
- Open checkbox (and switch) example: https://main.wc.design.infor.com/ids-checkbox/example.html
- Check the first checkbox/switch
- The value attribute not changed to true

**Expected behavior**
When checked, change the attribute value to `true`, and if uncheck change to `false` as described in the doc: https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-checkbox

> `value` {string} set the checkbox value.

**Version**
Latest

**Comment by tmcconechy** [comment]
The checkbox uses the `checked` attribute like normal checkbox inputs use. The value is the name on submit https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

So its sort of different on this one. Maybe we need to add tests and update that doc. But i think you want checked meanwhile

**Comment by fabiojpoli** [comment]
yes I am using checked for now, but since is a field and listed on doc I was expecting similar to other fields. Same for switch

**Comment by tmcconechy** [comment]
Yes i will check the standards for this and update the docs and code as needed

**Comment by AAlviar** [comment]
This issue is also tracked in #2020 and #2021

**Comment by jbrcna** [comment]
QA Passed
<img width="1716" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/33a7f704-9b93-48c6-b061-b789fe12dd72">
