### ISSUE TITLE
Test: Test all components for reattach

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#2040]
**Describe the bug**
Related to https://github.com/infor-design/enterprise-wc/issues/2015 we need to understand

**To Reproduce**

1. Go to each example page in web components (main page is fine)
2. paste the following in the console (but change the component name

```
(function() { const container = document.querySelector("ids-container"); const parent = container.parentNode; parent.removeChild(container); parent.appendChild(container); })()
```

**Expected behavior**
Report any bugs related to this in the issue tracker. Could also add a unit test for it (think about it) but thats not as easy so not required for now.

**Comment by tmcconechy** [comment]
@n-ace-ancog let me know if unclear

**Comment by n-ace-ancog** [comment]
Is my understanding correct @tmcconechy, for now you need a list of components which are affected by this issue? If time permits and we know how to detect it, we add this scenario in the automated unit test in the future?

**Comment by tmcconechy** [comment]
Yes that's correct. We want to know where the issues are with this and fix this.

**Comment by jdilag90** [comment]
Hey @n-ace-ancog! Just adding to the conversation...

Can you do the reattach logic that @tmcconechy  provided in a `test.beforeEach`. Like image below for dropdown tests...
That way each feature test is validated against a reattached component.
The reattach `test.beforeEach()` doesn't have to be committed in the test conversion PR (unless it's stable lol)
But, it could give us a heads up on some problematic components that are reattached to the DOM.

![image](https://github.com/infor-design/enterprise-wc/assets/98347152/eb24bf05-195b-4459-8583-eb27d0a14545)

**Comment by n-ace-ancog** [comment]
@jdilag90 will look into this. 
I do have some concern in adding a re-attachment procedure in the `beforeEach` since some test case refers to the first instance of the element in the page, re-attaching them (now with a different position) may lead to some issues. Also, adding a new test case may be tricky, since we need to consider the elements positions before testing.

**Comment by tmcconechy** [comment]
@n-ace-ancog or maybe that could be done just as a "faster" way to identify the issues.

**Comment by tmcconechy** [comment]
@n-ace-ancog closing this for now as i heard you were done here. Thanks for all this. We have a lot of issues to fix now 👍🏻
