### ISSUE TITLE
IdsSwitch: Marked as checked when define value as false

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#2045]
There is an issue opened about value on switch: https://github.com/infor-design/enterprise-wc/issues/2027

However there is a strange behavior that I thought would be interesting to register in an issue.

When set initial attribute value as false:
```html
<ids-switch value=false></ids-switch>
```

The component is automatically changing the "checked" to the opposite value "true":
![Screen Shot 2024-03-13 at 4 14 54 PM](https://github.com/infor-design/enterprise-wc/assets/663908/5fddc16c-c388-410e-9d55-e4af203c462c)

**Comment by tmcconechy** [comment]
Try using `checked` instead of value here. But i think we could make this work like checkboxes in terms of the value setting. Need to research the correct bahvior for checkboxes and checked vs value

**Comment by tmcconechy** [comment]
@fabiojpoli fixed this but note that you probably want `checked`. The `value` for checkboxes is a string value that is submitted to the server.

https://stackoverflow.com/questions/14323899/what-does-the-value-attribute-mean-for-checkboxes-in-html

**Comment by jbrcna** [comment]
QA Passed
<img width="1716" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/e6f55c1e-bf3e-4303-8058-f4e24f99a818">
