### ISSUE TITLE
IdsGlobal: `personalize` & `version` recursive getter

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#2046]
**Describe the bug**
Accessing an imported `IdsGlobal.personalize` / `IdsGlobal.version` causes endless recursion, because of this line:

https://github.com/infor-design/enterprise-wc/blob/9f7f09fc45b5fb87c9b4f2a73e5e6555cc02b952/src/components/ids-global/ids-global.ts#L54

This crashes with a "Maximal call stack exceeded error"

Side-note: It's a little bit confusing that there is a global `IdsGlobal` on the Window, and a class with the same name can be imported. Especially since e.g VSCode automatically imports the class when it's used:

```ts
// from Window / globalThis
IdsGlobal.personalize.colo = "#fff";
``` 

```ts
import IdsGlobal from "ids-enterprise-wc/components/ids-global/ids-global";
IdsGlobal.personalize.colo = "#fff"; // Crashes
```

Additionally, the `window.IdsGlobal` typings are _only available after importing it_, which is extra confusing since the imported one is not the same as the one on the window.

**To Reproduce**

1. Import "IdsGlobal"
2. Access the `personalize` property

**Version**

- ids-enterprise-wc: 1.0.0-beta.20

**Platform**
 - Infor Application/Team Name: Portal / Homepages

**Comment by anhallbe** [comment]
Yeah the no-import global makes sense (unless there's a way to "scope" IdsGlobal somehow?).

It's just unfortunate that it has to be imported for Typescript to pick up that it exists. And the fact that VSCode automatically imports it (unless `window.IdsGlobal`):

https://github.com/infor-design/enterprise-wc/assets/4991954/99b414b8-1098-4f69-a106-130af52157f6

**Comment by tmcconechy** [comment]
Also wanted to point out that you can retype window like this in TS 

https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-global/ids-global.ts#L10-L21
