### ISSUE TITLE
IdsAppMenu/IdsModuleNav: Highlighting  the Active Main Menu 

### ISSUE THREAD

**Issue by shalini-patro12** [infor-design/enterprise-wc#2048]
**Issue**
In the app-menu [IDS App Menu Component (infor.com)](https://main.wc.design.infor.com/ids-app-menu/example.html) when user click on any ids-accordion-panel and navigate to respective screen after that highlight  colour  of ids-accordion-panel is removing when user right click on any where in the screen .

Willing to use module nav instead but it also has a problem with this.

**To Reproduce**

1.open app-menu example https://main.wc.design.infor.com/ids-app-menu/example.html
2. click on any panel it will navigate to that respective panel UI at  that moment it will be highlighting by blue colour border line, the moment you will click outside the blue border line will vanish.
3. even if you close the app menu and reopen the menu also there is no highlighting of that particular menu item. so user won't able to identify that on which panel exactly user is.

![image](https://github.com/infor-design/enterprise-wc/assets/148531844/271e9762-fe5c-48bd-9cc9-dddf8ed1935d)

 
**Requirement**
I want when user  click on any panel and navigate to respective UI after that if user will close the app menu and reopen the app menu that respective panel should be highlighted so that user will get to know that he/she is in this page.
Below i have attached the snippet of my code .
![image](https://github.com/infor-design/enterprise-wc/assets/148531844/8876fe05-b824-43d1-bef5-19948a865079)

```
<ids-accordion>
				<ids-accordion-panel>
					<ids-module-nav-item id="item-document"
												slot="header"
												icon="home"
												aria-expanded="true"
												display-mode="expanded"
												selected="true"
												(click)="changeTab('home','Home')">
						<ids-text font-size="16"
									 overflow="ellipsis">{{language['HOME']}}
						</ids-text>
					</ids-module-nav-item>
				</ids-accordion-panel>
				<ids-accordion-panel>
					<ids-module-nav-item id="item-document"
												slot="header"
												icon="home"
												aria-expanded="true"
												display-mode="expanded"
												selected="true"
												(click)="changeTab('symphonies','Symphonies')">
						<ids-text font-size="16"
									 overflow="ellipsis">
							{{language['SYMPHONIES']}}
						</ids-text>
					</ids-module-nav-item>
				</ids-accordion-panel>

				<ids-accordion-panel>
					<ids-module-nav-item id="item-document"
												slot="header"
												icon="user-folder-open"
												aria-expanded="true"
												display-mode="expanded"
												selected="true"
												(click)="changeTab('extension','Extension')">

						<ids-text font-size="16"
									 overflow="ellipsis">
							{{language['EXTENSION']}}
						</ids-text>
					</ids-module-nav-item>
				</ids-accordion-panel>
				<ids-accordion-panel>
					<ids-module-nav-item id="item-document"
												slot="header"
												icon="workflow"
												aria-expanded="true"
												display-mode="expanded"
												selected="true"
												(click)="changeTab('configuration','Configuration')">
						<ids-text font-size="16"
									 overflow="ellipsis">
							{{language['CONFIGURATION']}}
						</ids-text>
					</ids-module-nav-item>
				</ids-accordion-panel>
			</ids-accordion>
			```

**Comment by tmcconechy** [comment]
Note the module-nav is the go forward menu for new adoption. I suggest using it instead.

**Comment by hey-yall** [comment]
Slated for design work in Jira: https://inforwiki.atlassian.net/browse/IDS-2057

**Comment by tmcconechy** [comment]
New design: https://www.figma.com/file/JZdeun4ht1IsqZpV9xAW8Y/Colors?type=design&node-id=1980-220378&mode=design&t=SlfqWXrTREDo1ibZ-4

**Comment by tmcconechy** [comment]
Good to go: Use design https://www.figma.com/file/JZdeun4ht1IsqZpV9xAW8Y/Colors?type=design&node-id=1980-220378&mode=design&t=1DorDPXOyfvFDPQL-0

Apply the same highlight color to both app nav and module nav.
