### ISSUE TITLE
IdsModal: "Scrollable" option not working as intended

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise-wc#2049]
**Describe the bug**
The scrollable option does not seem to have any effect on initial load of a modal. After adding `scrollable="true"` to the ids-modal does not seem to have scrollable support until there is a change such as a window rezise. after a window resize for example the scrollbar appears. 

**To Reproduce**
One can add a lot of content to the wc examples modal demo.(In my case angular wc examples)

1. In modal demo in wc examples project add a lot of content to a modal and the attribute to enable scroll
2. run and view the modal demo example
3. notice no scroll support so with enough content the content simply disappears outside of the screen
4. resize window
5. notice scroll bar appeared

**Expected behavior**
Scrollable attribute should enable scroll support for modal content on initial load of modal.

**Version**
- ids-enterprise: [1.0.0-beta.21](https://github.com/infor-design/enterprise-wc/releases/tag/1.0.0-beta.21)

**Screenshots**

![modalscroll](https://github.com/infor-design/enterprise-wc/assets/9215760/6f9150a2-0d7f-4893-91e2-a08531037295)

**Platform**
- Angular 17
 - Infor Application/Team Name: M3 Portals

**Comment by tmcconechy** [comment]
I cant recall why we have this option? Why would you not want it to scroll? But i see the issue with the scrollbar that should be corrected.
