### ISSUE TITLE
IdsHeader: `color` changes global personalization

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#2050]
**Describe the bug**
Setting the `color` attribute on a `<ids-header>` also changes the global personalization color. 

Given the following code:

```html
      <ids-header color="#ffffff">
        <ids-toolbar>
          <ids-toolbar-section type="title">
            <ids-text font-size="32">White Header</ids-text>
          </ids-toolbar-section>
        </ids-toolbar>
      </ids-header>

      <ids-header color="#000000">
        <ids-toolbar>
          <ids-toolbar-section type="title">
            <ids-text font-size="32">Black Header</ids-text>
          </ids-toolbar-section>
        </ids-toolbar>
      </ids-header>

      <ids-button appearance="primary">Primary Color</ids-button>
```

1. Instead of one white header and one black, both are black.
2. The primary button is also black

**To Reproduce**

1. Go to https://stackblitz.com/edit/web-platform-ptneuk?file=index.html
3. See issue

**Expected behavior**
Setting the header color should not affect other elements.

**Version**

- ids-enterprise: 1.0.0-beta.20

**Screenshots**
<img width="538" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/2bc7534e-71f5-4b48-8e98-91a3183851e4">

**Platform**
 - Infor Application/Team Name: Portal / Homepages

**Additional context**
The reason I wanted to set the color in the first place is to get a header to match the old SohoPersonalizeDirective, without also setting the color of all buttons/radio etc.

**Comment by tmcconechy** [comment]
Ok, Bug makes sense. We introduced a newer way to do the personalization with the theme.

https://main.wc.design.infor.com/ids-personalize/example.html

Maybe just need to reconcile this with the header component

**Comment by anhallbe** [comment]
Related: https://github.com/infor-design/enterprise-wc/issues/2054

Regarding the personalization API: Yes I think that'll work for us. The reason I wanted to set a header color explicitly is because I'm not sure if we want all the other elements to also use the personalization color. It looks good, but when mixing the old jQuery/Angular components with new ones we'll end up with different colors for buttons etc.

Will have to look into how we're going to solve this on our end, but we _might_ end up needing some way to only apply personalization to headers, and not other elements.
