### ISSUE TITLE
IdsDropDown: Tooltip is not set in option when is loaded by Ajax

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#2051]
When set tooltip on static options in dropdown works fine, but not when the option is loaded later (like by Ajax request).

**To Reproduce**
Following the Ajax example in the documentation: https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-dropdown

```html
<ids-dropdown id="dropdown-7" label="Dropdown Using Ajax" value="ak">
  <ids-list-box>
    <ids-list-box-option value="ak" id="ak">Alaska</ids-list-box-option>
 </ids-list-box>
</ids-dropdown>
```

```javascript
const dropdownAsync = document.querySelector('#dropdown-7');

dropdownAsync.beforeShow = async function beforeShow() {
  const url = '/data/states.json';
  const res = await fetch(url);
  const data = await res.json();
  return data;
};
```

1. On `states.json`, change the first record, adding icon and tooltip for it:
```json
[
	{
		"value": "al",
		"label": "Alabama",
		"tooltip": "State of Alabama",
		"icon": "project"
	},
	...
]
```
2. Reload the page

**Expected behavior**
The first option `Alabama` will bring an icon and a tooltip `State of Alabama` when passing the mouse over the option. The icon is showing but not the tooltip.

**Screenshots**
![Screen Shot 2024-03-14 at 7 53 48 AM (2)](https://github.com/infor-design/enterprise-wc/assets/663908/119904d5-6916-43b0-af99-4bc2da98fca6)

**Comment by jbrcna** [comment]
QA Failed. tooltip is not displayed
Also, using safari or firefox, the dropdown won't open when using click. sometimes there is a significant delay. using Enter key will open the dropdown right away.
<img width="886" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/181ef86c-555d-4984-9aa9-522f0585cd56">

**Comment by tmcconechy** [comment]
@jbrcna looking ok for me now. Maybe temporary? Or can you raise a new issue.

**Comment by jbrcna** [comment]
the issue still exists @tmcconechy . created a new issue https://github.com/infor-design/enterprise-wc/issues/2159
