### ISSUE TITLE
IdsCheckBox: re-attaching issue on required checkbox

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise-wc#2052]
**Describe the bug**
After re-attaching the `ids-check-box`, required validation is lost. Related to #2040.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-checkbox/example.html
2. Open developer's console
3. Type `(function() { const container = document.querySelector('ids-checkbox[label="Required"]'); const parent = container.parentNode; parent.removeChild(container); parent.appendChild(container); })()` then enter
4. Select and unselect the required checkbox
5. No error is displayed

**Expected behavior**
Required message appears

**Screenshots**
![Animation](https://github.com/infor-design/enterprise-wc/assets/156752175/8d2db90e-7125-41f1-98b7-3ee2ad1e12ef)

**Comment by tmcconechy** [comment]
Also fixed on https://github.com/infor-design/enterprise-wc/pull/2044

**Comment by n-ace-ancog** [comment]
Confirming that the issue is fixed.

![Animation](https://github.com/infor-design/enterprise-wc/assets/156752175/60ced277-5199-44f5-9dc3-80ce81fb7461)
