### ISSUE TITLE
IdsPersonalize: Alabaster White

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#2054]
**Describe the bug**
There are a couple of things going on when trying to use the "Alabaster" (#fff) as a personalization color. Not sure if bug or if I'm missing something.

1. Setting the color to `#fff` (old Alabaster color) causes some colors to be off, e.g the Header text color.
2. Setting it to `#ffffff` or `#fff` also causes buttons and other elements to become white (invisible).

Both of these make sense since `#fff` is not a full hex color, and if `#ffffff` is the primary color, then of course elements should use that color. However, if neither of these are usable, then how would one select the "Alabaster"/default color?

For example, in the Personalize sample ( https://main.wc.design.infor.com/ids-personalize/example.html ) the header starts out as white. But if you pick another color then it is not clear how to make it white again.

**To Reproduce**

1. Go to https://stackblitz.com/edit/web-platform-5dyza7?file=index.html
3. Click on 'Set color to ....' buttons

**Expected behavior**
Not sure to be honest. But somehow we need to be able to switch to the default (Alabaster) color.

**Version**

- ids-enterprise: 1.0.0-beta.20

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/4991954/9d700bcd-5914-4ae6-bc6d-750c07b8359c

https://github.com/infor-design/enterprise-wc/assets/4991954/3eccee74-ef4d-411e-9a94-41e10ae06465

**Platform**
 - Infor Application/Team Name: Portal / Homepages

**Comment by tmcconechy** [comment]
yeah agreed. I forget to or maybe need to add some sort of a `resetToDefault`. But in that example what will actually fix it technically is removing the new style sheet it adds with the updated color tokens.

Maybe the reset command would do this.

**Comment by anhallbe** [comment]
Something like this?
<img width="483" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/9a26a186-5e9a-438c-a8b6-b8f0574e8175">

**Comment by tmcconechy** [comment]
Yeah just has to be after the other style sheets to take presence. But I will work on these and add think about some API improvements.
