### ISSUE TITLE
IdsModuleNav/IdsAppMenu: Ability to provide a container for the menu

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#2074]
**Is your feature request related to a problem or use case? Please describe.**
In our application, we would like to use the `<ids-app-menu>` in a nested context. I.e when the menu is opened, it should not affect the size (or overlay) the whole `<ids-container>`. Think:

```
------------ masthead ------------
-------------- tabs --------------
|      | --------- header ---------
|      |
|  app |
| menu |      Content
|      |
|      |
```

However, the application menu is fixed to the viewport (`position: fixed;`) and the size of the `<ids-container>` changes based on whether the app menu is open etc.

**Describe the solution you'd like**
Provide a new (optional?) element that can work as an alternative container for the app menu: `<ids-app-menu-context>` or `<ids-app-menu-container>`?

This element would do what the `ids-container` currently does in terms of the app menu. I.e the app menu would cover the height of its' containing `ids-app-menu-context`, and would be resized if needed when the menu is opened. It may be a good idea to have this as an optional element, and just use the `<ids-container>` if no other container is found.

**Describe alternatives you've considered**
Tried to do this with CSS, with some success. But it feels very hacky and not really a solution:

<img width="642" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/f9af7c15-6b74-4ec9-8bdb-420403e2c7c3">

**Additional context**
And what application do you work on? Portal

**Comment by tmcconechy** [comment]
@anhallbe where do you picture the app-nav-container sitting? Something like this?

```
ids-container
  ids-masthead
  ids-tabs
  ids-app-nav-container
    ids-app-nav
       header
       contents
```

or

```
  ids-app-nav-container
  ids-masthead
  ids-tabs
    ids-app-nav
       header
       contents
```

or something else? I think it get this but trying to picture it. what if the component just resized based on whats in front if in the container?
