### ISSUE TITLE
IdsButton: The `<span>` should be optional

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#2080]
**Is your feature request related to a problem or use case? Please describe.**
`<ids-button>` looks different depending on whether it has a `<span>` or not. This is easy to forget because:

1. It is not apparent _why_ the `<span>` is needed, semantically.
2. HTML `<button>` does not require a `<span>`

**Describe the solution you'd like**
Make the `<span>` optional, with or without icons.

```html
<!-- This -->
<ids-button>Hello</ids-button>

<!-- ...should look and behave the same as this -->
<ids-button>
    <span>Hello</span>
</ids-button>
```

**Additional context**
Related: #2079 

And what application do you work on? Portal

**Comment by tmcconechy** [comment]
https://github.com/infor-design/enterprise-wc/pull/2065 mostly fixes this but i cant get the icon + no span to work

Wierd:
```
<ids-button><ids-icon icon="folder"></ids-icon>Button label</ids-button>
```

OK:
```
<ids-button><ids-icon icon="folder"></ids-icon><span>Button label</span></ids-button>
```

So when i use the icon i need the span to target. Dont think there is a css rule for textNodes? So will leave this open for more work later.

Example added http://localhost:4300/ids-button/no-span.html -> remove the span on the first icon one to test

**Comment by tmcconechy** [comment]
@anhallbe I made this work but i think its probably better for the buttons that have two things in the slot to use a `span` so i would stop short of reccomending this.

New soon to be added example is http://localhost:4300/ids-button/no-span.html
