### ISSUE TITLE
IdsSplitter: Need a way to set the splitter position when calling expand. 

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#2083]
**Is your feature request related to a problem or use case? Please describe.**
User slides the splitter all the way to the left then clicks the expand/collapse button (to expand) but nothing happens until you click the expand button again (and then it shows the splitter way to the right).

**Describe the solution you'd like**
If the users drags the splitter to zero would like the splitter to return to the original default when the expand/collapse button is clicked.

**Describe alternatives you've considered**
I don't have any other alternatives that seem to work. 

**Additional context**
And what application do you work on? Landmark

![splitter-expand-issue](https://github.com/infor-design/enterprise-wc/assets/4737815/e96b876d-e195-4f36-832d-9a76ac7ee260)

**Comment by tmcconechy** [comment]
@andrivarhanov thinking about this one...

1) add expand/collapse and a toggle function to do the expanding
2) when you collapse should save position
3) when you expand/toggle it restores the position
