### ISSUE TITLE
IdsNotificationBanner: Not updating valuing when value changes

### ISSUE THREAD

**Issue by ilb-infor** [infor-design/enterprise-wc#2087]
**Describe the bug**
When I calculate the error to show in the notification banner it does not change value.

**To Reproduce**
Use this: 
where the list of errorMessages = ['Field 'HEI' is invalid.']
```
    <ids-layout-grid-cell>
      <ids-notification-banner
        *ngIf="errorMessages.length > 0"
        id="error-message-for-configuration"
        type="error"
        [attr.message-text]="errorMessages"
      >
```

When I change programaticly so it removes it error code since everything is correct the notification banner do not update itself.  (I use [attr.message-text] because of: https://github.com/infor-design/enterprise-wc/issues/1888)

**Expected behavior**
I want when I have no error messages to update the banner so I do not have any errors.

**Version**
- ids-enterprise: 1.0.0-beta.21

**Screenshots**
First image when I have my error and then my ids-editor is red for the invalid value:
![Screenshot 2024-03-20 at 11 20 14](https://github.com/infor-design/enterprise-wc/assets/92725588/e5b85a77-3a39-4862-b675-4a6146caa56e)
Here I have validated and have no errors, but my ids-notification-banner still shows error: 
![Screenshot 2024-03-20 at 11 20 22](https://github.com/infor-design/enterprise-wc/assets/92725588/255dfa2f-d5ba-488c-860a-a3cb71591d00)

**Platform**
 - Infor Application/Team Name: M3Portals
 - Device: Macbook Pro
 - OS Version: Sonoma 14.4
 - Browser Name: Chrome
 - Browser Version: Version 122.0.6261.129 (Official Build) (x86_64)

**Additional context**

**Comment by tmcconechy** [comment]
Will test this out but did you try both these: https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc#attributes-and-settings

May also be linked to #1784
