### ISSUE TITLE
IdsTabs: Improve margin and colors

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise-wc#2095]
**Describe the bug**
1. The text of unselected tabs isn't very visible in dark mode.
2. The horizontal line underneath the tabs is too light in dark mode
4. The `margin-inline-start: 4px;` makes the position of the first tab look a little off

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-tabs/example.html
2. Notice how the position of the first tab looks a little off
3. Change to dark mode
4. Notice the color of the unselected tabs
5. Notice the color of the horizontal line

**Expected behavior**
Should probably look the same as in the core component

**Screenshots**
### Web component
![wc](https://github.com/infor-design/enterprise-wc/assets/63045013/b9d3adae-98a6-41c2-829f-034614876af4)

### Core component
![core](https://github.com/infor-design/enterprise-wc/assets/63045013/4529dbdc-9e36-4b64-9e87-c77d0cebf221)

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by tmcconechy** [comment]
https://github.com/infor-design/enterprise-wc/pull/2065 will change this. Will post back here shortly with a screen shot

**Comment by tmcconechy** [comment]
This is the new look. Will update the inset margins too. Not needed

![Screenshot 2024-03-26 at 3 41 46 PM](https://github.com/infor-design/enterprise-wc/assets/814283/485d372a-9e77-4117-ad14-2215a6e5707b)
