### ISSUE TITLE
IdsDropdown: Does not work in Safari

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#2096]
**Describe the bug**
IdsDropdown can't be opened in Safari. 

Same issue in both macOS and iOS.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-dropdown/example.html
2. Click on the dropdowns
3. The dropdowns cannot be opened

**Expected behavior**
Same as Chrome

**Version**

- ids-enterprise: 1.0.0-beta.22

**Screenshots**

**Platform**
 - Infor Application/Team Name: Portal
 - Device: MacBook Pro
 - OS Version: macOS Sonoma 14.4
 - Browser Name: Safari
 - Browser Version: 17.4

**Additional context**
Works fine in Chrome on the same machine

**Comment by glenlieorillo** [comment]
This is now working as expected in Safari.


https://github.com/infor-design/enterprise-wc/assets/102151352/7bc961c1-4921-4368-8706-691af1d0ddde


https://github.com/infor-design/enterprise-wc/assets/102151352/e0c620f8-f716-466f-bd7a-cd4e7c861001
