### ISSUE TITLE
IdsNotification: Icon is switching position after reattach

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise-wc#2114]
**Describe the bug**
IdsNotification: Icon is switching position after reattachment 
**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-notification-banner/standalone-css.html
2. Paste `(function() { const container = document.querySelector(".ids-notification-banner .alert"); const parent = container.parentNode; parent.removeChild(container); parent.appendChild(container); })()`

**Expected behavior**
Notification Icons should not change position
**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/45757016/68578504-d82c-4567-aa9c-427378805424">

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@janahintal i dont think one is a problem. I think the command should be..

```
(function() { const container = document.querySelector("ids-container"); const parent = container.parentNode; parent.removeChild(container); parent.appendChild(container); })()
```

Also should be on https://main.wc.design.infor.com/ids-notification-banner/example.html not the standalone css page. So since its seems working will close
