### ISSUE TITLE
IdsDataGrid: IdsDataGridColumn is missing the "ranges" option

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise-wc#2122]
**Describe the bug**
`IdsDataGridColumn` is missing the `ranges` option, which was in the core/angular component used for the `alert`, `badge` and `tag` (maybe more?) formatters.

In the web component, this isn't really a problem for `badge` and `tag` since `color` can be set dynamically for each row, but it's problematic for `alert` because it also uses `icon` which can't be set dynamically for each row due to not accepting a function.

**Expected behavior**
a) There should be a `ranges` option on `IdsDataGridColumn`
**OR**
b) change `icon` so that either a string or a function can be passed to it, the same way as for `color`, i.e:
`icon?: string | ((some row data) => string);`

Option `b` is probably preferable since it seems to be easier overall for everyone.

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by tmcconechy** [comment]
Yes i like b) better. The ranges option was a bit confusing to use.
