### ISSUE TITLE
Examples: Angular example doesn't work in subfolder (APP_BASE_HREF)

### ISSUE THREAD

**Issue by leensmits** [infor-design/enterprise-wc#2125]
Hi,

1. Take [angular-ids-wc](https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc)
2. npm install
3. npm run build
4. Copy dist/demo/browser to your local webserver http://yourlaptop/demo

Chunk files and themes are missing.

# Changes to get this working in the past

### angular.json
Add baseHref  "./"
```
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "outputPath": "dist/demo",
            "baseHref": "./",
```
### src/app/app-routing.module.ts
```
import { APP_BASE_HREF } from '@angular/common';
....
exports: [RouterModule],
  providers: [
      {
        provide: APP_BASE_HREF,
        useValue: window['base-href' as any]
      }
    ]
```

### src/index.html
```
...
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600&amp;display=swap" rel="stylesheet"/>
    <script>
      window['base-href'] = window.location.pathname;
      console.log(window['base-href']);
  
      if (global === undefined) {
        var global = window;
      }
    </script>
...
```

## Result (partial successful)
After these changes, the chunks are found.
But the theme is still not found.
`GET http://myserver/demo/.../themes/ids-theme-default-light.css 404 (Not Found)`

**Comment by tmcconechy** [comment]
@leensmits did you see the part about the assets on https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc maybe need to add the assets for the style sheets if you did not?

```
"assets": [
  {
    "glob": "**/*",
    "input": "./node_modules/ids-enterprise-wc/themes",
    "output": "themes"
  }
],
```

I think people where able to get this working but not sure. Also not sure about the step 4. About copying the files. Dont you need to just do this via Angular config?

i.e. the older repo does it in a subfolder https://github.com/infor-design/enterprise-ng-quickstart but not copying it manually.

Aside from those initial tips we will find some time to try this out

**Comment by leensmits** [comment]
@tmcconechy 
it is an exact copy of enterprise-wc-examples/tree/main/angular-ids-wc
So if I do:
1. Take [angular-ids-wc](https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc)
2. `npm install`
3. `npm run build`
4. Copy `dist/demo/browser` (its contents) to your local webserver http://yourlaptop/
It works.

So in both cases, I have the section from the sample code:
```
"assets": [
              "src/favicon.ico",
              "src/assets",
              "src/api",
              {
                "glob": "**/*",
                "input": "./node_modules/ids-enterprise-wc/locale-data",
                "output": "/locale-data"
              },
              {
                "glob": "**/*",
                "input": "./node_modules/ids-enterprise-wc/themes",
                "output": "themes"
              }
```
So, in both cases, with the modifications mentioned in the issue text. or without.
The themes folder is there. But the dynamic (or static / ) compilation of the themes/style path doesn't seem to honor the ./  current folder.

**Comment by tmcconechy** [comment]
@leensmits I think the only way to make this work is to not serve the files from node_modules as shown in that example. Instead:

1. Copy node_modules/themes to the project in a themes folder
2. adjust the theme output

```
              {
                "glob": "**/*",
                "input": "myproject//themes",
                "output": "themes"
              }
```

3. And or put the theme input direct in the index.html (may not need 2)
```
  <link id="ids-theme" href="yourpath/themes/ids-theme-default-light.css" nonce="0a59a005" rel="stylesheet">
```

If you do this the code will not try and load them from node_modules instead will look for that ID. Give that a try and let me know.

I cant see anything else we can do since we do already support just manually adding the style sheet for these case.

**Comment by kenneth-acejo** [comment]
We also have this issue when deploying to our servers. Somehow it looks for the themes folder in 
**<hostname>/eventhub/** instead of 
**<hostname>/eventhub/ui/**

Upon delving deeper, the error led me to this in class **IdsElement** inside function **loadTheme**
```
const baseHref = document.querySelector('base');
const subUrl = baseHref?.getAttribute('href') || '/';
const response = await fetch(`..${subUrl}themes/ids-theme-${theme}.css`, { cache: 'default' });
```

I noticed parent directory is used ".."
Should this be the case?

**Comment by tmcconechy** [comment]
@kenneth-acejo in the cases we had this works. What would work here for you? Just single dot or relative?

What about specifying the theme file directly as per https://github.com/infor-design/enterprise-wc/issues/2125#issuecomment-2261181423 as i tested that and it works for more complex URLS

**Comment by kenneth-acejo** [comment]
@tmcconechy I'm not sure of the location of the relative path, I'm thinking where IdsElement resides but I'm not really sure so I think single dot would work for us. 

When you specify the theme file directly, can you still switch themes from light to either dark or contrast ?

**Comment by tmcconechy** [comment]
@kenneth-acejo yes it will change the theme it will look for the id in:

` <link id="ids-theme" href="yourpath/themes/ids-theme-default-light.css" nonce="0a59a005" rel="stylesheet">`

And update the last part of the URL. Another idea if we need it is a setting like `IdsGlobal.themesPaths`?

**Comment by kenneth-acejo** [comment]
That's actually better so we don't have to create another file like index.prod.html in angular.
