### ISSUE TITLE
IdsModuleNav/IdsAppMenu: Height does not subtract the ids-masthead height

### ISSUE THREAD

**Issue by leensmits** [infor-design/enterprise-wc#2126]
**Describe the Issue**
If you have a masthead, followed by a container that contains the module-navigation, the height of the module navigation is not corrected with the height of the masthead.

**To Reproduce**
https://stackblitz.com/edit/ids-enterprise-wc-beta-22-fvdnzv?file=index.html
- Sorry, I can't get the component working inside stackblitz.

```
<ids-layout-grid auto-fit="true" id="ids-masthead-list" col="1">
  <ids-layout-grid-cell>
      <ids-masthead title="Infor Documentation &amp; Localization" icon="logo" role="navigation">
      <section title="end" slot="end">
          <ids-button icon="user"><span class="audible">User Button</span></ids-button>
          <ids-button icon="link"><span class="audible">Disconnect</span></ids-button>
          <ids-button icon="unlink"><span class="audible">Connect</span></ids-button>
      </section>
      </ids-masthead>
  </ids-layout-grid-cell>
</ids-layout-grid>
<ids-container padding="0" hidden>
    <app-nav></app-nav>  <!-- this is the ids-module-nav component -->
    <router-outlet></router-outlet>
</ids-container>
```

**What are you trying to do**
- How can I wrap the ids-module-nav so that the height fills up 100%.

**Version**

- ids-enterprise-wc: 0.22

**Platform**
 - Device   
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version Version 123.0.6312.59 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
What if you use:

```
<ids-container padding="0" hidden>
    <ids-masthead title="Infor Documentation &amp; Localization" icon="logo" role="navigation"></ids-masthead>
     <app-nav></app-nav>
    <router-outlet></router-outlet> <-- in here <ids-layout-grid>
</ids-container>
```

May not work on first try but at least we can make a css rule if they are siblings.

**Comment by leensmits** [comment]
I could work around this issue using:  
`::ng-deep ids-module-nav-bar { top: 40px; }`

**Comment by tmcconechy** [comment]
OK good, I think by structure we can make this work in example as well
