### ISSUE TITLE
IdsTree: Unable to change tree node icon with children 

### ISSUE THREAD

**Issue by kenneth-acejo** [infor-design/enterprise-wc#2151]
**Describe the bug**
I am not sure if this ticket qualifies a bug or maybe a feature request but setting the icon for a tree node with children is not working.

**To Reproduce**

**sandbox.ts**

```
import IdsIcon from '../../ids-icon/ids-icon';
import appIconJSON from '../../ids-icon/demos/app-icon-data.json';
import customIconJSON from '../../ids-icon/demos/custom-icon-data.json';

(async function initIcons() {
  const customIconUrl: any = customIconJSON;
  const customIconRes = await fetch(customIconUrl);
  const customIconData = await customIconRes.json();

  const appIconUrl: any = appIconJSON;
  const appIconRes = await fetch(appIconUrl);
  const appIconData = await appIconRes.json();

  IdsIcon.customIconData = { ...customIconData, ...appIconData };
}());
```

**tree-basic.json**

```
[
  {
    "id": "home",
    "text": "Home",
    "children": [],
    "icon": "custom-airplane"
  },
  {
    "id": "about-us",
    "text": "About Us",
    "some-extra-data": "Some extra data to use with this node",
    "xyz": "any key/value to be used for some other related",
    "children": [],
    "icon": "custom-cargo-ship"
  },
  {
    "id": "public-folders",
    "text": "Public Folders",
    "children": [],
    "icon": "custom-popup-media"
  },
  {
    "id": "icons",
    "text": "Icons",
    "expanded": "false",
    "icon": "custom-cargo-ship"
  },
  {
    "id": "blog",
    "text": "Blog",
    "icon": "custom-popup-media"
  },
  {
    "id": "contacts",
    "text": "Contacts",
    "icon": "custom-airplane"
  }
]
```

1. Edit src\components\ids-tree\demos\sandbox.ts and add the code above.
2. Edit src\assets\data\tree-basic.json and put the sample data above.
3. Go to http://localhost:4200/ids-tree/sandbox.html
4. Observe that the icons for "Icons", "Blog" and "Contacts" are correct.
5. Observe that the icons for "Home", "About Us" and "Public Folders" did not change

**Expected behavior**
The icons should be 
**custom-airplane** for "Home"
**custom-cargo-ship** for "About Us"
**custom-popup-media** for "Public Folders"

**Version**
beta.22

**Screenshots**

<img width="333" alt="tree_icons_sandbox" src="https://github.com/infor-design/enterprise-wc/assets/17284784/8caedcc3-61a8-4850-9cd1-3a5e7b9f283b">

**Comment by kenneth-acejo** [comment]
It would also be great if we could also set different icons to individual nodes and their expanded/collapsed icon.

**Comment by tmcconechy** [comment]
@kenneth-acejo is it only the custom icons not working? The sandbox page does show this. But not sure we tested with customIcons

**Comment by kenneth-acejo** [comment]
I tried using standard icons, it didn't work either. I actually should have started with standard icons.

**Comment by tmcconechy** [comment]
@kenneth-acejo I reviewed this more and Im thinking this isnt a bug (maybe).

If you notice on https://main.wc.design.infor.com/ids-tree/sandbox.html -> look at "custom icons" and "expand target"
To change the expand icon you need two icons... So you use these options:

```
    treeTtNoIr.toggleIconRotate = false;
    treeTtNoIr.collapseIcon = 'plusminus-folder-closed';
    treeTtNoIr.expandIcon = 'plusminus-folder-open';
    treeTtNoIr.toggleCollapseIcon = 'plusminus-folder-right';
    treeTtNoIr.toggleExpandIcon = 'plusminus-folder-down';
```

So question is:

a) Will that work? 
b) The only issue i see is you cant change individual icons but i think thats wierd anyways 
c) As for the issue with having both an icon and a expand/collapse icon. I know there is a thread for that being reviewed by design. If they think we should do it after that review lets make a new issue.

What do you think?

**Comment by kenneth-acejo** [comment]
There will be a discussion next week about our tree usage and design. Maybe we could wait for what the suggestions and agreement will be and then probably proceed from there?

**Comment by kenneth-acejo** [comment]
Coming from the meeting, it has been decided that a second icon will be supported much like in enterprise-ng but the placing of chevron icon will be switched with normal icon. Please see image below that was used in the meeting:

![chevron_tree](https://github.com/infor-design/enterprise-wc/assets/17284784/c17706a5-fffe-437d-80e2-217b827d0639)
 
I could also forward the email.

**Comment by kenneth-acejo** [comment]
Hi, I still can't seem to change icons dynamically if node has children. Please see link for demo
https://stackblitz.com/edit/ids-enterprise-wc-v1-morx2z?file=main.js

1) Click Change Icon button
2) Notice that the icons for nodes that has a chevron did not change
3) Also, even with toggleCollapseIcon and toggleExpandIcon set, toggling the nodes does not change the icons
4) Then, expanded property is not being set to true and back to false when expanding and collapsing the node respectively

```
{
    "id": "icons",
    "text": "Icons",
    "expanded": false,
    "icon": "triangle-filled"
}
```

**Comment by tmcconechy** [comment]
@jdilag90 @jmacaluso711 can you help verify if this works after the new tree changes? if not working we may need to reopen?

**Comment by jdilag90** [comment]
<img width="731" alt="image" src="https://github.com/user-attachments/assets/acc19d92-ae6c-4a6a-b5bd-b47964efd1e6">

Above example was run on current build.
Look at console to see usage
IdsTree has these settings to set icons
  * `expandIcon`
  * `collapseIcon`
  * `toggleExpandIcon` (second expand icon)
  * `toggleCollapseIcon` (second collapse icon)
  * `showExpandAndToggleIcons` (sets whether to show both expand and toggle icons)

**Comment by tmcconechy** [comment]
@kenneth-acejo we updated this further see above. Hopefully should work next release after some further refactors.

**Comment by kenneth-acejo** [comment]
Will the next release allow changing icon for a single node that has a `children` property?
