### ISSUE TITLE
IdsNotificationBanner: Get number of current active notifications

### ISSUE THREAD

**Issue by kels0** [infor-design/enterprise-wc#2160]
**Is your feature request related to a problem or use case? Please describe.**
I want a property on the notification-service to get number of active notification so we can set a limit on how many messages I can see.

**Describe the solution you'd like**
![image](https://github.com/infor-design/enterprise-wc/assets/4634476/23de514d-c1ab-4323-8970-ec75972dfdb4)

Add a property or a method to get the number of current banners.

**Comment by tmcconechy** [comment]
Api proposal..

```
import { notificationService } from ids-notification-service;
notificationService.closeAll();
notificationService.count();
notificationService.closeLast();
notificationService.closeFirst();
notificationService.show({ message: ' test', type: 'error' });
```
