### ISSUE TITLE
IdsDropdown: Default Height Assignment & Overlapping

### ISSUE THREAD

**Issue by NikosLardas** [infor-design/enterprise-wc#2165]
**Description:**

I encounter the following issue when utilizing the ids-dropdown web component. The component will take up space according to the height of the listbox of values available as shown in the demo below. The dropdown should take the only the space needed for it to render in closed mode. Also this does not let the dropdown overlay on top when there is a scrollbar, and instead increases the height of the container.

**Version**
Angular v16
ids-enterprise-wc: "^1.0.0-beta.22",

**Issue Demo**

[screen-capture (3).webm](https://github.com/infor-design/enterprise-wc/assets/69582244/06b5bb82-6e70-460a-9fb3-e8ee6e4a3f17)

**Comment by tmcconechy** [comment]
Can you clarify the issue? Is it if we put a dropdown on a IdsPopup it gets cut off?

**Comment by NikosLardas** [comment]
Hi @tmcconechy, we discussed the issue in detail here: 

https://teams.microsoft.com/l/message/19:b649a7c426e64e3dbedb0cc5202ce2d4@thread.skype/1710844168576?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1710844168576&teamName=IDS%20Enterprise%20Development&channelName=Web%20Components&createdTime=1710844168576


Issue summary:

The dropdown needs to take the space it needs when it is closed, while currently it takes the space it would require when it would be in open mode by default, which cause issues. One of these issues is that the dropdown does not overlap in the ids-popup and instead it increases the height of the container, even if the container has a fixed height.
