### ISSUE TITLE
IdsDatagrid: Row has no highlight on mouse over

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise-wc#2169]
**Describe the bug**
There is no highlight when you mouse over on the rows of the datagrid.

**To Reproduce**

1. Go to 'https://main.wc.design.infor.com/ids-data-grid/m3-features.html'
2. Mouse over on the rows

**Expected behavior**
The row where the mouse is hovered should have a highlight similar to this one https://latest-enterprise.demo.design.infor.com/components/datagrid/example-singleselect.html.

**Version**

- ids enterprise wc version: 1.0.0-beta.18

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@inforrpunay noted. I forget why i left this off. It may or may not be needed. Will check with my team.

**Comment by jbrcna** [comment]
QA Passeed
<img width="1712" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/50998cbc-2cad-49b8-8ab1-92b936c4463f">

<img width="1728" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/cf37c5c7-3998-4436-b1f7-a795341dc6bc">


**row highlight: disabled**
<img width="1711" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/50f843d2-1812-47a1-995f-962f744c848d">
<img width="1708" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/bbfad109-5d59-45e7-9151-9f5cb84bdb97">
