### ISSUE TITLE
IdsSearchField : Search suggestion are not visible

### ISSUE THREAD

**Issue by Jaydip14** [infor-design/enterprise-wc#2173]
**Describe the bug**
IdsSearchField does not show suggestions. I was able to observe popup opening related errors in console.

**To Reproduce**
1. Add ids-search-field web component
2. provide dataset with data in component
3. start application
4. Observe behavior

`<ids-search-field
        [data]="dataset$ | async"
        id="search-field-autocomplete"
        label-state="collapsed"
        placeholder="Search"
        caps-lock="true"
        align="start"
        search-field="label"
        autocomplete
        clearable
    ></ids-search-field>`

**Expected behavior**
We should be seeing suggestions in popup menu. However, I was observing errors in console.

**Version**
- ids-enterprise: 1.0.0-beta.21

**Screenshots**
<img width="662" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/12833458/0290c59e-df11-4688-a1ea-0505aa98f37d">

<img width="501" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/12833458/3aba11ab-2388-4c1b-8953-048b27722b59">

**Platform**
 - Infor Application/Team Name: Infor Birst ETLP
 - Device: MacBook
 - OS Version: MacOS 14.4.1
 - Browser Name: chrome
 - Browser Version: 123.0.6312.106

**Comment by tmcconechy** [comment]
So this is autocomplete? https://main.wc.design.infor.com/ids-input/autocomplete.html
Im not seeing any error there maybe we need a specific example?

**Comment by Jaydip14** [comment]
Yes, it is autocomplete with ids-search-field. As for the specific example, does providing video recording will work?

**Comment by tmcconechy** [comment]
Code would be better. If not possible to provide a code snippet i can try to make the example and see if it works

**Comment by Jaydip14** [comment]
This is an Angular application.

HTML Template:
`<ids-search-field
        (selected)="handleSelected($event)"
        (input)="handleSearch($event)"
        [data]="dataset$ | async"
        id="search-field-autocomplete"
        label-state="collapsed"
        placeholder="Search"
        caps-lock="true"
        align="start"
        search-field="label"
        autocomplete
        clearable
    ></ids-search-field>`

Component file:
`private readonly datasetSubject: BehaviorSubject<SearchableDataset[]> = new BehaviorSubject([{"id":"2","label":"Pipeline_1712323234225"},{"id":"workflow-1","label":"March Demo Pipeline"} {"id":"workflow-2","label":"Sales & Revenue 2021 - 3"}])`

`
public readonly dataset$: Observable<SearchableDataset[]> = this.search.dataset$`

    public handleSearch(ev: Event): void {
        const value: string = (ev.target as any).value
        this.search.search(value)
    }

    public handleSelected(ev: Event): void {
        const id = (ev.target as any)?.value
        this.search.handleSearchSelection(id)
    }
`

**Comment by ShwetaKhera** [comment]
Hi @tmcconechy, I am also seeing this issue in ids-enterprise version 1.0.0. Thanks

**Comment by tmcconechy** [comment]
@ShwetaKhera thanks. We didnt fix this just yet. Its in progress now
