### ISSUE TITLE
IdsAbout: Add copy button 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#2176]
**Describe the bug**
Add the copy to clipboard feature as per https://github.com/infor-design/enterprise/issues/8438

**Additional context**
http://localhost:4000/components/about/example-index.html

**Comment by glenlieorillo** [comment]
This has been tested and passed.

https://github.com/infor-design/enterprise-wc/assets/102151352/e88ddaaa-5e6d-4708-aafb-134831f97586
