### ISSUE TITLE
IdsButton: Add multi state toggle button (Segmented Control)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#2180]
**Describe the bug**
Add a component with multiple button selections like https://material.angular.io/components/button-toggle/overview#exclusive-selection-vs-multiple-selection

In previous discussions was called a segmented control

- called it segmented-control for now (was in Coms / roadmap ect)
- skip the single one (its a switch already)
- use semantic tokens for the colors and pick one so the unselected text has proper contrast

**Additional context**
https://inforwiki.atlassian.net/browse/IDS-1777 
https://www.figma.com/design/XALiPBQAENSzcZCCosNbW6/Toggle---Updated-Switch-IDS-Component?node-id=0-1&t=nvoAc868nw3WOUAO-0

**Comment by inforandy** [comment]
design here https://www.figma.com/file/XALiPBQAENSzcZCCosNbW6/Toggle---New-IDS-Component?type=design&node-id=0-1&mode=design&t=ALINBCm2xkG1VSpO-0
