### ISSUE TITLE
IdsMessage: Mobile - Modal takes the entire mobile screen

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise-wc#2183]
**Describe the bug**
Messages window takes the entire mobile screen.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-message/types.html
2. Open developer's console
3. Toggle device toolbar
4. Click on button
5. Message takes up the entire screen

**Expected behavior**
Small modal window
![Animation](https://github.com/infor-design/enterprise-wc/assets/156752175/a95fb5ab-957d-468b-a87d-941795c66d2e)

**Version**
- ids-enterprise: v1.0.0-beta.23

**Screenshots**
![Animation](https://github.com/infor-design/enterprise-wc/assets/156752175/e65f09bb-0e0b-45c8-bd2a-1c2a7e55db32)

![image](https://github.com/infor-design/enterprise-wc/assets/156752175/2ed8df4f-1ba8-4090-9255-2a7c63139037)

**Comment by glenlieorillo** [comment]
The issue has been fixed.

https://github.com/infor-design/enterprise-wc/assets/102151352/ff2a5d8c-417e-432c-bad7-6964e3964376


https://github.com/infor-design/enterprise-wc/assets/102151352/2763ed0e-34d3-4f5a-bf81-1de99fbbb148
