### ISSUE TITLE
IdsWizard: Add `disabled` property to `ids-step` for the wizard

### ISSUE THREAD

**Issue by SAIPRANAY-GANGULA** [infor-design/enterprise-wc#2192]
**Describe the bug**
Hello Team, We would like use ids-wizard(web component) & show to user if any particular step is disabled or not visually. Just like below example using ids-enterprise-ng.
https://stackblitz.com/edit/ids-quick-start-1730-icuaaq?file=src%2Fapp%2Fapp.component.html
 
I don't see `disabled` property on `ids-step`.  Even though we have clickable property which makes step not clickable but it doesn't have styling to show visually if step is clickable or not.

**To Reproduce**

We don't have any example with disabled step: https://main.wc.design.infor.com/ids-wizard/sandbox.html

**Expected behavior**

Expected Styling: (step1 is disabled)
![Screenshot 2024-04-08 121211](https://github.com/infor-design/enterprise-wc/assets/56952302/08f48837-0e85-4a51-868f-42bb5328eb47)

Current Styling:
![Screenshot 2024-04-08 121957](https://github.com/infor-design/enterprise-wc/assets/56952302/e32bddcb-c6d3-4d9f-8b01-1a9c95e73750)

**Version**

-     "ids-enterprise-wc": "^1.0.0-beta.22",

**Comment by glenlieorillo** [comment]
This has been tested and passed.


https://github.com/infor-design/enterprise-wc/assets/102151352/8b817b6e-7c40-458a-bea5-47ae460eaabc
