### ISSUE TITLE
IdsModal: Improve secondary IdsModalButton text color in dark mode

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise-wc#2197]
**Describe the bug**
The text color of the `IdsModalButton` with `secondary` appearance isn't very visible in dark mode.

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-modal/contains-components.html
2. Change to dark mode
3. Click "Trigger a Modal"
4. Notice the text color of the "Reset" button

**Expected behavior**
The text color should be more visible, should probably have the same color as in the core component

**Version**
`ids-enterprise-wc@1.0.0-beta.23`

**Screenshots**
**Core**
![core](https://github.com/infor-design/enterprise-wc/assets/63045013/9e344f22-e8d9-46ca-835a-9b96868e9553)

**Web Component**
![wc](https://github.com/infor-design/enterprise-wc/assets/63045013/34d9b3bc-8c72-41ff-b260-62a103b0680a)

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by glenlieorillo** [comment]
This is now working as expected.

**Mac Chrome**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/82ae22dc-2651-4d4f-a496-2bb184fbf31a">

**Mac FF**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/c5c08c6b-d0a0-4613-9dd7-d9b132e6f1e2">

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/102151352/1a70e939-e238-4b1b-a1ca-f35301a444e3">
