### ISSUE TITLE
Message: Ability to add a message with api (not in the html page) 

### ISSUE THREAD

**Issue by jayshindeinfor** [infor-design/enterprise-wc#2208]
**Is your feature request related to a problem or use case? Please describe.**
A clear and concise description of what the problem is. [e.g. {Component Name} has a problem when {...}]
ids-message need an ability to trigger and get values from API(title,message,button,error.. etc) attaching example of soho code for reference.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. [e.g. {Component Name} would work better if {...}]

```
this.sohoMessageService
              .error()
              .title(this.routingStateService.baseTranslation[BaseTranslationKey.NO_ACCESS_TITLE] as string)
              .message(this.routingStateService.baseTranslation[BaseTranslationKey.NO_ACCESS_MESSAGE] as string)
              .buttons([
                {
                  text: this.routingStateService.baseTranslation[BaseTranslationKey.NO_ACCESS_BTN] as string,
                  click: (_event, modal1): void => modal1.close(),
                },
              ])
              .open();
```

something like this which we can send all data to modal from .TS in angular.

**Describe alternatives you've considered**

**Additional context**
And what application do you work on? [e.g. {Infor XYZ}]

**Comment by tmcconechy** [comment]
Two API Proposals.

```
import { message } from ids-message;

message.show({ message: 'test', type: 'error'});
```

or

```
const message = document.createElement('ids-message');
message.type = 'error';
message.message = 'test';
message.show(); // removes it self when closed
```

**Comment by tmcconechy** [comment]
@jayshindeinfor I agree i like that one as well.

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4446

**Comment by tmcconechy** [comment]
This was added as per https://oxford.awsdev.infor.com/infor-design/enterprise-wc/-/merge_requests/20
