### ISSUE TITLE
ids-lookup inside Accordion?

### ISSUE THREAD

**Issue by silarapusandhya** [infor-design/enterprise-wc#2212]
**Description:**
 one of our requirements we have to use lookup inside accordion, whenever we are opening lookup, its restricted to accordion only instead of full page, any fix for this?

**Code**: 
```
<ids-accordion-panel expanded="true" class="accordion-panel">
    <ids-accordion-header slot="header" expander-type="plus-minus">
        <ids-text font-size="16">Document Settings</ids-text>
    </ids-accordion-header>
    <ids-lookup
        slot="content"
        id="lookup-1"
        label="Items"
        title="Select an Item"
        field="id"
        value=""
        searchable="true"
        searchfield-placeholder="Search for an item"
    ></ids-lookup>
</ids-accordion-panel>
```

<img width="478" alt="lookupAccordionErr" src="https://github.com/infor-design/enterprise-wc/assets/166589171/5f6f14ab-101e-4ea9-a809-3473f3414fd0"> 

**Expectations** :
<img width="722" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/166589171/d33f2290-f2f4-438a-918d-2fa30de95945">

**Comment by tmcconechy** [comment]
@clayinfor could be this line possibly https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-accordion/ids-accordion-panel.scss#L153 for the win.
