### ISSUE TITLE
IdsTree: Select method always deselects previous node when multi select is true

### ISSUE THREAD

**Issue by sean-keiffer-lee** [infor-design/enterprise-wc#2225]
**Describe the bug**
Programatically selecting nodes using the select method in the IdsTree always deselects the previous even when the IsMultiSelect property is set to true.

1. Create a tree with IsMultiSelect set to 'true'.
2. Call the Select() method from the tree and select a node.
3. Call the Select() method again and select a different node.

**Expected behavior**
Both nodes should be selected

**Actual behavior**
The first selected node gets unselected and the second node is selected.

**Additional context**
In the idsTree script, the Select method (line 187) always defaults to the private method this.#setSelected even if the IsMultiSelect is set to true and calls the private method this.#setMultiSelected.
https://github.com/infor-design/enterprise-wc/blob/7eeeeded6f2226591f6a72263a668f03b75a8379/src/components/ids-tree/ids-tree.ts#L187-L193

**Comment by seeeany** [comment]
Sorry, I wasn't able to add proper screenshots explaining the issue.

Here's the steps that I took when using the Select method
1. Select a node using the select method. ```ts idsTree.select("#home")
2. The specified node will be selected as expected
![image](https://github.com/infor-design/enterprise-wc/assets/32953723/8b888483-c069-4af0-a641-bc8c0f4b7d0a)
3. Select a different node with the same parent node using the select method.
4. The previously selected node will be unselected and the specified node will be selected.
![image](https://github.com/infor-design/enterprise-wc/assets/32953723/ddcca300-e5f8-492f-9b97-af2160dc4cb8)

Here's an GIF example showing the steps above using the dev console.
![chrome_XWygVjwOjA](https://github.com/infor-design/enterprise-wc/assets/32953723/8348b6ba-ff20-4965-badd-7594a1809940)

Regarding the usage of the select method, I've also been using a css selector to select specific nodes.
As a possible code fix, in the select method, just adding a return inside the if block or putting the normal setSelected method in an else block should fix the issue that I've mentioned.
```ts
// Return solution
 select(selector: string) { 
   const node = this.getNode(selector); 
   if (this.isMultiSelect) { 
     this.#setMultiSelected(node); 
     return;
   } 
   this.#setSelected(node); 
 } 
```
or
```ts
// Else block solution
 select(selector: string) { 
   const node = this.getNode(selector); 
   if (this.isMultiSelect) { 
     this.#setMultiSelected(node); 
   } else {
     this.#setSelected(node); 
   }
 } 
```
