### ISSUE TITLE
Ids:Datagrid: Adding a pageTotal duplicates rows

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise-wc#2232]
**Describe the bug**
When using a datagrid with pagination, adding the `pageTotal` property makes the rows duplicated.

**To Reproduce**

1. Go to https://stackblitz.com/edit/ids-enterprise-wc-beta-21-44r2ln?file=index.html
2. See mismatch between data and display data

**Expected behavior**
Pagination does not break the dataset display 

**Version**
wc-beta-23

**Screenshots**
N/A

**Platform**
N/A

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Note: Removing `dataGrid.pageTotal = caseTableData.rows.length;` causes the problem to go away.

**Comment by kshwetabh** [comment]
> Note: Removing `dataGrid.pageTotal = caseTableData.rows.length;` causes the problem to go away.

Thanks Tim. This workaround resolved the issue for me too. This is reproducible even when pagination feature is not enabled. I noticed this in v1.0.0.
