### ISSUE TITLE
IdsAreaChart & IdsLineChart: Selecting a very specific marker results in error

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise-wc#2235]
**Describe the bug**
Selecting a very specific marker cause the page to encounter error

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-area-chart/selectable.html or https://main.wc.design.infor.com/ids-line-chart/selectable.html
2. Open developer's console
3. Click on the very last marker of **Component C**

**Expected behavior**
No error is displayed

**Version**

- ids-enterprise-wc: v1.0.0

**Screenshots**
![Animation](https://github.com/infor-design/enterprise-wc/assets/156752175/f673ab4e-f30d-42ff-92a7-a7a853e78256)

**Comment by tmcconechy** [comment]
Fixed on https://oxford.awsdev.infor.com/infor-design/enterprise-wc/-/merge_requests/63
