### ISSUE TITLE
IdsBreadCrumb/IdsHyperlink: Add Hide Focus Mixin

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#2238]
**Describe the bug**

Should not show the focus state on click on links and breadcrumbs.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-breadcrumb/example.html#
2. Click on a link
3. See error - should not show a focus unless focused with the keyboard

**Expected behavior**

Adding hide-focus mixing should fix this.

**Comment by glenlieorillo** [comment]
This is now working as expected.


https://github.com/infor-design/enterprise-wc/assets/102151352/da75b425-0c1a-4d57-af77-1ac388b92fe6
