### ISSUE TITLE
IdsMultiselect: Popup not display in correct position with size='lg'

### ISSUE THREAD

**Issue by Varalaxmi26** [infor-design/enterprise-wc#2248]
1) Ids-multiselect when using the size property with size='lg', the popup of Ids-multiselect does not fit with the dropdown width.
2) When using label-state="collapsed" with ids-multiselect the gap between the label and multi-select element is not reduced. collapsed style is not applying.
![image](https://github.com/infor-design/enterprise-wc/assets/59650265/a8064804-55b5-47e8-82b7-21df20f60018)
 

**To Reproduce**
Add ids-multiselect with size attribute "lg"
Click on the dropdown icon and observe.
The popup width and dropdown width are not equal.

**Expected behavior**
Expected is the popup width should fit with the dropdown width based on the dropdown given size.

**Version**
"ids-enterprise-wc": "^1.0.0",

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/59650265/965260f9-2cb9-4342-92b9-29f8aa17179f)

**Platform**
Infor ION team

**Comment by ashachodavarapu** [comment]
HI @tmcconechy ,
After upgrading to version **1.3.0**, the issue has not been resolved. In which version will we receive this fix?! 
[image](https://github.com/infor-design/enterprise-wc/assets/105051938/24644937-e61e-4afd-b7da-7d32827d46a0)

Thanks

**Comment by tmcconechy** [comment]
@ashachodavarapu its working for us here https://main.wc.design.infor.com/ids-dropdown/sizes.html

Can you provide any details on how to reproduce as it seems fixed to me. Is maybe the size set dynamically or in angular or something that might make it a different case to check?

**Comment by tmcconechy** [comment]
@ashachodavarapu @jdilag90 

Update: I updated the NG project on a hunch and the problem is there. I guess in the NG context the size setting is not updating the dropdown size as expected yet.

@jdilag90 can you take another look

1. pull latest enterprise-wc-examples
2. Run ng project
3. go to http://localhost:4200/ids-dropdown/sizes
4. open large (and others

**Comment by ashachodavarapu** [comment]
@tmcconechy,
I updated my Angular project and checked this morning, and I noticed that the angular examples are from an older version.

**Comment by tmcconechy** [comment]
@ashachodavarapu no problem we see this issue in Angular and are working on an updated fix ASAP

**Comment by ashachodavarapu** [comment]
@tmcconechy 
I checked the angular examples and I observed the issue
![image](https://github.com/infor-design/enterprise-wc/assets/105051938/c5315fcd-9af1-4d9e-bcfa-e1d28af66994)
Thanks.

**Comment by tmcconechy** [comment]
yes we see it too @ashachodavarapu working on a fix

**Comment by Varalaxmi26** [comment]
Hi @tmcconechy , is the second point also fixed 

When using label-state="collapsed" with ids-multiselect the gap between the label and multi-select element is not reduced. collapsed style is not applying.
https://private-user-images.githubusercontent.com/59650265/325698169-a8064804-55b5-47e8-82b7-21df20f60018.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTk2MjgsIm5iZiI6MTcyMTgxOTMyOCwicGF0aCI6Ii81OTY1MDI2NS8zMjU2OTgxNjktYTgwNjQ4MDQtNTViNS00N2U4LTgyYjctMjFkZjIwZjYwMDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDExMDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNWY3YjE4ZGVmYjcyZDc3NmU2MWQ3ZDRmMTk2ZjNjNzU0OTc3NzI0M2NhYTAyODZjZmI0NGYzNzQ1NDkwMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.etzVivBMIEJ0k-AACWtVQulP-elqni31t-lM6nt6O9k

**Comment by tmcconechy** [comment]
@Varalaxmi26 Can you make an issue for the label-state issue on multiselect so we dont get too confused and mix up issues?

**Comment by Varalaxmi26** [comment]
I have created a new ticket for another issue as you suggested. 
https://github.com/infor-design/enterprise-wc/issues/2635
