### ISSUE TITLE
IdsLoadingIndicator: Overlay and align properties should work over a set area

### ISSUE THREAD

**Issue by ashachodavarapu** [infor-design/enterprise-wc#2256]
**Related Issue:**
https://github.com/infor-design/enterprise-wc/pull/1694
**Team: ION Notification Center**
**Current version: "ids-enterprise-wc": "^1.0.0",**

**HTML Tag:**

```
<ids-loading-indicator align="center" overlay></ids-loading-indicator>
```

**Use Case:**

- When sorting is applied to the list view based on the selected criteria, the UI should display a loading indicator while retrieving the API data. This will prevent the user from performing other actions in the list until the data is loaded. At this point, an overlay and alignment should be applied to block the view and show it center.
-When bulk removal of list items is initiated by clicking the button, a loading indicator should appear and the list view should be blocked to prevent other actions from being performed

**Issue:**
Currently, If I use overlay and align center for list view it applies to the whole page Like below
![image](https://github.com/infor-design/enterprise-wc/assets/105051938/61ecc2d5-6dac-4665-90a6-b58ea7d42908)

**Requirement:**
- [ ] For the ids-loading-indicator, the overlay and align properties should function in the list view.
- [ ] Include a list view example with a loading indicator in Angular, incorporating the overlay and align properties. If feasible, provide examples for the scenarios described above.

**Expected**

If the overlay and align properties of the ids-loading-indicator are applied to the list view instead of the entire page, they should only affect elements within the list view. For example, they should function as follows (overlay and align should work):

**Note: For demonstration purposes, I've added some styles to center it.**

![image](https://github.com/infor-design/enterprise-wc/assets/105051938/f68c0739-e672-47b2-bdb9-4117e972bd92)

**Comment by tmcconechy** [comment]
@ashachodavarapu I think what we should do is..

- make sure you can do the overlay on a set area like that listview pane (new setting)
- then make sure `opacity` works. In this case would be better to not make the area show opacity but still have the overlay
