### ISSUE TITLE
IdsDataGrid: With allow expand row both events are not correctly triggered

### ISSUE THREAD

**Issue by aparimalla** [infor-design/enterprise-wc#2275]
**Describe the bug**
Upon clicking the expand Row button in DATA GRID (ALLOW ONE EXPANDABLE-ROW), the Row Expanded is not triggered; instead, just the Row Collapsed event happens. 
When more than one expand Row button is clicked, I suppose the Row Collapsed event should be triggered first, and then the Row Expanded event.

**Steps to reproduce the behavior:**
1. Go to [https://main.wc.design.infor.com/ids-data-grid/expandable-row.html]
2. Click on anyone of the Expand Row button in DATA GRID (ALLOW ONE EXPANDABLE-ROW), check the console for triggered 
    event details(Row Collapsed event will be triggered).
3.Now click one more expand row button without collapsing the previous expanded row, again check the console for triggered 
   event(only Row Collapsed event will be triggered).
4. Also verify the above steps for DATA GRID (EXPANDABLE ROW). Then You will observe the differences.
5. Please Refer the below attached video clip.

**Expected behavior**  
>  Upon clicking the expand Row button in DATA GRID (ALLOW ONE EXPANDABLE-ROW), the Row Expanded event should be 
    triggered; instead of the Row Collapsed event. 
> When more than one expand Row button is clicked, the Row Collapsed event should be triggered first, and then the 
    Row Expanded event.

**Comment by janblankenburgh** [comment]
Hi @tmcconechy , I notice this issue already has your attention. Thanks! We'd appreciate it if this can be fixed with priority.
