### ISSUE TITLE
IdsPopup: Opens on bottom when it should not

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#2285]
**Describe the bug**
IdsPopup sometimes opens on the bottom when it should not.

**To Reproduce**

1. Go to http://localhost:4300/ids-data-grid/export-excel.html
3. See position is down
4. Click on Export 
5. See error: position is up.

**Expected behavior**
Algorithm should be:
- open at the position specified
- defaults below for menu button
- and then always below unless the menu is too big then try the other way
- if it doesnt fit there scroll and shrink

**Additional context**
Ms Teams post: IdsMenuButton - default position on the menu

**Comment by jbrcna** [comment]
QA Passed.
<img width="1692" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/3a1c05d6-3016-4e17-bade-403f521a450f">
<img width="406" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/179a7edf-e08b-4ce4-8f86-fe5b6a8e500e">
