### ISSUE TITLE
IdsAccordion: Customizable expander type icons 

### ISSUE THREAD

**Issue by ShwetaKhera** [infor-design/enterprise-wc#2290]
**Describe the bug**
Currently, for expander type icons we can only use plus-minus. We want to able to customize it to caret-up and caret-down.
What we have now:

**To Reproduce**

1. Add nested accordion
2. Add expander-type="plus-minus" to second level header

**Version**

- ids-enterprise: v1.0.0

**Screenshots**
![Screenshot 2024-05-06 at 11 57 39 AM](https://github.com/infor-design/enterprise-wc/assets/30701871/1f57740f-9c4e-4d6a-a5a8-adc32e1a4ae5)

What we want:
![Screenshot 2024-05-06 at 11 47 10 AM](https://github.com/infor-design/enterprise-wc/assets/30701871/0159a742-25de-4ae5-8996-6112b17bdd3e)

**Platform**
 - Infor Application/Team Name: Infor Birst
 - Device: MacBook Pro
 - OS Version: macOS Sonoma v14.4.1
 - Browser Name: Chrome
 - Browser Version: 123.0.6312.124

**Additional context**

**Comment by tmcconechy** [comment]
@ShwetaKhera This should be already possible. See the example: https://main.wc.design.infor.com/ids-accordion/nested.html

Source: https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-accordion/demos/nested.html

Note: This way is used in the Module Nav and Application Menu components (so you may also review if you should use them in your use case)

**Comment by bcborna10** [comment]
@tmcconechy  - just a side note: we often use a "+" icon to add a new entity (usually at the top of a list of items)

**Comment by ShwetaKhera** [comment]
@tmcconechy  
Just like @bcborna10 mentioned, we've received internal feedback that the plus symbol looks like adding or creating an entity for the second level item. In the context that we're working with, there're only 3 levels. 2 icons doing the same actions (expansion) in the same UI could use a simplification.

**Comment by tmcconechy** [comment]
OK Thanks @ShwetaKhera @bcborna10 

NOTES:
- I wont suggestchange app menu or module nan
- Just see if we can make the accordion work with that icon option on sub levels
- On a side note many apps use a tree with an add button on the page and does'nt seem to be an issue.

Would changing the add icon be an option? (Just thinking here)

**Comment by ShwetaKhera** [comment]
@tmcconechy 
> Would changing the add icon be an option? (Just thinking here)

That would work, thanks!
