### ISSUE TITLE
IdsPagerDropdown : Creating an instance of IdsPagerDropdown throws an error

### ISSUE THREAD

**Issue by mined14** [infor-design/enterprise-wc#2291]
**Describe the bug**
When creating an instance of IdsPagerDropdown, it throws the below error during calling the const pagerDropdown = new IdsPagerDropdown();

**To Reproduce**
Create new file or an existing one and try to import the idsPagerDropdown like snipper below:

`import IdsPagerDropdown from "ids-enterprise-wc/components/ids-pager/ids-pager-dropdown";`

After that, create an instance of IdsPagerDropdown like below snippet and run the code

`const pagerDropdown = new IdsPagerDropdown();`

**Screenshots**
<img width="532" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/167979611/ee2972f5-b1ba-45b4-9923-faa976dc0713">

**Comment by mined14** [comment]
Hi @tmcconechy , I tried that and the idsPagerDown is not displaying still as there is no generated attribute on it. Also, the issue in console still there. Please see below screenshot.

<img width="921" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/167979611/b54da313-b62b-4257-93bf-a1af2e784b2b">

I have also tried it in ids-pager/example.html and add the document.createElement('ids-pager-dropdown')  and the issue still there.  below is the sample snippet code, I just modified the example.ts to load the idsPagerDropdown

```
`// Supporting components
import '../ids-pager';

document.addEventListener('DOMContentLoaded', () => {
  // Add an event listener to test clickable links
  const pager = document.querySelector('#ids-pager-example');
  pager?.addEventListener('pagenumberchange', (e: any) => {
    console.info('pagenumberchange event fired ', e.detail.value);
  });
  
    const pagerdd = document.createElement('ids-pager-dropdown');
       pagerdd.slot = "start";

       pager.appendChild(pagerdd);
});
```

<img width="629" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/167979611/ad9d14a3-44d2-437e-a414-624d95bb3dd0">

`

**Comment by tmcconechy** [comment]
OK, we will look into this? What are you trying to make BTW? Just setup a pager dynamically? 
Are you trying to "only" use the page size picker? Or an entire pager with it in it?

**Comment by mined14** [comment]
@tmcconechy , Yep, I want to use the pager dropdown to handle the datagrid's page size based on what the pager dropdown selected.

**Comment by andrivarhanov** [comment]
@mined14 @tmcconechy there was this similar issue https://github.com/infor-design/enterprise-wc/issues/2193 a month ago and it's fixed. It seems like the `enterprise-wc` version used here it's not the recent one. I've added pager dropdown instance to Angular pager example here https://github.com/infor-design/enterprise-wc-examples/pull/69 `ids-enterprise-wc` **v1.0.0** no issues. Also there is a test for `document.createElement('ids-pager-dropdown')` case here https://github.com/infor-design/enterprise-wc/blob/main/tests/ids-pager/ids-pager.spec.ts#L71 isn't failing. 
Please let me know what to add to Angular example to reproduce the issue

**Comment by mined14** [comment]
@andrivarhanov , updating the wc version to "^1.0.0" fixed my issue. We can now close this ticket. Thanks for the help!
