### ISSUE TITLE
IdsBreadcrumb: Breadcrumb overflow popup does not appear

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise-wc#2317]
**Describe the bug**
When the screen size is resized, the overflow popup does not appear in breadcrumbs

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-wc-breadcrumb.html
2. Resize the page -> should get overflow
3. Try reloading the page and a narrow state -> should also see the overflow here

**Expected behavior**
The overflow button appears on the left. And onclick, the popup menu should appear.

**Version**

- ids-enterprise-wc 1.0.0-beta.23
- ids-enterprise 4.95 ( See commit https://github.com/infor-design/enterprise/commit/554349633e9210ffba28d781d778148dd2570e2d that has a style class in _header.scss for breadcrumbs. Crossing out display:inline-flex helps resolve the problem)

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/22720894/95e3bd91-3fca-4311-853a-458f1305eb5e)

**Platform**
 - Infor Application/Team Name: Infor Landmark
 - OS Version: Windows
 - Browser Name: chrome
 - Browser Version: 124.0.6367.201

**Comment by tmcconechy** [comment]
Fixed https://github.com/infor-design/enterprise-wc/pull/2318/files 

Note: Also adjusted this rule in enterprise for better padding https://github.com/infor-design/enterprise/commit/7e0da56a69572a42192dab71775f4618c5dd907f
