### ISSUE TITLE
IdsButton/IdsMenuButton: Want to add notification badges

### ISSUE THREAD

**Issue by Varalaxmi26** [infor-design/enterprise-wc#2323]
**Enhancement**

We have a requirement to show a notification badge on top of the ids-button and ids-menu-button.
There is an example for ids-icon https://main.wc.design.infor.com/ids-icon/notification-badge.html. 
In the same way, want to show a notification badge for the menu button and button.

**Notes** 
Team: ION

**Screen Shot**
![image](https://github.com/infor-design/enterprise-wc/assets/59650265/797f897a-7ab8-4339-ad64-ea7a7f1d33ec)

**Solution** 
- add the icon notification badge settings (or better a mixin) so that you can display the badge on the icon in the button
- Do we need design feedbacK?

**Comment by tmcconechy** [comment]
@laurensteiger its on the icon but the icon is in a button. So ultimately it would be the same design as now. We just dont have a way to put it on the icon when the icon is in a button yet. So need to add that setting to the button.
