### ISSUE TITLE
IdsText: translate-text not working for ids-text component in Angular

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise-wc#2324]
**Describe the bug**
The translate-text feature for the ids-text component doesn't translate the text string. Only seeing this in Angular, not enterpise.

**To Reproduce**
1. In the Angular WC example for ids-container add the following line of code anywhere inside the ids-container section:
![image](https://github.com/infor-design/enterprise-wc/assets/39279254/d9966a87-19db-4fcd-bf24-030a3cbb1e2b)
2. Open the component - note the 'AboutText' doesn't translate.
3. Repeat steps 1 & 2 using the Enterprise WC example, note that it translates correctly.

**Expected behavior**
In step 2 the proper translated text should appear.

**Version**
ids-enterprise-wc 1.0.0

**Screenshots**
Angular:
![image](https://github.com/infor-design/enterprise-wc/assets/39279254/0e53dc90-ea3c-4e63-aef0-112ace79c3bb)

Enterprise:
![image (1)](https://github.com/infor-design/enterprise-wc/assets/39279254/e57e2c15-3a7a-4e78-a8f4-205a17b96531)

**Platform**
 - M3 GLT
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 124.0.6367.203

**Additional context**
If you add the following line of code to the constructor method in the example component it will display the properly translated text:
_alert(IdsGlobal.getLocale().translate('AboutText'))_

![image](https://github.com/infor-design/enterprise-wc/assets/39279254/57e9fe95-371f-48b6-9f6a-df3cf725237e)

**Comment by tmcconechy** [comment]
Could be also seen here https://main.wc.design.infor.com/ids-text/translations.html
- switch to german in the ... menu
- the first time it doesnt change
- the second time it works (switch german - english - german)
