### ISSUE TITLE
ids-tabs broken in 1.0.0 & 1.1.0 

### ISSUE THREAD

**Issue by gustavpollak** [infor-design/enterprise-wc#2338]
**Describe the bug**
ids-tab component is not working as expected. First tab is not clickable and has bold styling. 
It does not matter which tab that is set as default, the first tab is never selectable.

**To Reproduce**
https://stackblitz.com/edit/ids-enterprise-wc-100-ntsrkq?file=index.html

1. Go to https://stackblitz.com/edit/ids-enterprise-wc-100-ntsrkq?file=index.html
2. Observe "example1" tab
3. Click on "example1" tab
6. See that nothing changes

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

![image](https://github.com/infor-design/enterprise-wc/assets/49652924/21ecfc3a-440e-40ea-870f-ab0e7936a44a)

**Platform**
 - Stackblitz 
 - Device: PC
 - OS Version: W11
 - Browser Name: Chrome
 - Browser Version: Version 124.0.6367.207 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Working on https://main.wc.design.infor.com/ids-tabs/example.html maybe something in the prod build? Will look
