### ISSUE TITLE
IdsMenuButton - Should possible to deselect an item that is selected.

### ISSUE THREAD

**Issue by Varalaxmi26** [infor-design/enterprise-wc#2339]
In the current ids-menu-button popup, it is possible to switch the selection between the menu items but not be able to deselect an item already selected with a single selection option.

https://main.wc.design.infor.com/ids-menu-button/example.html.

Implement the feature to deselect an item that is already selected.

Team: ION

**Comment by tmcconechy** [comment]
@Varalaxmi26 can i see an example of the menu your working on? Is it one item that is being toggled or a set of selected items?

**Comment by Varalaxmi26** [comment]
It is one item toggled.

![image](https://github.com/infor-design/enterprise-wc/assets/59650265/261a18ef-c4c5-484a-a706-16be30571f14)

**Comment by laurensteiger** [comment]
Users should be able to deselect a selected item/filter.

**Comment by andrivarhanov** [comment]
@tmcconechy @Varalaxmi26 there is `toggleable` attribute in `ids-menu-item` allowing it to be selected and deselected 
https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-menu/README.md#selection-event-handling

I've added `toggleable` to the main menu button example https://github.com/infor-design/enterprise-wc/commit/2c9e8d897d0d6615ecaecb0c50be9d2b782d5142 

Let me know if I need to make `toggleable` by default for checkmark items or any other changes required

**Comment by tmcconechy** [comment]
@andrivarhanov maybe we can add a new example section on https://main.wc.design.infor.com/ids-popup-menu/selected-state.html thats called "Toggleable/On/Off"

That way it would be easy to find? But this is great its there i thought we thought of it

**Comment by andrivarhanov** [comment]
@tmcconechy sure, I will add a new example, on it

**Comment by Varalaxmi26** [comment]
I see this bug as closed. May I know which release this fix will be available for?

**Comment by tmcconechy** [comment]
@Varalaxmi26 I would take 1.5.0 (which is latest)
