### ISSUE TITLE
Dropdown: Placement Issue in Version ^1.0.1

### ISSUE THREAD

**Issue by NikosLardas** [infor-design/enterprise-wc#2348]
**Description:**

I encounter the following issue when utilizing the ids-dropdown web component. Once the user clicks on the dropdown and it opens, the list of options is rendered in the bottom right of the dropdown, instead of directly underneath. This issue does not exist in the previous version of the web components library, but appeared only after the latest update to version `^1.0.1`. To reproduce simply use a ids-dropdown component in an angular project.

**Example Screenshot**

![image](https://github.com/infor-design/enterprise-wc/assets/69582244/2653061c-80a0-412c-92f0-1b17b8f99bc1)

**Version**
Angular v16
ids-enterprise-wc: `^1.0.1`

**Issue Demo**

[screen-capture (10) 1.webm](https://github.com/infor-design/enterprise-wc/assets/69582244/d534586e-94c2-4ffc-8915-afb70b956d75)

**Comment by tmcconechy** [comment]
Can try 1.1.0 but i think all the fixes will be done in 1.1.1 when released.
