### ISSUE TITLE
IdsDataGrid: removeRow removing the wrong record

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#2355]
**Description**
When using method `removeRow` to remove a grid record, the wrong record is being removed.

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-data-grid/example.html
2. On console, run: `document.getElementById('data-grid-1').removeRow(2)`
3. The first record "101" (row at index 0) is deleted instead of row at index 2.

**Expected behavior**
Remove the "103" record (which is on the index 2)

**Version**
Latest

**Screenshots**
![Screen Shot 2024-05-22 at 8 20 34 AM](https://github.com/infor-design/enterprise-wc/assets/663908/8daac4c3-4114-490b-a0a0-8aca28e66ef1)
![Screen Shot 2024-05-22 at 8 20 41 AM](https://github.com/infor-design/enterprise-wc/assets/663908/b3e4bf1d-083c-4230-aa31-168e96d456b8)

**Platform**
 - Chrome

**Comment by fabiojpoli** [comment]
Any chance to level up the priority for this one? I feel that removing incorrect row is kind of big deal. Thanks

**Comment by tmcconechy** [comment]
@fabiojpoli ok i agree. Lets retest this on 1.3.0 tho when released next week as a similar issue was fixed

**Comment by tmcconechy** [comment]
@fabiojpoli if needing a workaround i found out the problem is that if there is no `id` column the logic wont work correctly So you can try to set `idColumn` to your field that acts as a primary key or add data in an `id` column.

Then i think we can update the logic but there are some other cases that require a primary key

**Comment by tmcconechy** [comment]
Same issue as https://github.com/infor-design/enterprise-wc/issues/2501

**Comment by tmcconechy** [comment]
NOTE: This is also included in 1.3.0 release but the PR is for 1.4.0

**Comment by jbrcna** [comment]
QA Passed
<img width="1469" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/ddc68f5f-964c-462a-9dfa-5d7418a4979e">
