### ISSUE TITLE
IdsModuleNav: Role switcher is not showing pre-selected option text in Angular if it is a template variable

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise-wc#2362]
**Describe the bug**
This is pretty much a reopen of ticket [1880](https://github.com/infor-design/enterprise-wc/issues/1880) 

In angular the dropdowns are not showing the text of the preselected values in scenarios where the text is set by a template variable. So in reusable dropdowns where content is populated from a non static source the text does not show up and dropdown option remains blank until a new option is selected. 

**To Reproduce**
Can be reproduced by instead of having the text statically defined in the template instead moving it to the ts file and use a template variable reference. 

Change this: 
```
            <ids-list-box-option value="admin-console" id="admin-console">
              <ids-icon icon="icon-app-ac" height="32" width="32" viewBox="0 0 32 32" [attr.stroke]="'none'"></ids-icon>
              <span>Admin Console</span>
            </ids-list-box-option>
```

To this: 

```
            <ids-list-box-option value="admin-console" id="admin-console">
              <ids-icon icon="icon-app-ac" height="32" width="32" viewBox="0 0 32 32" [attr.stroke]="'none'"></ids-icon>
              <span>{{ optionText }}</span>
            </ids-list-box-option>
```

And of course add the optionText variable in the typescript file.

1. Update the module nav sandbox demo in the enterprise wc angular examples to use template variable instead of static text for the role switcher dropdown
2. Open demo and notice how dropdown is blank until something is selected

**Expected behavior**
Ideally the dropdowns should support having non static resources for the data used as options. A common scenario would be to have a dropdown being populated by data fetched from an api and then a reusable dropdown component would be set up something like this:

```
            <ids-list-box-option *ngFor="let option of options" value="{{option.text}}" id="{{option.id}}">
              <ids-icon *ngIf="{{options.icon}}" icon="{{option.icon}}" height="32" width="32" viewBox="0 0 32 32" [attr.stroke]="'none'"></ids-icon>
              <span>{{option.text}}</span>
            </ids-list-box-option>
```

Sidenote: Something I realize now while writing is that supporting a set of options where some have icons and some don't is also something that does not look good at the moment as the formatting would make things misaligned. But that is a minor separate issue.

**Version**
ids-enterprise-wc: 1.1.0
Angular: 17.3.9

**Screenshots**

![angularwc-moduleNav](https://github.com/infor-design/enterprise-wc/assets/9215760/dc52a88d-0ea3-4230-9326-3174b97ff1e1)

**Platform**
 - Infor Application/Team Name: M3 Portals

**Comment by Carlfjord** [comment]
FYI this seems to be an issue for dropdowns globally. So not necessarily limited to IdsModuleNav

**Comment by tmcconechy** [comment]
@Carlfjord i see we dont have an angular example so will have to add that and check. If ngFor isnt working we will fix.

Another suggestion is you could try control flow syntax similar to https://github.com/infor-design/enterprise-wc-examples/blob/main/angular-ids-wc/src/app/components/ids-breadcrumb/demos/control-flow/control-flow.component.html#L32 and see if it works

**Comment by Carlfjord** [comment]
@tmcconechy  ngFor works fine, that snippet was just to show how it is likely to be used with async data. So an example that ideally works with no issues. 

Right now the only issue I see is that the dropdown is not populating the text for the option that is selected when the component is initialized.

**Comment by Carlfjord** [comment]
It has a value but no text. But after another option is selected it gets its value and text.
