### ISSUE TITLE
IdsAppMenu: Close menu on each click in Mobile Mode

### ISSUE THREAD

**Issue by OlejnikKamil** [infor-design/enterprise-wc#2372]
**Is your feature request related to a problem or use case? Please describe.**
This use case indicates use of mobile mode ( around 600 px)
In our solution, as can be seen on attached video, user is able to select some position in menu. With current implementation user might be frustrated to click few times to access program, which user was able to open without closing menu before (in ids-enterprise-ng). This solution is not acceptable by our clients and currently we are not able to finish our work on appMenu component.
Our solution closes menu, when user pick desired program.

**Describe the solution you'd like**
It would be great to make some parameter to be attached to app-menu, which in case of mobile mode allow us to not close app menu on each click, as it is currently. In our case we need to move into folders to find some applications to load.

**Describe alternatives you've considered**
As suggested by Tim, we tried app-menu-nav, but we end up with previous solution (ids-app-menu).

**Additional context**

https://github.com/infor-design/enterprise-wc/assets/161036498/a134f59c-6924-4a99-8aaa-b9d763c1f93b

Application: Blending

**Comment by tmcconechy** [comment]
@OlejnikKamil ok maybe this makes sense, if they are not selecting or navigating might not need to close.

The go forward is more the module nav. Should we add there? Are you adopting that?

**Comment by OlejnikKamil** [comment]
As I mentioned, we want to stay with this solution, as it suits our needs.

**Comment by tmcconechy** [comment]
@OlejnikKamil its more about the styles of the new one (app styles in sync). But ok just mentioning it. Whatever we do here will need to on both.

**Comment by OlejnikKamil** [comment]
Would be great @tmcconechy ! As this is one of not so many left, that we need to release.

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4443
