### ISSUE TITLE
IdsDataGrid: Freeze header when scrolling inside IdsCard

### ISSUE THREAD

**Issue by kenneth-acejo** [infor-design/enterprise-wc#2382]
If you put datagrid inside ids-card, the card-content slot will then have a scroll and this will make the column header move with when scrolling.

Also, I tried attaching listener to scrollend event, both to IdsDataGrid and the ```<div slot="card-content">```, but it doesn't work since the scroll belongs to template slot ```<div class="ids-card-content" part="content">``` and I have no way to access that. I was trying to implement infinite scroll from https://main.wc.design.infor.com/ids-data-grid/infinite-scroll.html

Please see [stackblitz](https://stackblitz.com/edit/ids-enterprise-wc-v1-visymm?file=main.js) for demo.

**Describe the solution you'd like**
It would be better if the column headers stay in place while scrolling.

As for infinite scrolling, please advise if there is a way to implement the IdsDataGrid inside IdsCard.

**Additional context**
https://stackblitz.com/edit/ids-enterprise-wc-v1-visymm?file=main.js

<img width="497" alt="IdsDatagridHeader" src="https://github.com/infor-design/enterprise-wc/assets/17284784/9231f3a4-339d-46d0-9a37-6f6b718bdf61">

Label is **team: M3**

**Comment by tmcconechy** [comment]
We will probably need to implement something here to get it to work. Basically need to disable the card scroll so the grid can scroll (and size it to the right size)
