### ISSUE TITLE
IdsDataGrid does not set cell value if the dropdown editor options is empty

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#2386]
**Describe the bug**
When there is a column cell editor as dropdown type without options defined (in case options will come from server or later in some way), the value is not shown in the cell.

**To Reproduce**
```html
<ids-data-grid id="data-grid-1" editable=true></ids-data-grid>
```

```javascript
var grid = document.querySelector('#data-grid-1');

grid.columns = [{
  id: 'id',
  name: 'ID',
  field: 'id'
},{
  id: 'role',
  name: 'Role',
  field: 'role',
  formatter: grid.formatters.dropdown,
  editor: {
    type: 'dropdown',
    editorSettings: {
      autoselect: true,
      dirtyTracker: true
      //options: [] // will be set later with the server
    }
  }
}];

grid.data = [{
  id: 1,
  role: 'Administration'
},{
  id: 2,
  role: 'Manager'
}];

// applying options later, simulating server side gave options later
grid.columns[1].editor.editorSettings.options = [{
  value: 'Administration',
  label: 'Administration'
},{
  value: 'Manager',
  label: 'Manager'
},{
  value: 'Developer',
  label: 'Developer'
}];
```

The code above shows the grid with the columns and editor set correctly, but the "role" column does not show the values.
![Screen Shot 2024-05-29 at 3 13 21 PM](https://github.com/infor-design/enterprise-wc/assets/663908/9d9241fd-9be9-4094-8176-e47934895f90)

![Screen Shot 2024-05-29 at 3 13 31 PM](https://github.com/infor-design/enterprise-wc/assets/663908/e1d33f73-58bd-4eb1-b1bb-a353ef87c307)

If options are defined statically, works fine:
![Screen Shot 2024-05-29 at 3 14 19 PM](https://github.com/infor-design/enterprise-wc/assets/663908/3fccf37d-b172-4dda-80c8-f9d69c0edfa1)

**Expected behavior**
Even if the editor dropdown options are not set yet (to set later), keep the value on the cell and keep the editor working to set option later when server respond:
![Screen Shot 2024-05-29 at 3 18 38 PM](https://github.com/infor-design/enterprise-wc/assets/663908/816a8689-9c2a-4403-a896-cfab2160ac70)

**Version**
Latest

**Comment by inforandy** [comment]
valid, will schedule a fix for this in august

**Comment by fabiojpoli** [comment]
@tmcconechy  I am not sure if we can reuse this issue.

For our real world case, the simulation of the server is little bit different. 

By using your example I changed to populate the options on `beforecelledit` event because each dropdown editor even on the same column may bring different options, so we need one request per dropdown.

Also we need to consider the delay on server request by adding setTimeout. So instead of set data `grid.columns[1].editor.editorSettings.options = [{` I am doing this to set:

```javascript
// set option before the cell is edited because each dropdown editor even on the same column may bring different options
grid.addEventListener('beforecelledit', function(evt) {
  var ed = evt.detail.column.editor;

  if (ed && ed.type === 'dropdown') {
    // simulate the delay of the options comming from the server
    setTimeout(function() {
      ed.editorSettings.options = [{
        value: 'Administration',
        label: 'Administration'
      },{
        value: 'Manager',
        label: 'Manager'
      },{
        value: 'Developer',
        label: 'Developer'
      }];
    }, 200);
  }
});
```

The result is that on the first time you open a dropdown to see the options, it fails only at the first time. By removing the timeout is going to work fine.
![Screenshot 2024-08-14 at 11 16 51 AM](https://github.com/user-attachments/assets/4c60c3aa-8d29-4fcd-9464-7a9c321793a2)

**Comment by tmcconechy** [comment]
OK i think maybe we need a new issue. I've never tried to load the data in beforeCell edit so would need to add a way to load the dropdown data when you click the cell as an enhancement?

**Comment by fabiojpoli** [comment]
Ok I will create an issue. I see this more as an issue instead enhacement I think. `ed.editorSettings.options = [{...}]` call should load new options independently of when you are calling this line, no?
