### ISSUE TITLE
IdsDataGrid: Clicking on inline editor does not move cursor

### ISSUE THREAD

**Issue by rcoseng** [infor-design/enterprise-wc#2388]
**Describe the bug**
Cannot move cursor on text when clicking on inline editor.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/editable-inline.html
2. Edit "101" to "test"
3. Click between "t" and "e"
4. See text selection behavior

**Expected behavior**
Text cursor should be shown and moved in between "t" and "e"

**Version**

- enterprise-wc: v1.1.0

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/120151603/71b081a1-b0a4-4e57-a85f-9001087a564d

**Additional context**
Clicking anywhere on the text always highlights it.

**Comment by tmcconechy** [comment]
@rcoseng i see you made this issue in both repos. Do you need in both for sure? Which one do you need first?

**Comment by rcoseng** [comment]
@tmcconechy yes, we need it in both. A fix for enterprise first would be better
