### ISSUE TITLE
<ids-tab> together with Angular's content projection does not work

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-wc#2393]
**Describe the bug**
With the following template where tab content is provided with Angular's content projection
```html
@for (tab of tabOptions(); track tab.value; let index = $index) {
      <ids-tab-content [value]="tab.value">
        <ids-layout-grid auto-fit="true" padding="md">
          <ng-container
            [ngTemplateOutlet]="contentChildren()[index]"
          ></ng-container>
        </ids-layout-grid>
      </ids-tab-content>
    }
```

and templateRef are provided as following

```html
   <app-example-tabs [tabOptions]="tabOptions">
      <ng-template #tab>
        <ids-text font-size="16" type="p"
          >Facilitate cultivate monetize, seize e-services peer-to-peer content
          integrateAJAX-enabled user-centric strategize. Mindshare; repurpose
          integrate global addelivery leading-edge frictionless, harness
          real-time plug-and-play standards-compliant 24/7 enterprise strategize
          robust infomediaries: functionalities back-end. Killer disintermediate
          web-enabled ubiquitous empower relationships, solutions, metrics
          architectures.</ids-text
        >
      </ng-template>
      <ng-template #tab2>
        <ids-text font-size="16" type="p">
          Bricks-and-clicks? Evolve ubiquitous matrix B2B 24/365 vertical 24/365
          platforms standards-compliant global leverage dynamic 24/365 intuitive
          ROI seamless rss-capable. Cutting-edge grow morph web services
          leverage; ROI, unleash reinvent innovative podcasts citizen-media
          networking.
        </ids-text>
      </ng-template>
    </app-example-tabs>
```

I get the following result

https://github.com/infor-design/enterprise-wc/assets/542598/30b12513-1081-41a5-beca-ff9f612d5d20

wherein the selected tab content is not visible until I switch between tabs.

**To Reproduce**

**Expected behavior**
The initial selected tab content should be populated without the need to switch between tabs

**Version**

- ids-enterprise: 1.1.0

**Comment by jdilag90** [comment]
@guoliang can you send a .zip of the files related to your tab example so we can better understand the problem?

Projecting tab content seems to work in this simpler example
![image](https://github.com/infor-design/enterprise-wc/assets/98347152/2f3f52bd-f93e-430f-a6db-bb6ff2ce8569)

**Comment by guoliang** [comment]
I have attached a git patch file. You need to clone https://github.com/infor-design/enterprise-wc-examples first, then you can use `git apply diff.patch` to get the case which doesn't work.

[diff.patch](https://github.com/user-attachments/files/15744088/diff.patch)


1. Go to Tabs
2. Go to Example
