### ISSUE TITLE
Token table: Rename "type" column

### ISSUE THREAD

**Issue by infor-jake** [infor-design/enterprise-wc#2397]
The label for the "type" column should be "Tier" to align with existing docs. https://design.infor.com/foundations/design-tokens/overview/#naming-convention

![Screenshot 2024-05-30 at 5 32 25 PM](https://github.com/infor-design/enterprise-wc/assets/117312557/7059c479-52b0-4e2c-94c5-f5d8a5dc63f8)

**Comment by tmcconechy** [comment]
cc @jmacaluso711
