### ISSUE TITLE
Token table: Include semantic tokens

### ISSUE THREAD

**Issue by infor-jake** [infor-design/enterprise-wc#2398]
Include the semantic tokens from /[ids-foundation](https://github.com/infor-design/ids-foundation/blob/main/tokens/theme-soho) to display before the component tokens in the token table.

![image](https://github.com/infor-design/enterprise-wc/assets/117312557/0c42ba09-0020-4eff-83f7-df5b2e1639f6)

**Comment by tmcconechy** [comment]
cc @jmacaluso711
