### ISSUE TITLE
Token table: Column widths

### ISSUE THREAD

**Issue by infor-jake** [infor-design/enterprise-wc#2400]
Adjust column widths to give token name/value more space at smaller breakpoints. 
<img width="814" alt="Screenshot 2024-05-30 at 7 04 12 PM" src="https://github.com/infor-design/enterprise-wc/assets/117312557/11e6f7a9-339a-4539-882f-fd1663f27084">

**Comment by tmcconechy** [comment]
cc @jmacaluso711
