### ISSUE TITLE
Token table: incomplete component names

### ISSUE THREAD

**Issue by infor-jake** [infor-design/enterprise-wc#2401]
**Describe the bug**
The `Component` column displays only the 1st word in the component name after `ids-`, which doesn't work for all components.
<img width="1069" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/117312557/02e301cc-6ccb-4915-b189-18901945fbac">

**Expected behavior**
The values in the column should match the gray component names in the token file:

<img width="292" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/117312557/eccd6bed-558b-451c-9f00-d42172057dab">

**Comment by tmcconechy** [comment]
cc @jmacaluso711
