### ISSUE TITLE
General: Need an example of a responsive layout

### ISSUE THREAD

**Issue by ashachodavarapu** [infor-design/enterprise-wc#2411]
**ISSUE:**

Version: "ids-enterprise-wc": "^1.1.0",

The implemented service (using window.matchMedia) recognizes the device type when resizing the browser, but the HTML is not updated. I tried using CSS media queries, but the same issue occurred. I also tried using Angular CDK breakpoint observer, but the issue persisted.

Please observe the videos below:
https://github.com/infor-design/enterprise-wc/assets/105051938/2013e475-b140-4973-a860-14d7e988fa99
https://github.com/infor-design/enterprise-wc/assets/105051938/b39253cd-003c-441f-9b11-f16dca511dcb

**Expected Behavior:**

Please show how we can make an example like this:

https://github.com/infor-design/enterprise-wc/assets/105051938/5b1d59da-565a-42a9-a79a-a7abccd3e254

**Comment by tmcconechy** [comment]
I updated the title. To be clear we do support "responsiveness". But to help will make an example layout with a list like your "working example" but maybe a bit simpler.

**Comment by ashachodavarapu** [comment]
@tmcconechy okay!

**Comment by tmcconechy** [comment]
@ashachodavarapu one question. In the old one that works did you use the list detail pattern here: https://main-enterprise.demo.design.infor.com/components/page-patterns/example-list-detail.html

**Comment by ashachodavarapu** [comment]
Hi @tmcconechy,
The old application used an angular splitter and a mat-list-item(angular material).
Everything is placed inside the ng-container.

Thanks.

**Comment by tmcconechy** [comment]
@jmacaluso711 note the use of splitter in the example.. Thanks!

**Comment by ashachodavarapu** [comment]
Hi @tmcconechy,
I tried this, but it's not working as expected. I have a few queries on this. Please let me know when you have time, and we will discuss it. I will show my code flow.
Thanks.

**Comment by tmcconechy** [comment]
@ashachodavarapu 

The example is here https://main.wc.design.infor.com/ids-layout-grid/example-inbox.html
What is the question? We can build an angular example but it will take additional time. cc @jmacaluso711 
My calendar is updated please include other people on the email channel tho if you need a call.

**Comment by ashachodavarapu** [comment]
Hi @tmcconechy,
The responsiveness is working fine in my Angular application when I resize the screen. I am currently investigating a few issues which I believe are unrelated to responsiveness. Once my investigation is complete, if it turns out to be related to responsiveness, I will inform you.
Thanks.

**Comment by tmcconechy** [comment]
@ashachodavarapu please see the new angular example https://github.com/infor-design/enterprise-wc-examples/pull/83

Maybe it helps

**Comment by ashachodavarapu** [comment]
Thanks! @tmcconechy
