### ISSUE TITLE
Button: Second Click Not Working for IDS Menu Button in Production Mode in Angular

### ISSUE THREAD

**Issue by ashachodavarapu** [infor-design/enterprise-wc#2412]
**Describe the bug**

- The menu button can only be clicked once in production; the second click does not work. The menu can only be opened again after a refresh.

**Expected behavior**
The menu button should work on multiple clicks, but currently, it only works once. The menu can only be opened again after a refresh, which is not the expected behavior.

**Version**
- ids-enterprise:  1.1.0

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/105051938/df86d3b6-b69e-4be5-a448-d9e32a82a328

**Comment by ashachodavarapu** [comment]
Ok @tmcconechy.

**Comment by Varalaxmi26** [comment]
team: ion and notifications

**Comment by tmcconechy** [comment]
@ashachodavarapu I think maybe i found the issue it was this https://github.com/infor-design/enterprise-wc/pull/2463

So hopefully is fixed next version. Lets test on main if you can?

**Comment by ashachodavarapu** [comment]
okay @tmcconechy, I will test.

**Comment by tmcconechy** [comment]
Thanks @ashachodavarapu you will need to pull main and then do `npm run build:dist` then copy the build. But he PR is not quite merged yet FYI. Will get a release with it soon too but not sure exact day yet probably EOM

**Comment by tmcconechy** [comment]
Im assuming this is good on https://github.com/infor-design/enterprise-wc/pull/2463 let uys know when 1.3.0 is out next week

**Comment by ashachodavarapu** [comment]
Hi @tmcconechy ,
This issue is fixed in 1.3.0 release
please close this ticket
Thanks.

**Comment by tmcconechy** [comment]
Great thanks for confirming
