### ISSUE TITLE
ids-foundation - Update core token names for color-gray

### ISSUE THREAD

**Issue by infor-jake** [infor-design/enterprise-wc#2428]
The core values for [color-gray](https://github.com/infor-design/ids-foundation/blob/main/tokens/theme-soho/core.scss) range from white to black. 

Per design, we should rename the "gray" colors to "neutral." 
- Tokens: `color-gray-` to `color-neutral-` and `color-accent-gray-` to `color-accent-neutral-`
- [Demo](https://main.wc.design.infor.com/ids-color/palette.html): `Gray (Neutral)` to `Neutral`

![image](https://github.com/infor-design/enterprise-wc/assets/117312557/33ac693a-c99e-48a1-aecf-1d0a99388964)

Related to Jira [IDS-2299](https://inforwiki.atlassian.net/browse/IDS-2299)

**Comment by tmcconechy** [comment]
@infor-jake im not seeing any named `color-neutral-` at all?  or are you saying design will rename `gray` to `neutral`. If so this comes from the export so if you update it in figma it should come through next time i take an export?
