### ISSUE TITLE
IdsLoadingIndicator: All loading indicator types are circular

### ISSUE THREAD

**Issue by Rajarajeshwari14** [infor-design/enterprise-wc#2429]
**Problem**

On setting linear type loading indicator, it shows circular indicator.
Also while trying different types of loading indicators : linear, circular, sticky - All of them are showing circular indicators only.

**To Reproduce**

1. Go to http://localhost:4300/ids-loading-indicator/example
2. Check the different types of loading indicators
3. All will show in circular motion

**Expected behavior**

Correct loading indicator should be shown as per the type : linear 
NOTE: The behaviour in hosted ids demo app is correct : [example](https://main.wc.design.infor.com/ids-loading-indicator/example.html)

**Version**
ids-enterprise-wc : 1.2.0

**Screenshots (From local)**

<img width="698" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/67271163/060533b5-4b20-4be4-854a-0a974ffa157d">

**Comment by tmcconechy** [comment]
@Rajarajeshwari14 I do not understand this issue. If I go to https://main.wc.design.infor.com/ids-loading-indicator/example.html I do see some that are linear and some circular. So i dont follow what the issue is as described?

**Comment by Rajarajeshwari14** [comment]
@tmcconechy Hi Tim, the issue is that the loading indicator is shown as circular one when I set it as linear in our app.
Here https://main.wc.design.infor.com/ids-loading-indicator/example.html it shows the different types of indicators working correctly but if I run the WC example demo app in my local then all the indicators are shown as circular one.

**Comment by tmcconechy** [comment]
@Rajarajeshwari14 what type of app? Angular? Can you confirm the markup used?

**Comment by Rajarajeshwari14** [comment]
Hi @tmcconechy , its an angular application and the ids version is 1.2.0.

Please try running https://github.com/infor-design/enterprise-wc-examples in your local.

You will find, the example which is set as 'linear' loading indicator also works in circular fashion.
