### ISSUE TITLE
IdsMultiselect form control data is not updated ( Angular Reactive Forms )

### ISSUE THREAD

**Issue by venkatesh-infor** [infor-design/enterprise-wc#2430]
**Describe the bug**
In Web Components examples of Angular, while using Angular reactive forms multiselect, data is not updated as expected. logging data after submitting but values are not updated.

**To Reproduce**

1. Go to https://github.com/infor-design/enterprise-wc-examples/blob/main/angular-ids-wc/src/app/components/ids-reactive-forms/demos/example/example.component.html
2. Click on Multiselect and select some options as of your choice.
3. Click submit and check logs of form controls - [console.log(`FormControl(testMultiselect) value is: ${this.testForm.controls['testMultiselect'].value}`); ]
4. See error that values are not updated.

**Expected behavior**
After selecting values, those should be updated but an error is occurred. Should display all selected values.

**Version**

- ids-enterprise: v1.2.0

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/167736690/1cf6094b-a606-4db2-850f-5fac88808db5

**Comment by tmcconechy** [comment]
We had a similar fix recently (after 1.2.0). Will test and confirm this asap

**Comment by tmcconechy** [comment]
@andrivarhanov can you check these maybe a recent PR has a partial fix?

**Comment by andrivarhanov** [comment]
@tmcconechy looks like it's fixed, linking to the PR now
