### ISSUE TITLE
IdsMultiselect typeahead is not working as expected.

### ISSUE THREAD

**Issue by venkatesh-infor** [infor-design/enterprise-wc#2432]
**Describe the bug**
I encountered an issue while using multiselect typeahead. After adding one option, we cannot use typeahead for the next set of list. Once selected it should be cleared then only typeahead is working. 
Note : please check in Angular examples also. 

**To Reproduce**

1. Go to Stack Blitz - https://stackblitz.com/edit/ids-enterprise-wc-120-1w3xah?file=index.html
2. Click on Multiselect and search for any option.
3. Once selected, then we cannot use search for next list of options.
4. clear selected option and can use it.

**Expected behavior**
Search should work for any number of times whenever options reside in the list. Should not limit for one.

**Version**

- ids-enterprise: v1.2.0
- 
**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/167736690/a39df1af-6754-4e3c-970e-587d41469de8)

**Comment by tmcconechy** [comment]
@andrivarhanov can you check these maybe a recent PR has a partial fix?

**Comment by andrivarhanov** [comment]
@tmcconechy unfortunately the PR haven't fixed it, it doesn't work in web components also, on it
