### ISSUE TITLE
IdsDropdown: Drop menu does not have same size as dropdown component

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-wc#2435]
**Describe the bug**
![image](https://github.com/infor-design/enterprise-wc/assets/542598/20d1f50a-3ef1-4ebf-9828-fc3ff794be78)

**To Reproduce**

1. Add `size="full"`
2. Click on dropdown element

**Expected behavior**
Drop menu should have the same width as dropdown element

**Version**

- ids-enterprise: 1.2.0

**Comment by tmcconechy** [comment]
I think this is a duplicate of https://github.com/infor-design/enterprise-wc/issues/2001 moved it in the more important bucket

**Comment by guoliang** [comment]
> I think this is a duplicate of #2001 moved it in the more important bucket

Yes looks to be same. This one can be closed then.
