### ISSUE TITLE
IdsBreadCrumb: Relies on themes and slotted for color

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#245]
**Describe the bug**
When the theme is not set the color is not working for disabled.

**To Reproduce**
1. Go to http://localhost:4300/ids-breadcrumb
2. Notice the color is ok for disabled
3. Go to http://localhost:4300/ids-breadcrumb/side-by-side
4. Notice the color is not ok for disabled

**Expected behavior**
Since the theme is not set on this page it should set the color for lighht them by default and not use slotted for the styles

**Comment by Jah25** [comment]
@tmcconechy Hey Tim this new build has even stranger differences between the Percy screenshots, It doesn't seem like it would be from anything I would have touched but some of these errors are pretty severe

**Comment by tmcconechy** [comment]
@Jah25 fixed a few issues with the build on https://github.com/infor-design/enterprise-wc/pull/277 lets see if this solves it
