### ISSUE TITLE
IdsDropdown: Positioning issue when scrolling the page

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise-wc#2451]
**Describe the bug**
The `<ids-list-box>` stays open and follows the scroll when scrolling the page.

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-dropdown/example.html
2. Make the window height small enough for a scrollbar to appear
3. Open one of the dropdowns
4. Scroll the page
5. Notice the positioning of the `<ids-list-box>`

**Expected behavior**
I guess it should behave the same way as in the core component, which is to close the dropdown as soon as you start scrolling, see e.g. https://main-enterprise.demo.design.infor.com/components/dropdown/example-clearable.html

**Version**

- ids-enterprise-wc: `1.2.0`

**Screenshots**
![dropdown_scroll](https://github.com/infor-design/enterprise-wc/assets/63045013/a8727c37-6f9c-4c4f-9047-fd8af45a3a2f)

**Platform**
 - Infor Application/Team Name: `OS Portal`

**Comment by tmcconechy** [comment]
Yes, should close the component. I think we just need to find a way to link to the scroll events.

I did it this way https://github.com/infor-design/enterprise-wc/blob/main/src/mixins/ids-popup-open-events-mixin/ids-popup-open-events-mixin.ts#L69

Maybe need to add the page container or body as well in addition to looking for that class or ids-scrollable-area. This is possibly the workaround. Adding the class or the scrollable-area (something it can target).

**Comment by tmcconechy** [comment]
Checking https://github.com/infor-design/enterprise-wc/pull/2512 as i think this fixed the issue
