### ISSUE TITLE
IdsLayoutGrid: Set individual height for rows

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-wc#2454]
**Is your feature request related to a problem or use case? Please describe.**
Using `IdsLayoutGrid`, I want to be able to specify height for the grid cells.
Here's an example with using only CSS https://jsfiddle.net/kfzh2w08/1/

First row takes only required space, while the second row will take up the remaining space

**Describe the solution you'd like**
![image](https://github.com/infor-design/enterprise-wc/assets/542598/7e53a102-a3f1-4f67-8cb3-972cd8fb80a2)

**Describe alternatives you've considered**
Alternative would be to use CSS grid directly.

**Comment by tmcconechy** [comment]
cc @jmacaluso711 -> i noticed that the min/maxRowHeight sets a variable but it doesnt seem to be used anywhere.
Wonder if maybe you need this for https://github.com/infor-design/enterprise-wc/issues/2411 and want to add this to the fix?
