### ISSUE TITLE
Breadcrumb - Remove usage guidance from readme

### ISSUE THREAD

**Issue by infor-jake** [infor-design/enterprise-wc#2458]
As component usage is published in tabs on component pages, we aim to remove similar content from code docs in efforts to consolidate. 

By migrating broader component-level info to the "Overview" and "Guidelines" tabs, it will become easier to keep consistent/accurate/DRY while prioritizing framework-specific implementation in the readme. For more details, see component [content model](https://inforwiki.atlassian.net/wiki/spaces/IDX/pages/520101643/Component+documentation). Related to [IDS-2147](https://inforwiki.atlassian.net/browse/IDS-2147).

**Expected behavior**
Please remove the below documentation from the component readme, as content has been reviewed and is either available in other tabs on the [component page](https://design.infor.com/components/components/breadcrumb/) or is no longer relevant/accurate. 

>**Description**
A breadcrumb is a navigational element that shows a user their current location in the hierarchical context of an application and allows them to navigate back through page levels.
>
> A user can navigate between views using a breadcrumb. It is best for presenting hierarchical paths in a system and showing the user the location.
>
>Breadcrumbs show the user’s location within the context of a site’s navigational hierarchy. Since it only displays the navigational path from a single point of origin, it does not reflect the user’s previous site history. While multi-line breadcrumbs are supported and sometimes necessary, truncated or single-line breadcrumbs are preferred, as they are less content-dense.

> **Use Cases**
Breadcrumbs give users a way to view and trace their steps back through various levels within a hierarchy. Breadcrumbs help to minimize confusion in applications that contain a deep navigational hierarchy.

**Comment by tmcconechy** [comment]
@infor-jake feel free to PR ~ my only concern is we added usage guidelines and description to every doc page and its nice to have. should we have something in there?

**Comment by infor-jake** [comment]
Yeah, for usage, we should point people to the site so that we don't have to maintain it in separate spots. We might want to think about linking back to the website somewhere in the repo readme to convey that more docs are available there.

The components all have (or will) a description below the component name, so it may be a bit redundant if there's an alternate description there too, but not a huge deal if it's basic and doesn't conflict?
<img width="860" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/117312557/e88eb347-6e00-488e-96ce-61120b1e47c4">

**Comment by tmcconechy** [comment]
@infor-jake yeah maybe we can think about having this only in the component docs? Ok feel free to correct and link out for the guidelines. And then simplify the descriptions as you see fit
