### ISSUE TITLE
Badge - Remove usage guidance from readme

### ISSUE THREAD

**Issue by infor-jake** [infor-design/enterprise-wc#2459]
As component usage is published in tabs on component pages, we aim to remove similar content from code docs in efforts to consolidate. 

By migrating broader component-level info to the "Overview" and "Guidelines" tabs, it will become easier to keep consistent/accurate/DRY while prioritizing framework-specific implementation in the readme. For more details, see component [content model](https://inforwiki.atlassian.net/wiki/spaces/IDX/pages/520101643/Component+documentation). Related to [IDS-2147](https://inforwiki.atlassian.net/browse/IDS-2147).

**Expected behavior**
Please remove the below documentation from the component readme, as content has been reviewed and is either available in other tabs on the [component page](https://design.infor.com/components/components/badge) or is no longer relevant/accurate. 

> **Description**
The IDS Badge Component consists of a small circle containing alphanumeric or icon that appears to another object. Badges are used to display alphanumeric values. A User can easily skim object-related values. Note that the tags and badges look the same but should not be used interchangeably. A badge is used mainly for alphanumeric values i.e. numbers currency ect. and cannot take an icon or random text. For text embellishments use a tag. For icons use an icon or status icon or alert icon.

> **Use Cases**
Badges can be use to give a non-critical information update on a piece of alphanumeric information in your application.
Badges can be used to provide users with information about an object that is worthy of attention.

>**Keyboard Guidelines**
Badges do not have tab stops and have no keyboard interaction on their own, but they may be placed in a grid cell or object that has tab focus.

**Comment by tmcconechy** [comment]
@infor-jake feel free to PR any doc changes you want if your able to.
