### ISSUE TITLE
SideBySide: 4.x Reset Squashes text sizes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#246]
**Describe the bug**
This issue probably requires a fix to 4.x

**To Reproduce**
1. Go to http://localhost:4300/ids-skip-link/side-by-side
2. Tab into page
4. See error on the web component as it is squashed for text size

**Expected behavior**
We need to change the text default somehow for the web component skip-link. Might work to just add a font size in it's css

**Comment by vivz753** [comment]
<img width="507" alt="Screen Shot 2021-07-16 at 2 26 54 PM" src="https://user-images.githubusercontent.com/22609861/126010145-6c2e7d5e-9ff7-4d8a-948d-e85a54f87c2d.png">

Link doesn't work?

**Comment by tmcconechy** [comment]
It’s there https://github.com/infor-design/enterprise-wc/blob/main/app/ids-skip-link/side-by-side.html

but it’s new, maybe your on an older branch?try:

git checkout main
git pull
npm run start
// then branch

**Comment by vivz753** [comment]
Got it, thanks.

Do we want the first tab to look like the second tab text size? 
<img width="387" alt="Screen Shot 2021-07-16 at 6 48 17 PM" src="https://user-images.githubusercontent.com/22609861/126021760-e5c97f20-5a99-4903-a4a4-6c194efce7b4.png">
<img width="382" alt="Screen Shot 2021-07-16 at 6 48 22 PM" src="https://user-images.githubusercontent.com/22609861/126021761-db729400-926a-46dc-ac40-f0edca06c6c3.png">

**Comment by tmcconechy** [comment]
it should look like the bigger one see https://main-enterprise.demo.design.infor.com/components/skiplink/example-index.html

But in the new components we want the underline other size they should look the same. 
- same size
- same font/color
- but have the underline
