### ISSUE TITLE
IdsDropdown: Tooltips don't work when the dropdown is in a modal

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise-wc#2462]
**Describe the bug**
Tooltips on the dropdown and dropdown options don't work when the dropdown is in a modal

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-enterprise-wc-120-b3fpws?file=index.html
2. Hover the dropdown to confirm that the tooltip appears
3. Click on "Trigger a Modal"
4. Hover the dropdown
5. Notice that no tooltip appears

**Expected behavior**
Tooltips should work when the dropdown is in a modal

**Version**
- ids-enterprise: `1.2.0`

**Platform**
 - Infor Application/Team Name: `OS Portal`

**Comment by tmcconechy** [comment]
I think this is a duplicate but not finding the other issue in the maze of issues. Was a zindex issue.
So will take a look against this one.
