### ISSUE TITLE
ids-foundation - Add font tokens

### ISSUE THREAD

**Issue by infor-jake** [infor-design/enterprise-wc#2465]
Both core and system font tokens are [available](https://www.figma.com/design/7xMSXwCpK3eq4uGqkDDDav/IDS-Design-Tokens?m=auto&node-id=13366-2520&t=xpLcD7b3s7dHMut5-1) as variables in the Figma token library.

Properties include font-family, font-size, font-weight, line-height. 

They are available as both core and system-level tokens. Also available as unique combinations of family/size/weight using Figma Text Styles (their equivalent to classes).

- Add core font tokens to /theme-soho/core.scss 
- Add system font tokens to /theme-soho/
- Replace semantic tokens and mapped values in /enterprise-wc tokens

Related to [IDS-1991](https://inforwiki.atlassian.net/browse/IDS-1991).

**Comment by infor-jake** [comment]
CSS vars generated from Figma: [Fonts tokens.txt](https://github.com/user-attachments/files/15994224/Fonts.tokens.txt)

**Comment by tmcconechy** [comment]
Closing as done under https://github.com/infor-design/enterprise-wc/issues/2471
