### ISSUE TITLE
IdsButton: Add abilty to show truncated text w ellipsis and tooltip

### ISSUE THREAD

**Issue by ajayponnapati** [infor-design/enterprise-wc#2468]
**Describe the bug**
whenever we set a certain width to ids-button the text inside the button is not visible fully.

**To Reproduce**

1. Go to [stackblitz](https://stackblitz.com/edit/ids-enterprise-wc-120-czvxag?file=index.html)
2. See the content of the button.It is not fully visible

**Expected behavior**
The text should be visible via tooltip and it should have ellipsis class applied.

**Version**
- ids-enterprise: 1.2.0

**Comment by ashachodavarapu** [comment]
Hi @tmcconechy,
Can you please add my team label here, this requirement is also needed for the **Notification Center- ION**
Thanks.

**Comment by tmcconechy** [comment]
Fixed as per https://oxford.awsdev.infor.com/infor-design/enterprise-wc/-/merge_requests/32
