### ISSUE TITLE
IdsDatagrid: blank display on data grid with virtual scrolling

### ISSUE THREAD

**Issue by philinfor** [infor-design/enterprise-wc#2472]
**Describe the bug**
Blank display when toggling a column in data grid and when scrolling fast in a large data set

**To Reproduce**
Steps to reproduce the behavior (see screen recording):
 Access: https://stackblitz.com/edit/ids-enterprise-wc-120-scqypu?file=index.html

1. Blank display when scrolling fast in large data set.

https://github.com/infor-design/enterprise-wc/assets/173119452/f19ad936-d861-404e-aa8a-0ec5e143b891

2. Blank display when scrolling down then toggle hide/show column

https://github.com/infor-design/enterprise-wc/assets/173119452/409a53ba-1ae4-460f-a083-b42110240525

**Expected behavior**
There should be no blank display

**Comment by tmcconechy** [comment]
https://github.com/infor-design/enterprise-wc/issues/2281 may be related.

**Comment by tmcconechy** [comment]
Closed by PR in oxford https://oxford.awsdev.infor.com/infor-design/enterprise-wc/-/merge_requests/22
