### ISSUE TITLE
IdsDropdown in modal cause drop menu out of placement

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-wc#2473]
**Describe the bug**
Use of `IdsDropdown` in `enterprise-ng` modal causes drop menu out of placement

I suspect it is caused by the following fix which was added in `1.1.0`
- [Dropdown] Fixed dropdown positioning logic so it works on modals and popups, and better opens up if it does not fit. (https://github.com/infor-design/enterprise-wc/issues/2165)

**To Reproduce**

1. Use `IdsDropdown` in `enterprise-ng` modal

**Expected behavior**
Drop menu should be underneath the dropdown field.

**Version**

- ids-enterprise: 1.1.0, 1.2.0

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/542598/5a5947a1-ea77-46da-b34b-ef7da34535fc)

**Comment by anhallbe** [comment]
@guoliang @tmcconechy was this fixed? I'm seeing this in 1.4.0:


https://github.com/user-attachments/assets/7a2f7ffd-077f-4358-a7c0-666f51fa80da

It's not the exact same issue, but still doesn't quite work as expected when inside an `enterprise-ng` modal.

**Comment by guoliang** [comment]
@anhallbe I don't remember for `1.4.0` but it seems to work in `1.4.1`

**Comment by anhallbe** [comment]
Same issue in 1.4.1. Created https://github.com/infor-design/enterprise-wc/issues/2682

**Comment by guoliang** [comment]
@anhallbe aha, I didn't watch the video. looks like it another issue different from the one I reported.

**Comment by anhallbe** [comment]
Yeah after some testing it seems like the issue is quite different. We can reproduce it in a legacy modal, but really the issue can be seen in any scroll container. See https://github.com/infor-design/enterprise-wc/issues/2682#issuecomment-2272680008
