### ISSUE TITLE
IdsDataGrid: Default sort is not working for nested objects

### ISSUE THREAD

**Issue by aparimalla** [infor-design/enterprise-wc#2485]
**Is your feature request related to a problem or use case? Please describe.**
The default sort is not working for the name column in ids-expandable-datagrid.
FYI, the name/description column field is in an object of object(nested object). It is working fine for other columns that don't have fields as in the objects. Please see the below code and snapshots.

```
export interface Locations {
  entryInput: LocationInfo,
  status: string;
  version: string;
}

export interface LocationInfo {
  name: string;
  description: string;
}
```

```
ngAfterViewInit():void {
    this.dataGrid.nativeElement.columns = [
      {
        id: 'name',
        name: this.deskTranslateService.instant('nameColumn'),
        field: 'entryInput.name',
        sortable: true,
        resizable: true,
        formatter: this.dataGrid.nativeElement.formatters.expander,
        width: 350,
        overflow: 'ellipsis',
      },
      {
        id: 'description',
        name: this.deskTranslateService.instant('descriptionColumn'),
        field: 'entryInput.description',
        width: 350,
        sortable: true,
        resizable: true,
        formatter: this.dataGrid.nativeElement.formatters.text,
        overflow: 'ellipsis',
      },
     {
        id: 'version',
        field: 'version',
        name: this.deskTranslateService.instant('versionColumn'),
        width: 300,
        sortable: true,
        resizable: true,
    }];
    this.dataGrid.nativeElement.setSortColumn('name', true);
}
```
![image](https://github.com/infor-design/enterprise-wc/assets/114559476/429e558c-3bcf-4a26-b6a6-1ec1834e3940)

I've tried default sort with other column named 'version' ( this.dataGrid.nativeElement.setSortColumn('version', true); ) , the default sort is working fine for that column. Please see below snapshot for reference.

![image](https://github.com/infor-design/enterprise-wc/assets/114559476/7a863af2-7e86-4297-852c-b5424136963a)

**Additional context**
Please refer this Stackblitz example - https://stackblitz.com/edit/stackblitz-starters-9l4j2r?file=src%2Fapp%2Fexample%2Fexample.component.ts,src%2Fapp%2Fexample%2Fexample.component.html,src%2Fapi%2Fbooks.json

**Comment by janblankenburgh** [comment]
Hi @tmcconechy , any expectation when this issue will be fixed?

**Comment by tmcconechy** [comment]
@janblankenburgh if a priority we can try to slot it in next sprint. We currently have 300 plus issues in the backlog.

**Comment by janblankenburgh** [comment]
Hi @tmcconechy not sure what the length of your sprints is. We are aiming to code freeze the version that will need this fix October 14th. If you could facilitate that, would be great. In any case I'm interested to know when we can expect a fix so we can plan accordingly.
Thanks for the support.

**Comment by tmcconechy** [comment]
@janblankenburgh at this point the sprint is allocated. If someone finishes early might be able to get it but that timeline is very tight for us so cant promise that date.

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4290
