### ISSUE TITLE
IdsMultiSelect: Popup should move with scroll/hide on scroll

### ISSUE THREAD

**Issue by Varalaxmi26** [infor-design/enterprise-wc#2487]
Ids-multi-select popup is not moving along with the scroll.
 

**To Reproduce**
open ids-multiselect-> make sure the page has scroll-> now scroll the page and observe-> the popup is in a fixed position. Popup should move along with ids-multiselect.

Issue observed in https://main.wc.design.infor.com/ids-multiselect/groups.html also.

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/59650265/207bf686-cc4d-420a-aa0a-962ff93b2137)

**Expected behavior**
Popup should move along with scroll or hide on scroll

**Version**
 "ids-enterprise-wc": "^1.1.0",

**Comment by tmcconechy** [comment]
This should be the same issue as https://github.com/infor-design/enterprise-wc/issues/2451 but will keep this open to make sure we test it on multiselect too

**Comment by tmcconechy** [comment]
Should be fixed with #2451
