### ISSUE TITLE
IdsMenuButton: Too much space between tick boxes and text

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#2495]
**Describe the bug**
There is too much space between tick boxes and text.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-menu-button/disabled.html
2. Click on `Settings` button
3. Notice the space between check/tick boxes and text

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/102151352/2cd5aa81-3a1e-4857-82d2-6708f2104580)

**Platform**
 - All major browsers

**Additional context**

**Comment by tmcconechy** [comment]
Fixed as per https://oxford.awsdev.infor.com/infor-design/enterprise-wc/-/merge_requests/54
