### ISSUE TITLE
IdsAccordion: Clicking ids text closes the accordion

### ISSUE THREAD

**Issue by silarapusandhya** [infor-design/enterprise-wc#2497]
**Description:**
I have used the textbox in accordion panel. When ever I click enter or spacebar (inside or outside the textbox) then the accordion is getting closed automatically but it should close upon clicking header field.

**Code:**
```<ids-container role="main" padding="8" hidden>
  <ids-theme-switcher mode="light"></ids-theme-switcher>

  <ids-layout-grid cols="2" gap="md" padding-x="md">
    <ids-layout-grid-cell>
      <ids-accordion allow-one-pane="true">
        <ids-accordion-panel>
          <ids-accordion-header slot="header">
            <ids-text font-size="16">Warehouse Location</ids-text>
          </ids-accordion-header>
          <ids-text slot="content" id="content-1">
            <ids-input
              id="test-input"
              type="text"
              label="First Name"
              placeholder="Normal text Field"
            ></ids-input>
          </ids-text>
        </ids-accordion-panel>
      </ids-accordion>
    </ids-layout-grid-cell>
  </ids-layout-grid>
</ids-container>
```

**Reproduce steps:**
1) Open accordion 
2) Enter some text in textbox field.
3) Press enter key or space key in keyboard.
Note: Accordion is closing but actually it should not close.
 
 
 I am attaching the video for the reference. Please do check and suggest any way to fix this issue.
 

https://github.com/infor-design/enterprise-wc/assets/166589171/fd75856a-a256-4811-87f2-650d769df40c

**Comment by tmcconechy** [comment]
Fixed see notes on https://inforwiki.atlassian.net/browse/IDS-4392
