### ISSUE TITLE
IdsColorPicker: scrolls into view on page load in Angular

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise-wc#2502]
**Describe the bug**
In Angular apps, if the `IdsContainer` does **_NOT_** have the `hidden` attribute, `IdsColorPicker` is scrolled into view when the page is loaded.

**To Reproduce**
1. Run the Web Components with Angular project (https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc)
2. Go to `src/app/components/ids-color-picker/demos/example/example.component.html`
3. Remove `hidden` from `ids-container`
4. Add the following code between `<ids-theme-switcher>` and the first `<ids-layout-grid>`:
```html
<ids-layout-grid>
  <ids-layout-grid-cell height="5000px">Hello</ids-layout-grid-cell>
</ids-layout-grid>
```
5. Navigate to `http://localhost:4200/ids-color-picker/example`
6. Notice that the colors pickers are scrolled into view

**Expected behavior**
They shouldn't be scrolled into view

**Version**

- ids-enterprise-ng: `1.2.0`

**Platform**
 - Infor Application/Team Name: `OS Portal`

**Comment by tmcconechy** [comment]
The ids-container hidden is helping with the Flash of unstyled content but i wanted to try another way https://github.com/infor-design/enterprise-wc/issues/2357

I think the color picker is updating in a weird way because of angular. We will check this out

**Comment by anhallbe** [comment]
It looks like the color picker *always* steals focus when it is added to the DOM (connectedCallback -> #configureSwatches), if I read this line correctly:

https://github.com/infor-design/enterprise-wc/blob/8071eda7b07cdd7b6445c22ec86a2651db3be833/src/components/ids-color-picker/ids-color-picker.ts#L677
