### ISSUE TITLE
IdsButton: Change to slate60

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#252]
**Describe the bug**

Should make changes to the icon button and text only button and check the card button color as per https://github.com/infor-design/enterprise/pull/5413#pullrequestreview-705197287

In light/new theme the icon buttons should be slate60

**To Reproduce**
1. Go to http://localhost:4300/ids-button
2.  Check icon and text button color

**Expected behavior**
Change to slate like the EP PR

**Additional context**
https://github.com/infor-design/enterprise/pull/5413#pullrequestreview-705197287

**Comment by vivz753** [comment]
This is for the Secondary button, I'm guessing? 

Not sure if I'm understanding this correctly.. but I'm supposed to change the font color for the Secondary buttons from black to slate-6/slate-60 (#606066)?

The bottom button is what we're going for. Is that correct? 
<img width="217" alt="Screen Shot 2021-07-14 at 6 07 46 PM" src="https://user-images.githubusercontent.com/22609861/125712092-561d7077-8c42-461d-a2b1-ca79c914756b.png">

**Comment by tmcconechy** [comment]
Should refer to this issue https://github.com/infor-design/enterprise/issues/5307
It was the icon and text icon buttons to test. But to be thorough you could just compare the text and icon color on all buttons https://main-enterprise.demo.design.infor.com/components/button/example-index.html

And make sure they are in sync.

Thanks!
