### ISSUE TITLE
IdsNotificationBanner: Misnamed / miscased events

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#2524]
**Describe the bug**
The events here are misnamed  https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-notification-banner/ids-notification-banner.ts#L308-L310 (using mixed case)

Suggest we change these to `close/beforeclose` ect

**Comment by ashachodavarapu** [comment]
Hi @tmcconechy,
In my project also have this issue
please add the ION notification center label to this ticket.

Thanks
