### ISSUE TITLE
IdsEditor: Set value does not work

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#2526]
**Describe the bug**
`<ids-editor value="test"></ids-editor>` and `idsEditor.value = "test"` for on the fly value change does not work as `ids-input`.

**Expected behavior**
Work as input: `<ids-editor value="test"></ids-editor>` or `idsEditor.value = "test"`

**Comment by inforandy** [comment]
valid, scheduling a fix for this one in aug
