### ISSUE TITLE
IdsSplitter - splitter position isn't retained when expanding and collapsing. 

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#2527]
**Describe the bug**
The splitter position seems to get lost when expanding and collapsing. It seems to return to the initial 25% in the example only it puts that 25% on the right pane.

This is related to https://github.com/infor-design/enterprise-wc/issues/2083

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-splitter/expand-collapse.html - Notice the left split pane is at 25%.
2. Click on expand collapse button to collapse the left split pane and again to expand it
3. Notice the splitter is not it the original position. It seems to be setting the right split pane to 25%

**Expected behavior**
Expect calling expand to restore splitter to it's previous location.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

Animated GIF showing the issue

![splitter-position](https://github.com/infor-design/enterprise-wc/assets/4737815/da0ecd56-2a3b-4e79-89df-c4f0a68292c7)

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 11 
 - Browser Name: chromeVersion 126.0.6478.61 (Official Build) (64-bit)126.0.6478.61

**Additional context**

**Comment by tmcconechy** [comment]
@andriivarhanov this is a followup to that previous fix FYI
