### ISSUE TITLE
IdsEditor: modal doesn't close - BETA 1.3

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#2536]
**Describe the bug**

**To Reproduce**

1. Go to  https://main.wc.design.infor.com/ids-editor/example.html
2. Add image
3. See error
4. Refresh the page
5. Click on editor to set focus 
6. Add Image
7. See error
8. Unable to close the modal

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1270" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/7d5d5ca7-9366-4f4f-9360-0f0b9019a2d1">
<img width="1722" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/0901e3f3-bfce-4ab0-b1ec-687a36540f1a">
<img width="1057" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/49a2c21f-450a-4711-af74-2efe1cfd7b11">

**Platform**
All 

**Additional context**
Hyperlink is also affected

**Comment by tmcconechy** [comment]
Duplicate this is fixed already on main
