### ISSUE TITLE
IdsUploadAdvanced: Continuous script filename overlaps text and border - BETA 1.3

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#2541]
**Describe the bug**
Continuous script filename overlaps text and border.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-upload-advanced/example.html
2. Click on `upload files` link or Drag a file that has a long file name
3. See error

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/102151352/539f130e-46b6-4eca-8b71-1046ad63448a)

**Platform**
 - All major browsers

**Additional context**

**Comment by tmcconechy** [comment]
Fixed as per https://oxford.awsdev.infor.com/infor-design/enterprise-wc/-/merge_requests/61#c3b95502ddc385889ac90771e75e6b6bcc9eb082
