### ISSUE TITLE
IdsTabs: More button issue - BETA 1.3

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#2543]
**Describe the bug**
More button is not properly placed when the app menu is expanded.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-tabs/app-example.html
1. Click on menu button to expand the app menu
1. Click on more button
1. See error

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/102151352/21950b6c-4968-49b7-9c20-c6aae250932b)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by jbrcna** [comment]
this is now working as expected. thank you @andriivarhanov . Nice fix!
<img width="1704" alt="image" src="https://github.com/user-attachments/assets/a56e423f-8c16-4841-bfcd-5caa8425042e">
