### ISSUE TITLE
IdsInput: Autocomplete with dynamic data sometimes displays unformatted data

### ISSUE THREAD

**Issue by rokusasu13** [infor-design/enterprise-wc#2545]
**Describe the Issue**
I am using a web service to supply the autocomplete.data when the user types a key and the pop-up sometimes display unformatted data. I added screenshots below for comparison. Also are there plans to add the source attribute or something similar for dynamic data?

**To Reproduce**
Steps to see the question or problem:
1. Create an ids-input with autocomplete
2. Add an input event that calls a web service to set autocomplete data
3. Type different keywords in the ids-input field to test the web service
3. The pop-up shows the autocomplete data
4. Sometimes the pop-up shows unformatted data (See screenshot below)

**What are you trying to do**
The autocomplete data will be updated via web service whenever the ids-input field value changes.

**What did you try so far**
Setting autocomplete.data to false before setting the new data then switching it back to true fixes the issue but the pop-up closes every time the user types a key.

**Version**

- enterprise-wc 1.2.0

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/162077484/d3df9ebd-4752-46a8-b121-c10c1322f540)
![image](https://github.com/infor-design/enterprise-wc/assets/162077484/ff49480f-6d44-4593-a83e-6ec5c65c593f)

**Platform**
 - OS Version: Windows 11 Enterprise
 - Browser Name: Chrome
 - Browser Version: Version 126.0.6478.127 (Official Build) (64-bit)

**Additional  Context**
Add any other context about the question or problem here, including the use case if relevant.

**Comment by tmcconechy** [comment]
@rokusasu13 can you make an example for this https://stackblitz.com/edit/ids-enterprise-wc-120?file=index.html
Some the steps im not exactly sure what you did so might come out with a different outcome

**Comment by rokusasu13** [comment]
I used the link above and copied the ids-input autocomplete example code but I keep getting this error after typing some characters.

Code:
```
      <ids-input
        id="input-autocomplete-2"
        placeholder="This input's label is visible"
        size="md"
        label="Autocomplete Input (states)"
        autocomplete
        search-field="label"
      >
      </ids-input>
```

Error occurred:
this.alignTarget.getBoundingClientRect is not a function

**Comment by tmcconechy** [comment]
Fixed as per https://oxford.awsdev.infor.com/infor-design/enterprise-wc/-/merge_requests/27#db3540bd6872ad2aa50dd117af32876bc1dc568e
