### ISSUE TITLE
IdsProcessIndicator: Details are missing in a smaller viewport - BETA 1.3

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#2547]
**Describe the bug**
Details are missing in a smaller viewport.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-process-indicator/example.html
2. Adjust into a smaller viewport
3. Labels/details are missing

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/102151352/c65c51f4-ac48-44cf-b568-400112a3769a)

![image](https://github.com/infor-design/enterprise-wc/assets/102151352/27d5c3e5-fbbe-4ba8-adc3-ef3ba992fefa)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@glenlieorillo this is as designed. We cant show all the detail at the lowest breakpoint so it is hidden
