### ISSUE TITLE
IdsActionPanel: Action Panel is displaying in full screen instead of modal in Mobile Devices - BETA 1.3

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise-wc#2549]
**Describe the bug**
Action panel is displaying in full screen rather than being a modal.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-action-panel/example.html
2. Emulate to mobile device
3. Click the Open Action Panel
4. Action Panel shows full screen

**Expected behavior**
Action panel is displayed as modal window

**Version**

- ids-enterprise-wc: v1.3

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/156752175/4432b191-09b2-4236-ac5c-64293c6b5f03)

**Comment by tmcconechy** [comment]
@n-ace-ancog its using the modal code which will cause it to be full size on mobile. But this is configurable https://main.wc.design.infor.com/ids-modal/fullsize.html

So working as designed
