### ISSUE TITLE
Ids List View: Selected event is not triggered on row click/row selection in single selection list

### ISSUE THREAD

**Issue by ashachodavarapu** [infor-design/enterprise-wc#2565]
**Issue:**
The selected event is not triggered upon clicking the list row; only the click event is activated.

**Steps to reproduce the behavior:**
- Navigate to the IDs list view, which includes both click and selected events.
- Attempt to click on a list item and observe the console logs.
-**HTML:**
`  <ids-list-view-item
                                    (click)="onRowClick(item)"
                                    (selected)="selectedEvent($event)"
                                >`
-   **Type Script**
` selectedEvent($event: any) {
    console.log('Row selected event is logged', $event);
  }`
- typing `$('ids-list-view-item').selected = true` in the console on the single select example gives an error
 
**Expected behavior:**
Upon clicking a row, both the click and selected events should trigger in single selection mode.

**Version**
- ids-enterprise: ^1.2.0

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/105051938/b140339a-a652-4b8d-8045-e567f7570aae

**Comment by ashachodavarapu** [comment]
Hi @andrivarhanov ,
Can you please add an ION notification center label to this ticket?
CC: @tmcconechy

**Comment by ashachodavarapu** [comment]
Hi @tmcconechy,
It's not working in my application, and I've also checked the Angular example code at http://localhost:5000/ids-list-view/selected-event, where the selected event is not being triggered either.
please observe the below video=>
https://app.screencast.com/yYlTBbXvfvIiN

**Comment by tmcconechy** [comment]
@andrivarhanov can you take a look?

**Comment by andrivarhanov** [comment]
Hi @ashachodavarapu what version of `ids-enterprise-wc` is installed? The fix for selected event is in 1.4.0 

@tmcconechy the Angular example haven't worked because we have 1.3.0 in Angular examples

**Comment by tmcconechy** [comment]
@andrivarhanov please pull main and try again. I updated it to 1.4.0

**Comment by andrivarhanov** [comment]
works on 1.4.0 in Angular examples, just checked. @ashachodavarapu could you please try 1.4.0 and let us know

https://github.com/user-attachments/assets/c56d517a-3e0d-449d-b1bd-6d4ccd699994

**Comment by ashachodavarapu** [comment]
okay @andrivarhanov, I will check and let you know if I am facing any issues.
Thanks.

**Comment by ashachodavarapu** [comment]
Hi @andrivarhanov,
Now I can see the selected event is triggered, it's working as expected 
Thanks
cc: @tmcconechy

**Comment by inforandy** [comment]
https://www.figma.com/design/IFgqWZi79b414gT0OJTCCT/IDS-2551-%7C-Notifications-Standardize-row-height-in-notification-center-update-feed?node-id=0-1&t=rQjY9Fpp2duNeP3p-0 updated designs with standardized row height here for reference
