### ISSUE TITLE
IdsPopupMenu: Positioning is off when placed inside a query container

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#2566]
**Describe the bug**
When an IdsPopupMenu element (IdsDropdown, IdsMenuButton etc) is placed inside a query container, i.e an element with the [`container-type`](https://developer.mozilla.org/en-US/docs/Web/CSS/container-type) property, the positioning of the Popup Menu is off.

**To Reproduce**

1. Go to https://stackblitz.com/edit/stackblitz-starters-y5y12k?description=HTML/CSS/JS%20Starter&file=index.html&terminalHeight=10&title=Static%20Starter
2. Click on 'Menu'
3. See issue

**Expected behavior**
The Popup Menu should be correctly placed even if a parent element has a CSS `container-type` property.

**Version**

- ids-enterprise: 1.2.0

**Screenshots**
Minimal repro:
<img width="747" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/17e51594-7214-4d6d-a9f7-f8e1f64e10f1">

Real-world example:
<img width="1728" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/4991954/16c0f9df-5e49-4666-8a09-7340be1eb052">

**Platform**
 - Infor Application/Team Name: Portal

**Additional context**
This happens when the container is positioned with things like `position: absolute`, but also happens if the container is positioned based on other elements, such as a IdsLayoutFlexItem. See: https://stackblitz.com/edit/stackblitz-starters-h9agae?description=HTML/CSS/JS%20Starter&file=index.html&terminalHeight=10&title=Static%20Starter

**Comment by tmcconechy** [comment]
@anhallbe was not aware of [this](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries) it definitely has no idea in the code how to handle that right now
