### ISSUE TITLE
IdsLookup: size attribute

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-wc#2568]
**Is your feature request related to a problem or use case? Please describe.**
`IdsDropdown`, `IdsInput` has a `size` attribute to set the the field width.
`IdsLookup` doesn't seems to have that attribute option to set.

**Describe the solution you'd like**
Add `size` setting to `IdsLookup`, which works the same way as `IdsDropdown`, `IdsInput`

**Comment by jmacaluso711** [comment]
@guoliang `IdsLookup` currently has the `size` attribute available. You can see examples [here](https://main.wc.design.infor.com/ids-lookup/sizes.html). Is this what you were looking for? I noticed that the `size` attribute isn't mentioned in the `IdsLookup` documentation, so I can work on getting that added.

cc: @tmcconechy

**Comment by guoliang** [comment]
Seems like once you start to use the `nativeElement` to set the different options, the attribute set to the HTML element will not have any effect anymore.

I had to set the size to `lookup.nativeElement.size = "full"` for it to take effect instead of just using
```html
<ids-lookup size="full"></ids-lookup>
```

So for me to be able to entirely use the HTML tags to set the lookup component's settings I need the following to be fixed first https://github.com/infor-design/enterprise-wc/issues/2570

**Comment by guoliang** [comment]
Yea, I have no problem with using `nativeElement`. It just that in following section:
https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-lookup#settings-and-attributes

says `gridSettings`, and `size` and so on are available to use as `attributes` then I expect them to be used as attributes. but at least for `gridSettings` it doesn't work. instead I have to set it by using `nativeElement`. Consequence of that I need to use `nativeElement` to set every other attribute settings.

Something strange though, I can use and set the `size` attribute in the `enterprise-wc` examples, however the same template code with size set to `xs`

```html
  <ids-lookup
    id="lookup-6"
    label="Autocomplete Lookup"
    title="Select an Item"
    autocomplete
    field="description"
    size="xs"
  >
  </ids-lookup>
```
doesn't work in the `enterprise-wc-examples/tree/main/angular-ids-wc` project. I have changed to use latest version of `enterprise-wc: 1.5.0`. 

So something is strange, or maybe `main` has fixed some bug which hasn't been released to a package yet?

**Comment by tmcconechy** [comment]
@guoliang anything that takes an object like `dataset`, `gridSettings` cant be used as an Html Element as we dont have a JSON parser like angular does. Maybe you can make a setter that can do it. We can only do it on primative types. So for grid settings would have to do it as `lookup.gridSettings = {}`

We dont plan on adding object support for settings that take objects as we would have to bridge between angular or you would have to serialize it as a string on the property. Not being able to use objects is a known thing with web components.

I dont think right now main has any other fixes because it was just made. (at least in this area but i merged one or two PRs)

**Comment by tmcconechy** [comment]
@jmacaluso711 can you try out the `size` attribute in an angular example and see if this needs reopening? @guoliang Yes size is a primative type so should work. May be an issue with the setter...
