### ISSUE TITLE
IdsCard: Multiple selection on throws an unexpected error.

### ISSUE THREAD

**Issue by SAIPRANAY-GANGULA** [infor-design/enterprise-wc#2569]
**Describe the bug**
Multiple selection on `ids-card` throws an unexpected error.

**To Reproduce**

1. Go to https://stackblitz.com/edit/ids-enterprise-wc-130-aweu1j?file=index.html
2. see errors both on the console & page

![image](https://github.com/infor-design/enterprise-wc/assets/56952302/6d893b0f-e8c8-4bc1-beed-ac5e11306cc5)

**Expected behavior**
It should work properly similar to a single selection.
https://stackblitz.com/edit/ids-enterprise-wc-130-7x2xwr?file=index.html

**Version**

- ids-enterprise-wc: 1.3.0

**Comment by tmcconechy** [comment]
Fixed on https://oxford.awsdev.infor.com/infor-design/enterprise-wc/-/merge_requests/64#514f83d98ea8eaba028c4bb01a9e2fb7fa365bec
