### ISSUE TITLE
IdsDataGrid: resetDirtyCells for specific row

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#2586]
**Is your feature request related to a problem or use case? Please describe.**
After editing a record and sending to the server, I need to remove the dirty but just for that record not for the whole grid.

**Describe the solution you'd like**
A method like `resetDirtyCells(row|rowIdx)`

**Describe alternatives you've considered**
```javascript
resetFlagRow: function(rec) {
   var rowIdx = this.store.indexOf(rec),
      row = this.idsDom.rowByIndex(rowIdx),
      flagCls = 'is-dirty';

   Ext.each(row.querySelectorAll('ids-data-grid-cell.' + flagCls), function(cell) {
      cell.classList.remove(flagCls);
   });

   if (flagCls === 'is-dirty' && row.dirtyCells) {
      delete row.dirtyCells;
   }
}
```

**Comment by tmcconechy** [comment]
Yeah would need to add a rowParam to https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/ids-data-grid.ts#L3137

If you wanted to you could contribute a pull request? But we will get to this.

**Comment by fabiojpoli** [comment]
> Yeah would need to add a rowParam to https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/ids-data-grid.ts#L3137
> 
> If you wanted to you could contribute a pull request? But we will get to this.

Will be a honor to give a try!

**Comment by tmcconechy** [comment]
See: https://github.com/infor-design/enterprise-wc/blob/main/doc/CONTRIBUTING.md#submitting-pull-requests
