### ISSUE TITLE
IdsSplitter: initially setting collapse=true on a splitpane markup causes right ids-split-pane to not take up full width of ids-splitter

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#2588]
**Describe the bug**
using `<ids-splitter-pane collapsed="true" id="left-pane">` to initially display the left-pane as collapsed seems to mess up the width of the ids-splitter when calling idsSplitter.collapse() and expand()

**To Reproduce**
1. In `ids-splitter/demo/expand-collapse.html` add `collapsed="true"` to the `#left-pane`
2. Go to http://localhost:4300/ids-splitter/expand-collapse.html and notice it's initially collapsed
3. Click the expand/collapse button (hamburger icon button) to expand and collapse
4. Notice the right splitter seems to get smaller and smaller

**Expected behavior**
calling idsSplitter.collapse() and expand() should work normally even when initially setting to collapsed through the markup

**Version**
- ids-enterprise-wc: 1.2.0 and 1.3.0

**Screenshots**
![splitter-collapse-issue](https://github.com/user-attachments/assets/0ff8d8b4-191d-4105-bb1b-fd8a10543098)

expand-collapse.html 
[expand-collapse.zip](https://github.com/user-attachments/files/16196370/expand-collapse.zip)

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: latest

**Additional context**

**Comment by jdilag90** [comment]
@tmcconechy I think this was fixed in https://github.com/infor-design/enterprise-wc/pull/2734
