### ISSUE TITLE
IdsColor: Update palette demo

### ISSUE THREAD

**Issue by infor-jake** [infor-design/enterprise-wc#2593]
**Describe the solution you'd like**
Swap out hex values in the [palette demo](https://main.wc.design.infor.com/ids-color/palette.html) with core palette names, like green-10, green-20, to encourage token use.

**Additional context**
![Screenshot 2024-07-12 at 2 15 21 PM](https://github.com/user-attachments/assets/9d6161a0-60a0-4ea3-874e-1129dc7a015f)

Edit: 
- Also change `gray` values to `neutral` to reflect #2428 
- Reverse display order of swatches to begin with the bolder colors (-100, -90, -80...)

**Comment by infor-jake** [comment]
Can we remove `color-` from the names so that they fit when displayed at the doc site width?
![image](https://github.com/user-attachments/assets/db81d5c4-e150-4ecf-8161-5fcbc23a38ea)

**Comment by tmcconechy** [comment]
@infor-jake done https://github.com/infor-design/enterprise-wc/pull/2776

![Screenshot 2024-08-29 at 3 00 44 PM](https://github.com/user-attachments/assets/2ce21344-27d1-484f-a094-c65ebdbfc4a3)
