### ISSUE TITLE
IdsDatagrid: Double click is not consistent on some devices

### ISSUE THREAD

**Issue by patrickluisdeguzman** [infor-design/enterprise-wc#2599]
**Double click is not consistent on some devices**

**To Reproduce**

1. Open enterprise-wc
2. Go to Lists
3. Select Datagrid
4. Select double-click.html

or Go to https://main.wc.design.infor.com/ids-data-grid/double-click.html

**Expected behavior**
Double click should be triggered on any device

**Version**
"1.0.0-beta.18"
"1.3.0"

**Video**

https://github.com/user-attachments/assets/f2a3c1ae-d1fd-4bea-a4a4-481f79c6ffc5

https://github.com/user-attachments/assets/b233c3e3-ba20-4a1b-864e-1952797e1b52

**Platform**
Dell Laptop
Windows 11

Microsoft Edge
Version 126.0.2592.102 (Official build) (64-bit)
Chrome
Version 126.0.6478.183 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
I wonder if they implement them differently in browsers? I can test it later but did you try just putting a dblclick on any normal div element and see if it behaves the same?

Also dblclick in an editor might not be a thing, just rows.

**Comment by patrickluisdeguzman** [comment]
> I wonder if they implement them differently in browsers? I can test it later but did you try just putting a dblclick on any normal div element and see if it behaves the same?
> 
> Also dblclick in an editor might not be a thing, just rows.

Yes, Tim, already tried it on different elements even on a normal div element. Double clicking is not triggered on some devices.

**Comment by patrickluisdeguzman** [comment]
Hello Tim, can I ask for an update on this issue? Thanks!

**Comment by tmcconechy** [comment]
@patrickluisdeguzman we have many issues and this one felt minor so have it in the backlog. Any updates as to why it would not be a minor issue?

**Comment by patrickluisdeguzman** [comment]
> @patrickluisdeguzman we have many issues and this one felt minor so have it in the backlog. Any updates as to why it would not be a minor issue?

Hi @tmcconechy, the case has been escalated, and the customer is requesting regular updates.

**Comment by tmcconechy** [comment]
In progress here https://inforwiki.atlassian.net/browse/IDS-4386 for current sprint @patrickluisdeguzman

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4386
