### ISSUE TITLE
IdsText: Crashes Chrome when right clicking non-interactive text nodes

### ISSUE THREAD

**Issue by rob2d** [infor-design/enterprise-wc#260]
**Describe the bug**

Right clicking `<ids-text>` which is not surrounded by a button, or `draggable` handle, or anything else that does not contain cursor crashes Chrome web browser in MacOS (e.g. "Aw Snap" screen).

**To Reproduce**

1. go to http://localhost:4300
2. click on "Icon Only" portion of "Icon Only Buttons" subheader on the text/non whitespace chars themselves.
3. notice Chrome crashes and goes to an "Aw, Snap!" error screen.

**Expected behavior**
Regular browser context menu should appear, with no error/crash.

**Version**

latest/dev version of WC

**Screenshots**
![right-click-ids-text-error](https://user-images.githubusercontent.com/1799905/126017605-c4d5550e-21fa-471f-80e1-27e418e2e1cd.gif)

**Platform**
 - Infor Application/Team Name: IDS
 - Device: MacOS
 - OS Version: Catalina 10.15.7
 - Browser Name: Chrome (does not happen in Mozilla FF)
 - Browser Version: 91.0.4472.114 (Official Build) (x86_64)

**Additional context**

Currently, the only known way to prevent this issue via implementation so far is:

1. on `ids-text` or surrounding element, capture `contextmenu` and stop default menu behavior via `e.preventDefault()` (not ideal). Stopping via `e.stopPropagation()` to try to prevent bubbling still results in issues, however.
1. replace the `<slot></slot>` in `ids-text` in the `template()` method with `${this.innerHTML}`, and then add a `MutationObserver`. The most optimal property to limit mutation scope observer with  seems to be [`characterData`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserverInit/characterData) since it will observe any `innerHTML` changes directly which is relevant here.

Neither was done yet as we are trying to see if Chrome devs will take care of it vs add perf overhead to the text nodes as they are common. There is an issue posted on their tracker forum at:
https://bugs.chromium.org/p/chromium/issues/detail?id=1230127

**Comment by tmcconechy** [comment]
Could idea to have this logged.

**Comment by tmcconechy** [comment]
As per https://bugs.chromium.org/p/chromium/issues/detail?id=1230127 this is fixed in chrome 92. You can download the stable version from https://www.chromium.org/getting-involved/dev-channel
