### ISSUE TITLE
IdsDropdown: Does not work with ngValue

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-wc#2602]
**Describe the bug**
The following usage of `IdsDropdown` with `ngValue` does not work

```html
      <ids-dropdown
        #dropdownCar
        id="dropdown-car"
        label="Car Dropdown"
        [ngModel]="selectedOption()"
        (ngModelChange)="onSelectionChange($event)"
      >
        <ids-list-box>
          @for (car of carOptions; track car.id) {
            <ids-list-box-option [ngValue]="car">
              {{ car.name }}
            </ids-list-box-option>
          }
        </ids-list-box>
      </ids-dropdown>

```
`car` is an object

it should work though since using plain HTML `select/option` works
```html
      <select
        name="cars"
        id="cars"
        [ngModel]="selectedOption()"
        (ngModelChange)="onSelectionChange($event)"
      >
        @for (car of carOptions; track car.id) {
          <option [ngValue]="car">{{ car.name }}</option>
        }
      </select>

```

**To Reproduce**

1. Go to create a minimal Angular component implementation with the given template

**Expected behavior**
Selecting an object should trigger `ngModelChange`

**Version**

- ids-enterprise: 1.3.0

**Comment by tmcconechy** [comment]
@guoliang try checking https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc/src/app/components/ids-forms 

and https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc/src/app/components/ids-reactive-forms

I think you might need an import from angular?

**Comment by tmcconechy** [comment]
@clayinfor does this need a Form import? BTW

**Comment by guoliang** [comment]
@tmcconechy
Yes, `ngValue`, `ngModel` requires `FormsModule`, and I have imported it already.

I can give you the full example if required.

**Comment by tmcconechy** [comment]
Yes thats what i was trying to remember it was `FormsModule`. But still wondering why/if these work:

https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc/src/app/components/ids-forms

https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc/src/app/components/ids-reactive-forms

**Comment by guoliang** [comment]
There are no issue with `ngModel`, except the issue with that `ngModelChange` is always triggered at least once, which I reported here https://github.com/infor-design/enterprise-wc/issues/2442

The issue I found here is about `ngValue`, https://angular.dev/api/forms/NgSelectOption.

**Comment by tmcconechy** [comment]
I see. Why cant you use like this? Or does it work like that?

```
<ids-list-box-option id="ca" value="ca">California</ids-list-box-option>
```

```
@for (car of carOptions; track car.id) {
   <ids-list-box-option value="{{car.value}}" id="{{car.id}}" >
     {{ car.name }}
   </ids-list-box-option>
}
```

Maybe not sure how you can add several settings this way like id and value

**Comment by guoliang** [comment]
That would work only if `ngModel` is assigned with string as well.
I'm converting from enterprise-ng, where `ngValue` was working with `SohoDropdown` . So, it would be better if that option would work with `enterprise-wc` too I think.

**Comment by tmcconechy** [comment]
I know we cant bind any attributes to objects in web component setters/getters it cant serialize it. But we can see if anything is possible and look further

**Comment by guoliang** [comment]
I looked a bit, and seems like the following is required https://angular.dev/api/forms/ControlValueAccessor

```typescript
  carOptions = [
    { name: "volvo", id: 1 },
    { name: "saab", id: 2 },
    { name: "opel", id: 3 },
    { name: "audi", id: 4 },
  ];
```

**Comment by tmcconechy** [comment]
Ok that lines up with how we fixed the Form Accessor

**Comment by clayinfor** [comment]
hi @tmcconechy @guoliang , this has been resolved in the following PR: https://github.com/infor-design/enterprise-wc-examples/pull/95

**Comment by AndrewDeiakCZ** [comment]
Hey @tmcconechy , in which version was this fixed? Thanks!
