### ISSUE TITLE
IdsDropdown: select event does not work

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#2605]
**Describe the bug**
The select event on IdsDropdown is not being fired as documentation suggests: https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-dropdown#events
> Event listeners for input (trigger field) blur, change, focus, **select**, keydown, keypress, keyup, click, dbclick, beforetriggerclicked, triggerclicked events can be added to input component property:

**To Reproduce**
- Open: https://main.wc.design.infor.com/ids-dropdown/example.html
- Run this code on console:
```javascript
document.getElementById('dropdown-1').input.addEventListener('select', function() {
    console.log('select');
});
```
- Change the value of `Normal Dropdown with Dirty Tracker` Dropdown;
- Console does not return the message because select event does not happen

**Expected behavior**
Console returns "select"

**Version**
Latest

**Screenshots**
![Screen Shot 2024-07-18 at 4 21 02 PM](https://github.com/user-attachments/assets/0b6c58b1-d8b7-431a-99a3-0dd474a3c140)

**Comment by tmcconechy** [comment]
@fabiojpoli try this..

```
document.getElementById('dropdown-1').addEventListener('selected', function() {
    console.log('selected');
});
```

**Comment by tmcconechy** [comment]
That should fix....

**Comment by fabiojpoli** [comment]
Adding listener to dropdown directly not for input works for me, please update the documentation accordingly where says to register event on input reference: https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-dropdown#events

**Comment by tmcconechy** [comment]
ok done
