### ISSUE TITLE
IdsDatepicker: Allows invalid input when manually edited

### ISSUE THREAD

**Issue by ashachodavarapu** [infor-design/enterprise-wc#2607]
**Describe the bug**
The IDS date picker is allowing incorrect dates when manually edited. It accepts the invalid dates that are entered manually.

**Steps to reproduce the behavior:**
1. Open https://main.wc.design.infor.com/ids-date-picker/range.html
2. When you try to select any date and click "Apply," then attempt to edit the date with incorrect input, it accepts the input instead of rejecting it. (Please refer to the snippet below.)

**Expected behavior**
Date picker behavior should be that invalid dates are not allowed when manually entered.

**Version**
- ids-enterprise: 1.3.0

**Screenshots**
![image](https://github.com/user-attachments/assets/a3929909-5225-4375-a178-445e9c9e0d48)

**Comment by tmcconechy** [comment]
@ashachodavarapu please try to use validation for this. This will be hard to add to the mask. So validating invalid typing will be also required and you can do this now.

We can try to add an example but you can do it. Marked as 5 (hardest possible enhancement) to make it work with mask

**Comment by ashachodavarapu** [comment]
Okay! @tmcconechy , Please provide me the example

**Comment by tmcconechy** [comment]
@ashachodavarapu please review the "validation" examples in ids-input

https://main.wc.design.infor.com/ids-input/
https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-input/demos

This should work same on any "input" component

**Comment by ashachodavarapu** [comment]
@tmcconechy 
I tried giving below code, if I gave valid input also it's showing invalid date
` <ids-date-picker
                                id="rangepicker-no-value"
                                class="input-mask"
                                [attr.label]="'DATE_RANGE' | translate"
                                use-range="true"
                                format="M/d/yyyy"
                                placeholder="true"
                                mask="date"
                                validate="date"
                                size="lg"
                                [(ngModel)]="dateRangeFiled"
                                (change)="updateDateRangeField()"
                            ></ids-date-picker>`
                            
![image](https://github.com/user-attachments/assets/5164d2de-04f9-4b16-a45a-a1a4b98270a1)

**Comment by tmcconechy** [comment]
ok @ashachodavarapu will look at that too and make sure there is an example for that at least
