### ISSUE TITLE
IdsMultiselect: Selected items should be immediately added

### ISSUE THREAD

**Issue by ashachodavarapu** [infor-design/enterprise-wc#2609]
**Team**: ION Notification Center
In IDS multi select selected items are not added to the input field automatically when the user selects any item.
https://main.wc.design.infor.com/ids-multiselect/example.html
**Reproduction Steps:**
**For Selection**
- Select an item from the multi-select dropdown menu.
- Notice that the selected item does not automatically appear in the input field associated with the dropdown.
- Click outside the dropdown menu to confirm the selection.
- Verify that the selected item remains in the input field.

**For deselection:**
- Deselect an item from the dropdown menu.
- Confirm that the deselected item is removed from the input field.
**Expectation:**
the selected item should automatically appear in the input field associated with the dropdown

**Comment by tmcconechy** [comment]
Fixed on https://inforwiki.atlassian.net/browse/IDS-4457
