### ISSUE TITLE
IdsEditor: The first line of text does not change according to the settings in the tool bar

### ISSUE THREAD

**Issue by infor-mperalta** [infor-design/enterprise-wc#2610]
**Describe the bug**
For example, I added multiline text in the editor, then I highlighted all of the text, and change certain settings such as the "Heading", "Alignment", "Block Quote". As can be seen, changing such settings does not affect the first line of text.

**To Reproduce**

1. In the IDS website,/demo app go to IDS editor.
2. Add multiline text in the editor
3. Highlight all of the text in the editor
4. change the settings such as heading, alignment etc
5. observe that only the 2nd line of text and below are changing and following

**Expected behavior**
All of the text should be changing and following the settings in the toolbar if they are enabled by the user.

**Version**
latest version

**Screenshots**

https://github.com/user-attachments/assets/60f407d9-1faf-47fc-bcc2-d0d2d11927c4

**Comment by inforandy** [comment]
valid, will schedule this one to be fixed

**Comment by ericangeles** [comment]
It looks like this issue has already been resolved.

**Comment by tmcconechy** [comment]
@ericangeles yes agreed. I can no long reproduce (4.99)
