### ISSUE TITLE
IdsMenuButton: Sizing issues in NG 17 (and 18)

### ISSUE THREAD

**Issue by gustavpollak** [infor-design/enterprise-wc#2627]
**Describe the bug**
When trying to use the ids-menu button it gets resized and super cramped up. This is without setting any other sizes or forcing it to adjust to a parent etc.

**To Reproduce**

Create a simple ids-menu-button. 

View the differences of the rendered button

Pure JS: https://stackblitz.com/edit/ids-enterprise-wc-130-3umqd9?file=index.html
Angular 17: https://stackblitz.com/edit/stackblitz-starters-1ulqmq?file=src%2Fmain.ts

**Expected behavior**
The button is expected to not be squished by default.

**Version**
- enterprise-wc: 1.3.0

**Screenshots**

![image](https://github.com/user-attachments/assets/3f51f00f-cd60-4255-a5c4-1597e1034330)

**Platform**
 - Infor Application/Team Name: Infor OS Portal v2
 - Device: PC
 - OS Version: W11
 - Browser Name: Chrome
 - Browser Version: Version 126.0.6478.183 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
@gustavpollak 

I added the example to https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc/src/app/components/ids-button but could not reproduce the issue there.

Seems to not be removing the `ids-icon-button` class. So for 1.4.0 i added another refresh for this. After connected call back. Might work lets see when 1.4.0 is released?

Is there any special flags running here i could use on our NG project to reproduce?

**Comment by gustavpollak** [comment]
@tmcconechy 
"Is there any special flags running here i could use on our NG project to reproduce?"

I don't think so, I used a barebones angular 17 project for the stackblitz where it was reproduced. Yeah I'll check again when 1.4.0 is realeased, thanks 😊👍🏽
