### ISSUE TITLE
IdsFilterField: Field field doesn't honor field-height attribute

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise-wc#2628]
**Describe the bug**
IdsFieldField doesn't honor the field-height="xs" attribute.
![image](https://github.com/user-attachments/assets/c0b63a17-4064-4cf7-8f03-b2b7b0afbe78)

**To Reproduce**

1. Go to [field field demo](https://main.wc.design.infor.com/ids-filter-field/example.html)
2. Open the browser debug tools, 
3. In the DOM, modify the html for a ids-filter-field to include field-height="xs"
4. See that the field's height doesn't reduce.

**Expected behavior**
IdsFilterField should match the field-height behavior of other fields (dropdown and input for example).

**Version**

- ids-enterprise: 1.3.0

**Platform**
 - Infor Application/Team Name: Infor Landmark Web

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4214
