### ISSUE TITLE
IdsEditor: Hard coded id on internal element

### ISSUE THREAD

**Issue by fabiojpoli** [infor-design/enterprise-wc#2630]
**Describe the bug**
IDS Editor has hard coded `editor-container` which can cause many issues where this component is used. Duplicated ids can bring many issues on any application as my understand. For instance, on mongoose using Ext JS framework, the framework is throwing an error because of duplicated ID when I try to destroy or manipulate the element or any element related to that.

**To Reproduce**

1. Implement a page with two editors:
```html
<ids-editor id="editor-2"></ids-editor>
<ids-editor id="editor-2"></ids-editor>
```

**Expected behavior**
IDs, mainly internal must be generated automatically.

**Version**
Latest

**Screenshots**
![Screen Shot 2024-07-24 at 12 22 21 PM](https://github.com/user-attachments/assets/b9fec127-1091-4450-90d9-7f97dc17f0fd)

![Screen Shot 2024-07-24 at 12 23 52 PM](https://github.com/user-attachments/assets/430ac6d3-0057-4853-8855-9abe5f097d0e)

**Comment by tmcconechy** [comment]
Yeah since that ID is not in the shadowRoot thats not OK. If the ID was in the shadowRoot it would be ok because the shadowRoot is like a document.

So i agree here. Have to figure out something

**Comment by tmcconechy** [comment]
@jdilag90 i stole this one as i saw the fix working on another editor issue
