### ISSUE TITLE
IdsText: Text Clamping Failure with Spaceless Characters

### ISSUE THREAD

**Issue by shalini-patro12** [infor-design/enterprise-wc#2633]
**Reproduction Steps:-**

1 . open enterprise-wc project .
2. inside components folder open ids-text and inside ids-text open line-clamp.html.
3. inside line clamp.html replace the existing content with below content 
    `      <ids-layout-grid-cell>
        <ids-text>Line Clamp (2)</ids-text>
        <ids-text font-size="20" line-clamp="2" id="example-story">
          ghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
        </ids-text>
      </ids-layout-grid-cell>
      `
4. serve the project locally  and check the ui of line-clamp.html , you will see the line is not getting clamped.
**Below I am attaching the snippet of the issue created in web component **
![image](https://github.com/user-attachments/assets/10d03df9-17ea-4c2b-a394-a8403a8cb316)

**Comment by tmcconechy** [comment]
Im doubting if this is fixable since it works on splitting words? How reasonable of a test case is this? We can check but thinking about how to prioritize.

**Comment by tmcconechy** [comment]
Fixed as per https://oxford.awsdev.infor.com/infor-design/enterprise-wc/-/merge_requests/35#note_5486794
