### ISSUE TITLE
IdsTextArea: Text overlaps with the clear icon - BETA 1.4

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise-wc#2646]
**Describe the bug**
The text inside in the textarea overlaps with the clear icon.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-textarea/example.html
2. Populate **Clearable** with a lot of text
3. Hover on the clear (x) icon
4. See issue

**Expected behavior**
Text doesn't overlap with the clear icon

**Version**

- ids-enterprise-wc: 1.3

**Screenshots**
![image](https://github.com/user-attachments/assets/b5ca1986-ebe6-4209-a51e-e4dcc177dab5)

![image](https://github.com/user-attachments/assets/4900a0ea-8c63-4a07-a13c-96d4d67fbc06)

**Comment by tmcconechy** [comment]
Maybe we can add more padding to the right side for a fix

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4213
