### ISSUE TITLE
IdsCheckboxes: Checkbox layout in the small viewport is off - BETA 1.4

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#2648]
**Describe the bug**
Checkbox layout in the small viewport is off.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-checkbox/example.html on mobile (iPhone 15 Pro Max, Samsung Galaxy S22)
2. See error

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/user-attachments/assets/6350b3a3-b463-415e-bfcf-723b8832453c)

![image](https://github.com/user-attachments/assets/58dc94eb-e5e0-4ecb-a05c-42e18384ada3)

**Platform**
 - BrowserStack (iPhone 15 Pro Max, Samsung Galaxy S22)

**Additional context**

**Comment by tmcconechy** [comment]
Just need to adjust the layout-grid settings for mobile.
