### ISSUE TITLE
IdsEditor: labelHidden vs labelState document and removed

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise-wc#2649]
**Describe the bug**

We need to update the documentation of IdsEditor. `labelHidden` is no longer working and it should be removed.

**To Reproduce**

1. Go to https://design.infor.com/components/components/editor-rich-text/web-components/
2. `labelHidden` should be removed

**Expected behavior**
Update the doc site.

**Additional context**
It's in the IDS Teams Channel https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1722240384228?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1722240384228&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1722240384228

**Comment by tmcconechy** [comment]
Can do with https://github.com/infor-design/enterprise-wc/issues/2635
