### ISSUE TITLE
IdsEditor: Modals are not working on mobile - BETA 1.4

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise-wc#2650]
**Describe the bug**
Modals are not working on mobile.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-editor/example.html
2. Click on ellipses (more button)
3. Click on `Insert Hyperlink` or `Insert Image`
4. Click `Save` or `Cancel` button
5. See error

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

https://github.com/user-attachments/assets/0687f8ce-e639-4870-9532-27bd95d6ae30

**Platform**
 - BrowserStack (iPhone 15 Pro Max)

**Additional context**

**Comment by n-ace-ancog** [comment]
I think this is the same case as #2549. For mobile/smaller viewport, this is expected.

**Comment by tmcconechy** [comment]
Im thinking of fixing this one as the modals dont close on desktop...  It is correct @n-ace-ancog that it goes full screen but not being able to close them is an issue
