### ISSUE TITLE
IdsTabs: Show which tab is active in the tabs when a tab is clicked from the overflow popup menu

### ISSUE THREAD

**Issue by mrtipsytony** [infor-design/enterprise-wc#2658]
**Is your feature request related to a problem or use case? Please describe.**
There is a scenario in https://design.infor.com/components/components/tabs-module/enterprise/ where when a user clicks on a tab menu item in overflow popup, the whole tab container scrolls itself to where the active tab is for better user visibility. This is not available in ids-enterprise-wc at the moment. 

Here's what we currently have so far in WC samples and it does not show you the active tab once overflow popup is closed.
![image](https://github.com/user-attachments/assets/ef72b3ef-32cf-42dd-90d9-b7cc3085f819)
See it here: https://main.wc.design.infor.com/ids-tabs/module.html

While in Enterprise, it shows the user the active tab
![image](https://github.com/user-attachments/assets/a20bacf8-4ceb-44e3-ad72-6cb33e9e7640)

**Describe the solution you'd like**
Make the scenario from enterprise library available in web components too. 

**Describe alternatives you've considered**

**Additional context**
Checked the other WC samples but it does not support the enterprise scenario too. 
https://main.wc.design.infor.com/ids-tabs/overflow.html

**Comment by tmcconechy** [comment]
Closed as per https://inforwiki.atlassian.net/browse/IDS-4382
