### ISSUE TITLE
IdsIcon: circle-filled icon does not change colors

### ISSUE THREAD

**Issue by kamilbauer** [infor-design/enterprise-wc#2664]
**Describe the bug**
Icon circle-filled has hardcoded color
![image](https://github.com/user-attachments/assets/40ea6e89-832e-4a44-8766-2d3a528186f3)
![image](https://github.com/user-attachments/assets/924dce15-5815-4a3c-92b9-8e18d4d79fc1)

**To Reproduce**
Create ids-icon with icon _circle-filled_ and set a color
```
<ids-icon
        icon="circle-filled"
        [color]="button.backgroundColor"></ids-icon>
```

**Expected behavior**
Setting color on the icon should change the color.
![image](https://github.com/user-attachments/assets/c3813f5c-e2b1-491c-801f-2fcaa8f9b2f2)
![image](https://github.com/user-attachments/assets/bf3bb6c8-0700-473f-9b16-0eee755d47cb)

**Version**
1.4.0

**Platform**

Infor Application/Team Name: Ids Web Components
Device: PC
OS Version: Windows 11
Browser Name: Chrome
Browser Version: 126.0.6478.128

**Additional context**
On other icons, the color is set correctly.
Example: confirm-filled has the property fill set to "currentColor"
![image](https://github.com/user-attachments/assets/d30ae277-5e56-46f2-8342-e78e2f513a41)
![image](https://github.com/user-attachments/assets/f5a27ed3-f468-4c8e-9c6b-bda6a47562b7)

This should be a simple change In SVG path for the circle-filled icon from hardcoded value to currentColor. (by looking at custom icons, probably somewhere in a json file for the icons)

**Comment by tmcconechy** [comment]
Fixed as per https://oxford.awsdev.infor.com/infor-design/enterprise-wc/-/merge_requests/29
