### ISSUE TITLE
IdsDropdown: Does not render correctly inside a scroll container

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#2682]
**Describe the bug**
`<ids-dropdown>` content is not displayed correctly when inside an Enterprise modal (e.g `SohoModalDialogService`). The dropdown list expands the modal content rather than being displayed on top of it, like `<ids-modal>` and similar.

**UPDATE:** This may not be related to the modal at all. The issue can be reproduced when the dropdown is inside any scroll container. See https://github.com/infor-design/enterprise-wc/issues/2682#issuecomment-2272680008

**To Reproduce**

1. Clone https://github.com/anhallbe/enterprise-wc-examples
2. Install & start dev server
3. Go to http://localhost:4200/ids-dropdown/modal
4. Open Modal
5. Open the dropdown
6. Notice that the modal content expands and you have to scroll to see the dropdown list.

**Expected behavior**
The dropdown content should be displayed outside of the modal content area, similar to https://main.wc.design.infor.com/ids-dropdown/in-modal.html

**Version**

- ids-enterprise-wc: 1.4
- ids-enterprise-ng: 18.x

**Screenshots**
<img width="583" alt="image" src="https://github.com/user-attachments/assets/b3777da9-bd62-4e72-a583-bac5b1faf2c7">

https://private-user-images.githubusercontent.com/4991954/355401176-7a2f7ffd-077f-4358-a7c0-666f51fa80da.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTM5MTcsIm5iZiI6MTcyMjk1MzYxNywicGF0aCI6Ii80OTkxOTU0LzM1NTQwMTE3Ni03YTJmN2ZmZC0wNzdmLTQzNTgtYTdjMC02NjZmNTFmYTgwZGEubW92P1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDZUMTQxMzM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjkwZTc2ODEyNzcyMzVmNmI5YzNhMWFlZmNmNTMyZTU3NmFkNTM2Yjc3M2U5NDk1OTlmODE5NDI0NjhiOTRhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B3FDQAErnPxuXPD6rRe7BEUMF-22mTDgZclk695eBs8

**Platform**
 - Infor Application/Team Name: Portal

**Additional context**
Related: https://github.com/infor-design/enterprise-wc/issues/2473

**Comment by anhallbe** [comment]
Correction:
I don't think this is related to the legacy modal specifically, but rather any containing element that has  `overflow: auto`.

https://stackblitz.com/edit/stackblitz-starters-sbzcwz?file=index.html

https://github.com/user-attachments/assets/83e1feba-fa7d-4a82-9ea9-eff0b1a0d241

**Comment by tmcconechy** [comment]
@anhallbe ok... will take a look. I thought it may be due to the css transforms on the old modal. Since it does work here in an overflow https://main.wc.design.infor.com/ids-dropdown/in-modal.html

**Comment by anhallbe** [comment]
One difference is that in the "in-modal" example, the `<ids-dropdown-list>` gets `position-style="fixed"`. Maybe that's it?

Adding that attribute through the browser dev tools appear to solve it, at least at a first glance:

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/b07bd1a3-4ed4-4613-b3a1-7b505815c19f">

The `<ids-dropdown-list>` is internal so we can't really modify it from the outside, right?

Seems like it is added specifically when the dropdown is inside a modal: 

https://github.com/infor-design/enterprise-wc/blob/714da5d0866a75133f187b6e59ea2574380a6062/src/components/ids-dropdown/ids-dropdown.ts#L1351

**Comment by tmcconechy** [comment]
@anhallbe you can modify it on the child but i think its better if we do it internally maybe we just need a case for .modal (the old one) too. 

Thanks for looking into it i think you tracked it down

**Comment by tmcconechy** [comment]
@anhallbe could you do a PR and add that example to https://github.com/infor-design/enterprise-wc-examples ? Would like to have that one in the repo.
