### ISSUE TITLE
IdsCard: Mouse/focus states for selectable cards

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#2687]
**Describe the bug**
Selectable cards (`<ids-card selection="single">`) don't have any visible indicator for different states other than selected, such as :hover, :pressed, :active etc.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-card/single-selection.html
2. Hover and focus the cards
3. See issue

**Expected behavior**
Not sure. Something like the Actionable cards, perhaps?

**Version**

- ids-enterprise-wc: 1.4.1

**Screenshots**

https://github.com/user-attachments/assets/cb684d07-3f20-4c7c-9bd7-b9df53a14e6c

**Additional context**
https://inforwiki.atlassian.net/browse/SCRMPORTALV2-8570

**Comment by tmcconechy** [comment]
@anhallbe this is actually correct its the new states like on https://main.wc.design.infor.com/ids-stats/example.html where the hover state is very light and the selection is a blue border

Was changed here https://github.com/infor-design/enterprise-wc/pull/2012

So i dont think we want to change it back

**Comment by tmcconechy** [comment]
Working as expected
