### ISSUE TITLE
IdsTab: ids-tab-more overflow popup does not get updated when tab title is updated

### ISSUE THREAD

**Issue by rokusasu13** [infor-design/enterprise-wc#2693]
**Describe the bug**
I am using a web service to implement dynamic tabs. I noticed that the tab names from the overflow popup does not get updated when updating a tab title e.g. adding 0 to the tab title. It seems that there is a method to update the overflow popup because when I manually resize the tabs it gets updated. I added screenshots below for reference.

**To Reproduce**

1. Create an ids-tab similar to the one below

              <ids-tab *ngFor="let tab of tabs" dismissible value="{{ tab.id }}">
                {{ tab.title }}
              </ids-tab>
              <ids-tab-more overflow></ids-tab-more>

2. Add multiple tabs to trigger an overflow
3. Update the tab title of one of the overflow tabs (tab cannot be seen)
5. Click the "More" button to show the overflow popup
6. The overflow popup displays the old tab title
7. Resize the tabs to force a refresh
8. Click the "More" button to show the overflow popup
9. The overflow popup now displays the updated tab title

**Expected behavior**
The tab title should always be in sync with the overflow popup.

**Version**

- enterprise-wc 1.4.1

**Screenshots**
![image](https://github.com/user-attachments/assets/db41c552-a434-47db-a739-e8def6c796a0)
![image](https://github.com/user-attachments/assets/0bf4bc0d-ec15-4993-93f1-6b90325101b1)
![image](https://github.com/user-attachments/assets/1df8da3c-7e06-4baf-84a8-f1209761f84d)

**Platform**
 - OS Version: Windows 11 Enterprise
 - Browser Name: Chrome
 - Browser Version: Version 126.0.6478.127 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4239
