### ISSUE TITLE
Splitter: Unable to drag splitter after dragging the splitter in certain scenarios

### ISSUE THREAD

**Issue by rvaja-infor** [infor-design/enterprise-wc#2695]
**Describe the bug**
The splitter is no longer able to be dragged after it has been dragged to the minimum and then extended. From observation and playing around, it seems it begins preventing from dragging beyond the minimum.

**To Reproduce**

1. Go to https://stackblitz.com/edit/ids-enterprise-wc-140-yavpt5?file=index.html
2. Drag the left hand splitter to the minimum.
3. Drag the left hand splitter to the maximum. Notice how the splitter snaps back to the minimum and now can no longer be extended.

In the examples provided, the same can happen with the right hand splitter by extending to the maximum, and then going to the minimum. It will again snap back and be fixed at the minimum.

**Expected behavior**
Splitter should not end up in a state where it becomes fixed at the minimum and cannot be adjusted.

**Version**
- ids-enterprise-wc: 1.4.0

**Screenshots**
1. Initial
![image](https://github.com/user-attachments/assets/625318ca-a1a9-4697-9641-9b4dece7a516)
2. Drag to minimum
![image](https://github.com/user-attachments/assets/f3d87ceb-6c48-4525-bd6d-34f6bd1d3014)
3. Drag to maximum and snaps back to the minimum
![image](https://github.com/user-attachments/assets/c4438a37-64d9-415a-9621-8ac7f96d0d18)

**Platform**
 - Infor Application/Team Name: Infor SunSystems
 - Device: Windows Desktop
 - OS Version: Windows 11
 - Browser Name: Edge/Chrome
 - Browser Version: latest 64bit

**Comment by jdilag90** [comment]
@tmcconechy @n-ace-ancog I haven't been able to replicate the issue.
You can test here https://main.wc.design.infor.com/ids-splitter/example.html
Could have been fixed with recent splitter fixes?

**Comment by tmcconechy** [comment]
@jdilag90 if you can reproduce it in https://stackblitz.com/edit/ids-enterprise-wc-140-yavpt5?file=index.html and not main. Lets try to make a new stackblitz off the new 1.5.0 release im making and confirm.

Will be ready shortly

**Comment by jdilag90** [comment]
@tmcconechy @n-ace-ancog looks fixed with wc v1.5

https://stackblitz.com/edit/ids-enterprise-wc-150-yppwsd?file=index.html,package.json

1) Drag left splitter handle all the way to the left (min)
2) Drag left splitter handle all the way to the right (max)
3) There should be no "snapping resize"
