### ISSUE TITLE
IdsRadio: Not preselected using FormControl

### ISSUE THREAD

**Issue by AndrewDeiakCZ** [infor-design/enterprise-wc#2700]
**Describe the bug**
I am using angular form controls with radio buttons. The radio button is not preselecting if used in a typical angular way.

**To Reproduce**

https://stackblitz.com/edit/stackblitz-starters-mvagks?file=src%2Findex.html,angular.json,src%2Fmain.ts,package.json

![image](https://github.com/user-attachments/assets/eb258b1e-848c-4eee-b604-80ffb5210307)

**Expected behavior**
Radio button should be preselected using a typical angular way.

**Version**
- ids-enterprise: 1.4.0
- angular: 17

**Screenshots**
![image](https://github.com/user-attachments/assets/1efa8b29-9018-4bec-a2dc-9903c071751b)

**Comment by tmcconechy** [comment]
Initial impression: Do any of these examples show it? 

https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc/src/app/components/ids-reactive-forms/demos/example

https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc/src/app/components/ids-forms/demos

Preselected means? Checked?

**Comment by AndrewDeiakCZ** [comment]
yes, Preselected means Checked.

I checked now https://github.com/infor-design/enterprise-wc-examples/tree/main/angular-ids-wc/src/app/components/ids-forms/demos, but there you are using `ngModel`.  My original issue is to use `new FormControl()`;

I also created a sample here to have a default checked radio button, doesn't work - https://stackblitz.com/edit/stackblitz-starters-kwzy3l?file=src%2Findex.html,angular.json,src%2Fmain.ts,src%2Fglobal_styles.css
