### ISSUE TITLE
IdsMessage: Cuts the text inside of it

### ISSUE THREAD

**Issue by AndrewDeiakCZ** [infor-design/enterprise-wc#2702]
**Describe the bug**
I wanted to have any content inside of the ids-message modal. Currently, the issue is ids-message limiting the width of it:

![image](https://github.com/user-attachments/assets/a7b6ce41-3288-4c7b-976e-666657a7037f)

**To Reproduce**
https://stackblitz.com/edit/stackblitz-starters-qvyhkg?file=src%2Findex.html,angular.json,src%2Fmain.ts,src%2Fglobal_styles.css

**Expected behavior**
The modal contact size should depend on its content, the same as we have for the ids-modal.

**Version**
   "ids-enterprise-wc": "1.4.0"

**Screenshots**
![image](https://github.com/user-attachments/assets/17604c92-fda5-499d-973d-9aadad57a223)

![image](https://github.com/user-attachments/assets/3d656df3-25b5-41fc-af4f-149ada55c145)

**Comment by tmcconechy** [comment]
In the legacy repo we fixed this by adding a `maxWidth` setting and setting it to `fit-to-content`. So that would be my fix here if it works

**Comment by AndrewDeiakCZ** [comment]
yes, that should work. Thank you!

**Comment by tmcconechy** [comment]
Fixed as per https://oxford.awsdev.infor.com/infor-design/enterprise-wc/-/merge_requests/49#537ade10902ec3f76221a4a32b01db628e23d0f8
