### ISSUE TITLE
IdsDatagrid: how to implement data driven ui, rather than setting the data to datagridRef.current.data again?

### ISSUE THREAD

**Issue by hyzhang** [infor-design/enterprise-wc#2713]
We're trying to use IdsDatagrid, according to [examples](https://github.com/infor-design/enterprise-wc-examples/blob/main/react-ids-wc/src/examples/ids-data-grid/index.js) set datagridRef to ids-datagrid's `ref` property, and fetches data in useEffect and set it to `datagridRef.current.data`, here let's assume there's a state: `const [students, setStudents] = useState<IStudent[]>()`, and a confirm dialog, if user clicks Yes then fetch the students data, and I have to call `setStudents(fetchedData); // to trigger render` and `datagridRef.current.data = fetchedData` so the datagrid will be refreshed, is there any way to implement a "data driven UI change" style? For example, I only need to call `setStudents(fetchedData);`, the datagrid will be refreshed.

**Comment by tmcconechy** [comment]
@hyzhang not 100% sure how the react `ref` would but in the component code you just want to call the `data` setter to set/reset and refresh the data. In JS/TS in this would be..

```js
document.querySelector('#datagrid-id').data = [<array of objects data>];
```

There are some internal private properties you should not touch other than that

**Comment by tmcconechy** [comment]
@hyzhang did that solve your issue?
