### ISSUE TITLE
Module-Nav issue with dynamic child menu items

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise-wc#2722]
**Describe the bug**
Similar to issues [2517 ](https://github.com/infor-design/enterprise-wc/issues/2517) and [1881](https://github.com/infor-design/enterprise-wc/issues/1881) we're having an issue with adding or updating children of the menu. This previously worked for us in WC 1.2.x but stopped at WC 1.3. Our application has a requirement that the parent menu items are static and that the menu item children be dynamically updated on every expand of the parent. We have tried two ways to do this with WC:
1. Create the parent with a dummy child and then replace that dummy with proper children on expand. This does show the caret properly but when the parent is first expanded, the parent immediately collapses. Subsequent expands of that parent show correctly.
2. Create the parent with no children and add them at first expand. When we do this the caret does not appear but you can expand the parent.  

**To Reproduce**
Using the WC Angular demo:
1. Replace \src\app\components\ids-module-nav\demos\dynamic-content.compopnent.ts with the dynamic-content.compopnent.ts attached to this issue below.
[dynamic-content.component.ts.zip](https://github.com/user-attachments/files/16604864/dynamic-content.component.ts.zip)

2. Run the demo app and open the above mentioned demo.  
3. Click the caret on the "Change children" parent. The children of this item are **replaced** dynamically. Note it expands then immediately collapses.
4. Click the area where the caret should be on the 'Add children' item. The children of this item are **added** dynamically. Note it expands.

**Expected behavior**
In step 3 above, it should not immediately collapse.
In step 4 above, the caret should show.

**Version**
WC ^1.4.1

**Screenshots**

https://github.com/user-attachments/assets/15020bea-76f1-4b3f-a354-61409be8a1e4

**Platform**
 - Infor Application/Team Name: M3 GLT
 - OS Version: Win 11
 - Browser Name: Chrome
 - Browser Version: 127.0.6533.100

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4230
