### ISSUE TITLE
IdsPager: When using ids-pager in angular the disabled state of the buttons sometimes is not applied.

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise-wc#2738]
**Describe the bug**
When using ids-pager in angular the disabled state of the buttons sometimes is not applied. This definitely happens on initial load. The are a couple other scenarios where I've seen this and will update this branch if I can dup them.

**To Reproduce**
1. In `enterprise-wc-examples` repo check out branch `pager-wrapper-example`
2. Open demo app and navigate to http://localhost:4200/ids-pager/wrapper
3. Notice the first and next pager buttons are enabled. They should be disabled.

Another example of the issue
1. click the last pager button and notice the first and previous pager buttons are disabled.
2. select a different page size and notice the first and previous pager buttons are now enabled.

**Expected behavior**
first and previous pager buttons set to disabled should be disabled.

**Version**

- ids-enterprise-wc: 1.4.1

**Screenshots**

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: Latest

**Additional context**
Seems to be related to ids-pager-button calling connectedCallback when an attribute changes. 
https://github.com/infor-design/enterprise-wc/blob/babaacb14482a39ee51bae4e7c1187e208291c22/src/components/ids-pager/ids-pager-button.ts#L87

That function seems to set the pager-button disabled state to the pagers disabled state.
https://github.com/infor-design/enterprise-wc/blob/babaacb14482a39ee51bae4e7c1187e208291c22/src/components/ids-pager/ids-pager-button.ts#L113

**Comment by andrivarhanov** [comment]
@tmcconechy sure

**Comment by pwpatton** [comment]
I was able to test this and it seems to be working, thanks @andrivarhanov
