### ISSUE TITLE
IdsEventsMixin: Handling Native Events better for React

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#274]
**Describe the bug**
The IdsMixin code is firing custom events all the time even if its a native event https://github.com/infor-design/enterprise-wc/blob/main/src/mixins/ids-events-mixin/ids-events-mixin.ts#L173

This causes react users to have to use the useEffect pattern to listen to these events in a less convenient way:

```
useEffect(() => {
    if (textRef && textRef.current) {
        textRef.current.addEventListener('change', onChange);

        return () => {
            textRef.current.removeEventListener('change', onChange);
        }
    }
});
```

instead of the native react way of 

```
<ids-input
    id={id}
    onChange={onChange}
```

While this is a known pattern. We also need this to work ok in svelte, ng, vue ect..

**Ideas**
- check if the event is native and fire the native event instead https://stackoverflow.com/questions/30297555/how-to-know-in-javascript-if-an-event-name-is-custom
- dont use events at all? (probably not great)
- wrap the custom events for react somehow
- use normal events but pass the data differently

**Research**
- is there a way to wrap the custom events for react? or cleaner pattern?

**Additional context**
Email

**Comment by tmcconechy** [comment]
See https://github.com/lit/lit/issues/2026 for more info

**Comment by clayinfor** [comment]
See this duplicate issue for useful screenshots:  https://github.com/infor-design/enterprise-wc/issues/849

**Comment by tmcconechy** [comment]
https://blog.logrocket.com/using-custom-events-react/
