### ISSUE TITLE
IdsMenuButton: All menus are initially open

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-wc#2747]
**Describe the bug**
When one or more `<ids-menu-button>` are on a page, they are (sometimes) opened automatically. This happens in 1.4.2, but not in 1.4.1, so it could be caused by https://github.com/infor-design/enterprise-wc/pull/2674

**To Reproduce**

Not quite sure how to reproduce this outside our app yet. But the Angular router might be involved since this only happens when:

1. Go to a page where the buttons are
2. Navigate away from it
3. Navigate back to it
4. The menus are now open

I don't think it's an issue specifically with the Angular router, but rather something with the lifecycle of the menu button when it is (re)attached to the DOM.

UPDATE: Here's a Stackblitz where the issue can be reproduced: https://stackblitz.com/edit/stackblitz-starters-mhnb1p?file=src%2Fmain.ts

**Version**

- ids-enterprise-wc: 1.4.2

This issue is NOT in 1.4.1

**Screenshots**

https://github.com/user-attachments/assets/a2651e06-f56d-4596-9559-7224b04eecd7

**Platform**
 - Infor Application/Team Name: Portal

**Comment by tmcconechy** [comment]
@anhallbe we didnt do much on that fix but maybe... 

Because we have https://main.wc.design.infor.com/ids-menu/example.html and it shows open we need to add 

```
:host {
  display: none;
}
```

To ids-popup-menu and make sure it all works still on https://main.wc.design.infor.com/ids-menu-button/example.html

Can you try @andrivarhanov ? I didnt check the ng example

**Comment by andrivarhanov** [comment]
@tmcconechy sure, I will try, currently trying to reproduce it in our Angular examples with the same scenario

**Comment by andrivarhanov** [comment]
Example of the layout where the menu is initially opened

```
@let idPrefix = "something-dynamic";
@let items = ["item-one", "item-two", "item-three"];

<ids-toolbar>
  <ids-toolbar-section type="buttonset"
                align="end">
    <ids-menu-button [id]="idPrefix + 'the-button-id'"
                icon="sort-down"
                appearance="tertiary"
                dropdown-icon
                [menu]="idPrefix + 'the-menu-id'">
      <span>Menu Button</span>
    </ids-menu-button>
    <ids-popup-menu [id]="idPrefix + 'the-menu-id'"
               [target]="idPrefix + 'the-button-id'"
               trigger-type="click">
      <ids-menu-group>
        @for (item of items; track $index) {
        <ids-menu-item [value]="item">{{ item }}</ids-menu-item>
        }
      </ids-menu-group>
    </ids-popup-menu>
  </ids-toolbar-section>
  <ids-toolbar-more-actions overflow></ids-toolbar-more-actions>
</ids-toolbar> 
```

Example of the layout that works fine

```
@let items = ["item-one", "item-two", "item-three"];

<ids-toolbar>
 <ids-toolbar-section type="buttonset"
        align="end">
  <ids-menu-button id="static-button-id"
         icon="sort-down"
         appearance="tertiary"
         dropdown-icon
         menu="static-menu-id">
   <span>Menu Button</span>
  </ids-menu-button>
  <ids-popup-menu id="static-menu-id"
        target="static-button-id"
        trigger-type="click">
   <ids-menu-group>
    @for (item of items; track $index) {
    <ids-menu-item [value]="item">{{ item }}</ids-menu-item>
    }
   </ids-menu-group>
  </ids-popup-menu>
 </ids-toolbar-section>
 <ids-toolbar-more-actions overflow></ids-toolbar-more-actions>
</ids-toolbar>
```

The issue seems like related to popup menu's `target` attribute when it's dynamic (binding)

Some notes:
- target is not required for popup menu when using with menu button since `menu` attribute handles the menu from button's side
- target should be a valid CSS selector, like `#static-button-id`

**Comment by andrivarhanov** [comment]
Example where the menu is initially opened:

```
@let idPrefix = "something-dynamic";
@let items = ["item-one", "item-two", "item-three"];

<ids-toolbar>
  <ids-toolbar-section type="buttonset"
                align="end">
    <ids-menu-button [id]="idPrefix + 'the-button-id'"
                icon="sort-down"
                appearance="tertiary"
                dropdown-icon
                [menu]="idPrefix + 'the-menu-id'">
      <span>Menu Button</span>
    </ids-menu-button>
    <ids-popup-menu [id]="idPrefix + 'the-menu-id'"
               [target]="idPrefix + 'the-button-id'"
               trigger-type="click">
      <ids-menu-group>
        @for (item of items; track $index) {
        <ids-menu-item [value]="item">{{ item }}</ids-menu-item>
        }
      </ids-menu-group>
    </ids-popup-menu>
  </ids-toolbar-section>
  <ids-toolbar-more-actions overflow></ids-toolbar-more-actions>
</ids-toolbar> 
```

The example that works fine:

```
@let items = ["item-one", "item-two", "item-three"];

<ids-toolbar>
 <ids-toolbar-section type="buttonset"
        align="end">
  <ids-menu-button id="static-button-id"
         icon="sort-down"
         appearance="tertiary"
         dropdown-icon
         menu="static-menu-id">
   <span>Menu Button</span>
  </ids-menu-button>
  <ids-popup-menu id="static-menu-id"
        target="static-button-id"
        trigger-type="click">
   <ids-menu-group>
    @for (item of items; track $index) {
    <ids-menu-item [value]="item">{{ item }}</ids-menu-item>
    }
   </ids-menu-group>
  </ids-popup-menu>
 </ids-toolbar-section>
 <ids-toolbar-more-actions overflow></ids-toolbar-more-actions>
</ids-toolbar>
```

The issue seems like related to the `target` attribute being dynamic (binding)

Some notes:
- target is not required when used with menu button since `menu` attribute handles popup on the button's side
- target should be a valid CSS selector like `#static-button-id`

**Comment by anhallbe** [comment]
Update: I managed to reproduce the issue in this Stackblitz:

https://stackblitz.com/edit/stackblitz-starters-mhnb1p?file=src%2Fmain.ts

https://github.com/user-attachments/assets/954e30ad-1240-4865-bab6-ca82d14710ea


I also tried earlier versions, and the issue definitely first appears in 1.4.2.

**Comment by tmcconechy** [comment]
@andrivarhanov can you take a look then? this one is highest priority right now due to releases.

**Comment by tmcconechy** [comment]
@anhallbe im going to dig into this next week but wondering if https://github.com/infor-design/enterprise-wc/pull/2782 somehow fixes this. I can check next week but positing here for now

**Comment by anhallbe** [comment]
I tried building from the `2777-lookup-space` branch, and unfortunately the issue is still there :(
