### ISSUE TITLE
IdsSummaryField:  Add new web component

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#276]
**Is your feature request related to a problem or use case? Please describe.**

Add an ids-summary-form like the summary form section on https://main-enterprise.demo.design.infor.com/components/form/example-forms.html

The new name should be` IdsSummaryForm`. Will use a slot for extra flexibility.

**Phase 1 Features (MVP)**

- Themes / RTL
- Margin / Padding (like inputs and like before)
- Set the colors and font size unless overridden in the slot to the old values
- build the same example as 4.x (just the summary field part)

**Possible Internal Markup**
```js
  <ids-summary-field>
    <ids-text slot="label" color="red">Label</ids-text>
    <ids-text slot="data" color="red">Label</ids-text>
  </ids-summary-field>
```

Also could be...this but having the slots allows text overrides.
```
<ids-summary-field data="label" value="value"></ids-summary-field>
```

**Suggested Dependencies**
- ids-text

**Settings**
N/A

**Events**
N/A

**Other**
Pass the following checklist ordered in priority (some may be left for later) https://github.com/infor-design/enterprise-wc/blob/main/doc/CHECKLIST.md

**Comment by vivz753** [comment]
Am having issues setting the font-weight and colors to match the original example for the slotted `ids-text` data and label

What I'm trying to do:
- set `::slotted(.label)` **color** to **slate-80**
- set `::slotted(.label)` **margin-bottom** to **8px**
- set `::slotted(.data)` **color** to **black**
- set `::slotted(.data)` **font-weight** to **bold**

color cannot be modified through slotted `ids-text` unless

```html
<ids-summary-form>
  <ids-text slot="label" color="unset"></ids-text>
  <!-- Or -->
  <ids-text slot="label" color="asfsdlfkj"></ids-text>
</ids-summary-form>
```

Side note: wouldn't it be better if unset was already the default?

Upon further inspection of `ids-text.js`
```js
  set color(value) {
    if (value === 'unset') {
      this.setAttribute(attributes.COLOR, value);
      this.container.classList.add('ids-text-color-unset');
      return;
    }
    // I feel like this should also take in hex values #****** or ids-color-status-*
    if (typeof value === 'string') {
      this.setAttribute(attributes.COLOR, value);
      this.container.classList.remove('ids-text-color-unset');
      this.container.style.color = `var(--ids-color-palette-${value})`;
      return;
    }
    this.removeAttribute(attributes.COLOR);
    this.container.classList.remove('ids-text-color-unset');
  }
```
Side note: I think we should add in the ability to take hex values and ids-color-status-* colors--it would be  good to have consistent `set color()` strategy through the repo since that's how I designed mine for `ids-progress-chart`

Back to the main point, I still can't figure out how to make the `data` bold by default in `ids-summary-form`. Users would have to explicitly add it as an attribute in the slotted `ids-text` if they wanted it bold :\
```html
<ids-summary-form>
  <ids-text slot="data" font-weight="bold"></ids-text>
</ids-summary-form>
```

**Comment by tmcconechy** [comment]
For this line the idea was you would pass in only palllette colors not hex so we stick with the pallet:

https://github.com/infor-design/enterprise-wc/blob/main/src/ids-text/ids-text.js#L219

So you could do this...

```
<ids-text font-size="16" font-weight="bold" color="slate-80">Bold Text</ids-text>
```    

in order to do it "automatically" you could just have

```
<ids-summary-form>
  <ids-text slot="data" font-weight="bold"></ids-text>
</ids-summary-form>
```

Then do something like

```
this.querySelector('[slot="data"]').setAttribute('font-weight', 'bold');
this.querySelector('[slot="data"]').setAttribute('color', 'slate-80');
```

Or you could try to unset it and style it in the css sheet.

We didn't make it `unset` by default as the default for text is "something". If there was a way to have it work with unset but still style it that would be nice but couldnt find a way

**Comment by EdwardCoyle** [comment]
We may want to experiment with `unset` by default now... The changes in #278 moved the theme's base font color from being applied directly on IdsText to higher-level components like the IdsContainer, IdsHeader, etc, and should now be inherited by IdsText.  Having no base color should be possible now, so that bullet point might already be accomplished.

**Comment by vivz753** [comment]
@EdwardCoyle I just took a peek at your #278 and your line for setting the default `color: currentColor` in `ids-text.scss` solves it! Thanks. Based on that, it makes sense to make `unset` default now. Can probably be done here: https://github.com/infor-design/enterprise-wc/blob/8bf033bd48e334664d62672b2232f351bc9c0141/src/ids-text/ids-text.js#L88

@tmcconechy the querySelector examples worked, thanks! What's the best way to call these upon initialization? Is it best to set the default styles it in the constructor() or connectedCallback() or neither? Also, if the user does this 

```html
<ids-summary-form label="some title" data="200%">
  <ids-text slot="label">duplicate title</ids-text>
  <ids-text slot="data">duplicate data</ids-text>
</ids-summary-form>
```
do we want to remove the slots and prioritize the label/value attributes over whatever they insert in the children/slots?

**Comment by tmcconechy** [comment]
Yeah i think it would be fine to just do

```
<ids-summary-form label="some title" data="200%">
</ids-summary-form>
```

For this. I can't think what else they would want in the slot. 

As for the querySelector examples try them in connectedCallback() if that doesnt work add a rendered() which happens after.

Set set bold maybe just use `font-weight="bold"`

**Comment by vivz753** [comment]
Is it just me or does `bolder` and `bold` produce the same font-weight?

```html
  <ids-text font-weight="bolder">bolder</ids-text>
  <ids-text font-weight="bold">bold</ids-text>
```

<img width="285" alt="Screen Shot 2021-08-06 at 10 20 11 AM" src="https://user-images.githubusercontent.com/22609861/128548507-b3983b7b-5763-416c-adb3-7e1d905f6c97.png">

According to MDN documentation, font-weight will only have 2 distinct font-weights for some fonts

In this example my browser renders only 2 distinct font-weights
[https://codepen.io/impressivewebs/pen/EIncg](https://codepen.io/impressivewebs/pen/EIncg)

**Comment by tmcconechy** [comment]
I think we just need bold (600) one part of it is that the font only brings in these fonts https://github.com/infor-design/enterprise-wc/blob/main/app/layouts/head.html#L13 so we woudnt want to add an extra one as its an extra larger download and also we want to minimize the permuations of these all around so its either usually bold or not in our designs.

Can you test if bold / 600 works?

**Comment by vivz753** [comment]
@tmcconechy 

Regular `ids-text` **font-weight**
<img width="514" alt="Screen Shot 2021-08-06 at 1 18 53 PM" src="https://user-images.githubusercontent.com/22609861/128566830-63127817-fd3f-4900-8f64-8c8e091519c3.png">

Modified **font-weight** examples:
<img width="520" alt="Screen Shot 2021-08-06 at 1 18 45 PM" src="https://user-images.githubusercontent.com/22609861/128566824-8eff8dd1-e492-409a-a8ab-756a5951ced3.png">
<img width="531" alt="Screen Shot 2021-08-06 at 1 14 33 PM" src="https://user-images.githubusercontent.com/22609861/128566703-8c9de885-8cfb-475a-96ec-b3097a58a9f3.png">
<img width="526" alt="Screen Shot 2021-08-06 at 1 14 45 PM" src="https://user-images.githubusercontent.com/22609861/128566705-d23ae89c-b4d8-4b8a-86e9-08cfb8d8141e.png">
<img width="518" alt="Screen Shot 2021-08-06 at 1 14 53 PM" src="https://user-images.githubusercontent.com/22609861/128566706-2d60039f-2acb-4415-93a0-edc85d39e9cf.png">

`600`, `bold`, and `bolder` render the same for me

**Comment by tmcconechy** [comment]
I wouldn't worry about this just use `font-weight="bold"` that is correct and in the css we have used `fontWeight: 600`. 

Its because this font https://github.com/infor-design/enterprise-wc/blob/main/app/layouts/head.html#L13 only brings in 600. So it maps to the closest one (always 600).

But we dont need to use `bolder` at all its not part of any of our designs. If it was we would add to that font but we really dont need it.

**Comment by tmcconechy** [comment]
Hmm actually we have bolder in some places..
