### ISSUE TITLE
IdsTabs: More Button Issue

### ISSUE THREAD

**Issue by Kesavamanoj** [infor-design/enterprise-wc#2774]
It is reproducible on https://main.wc.design.infor.com/ids-tabs/overflow.html
 
Pre-Requiste:-
Make sure you have More tab with fewer tab options.
 
Steps to Reproduce:-
1.Select a tab from More options. (Let's say Tab 10)
2.Select a tab which is not from More options. (Lets say Tab 1)
3.Now try to switch to Tab 10 which is same as Step 1.
4.Observe that Tab 10 is not switched.

![image](https://github.com/user-attachments/assets/585d317a-3af1-4f8d-9dd8-9e08aa67ff2d)

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4537
