### ISSUE TITLE
IdsDatePicker: Selected Date range should be highlighted on clicking date picker in angular

### ISSUE THREAD

**Issue by ashachodavarapu** [infor-design/enterprise-wc#2796]
**Team: ION Notification Center**
**Issue**
The selected date range is not being highlighted (it is clearing).
**Observed behavior in WC main:**
- In the web component (wc) example, after selecting a date range and applying it, the initial value should be retained.
- When we click on the calendar icon of the date range component again, the date range popup should open with the previously selected values highlighted.
![image](https://github.com/user-attachments/assets/529d2779-d68b-4429-8ea0-5beaf0c52f16)
**WC angular examples:**
- In the Angular example, the issue occurs where the selected date range is missing when reopening the popup.
- When the date range popup is opened again, instead of showing the previously selected range, it defaults to today's date.
![image](https://github.com/user-attachments/assets/9bb2f316-398f-400e-a6a7-0cc8f3c75240)

**Steps to reproduce the behavior:**
1. Open the date range HTML example [here](https://main.wc.design.infor.com/ids-date-picker/range.html) in the Angular version.
2. Select any date range from the calendar and click "Apply."
3. Reopen the calendar and observe the issue: the previously selected date range is cleared, and only today's date is selected.
4. However, in the main web component (WC) example, the selected dates remain highlighted when reopening the calendar.

**Expected behavior**
1. After selecting a date range and clicking "Apply," the chosen range should be saved.
2.When reopening the date picker, the already selected date range should be highlighted, similar to how it works in the main web component (WC) example.
3. Currently, the issue is that upon reopening, the calendar shows only today's date instead of the previously selected range.

**Version**
- ids-enterprise: 1.4.2

**Screenshots**
expected result: 
![image](https://github.com/user-attachments/assets/457caf63-7554-4545-82a3-beea1ee6e478)

**Comment by tmcconechy** [comment]
https://inforwiki.atlassian.net/browse/IDS-4856

**Comment by tmcconechy** [comment]
Closed as per https://oxford.awsdev.infor.com/infor-design/enterprise-wc/-/merge_requests/23
