### ISSUE TITLE
IdsText: add the ability to use tooltip without overflow

### ISSUE THREAD

**Issue by infor-mperalta** [infor-design/enterprise-wc#2811]
**Is your feature request related to a problem or use case? Please describe.**
The IDS text component has the tooltip attribute but currently, it needs the overflow attribute for it to work/show the tooltip.

**Describe the solution you'd like**
The IDS Text component would work better if, regardless of having the overflow attribute activated, the tooltip attribute could still be used/shown

**Describe alternatives you've considered**
None

**Additional context**
![image](https://github.com/user-attachments/assets/5f0651f6-374f-488d-aa04-86173bd0881f)

**Comment by anhallbe** [comment]
How about this, as a workaround?

```html
<ids-text id="the-text">
  This text has a tooltip
</ids-text>
<ids-tooltip target="#the-text" placement="bottom">
  This is a tooltip for the text
</ids-tooltip>
```

**Comment by AAlviar** [comment]
https://inforwiki.atlassian.net/browse/IDS-4754

**Comment by tmcconechy** [comment]
Fixed on https://oxford.awsdev.infor.com/infor-design/enterprise-wc/-/merge_requests/47
