### ISSUE TITLE
ModuleNav: Extra margin in fields under columns with Navigation Module

### ISSUE THREAD

**Issue by charantejpola** [infor-design/enterprise-wc#2812]
**Describe the bug**
Have observed an issue with fields which are under columns div where an extra margin is being added.

```
.module-nav-container .columns .field {
    margin-inline-end: 20px;
}
```

**To Reproduce**

1. Create an soho-module-nav
2. Now create a layout in its container using columns
3. Now add fields class inside columns
4. We can see the extra margin being added to all fields

**Expected behavior**
The extra margin should not be added

**Version**

- ids-enterprise-ng : 18.2.1

**Screenshots**
![image](https://github.com/user-attachments/assets/af8a646a-6306-4413-a8e2-59c96da2d960)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
Please refer to the stackblitz:
[https://stackblitz.com/edit/ids-quick-start-1821-gqy2wp?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.css](url)

**Comment by tmcconechy** [comment]
https://inforwiki.atlassian.net/browse/IDS-4853

**Comment by tmcconechy** [comment]
Fixed on https://oxford.awsdev.infor.com/infor-design/enterprise/-/merge_requests/32/diffs#264fd6f67cedbf82c150d8cb8421b4051f62b8b3
