### ISSUE TITLE
IdsIcon - add new sizes, rename existing sizes

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#296]
**Is your feature request related to a problem or use case? Please describe.**
IdsIcon currently supports three sizes:
- `small` - 10px
- `medium` - 18px
- `large` - 24px

We've discovered the need to support a couple other sizes:
- IdsProgressChart displays a status icon inline with text that would look nicely-aligned if it were **14px** (between `small` and `large`) -- See #284
- IdsAppMenu has an optional Infor Logo displayed at its bottom-left that calls for a **34px-sized** icon (larger than `large`), if we keep this icon similar to the 4.x Application Menu. -- See #130

Some examples of these needed icons sizes are in the screenshots from 4.x below:

Progress Chart Icon | App Menu Icon
------------ | -------------
<img width="219" alt="Screen Shot 2021-08-05 at 11 12 49 AM" src="https://user-images.githubusercontent.com/3249601/128374690-9263fc26-ed68-404e-bbd7-bad1b1c52279.png"> | <img width="300" alt="Screen Shot 2021-08-05 at 11 13 16 AM" src="https://user-images.githubusercontent.com/3249601/128374691-dd6428a2-e93e-4be0-85bb-e4d2dd5f383f.png">

Unfortunately to add this "in-between" size breaks our naming convention for the sizes.  It may be wise for us to do this sooner than later if we need to support these icon sizes, as it requires changes to many example pages, and in some cases usage within other components.

**Describe the solution you'd like**

A rough naming convention change example could be:
- `extra-small` : 10px
- `small`: 14px
- `medium`: 18px (normal)
- `large`: 24px
- `extra-large`: 34px
- `logo-small`, `logo-large` has specific sizes (map)
- `empty-message` ??? (type? or size?)

**Describe alternatives you've considered**
We thought about calling the new 14px size `small-medium`, but we did try similar naming conventions in 4.x that proved to be confusing in the end.  

Alternatively, It might be better to come up with something more future-proof that may not need drastic changes -- potentially provide an API for custom icon sizes for specific situations?

**Comment by tmcconechy** [comment]
As a not I was trying to reduce the size variants to 3 but i think we are seeing this isnt going to work. So i think this is the best approach.

**Comment by tmcconechy** [comment]
Check is it was all covered on https://github.com/infor-design/enterprise-wc/pull/356
