### ISSUE TITLE
Webpack optimization for new demo app

### ISSUE THREAD

**Issue by danielortiz1982** [infor-design/enterprise-wc#301]
**Is your feature request related to a problem or use case? Please describe.**

This optimization will try to address the concerns listed below.
1. Bundle size
2. Speed
3. Duplicate code included in bundles
4. Better code splitting strategy 
5. Lazy loading 
6. Better manage shared dependencies 

**Resources**
- [x] 1. [Code Splitting](https://webpack.js.org/guides/code-splitting/)
- [x] 2. [Build Performance](https://webpack.js.org/guides/build-performance/)
- [x] 3. [Dependency Management](https://webpack.js.org/guides/dependency-management/)
- [ ] 4. [Tree Shaking](https://webpack.js.org/guides/tree-shaking/)
- [ ] 5. [Lazy Loading](https://webpack.js.org/guides/lazy-loading/)
- [x] 6. Loading the cultures correctly

**Describe the solution you'd like**
TBD...

**Describe alternatives you've considered**
TBD...

**Additional context**
After this is done we should look at:

a) that this can load in our examples (NG, React Ect)
b) if we can fix the loading of cultures which is currently broken:

```
zone.js:1063 Unhandled Promise rejection: Loading chunk src_components_ids-locale_cultures_en-messages_js failed.
(error: http://localhost:4200/src_components_ids-locale_cultures_en-messages_js.js) ; Zone: <root> ; Task: Promise.then ; Value: ChunkLoadError: Loading chunk src_components_ids-locale_cultures_en-messages_js failed.
(error: http://localhost:4200/src_components_ids-locale_cultures_en-messages_js.js)
```

**Comment by tmcconechy** [comment]
I also want to look at ESM https://webpack.js.org/guides/ecma-script-modules/ if its a solution for any of this.
Will sync up tomorrow.

This is probably going to be a joint PR while i do https://github.com/infor-design/enterprise-wc/issues/288
