### ISSUE TITLE
General: Add more react examples

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#315]
**Is your feature request related to a problem or use case? Please describe.**
Expand the react exampes over at https://github.com/infor-design/enterprise-wc-examples/tree/main/react-ids-wc to include more components

Think about react features that might want to be used with the component and try them. Ideally we don't need special wrappers or too much.

**Describe the solution you'd like**

Add a page for each component and a simple link on the first page to that page make it render and test features like:

- Provide binding to the model for values
- Catching and handling events emitted
- Setting and changing settings (color for example)
- Templating like loops or text values
- Test and Research common framework features (forms ect)
- Add basic sanity puppeteer tests like the https://github.com/infor-design/enterprise-wc has for some of these pages

**Concrete Steps**

- [ ] Add and fix and test the examples in https://github.com/infor-design/enterprise-wc-examples
- [ ] Add another project in a folder `react-typescript-ids-wc` with similar examples in TS
- [ ] PR to that repo with the examples
- [ ] Add any docs and notes to the README(s)

**Additional context**
https://github.com/infor-design/enterprise-wc/issues/177

**Comment by andriivarhanov** [comment]
@tmcconechy I've got an error loading locale translation files for components using ids-locale, did you get the same when you initialized react examples repo?

![Unhandled Rejection (ChunkLoadError) Loading chunk 6429 failed](https://user-images.githubusercontent.com/5204821/133610092-f204bf1b-b400-49cb-b048-7c78fcba2ef2.png)

**Comment by tmcconechy** [comment]
Yes i get the same thing. This might not have been working since we added locale. I guess the way that the cultures are shipped needs to be somehow changed. I tried on the latest and it shows some more info...

<img width="1011" alt="Screen Shot 2021-09-16 at 10 07 21 AM" src="https://user-images.githubusercontent.com/814283/133627005-b7ae986d-8889-4653-a50e-51de9664690e.png">

I guess the files need to be served from cultures folder? Im not 100% sure. Any ideas @danielortiz1982 ?

**Comment by danielortiz1982** [comment]
I have seen a similar errors on the Angular side, I am still unclear what the issue is however after doing some research I found it can possibly be more of a Babel runtime issue. I am still not sure tho.
https://github.com/babel/babel/issues/8462

**Comment by andriivarhanov** [comment]
@tmcconechy I've added the PR with notes on what issues I've found so far, these issues are highly likely similar to angular version or any other version where enterprise-wc is going to be used

**Comment by danielortiz1982** [comment]
@clayinfor please use a lazy loading pattern where possible. Thanks!
https://reactjs.org/docs/code-splitting.html

**Comment by tmcconechy** [comment]
Closing this for now. Whats left needs to be spec'd out.
