### ISSUE TITLE
Clearable button has 2 different colors

### ISSUE THREAD

**Issue by vivz753** [infor-design/enterprise-wc#376]
http://localhost:4300/ids-trigger-field
http://localhost:4300/ids-search-field

- focus styles

<img width="250" alt="image" src="https://user-images.githubusercontent.com/38439203/135632454-42c9f17f-346c-4c8d-a788-745303630fda.png">

**Comment by tmcconechy** [comment]
The focus state should be a white border? Is this a question? Or is it about fixing the focus state color?

**Comment by EdwardCoyle** [comment]
@vivz753 this might be solvable with an attribute `color-variant="alternate"` on the trigger buttons.  We may need some mechanism to automatically apply it when the IdsSearchField exists within an IdsHeader -- currently all buttons are expected to have the `color-variant` attribute applied manually when placed inside an IdsHeader.

**Comment by tmcconechy** [comment]
assigned to Jeff but waiting on his email to come through so assigning to me
