### ISSUE TITLE
IdsSortable: New Mixin

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#399]
**Is your feature request related to a problem or use case? Please describe.**

- [ ] Implement the ["Arrange"](https://github.com/infor-design/enterprise/blob/main/src/components/arrange/arrange.js) behavior from 4.x as `IdsSortable` (mixin?)
- [ ] Should extract drag/drop/sort code from Listbuilder (implemented in #392) into standalone functionality that can be applied to any component
- [ ] Need to do some R&D on how this works best in a WebComponent structure (Mixin vs Component vs other)

**Places that use it or will use it**
- [ ] Listview (listbuilder)

**Future Discussion*
- [ ] Tabs
- [ ] Datagrid
- [ ] Swaplist

**Comment by tmcconechy** [comment]
This is working on the listbuilder added so i think it should just be extracted to a mixin from the work in listbuilder.

**Comment by vivz753** [comment]
Here's my suggestion:

1. Move arrange/dragging functionality from ids-list-builder to ids-list-view 
2. Refactor ids-datagrid to inherit or use ids-list-view as a child-component--there is a repeating pattern of conditionally rendering virtualScroll code that is already handled in list-view + it will include the arrange functionality, killing 3 birds with one stone
3. Extract arrange/dragging functionality from ids-list-view into a mix-in (or component--haven't decided yet which would be better, but i'm leaning more towards component; could be something like <ids-drag-and-drop>) 
4. Have all components that need it import the mix-in/component

We should decide on a singular name--arrange/sortable/draggable/drag-and-drop. I vote drag-and-drop.

It could work like this

```html
<ids-list-view>
  <ids-drag-and-drop>
     ${listItems}
  <ids-drag-and-drop>
</ids-list-view>

```
The current functions for drag-and-drop work for dragging up & down on a y-axis; it would need to have a configuration for horizontal dragging for tabs--wouldn't be hard to implement, but would be another task. 

Can't really comment on swaplist. What is that component for and how does it differ? 

How doable do you think #2 is? @tmcconechy Would it be easy to get rid of the virtual-scroll code and just plop in the ids-list-view? Or would the majority of the code have to be re-written from scratch? 

After a quick glance at ids-tabs, I'm assuming it could work like this. @EdwardCoyle ? 

```html
<ids-tabs>
  <ids-drag-and-drop horizontal>
    <ids-tab></ids-tab>
    <ids-tab></ids-tab>
    <ids-tab></ids-tab>
  </ids-drag-and-drop>
<ids-tabs>
```

Here is a UML diagram to depict my thinking
![IMG_4614](https://user-images.githubusercontent.com/22609861/141039390-28c2a392-ba27-479a-9037-df9dac19ff40.jpg)


This article helped me build the drag & drop function if anyone's interested in how it works
https://htmldom.dev/drag-and-drop-element-in-a-list/

**Comment by tmcconechy** [comment]
1. No i dont think it belongs IN ids-list-view. I think it should be another subcomponent or mixin.
2. Definitely dont think we should do this... I dont think the list-view belongs in the table and code maybe through off the layout (table/accessibility ect). Maybe rather just leave datagrid along and start making list-view use a mixin or sub component for now?

I think it should be this:
<img width="358" alt="Screen Shot 2021-11-10 at 10 15 29 AM" src="https://user-images.githubusercontent.com/814283/141139794-d3a90b5e-5862-405e-9ee7-06da5c018330.png">

3. What about just keeping it as ids-draggable? Before it was ids-sortable? I think ids-drag-drop is maybe too overloaded as we might gave other drag drop situations. So can it just be an option in ids-draggable or a component like ids-sortable or ids-drag-sort ext.. Based on ids-draggable? Question is really where this needs to go. Maybe lets connect on this and go through it?

4. Yep but maybe start in list view

**Comment by vivz753** [comment]
That sounds good! I can definitely do that. Thanks for the diagram.

ids-draggable is an already existing component that allows objects to be dragged. I use it to wrap my list items. However, swapping nodes as they are being dragged and "previewing" the position that they will land in requires another set of functions.

how about ids-draggable-list? Technically all items inside must be of type ids-draggable, so that would be clear to readers 

<ids-draggable-list>
  <ids-draggable>
    <ids-tab>tabName1</ids-tab>
  </ids-draggable>
</ids-draggable-list>

**Comment by tmcconechy** [comment]
i like the name `<ids-draggable-list>` however there is a thing i thought of in that the hierarchy is important for accessibility. So.. i think this might need to be a mixin:

For example:

```
<ids-tabs role="tablist">
  <ids-tab role="tab"></ids-tab>
  <ids-tab role="tab"></ids-tab>
</ids-tabs>
```

So you cant really wrap each tab in a ids-draggable. 
```
<ids-tabs role="tablist">
  <ids-draggable><ids-tab role="tab"></ids-tab></ids-draggable> <-- broken....
  <ids-tab role="tab"></ids-tab>
</ids-tabs>
```

You could put something outside tho? So something like this..

```
<ids-tabs role="tablist" draggable-list="true">
  <ids-tab role="tab" draggable="true"></ids-tab>
  <ids-tab role="tab" draggable="true"></ids-tab>
</ids-tabs>
```
