### ISSUE TITLE
Search Field: Implement Collapsible Behavior

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#403]
**Is your feature request related to a problem or use case? Please describe.**
We need a collapsible setting for Search Fields that responds to breakpoints, in order to make IdsToolbar feature parable with 4.x

**Describe the solution you'd like**
- [ ] Add a new boolean setting `collapsed` to Search Field
  - toggled by CSS
  - ignored when the `collapsible` setting doesn't call for collapse being enabled
- [ ] Add a new enumerated setting `collapsible`:
  - `none` would be default
  - `responsive` for listening to a specific breakpoint
  - `always` to always be collapsible regardless of breakpoint
- [ ] Test specifically in IDS Toolbar and IDS Header, and ensure their corresponding styles are implemented as part of this issue
- [ ] Check all themes for this styling as well

**Describe alternatives you've considered**
We should talk about how the breakpoint response system works, and maybe pull it into a more general mixin (related to #348)

**Comment by Sovia** [comment]
Landmark will need this feature for our web component implementation. We just need the ability for the input field to expand and collapse on a toolbar, we don't use the categories dropdown.
