### ISSUE TITLE
General: Review component TODOs and add backlog issues

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#404]
**Describe the Issue**
Many 4.x Components now have a WebComponent foundation, but are not 100% feature parable.

**Describe the desired solution**
- [ ] Audit each WebComponent for existing features
- [ ] Document what still needs to be added in a "Phase 2" issue for each component in this backlog
- [ ] Convert any potential ideas from each component's `TODO.md` into issues for this backlog

**Comment by tmcconechy** [comment]
Thanks I'll gradually take a look at a few of these... Lets sync on it and maybe split it up?

**Comment by EdwardCoyle** [comment]
Not sure yet how we will document these for real, but just noting here for now:

- [Ids App Menu Highlighting](https://github.com/infor-design/enterprise-wc/blob/439-appmenu-filter/src/components/ids-app-menu/TODO.md#filtering) - Covered by #494

**Comment by tmcconechy** [comment]
All TODO's completed for what we know / found so far
