### ISSUE TITLE
VirtualScroll: Dynamic Height

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#414]
**Describe the bug**
The way the virtual scroll calculates height isn't very dynamic, It would be good that if the height of the list view changes (view css height 100 and resizing the page) then the virtual scroll height is auto calculated.

**To Reproduce**

1. Go to http://localhost:4300/ids-list-view/
2. Change the height of the card/listview so it is higher (or more dynamic)
3.  See error

**Comment by vivz753** [comment]
A couple things:

1. Supporting **dynamic/responsive height** for the virtual-scroll viewport according to screen size is a separate feature from supporting **dynamic/varying row heights list items** within virtual-scroll content
2. The PR for this will solve the former--do we need to support the ladder? 
3. ids-card `auto-height` attribute must be enabled for dynamic height to work--i.e. wrapping a virtual-scroll inside of a fixed card will require specifying a fixed height of virtual-scroll.

- The example in http://localhost:4300/ids-list-view now adjusts to page height. However, `auto-height` removes the card-header FYI. This seems to be intended based on the css.

4. ids-datagrid by default allows a dynamic/responsive height. No modification needed and no need to set height for virtual-scroll (see http://localhost:4300/ids-virtual-scroll and http://localhost:4300/ids-data-grid <-- now fills up the height of the screen and adds white space on the bottom when viewport is larger than height of contents)

**Comment by tmcconechy** [comment]
1. I think this should be fine for now until we uncover other scenarios... I sort of meant them interchangably as the same thing.
2. Sounds good
3. I think thats acceptable as otherwise it will be fixed size. But removing the card header doesn't seem correct.
4. Is this shown on the PR? As i think i need to look there?
