### ISSUE TITLE
VirtualScroll: Arrow Keys

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#415]
**Describe the bug**

The arrow keys don't work well with virtual scroll.

**To Reproduce**
1. Go to http://localhost:4300/ids-list-view
2. Tab into the list
3. Down arrow continuously until it "scrolls" and notice the arrow key functionality breaks and loses focus

**Comment by vivz753** [comment]
The problem with virtual-scroll is that it completely replaces the innerHTML on render which happens each time the user scrolls--replacing the entire list of elements, losing the drag/keyboard event listeners AND the focus/tabindex=0 for the focused item. Virtual scroll needs a way of keeping track of which element in the data array has focus/tabindex=0. In my PR I solved this with a solution which saves the focused item's index number as a variable in ids-list-view.

**Comment by vivz753** [comment]
This brings up another issue, where in list-builder, any modified/moved items, or items that were added/deleted are completely forgotten about once user scrolls --> virtual-scroll re-renders the original data list. Opening Issue #442 for updating data each time there is a modification done with the list-builder toolbar--also need to scroll to index of selected item if it's out of range and modified using Enter key, or any of the buttons on list-builder toolbar.

**Comment by tmcconechy** [comment]
This works now https://main.wc.design.infor.com/ids-data-grid/virtual-scroll.html
