### ISSUE TITLE
Chore: Add auto height and fit options to several components

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#419]
**Describe the Ask**

For several key components the heights can either be a default, fit to whats inside it or expand down to the bottom of the page. The rules are as follows:

Virtual Scroll -> Dynamic by default and can pick up fixed height
Card -> 360px fixed by default - but set to auto-fit or auto-height
List View -> auto-fit by default and nothing else right now (so really card or page of the parent)
Datagrid -> Number of rows or auto-fit (future option)

**Expected behavior**
Add auto-fit and auto-height to the above components:

Virtual Scroll -> Just dynamic to what its in
Card -> Fixed default with both auto-height and auto-fit. Also for the example remove the code that is hiding the header and take the header out of the example to make it work the same way.. So the header can be optional.
List View  -> Auto-fit only
Datagrid -> Fixed default with both auto-fit added

**Other Rejected Ideas**
Use a different set of options
```
height="auto" -> auto-fit
height="100vh" -> fit down? but from screen
height="100%" ->  fit down? but from parent
height="400px" -> fixed??
```

Other rejected name ideas.
```
autogrow = auto-height
full-height
content-fit
size-to-parent
fit-parent
fit-content
size-parent
size-content?
```

**Comment by vivz753** [comment]
Card works as described, but I found a bug. `ids-card` provides header padding even if there is no header, pushing the contents down. IMO, it should only provide padding if there is a heading. Or the padding can be removed entirely and just let the user add in their own padding. (out of scope)

ids-list-view adjusts to parent container by default now using 100% height, and passes that down to virtual-scroll. 

WIP: ids-data-grid now has auto-fit attribute for making the container responsive to screen size

**Comment by tmcconechy** [comment]
Yeah i noticed that too. I think maybe what you can do is just show two examples on http://localhost:4300/ids-card/auto-size.html one with a header AND a title AND contents to fit and one without a header and just contents to fit (as it was before).

If they use the header they are going to have a title so it probably doesn't matter that there is padding there and shows it works it works in both cases.
