### ISSUE TITLE
AppMenu: Add filtering and filter options

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#439]
**Is your feature request related to a problem or use case? Please describe.**
Add a search option to the new app menu https://main.wc.design.infor.com/ids-app-menu/. And add other settings in the process.

**Describe the solution you'd like**

- [x] Add filterable setting that adds an input to search like https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html
- [ ] Add options to showChildren and Highlight as well see 

**Describe alternatives you've considered**
NA

**Additional context**
https://github.com/infor-design/enterprise/issues/5882

**Comment by EdwardCoyle** [comment]
Note:  Punting on the "highlight" portion of this issue.  I raised #494 for that one considering we might use it in more components than this one.
