### ISSUE TITLE
IdsWeekView: Month Not translated/localized

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#454]
**Describe the bug**
Testing some local changes i noticed a bug

**To Reproduce**
1. Go to  https://main.wc.design.infor.com/ids-week-view/
2. Inspect the page, find `ids-container` and set language to `de`
3. Notice that the days of the week change but the Month in the header says the month in english.

**Expected behavior**
Need to add code to translate this too. The strings are in the locale files...

**Comment by andriivarhanov** [comment]
@tmcconechy a bit more info on it. I can't confirm the days of the week change on container language change. Everything related to date uses  IdsLocale `formatDate` util what uses `locale` to translate date i.e

`document.querySelector('ids-container').setLocale('de-DE')`
will translate month, days and time

`document.querySelector('ids-container').setLanguage('de')`
will translate audible strings, 'today', 'all day'

sure thing we can also add translations to months and days from the locale files

**Comment by tmcconechy** [comment]
Should have closed this. Its no longer an issue/something temporary
