### ISSUE TITLE
IdsToolbarSection: Add `spacing` setting

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#493]
**Is your feature request related to a problem or use case? Please describe.**
IdsToolbarSection could use a setting that can optionally add flexbox spacing properties and width values to their `.container` shadow DOM elements.  An example implementation are the toolbars in the App Menu, which are currently using a "centered" toolbar section, but the buttons are crushed together.  The screenshots below demonstrate the current and "desired" looks, respectively.

| current | desired |
| ---- | ---- |
| ![Screen Shot 2022-01-19 at 9 56 52 AM](https://user-images.githubusercontent.com/3249601/150157692-1b41c2e7-6389-4845-bb8f-b7f6f6d66ea9.png) | ![Screen Shot 2022-01-19 at 9 56 37 AM](https://user-images.githubusercontent.com/3249601/150157688-591a72aa-6dd7-4787-8a1f-4bc31b60811b.png) |

**Describe the solution you'd like**
- [ ] Implement a `spacing` setting.
    - `default` (do not alter container)
    - `spaced-evenly` (causes toolbar section to be `width: 100%` and `justify-content: space-evenly`)
- [ ] Test this setting against the Toolbar Overflow system (what happens if there is no "space" -- which direction does overflow occur in, and does it occur correctly?)

**Additional context**
Discovered while working on #439

**Comment by tmcconechy** [comment]
Dont need ATM
