### ISSUE TITLE
New Util: IdsHighlightUtil

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#494]
**Is your feature request related to a problem or use case? Please describe.**
We need to create a utility library for components that require wrapping/unwrapping HTML tags around arbitrary text within their control.  This is necessary for features like:

- highlighting text to match a search filter, like in the App Menu, and eventually removing that same highlight.
- possibly to help remove `document.execCommand()` calls in the editor?

**Describe the solution you'd like**
- [ ] Needs to be able to take a context element for scanning
- [ ] needs to have a `highlight(val?: string)` method, with an argument for searching text within the context element
- [ ] needs to also have an `unhighlight()` method that can clear a previous highlight
- [ ] (optional?) a flag for state to determine if a highlight is currently applied
- [ ] (optional?) maybe a setting to control the tags applied (element type, css class, id, etc)

**Describe alternatives you've considered**
This spec is loosely based on the [Mark.js](https://markjs.io/) API which is a popular JS library that has similar features

**Additional context**
- Discovered that we needed this while working on #439 
- Also talked about this during discussion about #350

**Comment by tmcconechy** [comment]
Dont need ATM
