### ISSUE TITLE
IdsAppMenu: Collapse accordion panes that don't contain filter matches

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#511]
**Describe the bug**
There's some incorrect rendering occurring in filtered App Menu accordions, where sometimes panels remain expanded when they should become collapsed.

**To Reproduce**
1. Go to http://localhost:4300/ids-app-menu and expand the App Menu
2. Click on the search field and type something that will match a child header under "Employee", such as benefits.  This causes the child panel under "Employee" to expand.
3. Type another phrase that won't match any accordion headers, such as "z".  This should produce a visibly empty accordion panel with some padding:

**Expected behavior**
We need to adjust the filter logic so that during or after the filter has occurred, a check can be done on expanded accordion panels to see if they contain no filter matches, and if so -- collapse the panel(s).  It may be possible to do this by checking for accordion headers containing a `child-filter-matches` attribute after a filter has completed.

Additionally, this behavior should take into account animation of the expand/collapse of the Accordion Panels, and should correctly cancel/activate expand/collapse behaviors.

**Version**
Available on #495, or after that PR is merged into `main`

**Screenshots**
![Screen Shot 2022-01-25 at 5 42 16 PM](https://user-images.githubusercontent.com/3249601/151072034-373c8e9e-b941-4fe2-891e-85d7b0b606ea.png)

**Additional context**
Related to #439

**Comment by tmcconechy** [comment]
Dont need ATM
