### ISSUE TITLE
IdsText: Is not translating text when used in another component

### ISSUE THREAD

**Issue by andriivarhanov** [infor-design/enterprise-wc#513]
**Describe the bug**
There is an attribute in `ids-text` `translate-text` where if it's true it listens to ids-container language change and translates text by translation key. The issue is `this.closest('ids-container')` is null if `ids-text` is used in another container so it doesn't translate.

https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-text/ids-text.js#L97-L104

Possible solution is to change `this.closest('ids-container')` to `document.querySelector('ids-container')` for `ids-text` and possibly for all components dependent from container languagechange event

**To Reproduce**
- Pull `150-ids-date-picker` branch
- If the branch doesn't exist go to http://localhost:4300/ids-date-picker
- Open calendar popup by clicking to input icon
- Check `Clear`, `Apply` buttons
- Open browser console and change container language
`document.querySelector('ids-container').setLanguage('fr')`
- Open the popup and see buttons don't translate

**Expected behavior**
`ids-text` translate feature should translate text in any place where component added

**Comment by tmcconechy** [comment]
My idea was it should be the closest container as there could be more than one in a page. So i think to fix this you can just change it to use this util https://github.com/infor-design/enterprise-wc/blob/main/src/utils/ids-dom-utils/ids-dom-utils.js#L44

Which goes up through the various shadowRoots until it finds it. Thats probably safer. Feel free to test and include if it fixes?

**Comment by andriivarhanov** [comment]
@tmcconechy the util works, thanks. I've included it as part of the date picker PR https://github.com/infor-design/enterprise-wc/commit/76455017b2fa14412314dd2df5a3a03344dad492. The issue can be closed
