### ISSUE TITLE
IdsMenuButton: Styling issues in RTL Mode

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#524]
**Describe the bug**
The arrow styles are off in RTL mode.

**To Reproduce**
1. Go to http://localhost:4300/ids-tag or http://localhost:4300/ids-menu-button
2. In the html inspector find `ids-container` and change `language="ar"` to force RTL
3. Click ....

**Expected behavior**
Fixed styles in RTL mode for menu button/theme switcher

**Screenshots**
![Screen Shot 2022-01-27 at 1 52 23 PM](https://user-images.githubusercontent.com/814283/151424695-b368b01d-24fe-4fae-9286-5f313cde785d.png)

**Comment by andriivarhanov** [comment]
@tmcconechy I would like to also add style issue of `ids-popup` arrow in RTL mode, same steps to reproduce just on the page http://localhost:4300/ids-menu-button
![image](https://user-images.githubusercontent.com/5204821/151548510-acf39f70-190e-4c0b-82de-8c623cd25b5e.png)

**Comment by tmcconechy** [comment]
Right! Pretty sure a css fix would fox both cases..
