### ISSUE TITLE
IdsDatePicker: Additional Features

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#538]
**Describe the bug**
Carry on with datepicker adding additional features..Round 2

**Specs**
- [x] Keyboard Shortcuts according to https://github.com/infor-design/enterprise/blob/main/src/components/datepicker/readme.md#keyboard-shortcuts
- [x] General accessibility (screen reader) / axe
- [x] Clicking the month/year opens the month and year selection panel
- [x] Configurable legend https://main-enterprise.demo.design.infor.com/components/datepicker/example-legend.html
- [x] Range picker https://main-enterprise.demo.design.infor.com/components/datepicker/example-range.html
- [x] Make it open faster (seems a little slow and for @EdwardCoyle it was 2-3 seconds)

**Additional context**
#510

**Comment by EdwardCoyle** [comment]
@andriivarhanov regarding this one:

> Make it open faster (seems a little slow and for @EdwardCoyle it was 2-3 seconds)

See [these comments](https://github.com/infor-design/enterprise-wc/issues/562#issuecomment-1058080578) before addressing
