### ISSUE TITLE
Update Puppeteer tests to replace deprecate API waitFor to waitForTimer

### ISSUE THREAD

**Issue by danielortiz1982** [infor-design/enterprise-wc#544]
**Describe the bug**
Puppeteer currently has an open issue to deprecate the waitFor API. This means at some point any test containing a call to this API could potentially fail disrupting our automation/pipeline process. 

**To Reproduce**

1. Checkout to main `git checkout main`
2. Pull the latest codebase `git pull -f`
3. Run all test `npm run test` 

**Expected behavior**
All test passing with an added warning message regarding notice of API deprecation.

Warning Message:
`waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code`.

**Version**

- ids-enterprise-wc: [0.0.0-beta.18]

**Screenshots**
<img width="1249" alt="Screen Shot 2022-02-07 at 8 24 59 AM" src="https://user-images.githubusercontent.com/5215954/152798027-c86595e5-d83a-4358-a2cf-03583e5fcc54.png">

Github related issue:
[6214](https://github.com/puppeteer/puppeteer/issues/6214)

Related test:

- [ ] enterprise-wc/src/components/ids-modal/ids-modal.js
- [ ] enterprise-wc/src/components/ids-popup/ids-popup.js
- [ ] enterprise-wc/src/utils/ids-dom-utils/ids-dom-utils.js
- [ ] enterprise-wc/test/helpers/wait-for.js
- [ ] enterprise-wc/test/ids-about/ids-about-percy-test.js
- [ ] enterprise-wc/test/ids-accordion/ids-accordion-func-test.js
- [ ] enterprise-wc/test/ids-app-menu/ids-app-menu-func-test.js
- [ ] enterprise-wc/test/ids-app-menu/ids-app-menu-percy-test.js
- [ ] enterprise-wc/test/ids-button/ids-button-e2e-test.js
- [ ] enterprise-wc/test/ids-color-picker/ids-color-picker-func-test.js
- [ ] enterprise-wc/test/ids-data-grid/ids-data-grid-percy-test.js
- [ ] enterprise-wc/test/ids-date-picker/ids-date-picker-e2e-test.js
- [ ] enterprise-wc/test/ids-drawer/ids-drawer-func-test.js
- [ ] enterprise-wc/test/ids-dropdown/ids-dropdown-func-test.js
- [ ] enterprise-wc/test/ids-header/ids-header-percy-test.js
- [ ] enterprise-wc/test/ids-image/ids-image-e2e-test.js
- [ ] enterprise-wc/test/ids-lookup/ids-lookup-func-test.js
- [ ] enterprise-wc/test/ids-message/ids-message-e2e-test.js
- [ ] enterprise-wc/test/ids-message/ids-message-percy-test.js
- [ ] enterprise-wc/test/ids-modal/ids-modal-e2e-test.js
- [ ] enterprise-wc/test/ids-month-view/ids-month-view-e2e-test.js
- [ ] enterprise-wc/test/ids-search-field/ids-search-field-percy-test.js
- [ ] enterprise-wc/test/ids-spinbox/ids-spinbox-func-test.js
- [ ] enterprise-wc/test/ids-splitter/ids-splitter-e2e-test.js
- [ ] enterprise-wc/test/ids-toast/ids-toast-percy-test.js
- [ ] enterprise-wc/test/ids-toolbar/ids-toolbar-func-test.js
- [ ] enterprise-wc/test/ids-toolbar/ids-toolbar-more-actions-func-test.js
- [ ] enterprise-wc/test/ids-tooltip/ids-tooltip-e2e-test.js
- [ ] enterprise-wc/test/ids-treemap/ids-treemap-e2e-test.js
- [ ] enterprise-wc/test/ids-virtual-scroll/ids-virtual-scroll-percy-test.js
- [ ] enterprise-wc/test/ids-week-view/ids-week-view-e2e-test.js

**Comment by tmcconechy** [comment]
Closing this as it doesnt seem to be true anymore for e2e tests. I also renamed waitFor in functional tests (a custom function). For consistency
