### ISSUE TITLE
IdsLookup: Prevent Blurriness

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#577]
**Describe the bug**
IdsLookup Modals are blurry for some reason.  They seem to be bypassing the [`#correct3DMatrix` code path]() that standard IdsModals and IdsContextualActionPanels use to "shift" the coordinate locations of the modal into full numbers and away from half-pixels, which is the source of the blurriness:

| Modal | Lookup Panel |
| ---- | ---- |
| ![Screen Shot 2022-03-07 at 11 23 32 AM](https://user-images.githubusercontent.com/3249601/157078568-712d3255-268e-481e-b4d6-f978b3718291.png) | ![Screen Shot 2022-03-07 at 11 23 52 AM](https://user-images.githubusercontent.com/3249601/157078618-4f49cddd-8ee7-4e2c-b16d-717fa9ec85dc.png) |

**To Reproduce**

**NOTE** This problem has occured in 4.x before and is difficult to see on 4K or Retina displays, and is almost exclusively a problem on computer monitors that are 72 DPI (1080p or less).  YOU WILL NOT SEE IT ON HIGH RESOLUTION DISPLAYS. Whoever picks this issue up needs to use a display that is not a Macbook Pro monitor or other high-definition display.

1. Go to http://main.wc.design.infor.com/ids-lookup
2. Open the lookup.
3. See that it's blurry

**Expected behavior**
The lookup contents should not be blurry

**Additional context**
- Discovered while testing #569 
- The [CSS-matrix-producing code](https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-popup/ids-popup.js#L1369) that should be running in IdsPopup doesn't appear to be running on the Lookup example
- The matrix code should also be [running on every page resize](https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-popup/ids-popup.js#L143-L158), which also doesn't seem to occur on the Lookup example

**Comment by tmcconechy** [comment]
Appears fixed now
