### ISSUE TITLE
IdsPager: Number List Pager has misaligned "next" and "previous" buttons

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#578]
**Describe the bug**
The IdsPager's "Number List" mode is currently visually broken, containing misaligned next/previous buttons.

![Screen Shot 2022-03-07 at 12 08 35 PM](https://user-images.githubusercontent.com/3249601/157083046-e53b62d5-76d8-44fa-935e-f5b3b3045713.png)

**To Reproduce**
The problem can be seen on the Number List example on the [IdsPager sandbox page](https://main.wc.design.infor.com/ids-pager/sandbox.html)

**Additional context**
- Discovered while testing #569

**Comment by tmcconechy** [comment]
Should be looking like https://main-enterprise.demo.design.infor.com/components/pager/example-listview.html
