### ISSUE TITLE
IdsMenuButton: Bug where it opens twice

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#607]
**Describe the bug**
Seeing a bug opening the menu with the keyboard.

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-menu-button/
2. Focus the first button and hit enter
3. Use down arrow to for example "small" and hit enter to select
4. Notice the menu opens and closes twice and two events fire
5. after that i cant open it anymore

**Expected behavior**
Should not open twice

**Additional context**
[Add any other context about the problem here.](https://github.com/infor-design/enterprise-wc/pull/605)

**Comment by EdwardCoyle** [comment]
[Relevant info about where the bug resides](https://github.com/infor-design/enterprise-wc/pull/605#issuecomment-1068143870)
