### ISSUE TITLE
IdsTooltip: Remaining Features/Issues

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#616]
**Original Issue**: #124 

**Major:**

- [ ] Use `aria-describedby` - This is not 100% working yet see [179](https://github.com/elix/elix/issues/179)
- [ ] Sync IdsTooltip's trigger event handling with IdsPopupInteractionsMixin (use mixin over one-off trigger events/share trigger types, move "hover" trigger type into IdsPopupInteractionsMixin)

**Comment by tmcconechy** [comment]
Closing this one for now
