### ISSUE TITLE
IdsButton: Requires ids-theme-switcher to work

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#633]
**Describe the bug**
Some types of buttons (not all tested) do not work (do get the right style) unless a theme switcher is added to the page.

**To Reproduce**

1. Go to http://localhost:4300/ids-about and notice it works
1. edit src/components/ids-about/demos/index.html and remove ids-theme-switcher
1. Go to http://localhost:4300/ids-about and notice it doesnt work
1. See missing styles

This doesnt work on secondary buttons - but does work on primary buttons. So please test all button types for this issue

**Expected behavior**
Should get light theme styles even if there is no ids-theme-switcher

**Comment by EdwardCoyle** [comment]
In the interests of not having colors applied to base styles (meaning trying to avoid always needing overrides for new themes), the button only gets theme colors by way of the mode/version attributes... [for example](https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-button/ids-button-base.scss#L130-L158) 

Would it make sense to apply default colors with something like: `&.ids-button:not([mode])` ?

**Comment by tmcconechy** [comment]
What i was thinking is that the base color should be "new - light" and only every other theme would need the theme switcher. Does that Jive with you because i dont get the relation to modal.

Also this one would be good to fix sooner than later

**Comment by tmcconechy** [comment]
@EdwardCoyle i just realized this is in other components like input. I think maybe a change to the theme mixin was made that made the defaults unset to light/new. or something like that

**Comment by EdwardCoyle** [comment]
The downside to defaulting all the colors to New/Light is that every other theme type (Dark/Contrast/future new ones) will have to depend on CSS order-of-operations, or have a stronger/more-specific CSS selector to override the default colors when building new themes.  The way it is now, that's not necessary -- but of course that means there are no colors applied if you miss applying the `mode` attribute.

**Comment by EdwardCoyle** [comment]
Maybe also related to this ticket - we should probably reconsider using `mode/version` attributes to apply theme colors on Shadow DOM, as opposed to good-old CSS classes... depending on the element type, adding those two attributes to standard DOM elements might not be valid
