### ISSUE TITLE
ReactExamples: Build Errors

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#638]
**Describe the bug**
Tried to fix the react examples but could not figure it out in time. Had to timebox. Was trying to get react 18 to work since it wasnt working anyways.

**To Reproduce**

1. Clone https://github.com/infor-design/enterprise-wc-examples
2. Go to react-examples in the console
3. npm prune && npm i
4. check the console in the terminal and browser

**Expected behavior**
No errors in either the terminal and browser and app shows up

**Comment by tmcconechy** [comment]
@andriivarhanov would you be willing to take a quick look at whats in main now for react. I cant quite figure it out and had to move to something else.

Thanks in advance if you can

**Comment by andriivarhanov** [comment]
@tmcconechy sure, on it

**Comment by andriivarhanov** [comment]
@tmcconechy please check if it works for you https://github.com/infor-design/enterprise-wc-examples/pull/9
