### ISSUE TITLE
Types: Make Components Have Correct Types

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#650]
**Describe the bug**
Try to make the types for elements have the right casting to types and work in certain situations with types.

**Problem One**
Edit any example like src/components/ids-about/demos/index.ts to something like:

```
import IdsAbout from '../ids-about';
const about: IdsAbout  | null = document.querySelector('#about-example');
// Type 'Element' is missing the following properties from type 'IdsAbout': connectedCallback, template, attachEventHandlers, #attachCloseButton, and 14 more.
```

or

```
const about = document.querySelector<IdsAbout>('#about-example');
// Type 'IdsAbout' is missing the following properties from type 'Element': attributes, classList, className, clientHeight, and 160 more.
```
**Problem Two**
A component inheriting from another. IdsMessage inherits from IdsModal and Mixins. How can we make all the methods and props in both the mixin and modal be visible inside the IdsMessage child. In the types

**Expected behavior**
How can we construct the code so this works in both cases?

**Additional context**
Would be nice to have - bounty 🎁

**Comment by danielortiz1982** [comment]
Investigating this from a high level, seem the issue stems from our mix pattern containing a `any` type that is being pass down to the ids web components. The proper `mixin` pattern can be outlined in the documentation reference below. I think this is a good place to start.

TS Mixin Docs:
https://www.typescriptlang.org/docs/handbook/mixins.html
