### ISSUE TITLE
Image: Add support for image drag and drop, cropping, scaling and rotation.

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise-wc#653]
**Is your feature request related to a problem? Please describe.**
We need capabilities to modify images including the following features: drag and drop, cropping, scaling and rotation.

**Describe the solution you'd like**
- ability to adjust/edit the image before uploading automatically 
- scaling or re-sizing high resolution images down for better performance and so they can be successfully stored in the database.
- drag and drop
- image rotation
- cropping
This is particularly compelling for use cases where a user uploads images from a mobile device.

**Comment by tmcconechy** [comment]
Moving as if doing this in the future could do it in the web component `image` component. But cant prioritize this at this time
