### ISSUE TITLE
Chore: Observe color contrast in Axe tests

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#669]
**Describe the bug**
Currently there is a problem with aXe Core that causes it to incorrectly flag color contrast problems on some WebComponents.  As a workaround we've added this setting to `toPassAxeTests()` on some e2e tests:

```ts
await (expect(page) as any).toPassAxeTests({ disabledRules: ['color-contrast'] })
```

The affected components are:
- IdsBadge
- IdsTag

**Expected behavior**
Eventually we should be able to pass tests without this setting

**Additional context**
See dequelabs/axe-core#3329 for context - we should be able to fix after this issue is closed

**Comment by tmcconechy** [comment]
No longer needed
