### ISSUE TITLE
IdsSplitter: Implement API for sizing/expanding/collapsing split panes

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#693]
**Is your feature request related to a problem or use case? Please describe.**

- Add new apis for `size`, `maxSize` and `minSize`.
- Enhance collapse api for multi pane
- Add tests

**Describe the solution you'd like**
IdsSplitter's API should be augmented with:

- [x] Max-size with multi splits
- [x] Api to set dynamically size for single, multiple and all panes
- [x] Api to set dynamically minSize for single, multiple and all panes
- [x] Api to set dynamically maxSize for single, multiple and all panes
- [x] Api to collapse for multiple and all panes
- [x] Api to expand for multiple and all panes
- [ ] Add Tests for above
- [ ] Convert Tests

**Describe alternatives you've considered**
TBD

**Comment by tmcconechy** [comment]
ok for this issue thats the easiest fix. It seems like the `size` does not update the component live (it only works on initial start). To reproduce:

1. go to https://main.wc.design.infor.com/ids-splitter/sandbox.html
2. in the "MINIMUM / MAXIMUM (MIN: 10%, MAX:80%)" example try to change the size in the DOM (result doesnt refresh)

Workaround for now is to just update it at the start, we'll fix

**Comment by mecharmor** [comment]
@tmcconechy got it, so we have to remove and re-add the slider to the DOM if we want to brute force the size to change?

**Comment by tmcconechy** [comment]
Thats what i saw for now. But i will fix it. Put this as candidate for next spring plan
