### ISSUE TITLE
IdsDatepicker: Double click does not enforce Range - Min (N) Days

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise-wc#780]
**Describe the bug**
1. Double click does not enforce Range - Min (N) Days
2. Cannot select date(s) on FF and Safari

**To Reproduce**

- https://main.wc.design.infor.com/ids-date-picker/range.html
1. Click on datepicker with Range - Min (5) Days (all browsers)
    - Select a date and double click it
    - See error: user is able to input a single day on datepicker with range Min 5 days
2. Click on any of the range fields (Safari & FF)
    - Select first date
    - See error: popup directly closes before selecting second date

**Expected behavior**
should only accept minimum required value
popup should not close when selecting date

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
(https://www.screencast.com/t/eyUpmLeQK)

**Platform**
 - Infor Application/Team Name: [WC IDS New Web Components]
 - OS Version: [iOS 8]
 - Browser Name: [safari]

**Additional context**
None

**Comment by danielortiz1982** [comment]
@CindyMercadoReyes Is this bug/issue in WC 5x or Enterprise 4x? In the description you outlined `Version ids-enterprise: [e.g. v4.9.0 or v4.10.0]` just want provide some clarity for @celhalal 
Thanks!

**Comment by celhalal** [comment]
Hi @tmcconechy!
- When reproducing the steps, the demo Range in the component Date Picker does not work in Safari nor FF. When you open any of the date fields, the calendar immediately closes once you select the first date. Should I make a new ticket or add it to the description in this ticket?
- The bug described in the ticket is for all browsers, not only Safari. In Chrome, the Range demo does work but the Min(5) Days field does not (as described in this ticket only for Safari), which I was able to find a solution for.

**Comment by tmcconechy** [comment]
Hi @celhalal you can just add to this ticket and include that fix if you want here (its ok to modify the description), as that seems 100% related
