### ISSUE TITLE
IdsContextualactionpanel: Contextual Action Panel is not responsive

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise-wc#781]
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-contextual-action-panel/example.html
2. Minimize the screen 
3. The CAP is not responsive 

**Expected behavior**
Should be responsive 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
None

**Platform**
 - Infor Application/Team Name: [WC IDS New Web Components]
 - OS Version: [e.g. Windows 10]

**Additional context**
None

**Comment by tmcconechy** [comment]
This was added on https://main.wc.design.infor.com/ids-modal/fullsize.html and the page is now responsive as it uses the modal under it
