### ISSUE TITLE
Bug: Failed to construct 'CustomElement'

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#789]
**Describe the bug**
Some components are giving an error: `Failed to construct 'CustomElement'`. This happens when the constructor (read template).  Makes writes. For example writing a setter.

**Task**
1. Make a test that can identify this
2. Run it on all components
3. See which needs fixed
4. Fix it

**Additional context**
Also this react is having.  Some related issues. We may need to fix this by changing that we load the template in the connectedCallback NOT the constructor

**Comment by EdwardCoyle** [comment]
Just noting here that the Svelte examples are having similar issues - specifically I'm looking at resolving this error on IdsInput
