### ISSUE TITLE
General: Systems Audit

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#796]
Do a general audit about servers and containers and document and share.
Where should it go?

**Comment by danielortiz1982** [comment]
Thanks @corpulent for putting this list together. 

### EC2
1 EC2 for Jenkins server.
3 EC2s for hl-cluster K8S cluster. This is our main job runner.
15 EC2s for soho-demo K8S cluster. This hosts our enterprise demos.
4 EC2s for Elastic Beanstalk.
1 for ids-com-prod. https://design.infor.com/
1 for ids-com-staging https://staging.design.infor.com/
1 for ids-dev https://dev.design.infor.com/
1 for project-max https://app.projectmax.nyc/

### Elastic Beanstalk
1 for ids-com-prod. https://design.infor.com/
1 for ids-com-staging https://staging.design.infor.com/
1 for ids-dev https://dev.design.infor.com/
1 for project-max https://app.projectmax.nyc/

### RDS instances
1 for a single figma-exporter database, which holds all of our exports from Figma to feed design-system npm releases.
1 for 3 databases (ids_com_dev, ids_com_staging, ids_com_prod) which are the databases for the 3 IDS website environments.
1 for ops, which is our sandbox database.

### Docker images
hookandloop/enterprise
hookandloop/4650-beta
hookandloop/ids-material-react
hookandloop/ids-infor-edu
hookandloop/ids-material
hookandloop/ids-styles
hookandloop/docs-migrate-postgres
hookandloop/soho-export
hookandloop/html-generator
hookandloop/docs-nginx
hookandloop/docs-backend
hookandloop/docs-nginx-dev

**Comment by tmcconechy** [comment]
@danielortiz1982 just wanted to point out that something was added here and then removed? Is that what you wanted?

```
Thanks @corpulent for putting this list together.

EC2

1 EC2 for Jenkins server.
3 EC2s for hl-cluster K8S cluster. This is our main job runner.
15 EC2s for soho-demo K8S cluster. This hosts our enterprise demos.
4 EC2s for Elastic Beanstalk.
1 for ids-com-prod. https://design.infor.com/
1 for ids-com-staging https://staging.design.infor.com/
1 for ids-dev https://dev.design.infor.com/
1 for project-max https://app.projectmax.nyc/

Elastic Beanstalk

1 for ids-com-prod. https://design.infor.com/
1 for ids-com-staging https://staging.design.infor.com/
1 for ids-dev https://dev.design.infor.com/
1 for project-max https://app.projectmax.nyc/

RDS instances

1 for a single figma-exporter database, which holds all of our exports from Figma to feed design-system npm releases.
1 for 3 databases (ids_com_dev, ids_com_staging, ids_com_prod) which are the databases for the 3 IDS website environments.
1 for ops, which is our sandbox database.

Docker images

hookandloop/enterprise
hookandloop/4650-beta
hookandloop/ids-material-react
hookandloop/ids-infor-edu
hookandloop/ids-material
hookandloop/ids-styles
hookandloop/docs-migrate-postgres
hookandloop/soho-export
hookandloop/html-generator
hookandloop/docs-nginx
hookandloop/docs-backend
hookandloop/docs-nginx-dev
```
