### ISSUE TITLE
IdsDropdown/IdsTooltip: Tooltip isn't pointing to the right place

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#816]
**Describe the bug**
In some cases IdsDropdown's optional tooltip doesn't appear to center in the correct place:

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-dropdown/example.html
2. Hover the example dropdown labeled "Dropdowns with Tooltips" without opening the dropdown
3. When the tooltip appears, it's "near" the source dropdown but is centered in the page instead

![Screen Shot 2022-07-19 at 10 50 48 AM](https://user-images.githubusercontent.com/3249601/179780629-fe017a58-1e29-4b27-937a-65f14372cb60.png)

**Expected behavior**
The tooltip should be centered above the dropdown when positioned.

If you use Dev Tools to examine the shadow root containers for both IdsTriggerField and IdsDropdown, they are stretching the full width of the page... We should see if making the shadow root containers of these elements `display: inline-block;` or `display: inline-flex;` helps.  However, this change would need testing against all different `field-height` and `size` attributes for both components:

- https://main.wc.design.infor.com/ids-dropdown/sizes.html
- https://main.wc.design.infor.com/ids-trigger-field/test-sizes.html

**Version**
WC 1.0.0-beta.0

**Comment by tmcconechy** [comment]
Stumbled over a fix testing ids-dropdown - should be ok after https://github.com/infor-design/enterprise-wc/pull/823 is merged
