### ISSUE TITLE
Tests: Add better output for memory leak tests

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#820]
**Describe the bug**
Need to find a way to print some console output for the e2e test that checks for memory leaks.

**To Reproduce**

1. Go to test/ids-tag/ids-tag-e2e-test.ts
2. Remove the skip on `it.skip('should not have memory leaks', async () => {`. (if there still)
3. In the same test uncomment out the `// For testing - leaving this here for now` section
4. run `npx jest -u -- tag`

**Expected behavior**
Would like the test to output more info on what leaked other than just the count. After this logging is added, try to unskip the following tests `it.skip('should not have memory leaks'` see if we can better diagnose. Seems like they pass alone but not as a group indicating maybe we need to ignore some puppetteer or test objects or something.

**Additional context**
Can use the test in all / more components if we have that.

**Comment by danielortiz1982** [comment]
@deep7102  From a high level I think you'll need to explore a `Recursion` pattern for this issue. Recursion allows you to dig deep into a data structure without having to use nested loops. 👍 

Recursion:
https://developer.mozilla.org/en-US/docs/Glossary/Recursion

**Comment by tmcconechy** [comment]
This was what i was looking at for a deep diff https://stackoverflow.com/questions/8572826/generic-deep-diff-between-two-objects

**Comment by tmcconechy** [comment]
closing in favor of https://github.com/infor-design/enterprise-wc/issues/878 as this is not possible since the object cannot be serialized in `page.evaluate`
