### ISSUE TITLE
IdsBreadcrumb: Truncated Breadcrumb Menu is broken

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#831]
Not sure where this fits so putting it here: But noticed that on https://main.wc.design.infor.com/ids-breadcrumb/truncated.html the popup doesnt open right (cut off). Maybe see if we need an issue?

_Originally posted by @tmcconechy in https://github.com/infor-design/enterprise-wc/issues/769#issuecomment-1178089616_

**Comment by tmcconechy** [comment]
duplicate of https://github.com/infor-design/enterprise-wc/issues/906
