### ISSUE TITLE
IdsPopup: Arrow not aligned the first time

### ISSUE THREAD

**Issue by deep7102** [infor-design/enterprise-wc#836]
**Describe the bug**
When run first time the popup arrow not align. It has wrong position calculated in `placeArrow()` method.

**To Reproduce**
- Open with any editor (ie: vs-code) `src/components/ids-pie-chart/ids-pie-chart.ts`
- Search for commented line `// TODO: Find a way to work without initial visible call`
- Make disable/comment next line `tooltip.popup.visible = true;`
- build/run and goto: http://localhost:4300/ids-pie-chart/example.html
- Hover on any pie slice to show tooltip
- See the bug now, very first time the tooltip arrow not align

**Expected behavior**
Tooltip/popup arrow should not misaligned first or any time

Related #736

**Comment by jbrcna** [comment]
Hello, this is now working as expected. see below screeshot.
<img width="445" alt="image" src="https://user-images.githubusercontent.com/56722184/222036582-023f17e7-3181-423c-bb4b-64168f6d640e.png">

 not sure if this is related but the arrow is doubled when using RTL
<img width="523" alt="image" src="https://user-images.githubusercontent.com/56722184/222036706-5289eb91-4893-4ef8-81cd-8ac6e7ce8b17.png">
