### ISSUE TITLE
IdsButton: Remove named slots and only use default slot for content

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#839]
**Is your feature request related to a problem or use case? Please describe.**
IdsButton currently has both an unnamed default slot, but also a named "text" and "icon" slot for its content.  Originally I thought this would be better for organizing component content, but it seems to just add complexity and cause confusion about usage... so I think we should model it like some newer components and only use the default slot for content.  This has some benefits:
- Users will define the order of the slot contents
- Component won't have to update multiple places
- Lessens the amount of boilerplate needed to construct a button

**Describe the solution you'd like**
- [x] Remove named slots from IdsButton code (template/setters)
- [x] Update all examples to not use named slots (many of our examples currently do)
- [x] Update tests/docs

**Comment by whernebrink** [comment]
Do the slots respect RTL/LTR? I.e. The icon slot is to the left of the text slot for LTR but right to the text in RTL. If so, then they'd be sweet to keep. :) If there are no slots, what styles do the ids-button have? Can one expect the content below, which will be projected to the default slot, to be aligned both horizontal and vertical (e.g. align-items: center; justify-content: center;)? If not, one would need to wrap it's content in a div with those styles and take the full width and height of the button?
E.g. 
``html
<ids-button>
  <ids-icon icon="something" />
  <span>My text</span>
</ids-button>
```

**Comment by tmcconechy** [comment]
As long as the code uses `start` `end` settings for margin and padding it will work right in RTL. The only issue i can think of with unnamed slots is that you can only have one un-named slot (but im sure there is some way to make it work.

**Comment by EdwardCoyle** [comment]
@whernebrink:

> Do the slots respect RTL/LTR?

Currently I believe both the named and default slots respect RTL correctly but I haven't tested every case

> If there are no slots, what styles do the ids-button have? ...

The default slot should display the content inside as if it's "flex" aligned (centered vertical/horizontal) with spacing between the slotted elements.

**Comment by jbrcna** [comment]
QA Passed. moving this ticket to done. thanks
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/56722184/211248577-15688849-8f80-4ac1-bb5c-69caccb3eb22.png">
