### ISSUE TITLE
Frameworks: React Typescript Error

### ISSUE THREAD

**Issue by clayinfor** [infor-design/enterprise-wc#847]
## The problem:
I get the following error when trying to use WC with react typescript:

<img width="1440" alt="Screen Shot 2022-08-09 at 14 29 50" src="https://user-images.githubusercontent.com/93789065/183735502-17624401-c20d-4afd-817f-534824f238f7.png">

## Steps to reproduce:

1. Run this command: `npm create-react-app wc-react-ts --template typescript`
2. Run this command: `npm install --save ids-enterprise-wc@latest`
3. Add this to App.tsx with: `import 'ids-enterprise-wc/components/ids-button/ids-button';`
4. add `<ids-button>Test Button</ids-button>` to the markup of App.tsx

## Possible Solutions:

- https://coryrylan.com/blog/how-to-use-web-components-with-typescript-and-react

## More screenshots:
<img width="1440" alt="Screen Shot 2022-08-09 at 14 38 14" src="https://user-images.githubusercontent.com/93789065/183736023-f02d364f-1d80-4529-8188-e40bed186ca5.png">

**Comment by Carlfjord** [comment]
Hi, I was exploring the potential for using the react ts and ids wc combination and stumbled on the same issue. 

For anyone else seeing the same issue here is another resource for temporary work around: https://goulet.dev/posts/consuming-web-component-react-typescript/ 

Just posting to add a tiny bit of weight to the issue and to check if this fix is something that will be prioritized in the near future?

**Comment by tmcconechy** [comment]
@Carlfjord would this just be considered an quirk of React? To add to our docs? Or can you think of a way we could actually fix it without not using web components?

**Comment by clayinfor** [comment]
Hey @tmcconechy, here's a comment I made regarding add the `src/declarations.d.ts` file to our `enterprise-wc` repository:

https://github.com/infor-design/enterprise-wc-examples/pull/31/files#r1142517038
