### ISSUE TITLE
IdsAppMenu: Header is not consistent with 4x

### ISSUE THREAD

**Issue by danielortiz1982** [infor-design/enterprise-wc#852]
**Expected behavior**
Ids App Menu example should look like 4x.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1440" alt="Screen Shot 2022-08-10 at 1 46 50 PM" src="https://user-images.githubusercontent.com/5215954/183985506-e1b4779e-8b65-4733-aea5-f484f5a7ab91.png">

**Additional context**

**Comment by tmcconechy** [comment]
We did this on purpose as to separate it from all the related components, or maybe because header wasn't done.
But we could put it in a header on the page. It might not be 100% the same tho

**Comment by tmcconechy** [comment]
There is one example like this here https://main.wc.design.infor.com/ids-header/example.html
