### ISSUE TITLE
idsTriggerField: Timepicker icon is slightly cut off on left side in safari

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise-wc#874]
**Describe the bug**
Timepicker icon is slightly cut off on left side in safari

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-trigger-field/example.html
2. Verify time picker
3. Zoom in to clearly see the issue
4. Timepicker icon is slightly cut off on left side in safari

**Expected behavior**
TimePicker should not be cut off

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
https://www.screencast.com/t/Yw0FMCBKBsjy

**Platform**
 - OS Version: [ iOS 8]
 - Browser Name: [safari]

**Additional context**
Add any other context about the problem here. NONE

**Comment by tmcconechy** [comment]
This is probably related to https://github.com/infor-design/enterprise-wc/issues/876 so closing. We can test this after thats fixed
