### ISSUE TITLE
idsBadges: Timepicker icon is slightly cut off in safari

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise-wc#875]
**Describe the bug**
Timepicker icon is slightly cut off in safari

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-badge/example.html
2. See error
3. Notice the time picker icon is cut off on the side
4. Timepicker icon is slightly cut off in safari

**Expected behavior**
Timepicker icon should not be cut off in safari

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
https://www.screencast.com/t/SoZMmBWBvw8D

**Platform**
 - OS Version: [ iOS 8]
 - Browser Name: [safari]

**Additional context**
Add any other context about the problem here. NONE

**Comment by tmcconechy** [comment]
Decided to close this as being minor/impossible to reproduce based on zoom. But #874 may help a bit
