### ISSUE TITLE
IdsIcons: Some of the icons are slightly cut-off on all browsers

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise-wc#876]
**Describe the bug**
Some of the icons are slightly cut-off on all browsers

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-icon/example.html
2. Notice the icons
3. Some of the icons are slightly cut-off in Safari, Edge, Chrome, and FF

**Expected behavior**
The icons should not be cut off

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
https://www.screencast.com/t/X3kRgtUJYR - Safari
https://www.screencast.com/t/flERSLgJIGfN - Edge
https://www.screencast.com/t/Kyjquek5p9U - Chrome
https://www.screencast.com/t/MVqOI90Cm7FL - FF

**Platform**
 - Browser Name: [All browser]

**Additional context**
Add any other context about the problem here. NONE

**Comment by tmcconechy** [comment]
Requires updates to the figma files.. I believe

**Comment by tmcconechy** [comment]
Added new icons should be ok now
