### ISSUE TITLE
All: Find and fix memory leak(s)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#878]
**Describe the bug**
Action panel is exhibiting some memory leak that is proving difficult to track down.

**To Reproduce**
1. Go to test/ids-action-panel/ids-action-panel-e2e-test.ts
2. Remove skip from `it.skip('should not have memory leaks`...
3. Run `npx jest -- action-panel-e2e`

Components:

- [x] popup-menu
- [x] axis-chart
- [ ] menu
- [ ] card
- [ ] text-area
- [ ] menu button
- [ ] input
- [ ] dropdown
- [ ] action-panel
- [ ] calendar
- [ ] form
- [ ] error page
- [ ] counts
- [ ] upload
- [ ] slider
- [ ] about (modal)?
- [ ] scroll view
- [ ] accordion
- [ ] search field
- [x] counts  https://github.com/infor-design/enterprise-wc/pull/927
- [x] container https://github.com/infor-design/enterprise-wc/pull/927
- [ ] checkbox
- [ ] checkbox group
- [ ] block grid
- [ ] pager
- [ ] process-indicator
- [ ] hidden
- [ ] modal
- [ ] multi select
- [ ] action sheet
- [ ] masthead
- [ ] draggable
- [ ] editor
- [ ] swap list
- [ ] spin box
- [x] theme switcher  https://github.com/infor-design/enterprise-wc/pull/927

**Expected behavior**
Now test in the browser and see if we can find what this leak is.

**Additional context**
Use these links for troubleshooting/profiling
- https://medium.com/coding-blocks/catching-memory-leaks-with-chrome-devtools-57b03acb6bb9
- https://developer.chrome.com/docs/devtools/memory-problems/
- https://addyosmani.com/blog/taming-the-unicorn-easing-javascript-memory-profiling-in-devtools/

**Comment by EdwardCoyle** [comment]
I took a look at this one and pushed some changes here: [`792-more-sveltekit-examples`](https://github.com/infor-design/enterprise-wc/commit/c24b17af61cec78c6fa83269fcb6f003d314ad4b).  The commit in the link specifically addresses the leaks only.

The gist of the changes are:
- Added `disconnectedCallback` to components and mixins in the Action Panel stack that were missing
- In these callbacks, cleaned up members of each mixin/component that needed it (`null`-ed out some items, and in some cases unbound events and observers)

Comparing the output of the memory leak test between the before and after seems to have only knocked the object count down by a handful of points.  These points also seem to vary on occasion between test runs:

| before | after |
| ---- | ---- |
| ![Screen Shot 2022-08-24 at 12 29 00 PM](https://user-images.githubusercontent.com/3249601/186472839-73754b96-c19a-4822-90a2-1d50f77cd05c.png) | 
![Screen Shot 2022-08-24 at 12 03 58 PM](https://user-images.githubusercontent.com/3249601/186472896-4e1c3024-b7b0-472b-9c2c-6c5f9cf9edcf.png) |

I think ultimately this helped, but the problem may lie elsewhere -- or maybe there's just more cleanup to do.
