### ISSUE TITLE
IdsColor: Incorrect outline placement

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#888]
**Describe the bug**
There are some incorrectly placed outlines representing IdsColor's focus state appear where the component is present.

**To Reproduce**
1. Go to http://localhost:4300/ids-color/example.html
2. Use the keyboard to focus color swatches with "no color" (red slash over white background).
3. Notice the outlines in other areas of the page

**Expected behavior**
The outline should just focus the color swatch

**Screenshots**
![Screen Shot 2022-08-25 at 10 51 52 AM](https://user-images.githubusercontent.com/3249601/186699660-c5f73653-c682-4a93-819b-03289486f1a7.png)

**Comment by tmcconechy** [comment]
Issue is no longer there
