### ISSUE TITLE
IdsDataGrid: XSS issue in cells

### ISSUE THREAD

**Issue by danielortiz1982** [infor-design/enterprise-wc#899]
**Describe the bug**
Review of IdsDataGrid usage with the M3 team revealed that it's currently possible to inject script tags into IdsDataGrid cells.  They were doing this by loading existing data into a cell (not necessarily from editing a cell).

**How to Reproduce**
We can't currently reproduce in the WC project -- we need to create some test cases for these conditions (may be able to [re-use the ones from Enterprise](https://main-enterprise.demo.design.infor.com/components/datagrid/test-xss-prevention.html))

- Create an example page containing an IDS Datagrid with a pre-determined dataset.
- In this dataset, add cell content with JS script tags, like one that creates an alert with arbitrary text.
- Open the new example page. When the data grid is invoked, an alert will be displayed.

**Additional Context**:
- Discovered by the M3 Team (cc @inforrpunay)
- Should be completed along with #737

**Comment by tmcconechy** [comment]
have a fix as part of #862 which i need for editing (was already going to be part of this)
