### ISSUE TITLE
IdsScrollView: Remove hash links for navigation

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/enterprise-wc#904]
**Describe the bug**
Find an alternate solution to using hash links in the ids-scroll-view component to avoid issues within SPA frameworks routing systems

**To Reproduce**

1. Pull angular-ids-wc example branch https://github.com/infor-design/enterprise-wc-examples/tree/316-angular-examples
2. `npm i && start`
3. go to http://localhost:4200/ids-scroll-view/example

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
n/a

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
n/a

**Comment by tmcconechy** [comment]
- dont use href / effect the URL
- make sure there is an api to focus a image
