### ISSUE TITLE
IdsBreadCrumb: Truncated example not displaying correctly

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/enterprise-wc#906]
**Describe the bug**
The popup menu containing the overflowed menu items is cutoff in ids-breadcrumb truncated example.

**To Reproduce**

1. Go to http://localhost:4300/ids-breadcrumb/truncated.html
2. Click on the '...' menu button

**Expected behavior**
The popupmenu should not be cutoff

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![Screen Shot 2022-08-31 at 5 03 19 PM](https://user-images.githubusercontent.com/1084735/187781739-fa7a4fb2-3a48-44ac-8ef6-55ceaad17b35.png)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
had this already but will close the older on https://github.com/infor-design/enterprise-wc/issues/831

**Comment by glenlieorillo** [comment]
QA tested and passed.


https://user-images.githubusercontent.com/102151352/206611566-ac123e20-4c0f-4902-96d8-f1952f3212c5.mov

**Comment by glenlieorillo** [comment]
QA tested and passed.

https://main.wc.design.infor.com/ids-breadcrumb/truncated.html#

https://user-images.githubusercontent.com/102151352/206616901-89c388ad-c0db-4660-afbc-a3fac3d70dd2.mov
