### ISSUE TITLE
Suppress Enter = true do not work  on SohoModal

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise-wc#907]
**Describe the bug**
Using the suppressEnterKey setting for modal does not work on the succeeding use of enter key for the modal. This happens if you opened and closed another modal with suppressEnterKey=false.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/4.64.0/demo/components/modal/example-index.html.
2. Click on the Show Modal (Suppressed Enter) button to show the modal with suppressEnterKey=true.
3. Press Enter key. The modal will not close as expected.
4. Close the modal by clicking the Cancel button
5. Click on the Show Modal button to show the modal with suppressEnterKey=false.
6. Press Enter key. The modal will close as expected.
7. Click again on the Show Modal (Suppressed Enter) button to show the modal with suppressEnterKey=true.
8. Press Enter key. The modal will close but it should not.

**Expected behavior**
Modal window should not close on press of Enter key if suppressEnterKey=true is set.

**Version**

- ids-enterprise: v4.64.0

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 104.0.5112.82 (Official Build) (64-bit)

**Comment by inforrpunay** [comment]
Apologies as I have reported the issue in the web component project. This is encountered in ids-enterprise. Kindly move accordingly. Regards!

**Comment by ericangeles** [comment]
@inforrpunay please create another issue in EP version instead. Thanks!

**Comment by inforrpunay** [comment]
> @inforrpunay please create another issue in EP version instead. Thanks!

Hi @ericangeles, I created https://github.com/infor-design/enterprise/issues/6793. Closing this ticket now. Thanks!
