### ISSUE TITLE
General: Add theme switch to side-by-side examples

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#939]
**Is your feature request related to a problem or use case? Please describe.**
We can't currently see the different IDS themes' implementation between the Web Components and the 4.x components in their side-by-side examples -- there is no way to switch the theme

**Describe the solution you'd like**
- [ ] Implement theme switcher on all side-by-side example pages
- [ ] Log any discrepancies between the themes in both libraries in a new issue
- [ ] Specifically it was requested we also do this in the Angular example library
~- [ ] Also Personalization and Locale~ -> scope to another issue

**Additional context**
Suggested by @whernebrink

**Comment by EdwardCoyle** [comment]
Noting here that we should try to include examples of how theme switching would operate on a page that includes components from all libraries:  Enterprise, Enterprise Angular, and Web Components.  We should demonstrate how someone could tie all the event handling together to make themes switch across libraries in-tandem

**Comment by whernebrink** [comment]
May I ask where I can see this example implemented? :)

**Comment by tmcconechy** [comment]
any side by side page like for example http://localhost:4300/ids-badge/side-by-side.html

**Comment by whernebrink** [comment]
Oh, so this issue is adding support for theme switching for all examples? 

I was merely interested in the following that @EdwardCoyle wrote above:

> Noting here that we should try to include examples of how theme switching would operate on a page that includes components from all libraries: Enterprise, Enterprise Angular, and Web Components. We should demonstrate how someone could tie all the event handling together to make themes switch across libraries in-tandem

We don't have that yet, or?

**Comment by tmcconechy** [comment]
I didn't update the https://github.com/infor-design/enterprise-ng repo but this method should work. All you need to do is add the new switcher and manage the theme change through this. And it will change for both libraries

```
<ids-theme-switcher theme="default-light"></ids-theme-switcher>
```

Added some docs here https://github.com/infor-design/enterprise-wc/blob/main/doc/SIDE-BY-SIDE.md

**Comment by whernebrink** [comment]
Awesome, thanks @tmcconechy!

**Comment by jbrcna** [comment]
QA Failed.
i just noticed that on first load and change themes i saw a bunch of characters on `4.X BADGE` instead if icons. wasn't able to take a snapshot because it works fine after refresh and trying again.

also in RTL of accordion
https://main.wc.design.infor.com/ids-accordion/side-by-side.html
<img width="1573" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/83b0518e-5601-444c-af82-7bf37dad67f3">
