### ISSUE TITLE
Angular: Property binding issues

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/enterprise-wc#941]
**Describe the bug**
Noticing issues in components in angular where attributes need property binding in order to work properly.

- ids-toggle-button https://github.com/infor-design/enterprise-wc-examples/blob/38e2e0541c65f0f1cfc434fa33b2b491fd1f1ff0/angular-ids-wc/src/app/components/ids-toggle-button/demos/example/example.component.html#L9
- ids-search-field (in ids-app-menu) https://github.com/infor-design/enterprise-wc-examples/blob/38e2e0541c65f0f1cfc434fa33b2b491fd1f1ff0/angular-ids-wc/src/app/components/ids-app-menu/demos/example/example.component.html#L59
- ids-menu-button https://github.com/infor-design/enterprise-wc-examples/blob/38e2e0541c65f0f1cfc434fa33b2b491fd1f1ff0/angular-ids-wc/src/app/components/ids-menu-button/demos/example/example.component.html#L15
- ids-pager https://github.com/infor-design/enterprise-wc-examples/blob/38e2e0541c65f0f1cfc434fa33b2b491fd1f1ff0/angular-ids-wc/src/app/components/ids-pager/demos/example/example.component.html#L10
- ids-text (color attribute)

**To Reproduce**

1. Clone https://github.com/infor-design/enterprise-wc-examples 
2. `cd angular-ids-wc`
3. `npm i && start`
4. Remove property bindings in above lines and see the errors on the following examples:
5. http://localhost:4200/ids-toggle-button/example
6. http://localhost:4200/ids-app-menu/example
7. http://localhost:4200/ids-menu-button/example
8. http://localhost:4200/ids-pager/example

**Expected behavior**
Be able to add settings without property binding

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
n/a

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
#931

**Comment by EdwardCoyle** [comment]
IdsListView also needs a look
