### ISSUE TITLE
General: Review Dark Mode background color

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#944]
**Describe the bug**
Dark mode's background color (Slate 90) is a shade lighter than its 4.x mode's counterpart (Slate 100).  I'm flagging this because I'm not sure if it's intentional, and adjusting it may have other implications on the system (for example, the dark mode BG color on accordion panels in IdsAppMenu is the same color).

**To Reproduce**
1. Open https://main.wc.design.infor.com/ids-data-grid/alternate-row-shading.html and use the theme switch to change Mode to "Dark".
2. Also open [this demo's 4.x example](https://main-enterprise.demo.design.infor.com/components/datagrid/example-alternate-row-shading.html?theme=new&mode=dark&layout=nofrills)
3. Compare the background colors between the two

**Expected behavior**
- [ ] The Web Component's Dark Mode background color should be the same as the 4.x mode.  Any related colors in WC should be updated to reflect this change as well.

**Additional context**
Discovered while testing #943

**Comment by tmcconechy** [comment]
This doesnt seem to be the case anymore. Both are Slate 100. (Darkest Color) Must have been fixed.
