### ISSUE TITLE
IdsTimePicker: Review for Memory Leaks

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise-wc#947]
**Describe the bug**
IdsTimePicker continues to be flagged on CI/CD as having a small memory leak.  This issue is for exploration of this specific memory leak.

**To Reproduce**

1. Re-enable [this test](https://github.com/infor-design/enterprise-wc/blob/main/test/ids-time-picker/ids-time-picker-e2e-test.ts#L150)
2. On a terminal run `npm run test -- ids-time-picker-e2e
3. See test failure

**Expected behavior**
IdsTimePicker should not have memory leaks

**Additional context**
Related to #878

**Comment by andriivarhanov** [comment]
@jdilag90 @tmcconechy I had no luck with finding the bug, but if we place the component to ids-container in the test https://github.com/infor-design/enterprise-wc/commit/2cfec18df675963ce087250318dba5952c3dc013 it works, so it must be something related to `ids-container` dependency like `ids-locale` or other state dependency. I hope it helps

**Comment by tmcconechy** [comment]
Just fyi @andriivarhanov I thought you had'nt started this and Joe is working on https://github.com/infor-design/enterprise-wc/issues/878 so i assigned this as it overlaps. Sorry - and thanks for the Info. Hopefully @jdilag can figure it out from here.

**Comment by andriivarhanov** [comment]
@tmcconechy it's ok, I'm stuck here anyway, was going to ask you for a help

**Comment by tmcconechy** [comment]
Closing this for now
