### ISSUE TITLE
General: Fix bugs in the react examples

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#974]
**Describe the bug**
Fix some of the bugs in the react examples as noted here https://github.com/infor-design/enterprise-wc-examples/pull/23/files#diff-b91c99af42569f25d4446c551bbdd526a88f67c1eeb8637421bf648fab71b594R4 (this willbe updated again soon)

**Additional context**
Can also look for any other bugs/missing components in the examples.

**Open Issues**

- [x] Broken: http://localhost:3000/ids-about
- [x] Broken: http://localhost:3000/ids-accordion
- [x] Broken: http://localhost:3000/ids-message
- [x] Broken: http://localhost:3000/ids-modal
- [x] Broken: http://localhost:3000/ids-pager
- [x] Broken: http://localhost:3000/ids-slider
- [x] Broken: http://localhost:3000/ids-trigger-field
- [x] Lacking: http://localhost:3000/ids-virtual-scroll
- [x] Missing: http://localhost:3000/ids-render-loop
- [x] Missing: http://localhost:3000/ids-summary-field
- [x] Styles: http://localhost:3000/ids-progress-chart
- [x] Styles: http://localhost:3000/ids-swipe-action
- [x] Styles: http://localhost:3000/ids-tag
- [x] Styles: http://localhost:3000/ids-tree

**Comment by tmcconechy** [comment]
@andriivarhanov for next sprint we want t work on data grid so lets table this or push if you have some fixes to wrap it up
We can come back to the rest later

**Comment by andriivarhanov** [comment]
@tmcconechy sure, I will make PRs today and switch to the data grid
