### ISSUE TITLE
IdsEditor: Insert hyperlink not working in safari & firefox

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#982]
**Describe the bug**
When using  safari/ firefox browser, the insert hyperlink feature is not working

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-editor/example.html
2. Click on  hyperlink icon/button
3. Click Apply button
5. In safari browser, the page freezes after clicking  hyperlink icon/button
6. check console error

**Expected behavior**
should be able to insert hyperlink

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/56722184/199714434-8b9b363d-2a7b-4846-847b-f94b6db88bd2.png">

**Platform**
Safari and Firefox Browser

**Additional context**

**Comment by tmcconechy** [comment]
@andriivarhanov - is this fixed on https://github.com/infor-design/enterprise-wc/pull/973 by any chance as well? Thanks!

**Comment by andriivarhanov** [comment]
@tmcconechy it's not there as well

**Comment by ericangeles** [comment]
@tmcconechy this is for WC.

**Comment by jbrcna** [comment]
this is now working as expected. you can now insert a hyperlink. However, the links are unclickable via click or cmd + click
<img width="945" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/847d466e-edeb-47db-8eda-23ea7fac6fa0">
