### ISSUE TITLE
IdsTimepicker - read only and dirty tracker safari issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise-wc#986]
**Describe the bug**
in safari browser,`Time Picker - readonly` & `Dirty Tracker` is not working as properly

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-time-picker/example.html
2. Click on `Time Picker - readonly`
3. Type to edit
5. Also Notice that the `Dirty Tracker`format is 10/30/ and not 10:30

**Expected behavior**
`Time Picker - readonly` should not be editable
`Dirty Tracker`format should be 10:30 by default
<img width="250" alt="image" src="https://user-images.githubusercontent.com/56722184/200317223-78b4a90a-25e4-4518-b3ee-a2a4631ce61e.png">

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="327" alt="image" src="https://user-images.githubusercontent.com/56722184/200317000-2ca9fe35-cb08-441f-a857-e77aab2997c7.png">

**Platform**
Safari

**Additional context**

**Comment by tmcconechy** [comment]
What about this one @andriivarhanov ?

**Comment by andriivarhanov** [comment]
@tmcconechy there is similar fix for date picker (readonly) but not for time picker, it's a quick fix, should I include it in the PR?

**Comment by tmcconechy** [comment]
Sure might as well get these out of the way 👍🏻
