### ISSUE TITLE
IdsDataGrid: Save user settings

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-wc#992]
**Enhancement**

Add save user settings feature like the old version:
https://main-enterprise.demo.design.infor.com/components/datagrid/test-save-settings-manual.html
https://main-enterprise.demo.design.infor.com/components/datagrid/test-save-settings-serverside.html
https://main-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html

But instead of an object for the settings flatten it to individual settings. Save each of these:

```
 saveUserSettings: {
    columns: true,
    rowHeight: true,
    sortOrder: true,
    pagesize: true,
    activePage: true,
    filter: true
},
```

```
saveColumns, saveFilterRow
```

- fire events in case they want to save it
- give methods to save and restore it
- use locale storage or can save manual

**Comment by jbrcna** [comment]
QA Passed. moving thing ticket to done. thanks
https://main.wc.design.infor.com/ids-data-grid/save-settings.html
https://main.wc.design.infor.com/ids-data-grid/save-settings-manual.html
